### ISSUE TITLE
Edited: convert verbatim collectors to agent collectors for UAM Ento

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7326] opened 2024-01-24 17:53 UTC
Can I get collectors (as real agents) added back to my records that had them removed? I don't know how many agents or records are involved in this, but here's one: https://arctos.database.museum/guid/UAM:Ento:103160

Apologies if this is already in the to-do queue!

**Comment by dustymc** [comment] 2024-01-24 18:16
I think this is a duplicate of https://github.com/ArctosDB/arctos/issues/7135, although that has taken on a life of its own and a new focused issue might be more actionable.

My (perhaps not terribly clear) understanding is

1. https://github.com/ArctosDB/arctos/issues/6813 is relatively solid; we know where we're going with this.
2. https://github.com/ArctosDB/arctos/issues/7318 is the first step in that direction. Implement agent attributes, give it a bit of exposure, then
    * convert other stuff to that model, and in that process
    * get any 'requirements' in line with (1)
3. And at that point this will be approachable.

I'm not sure how we move forward on https://github.com/ArctosDB/arctos/issues/7318 (I was under the impression that I was to begin work on it a couple days ago, now it seems to be an agenda item), and I'm REALLY not sure how we'll take the next step (bringing addresses, names, statuses, relationships into that model) from there.

It's not *completely* out of the realm of possibilities that I could drop some (certainly not all) constraints in the current model and proceed with what's being asked here, but that would involve some extra work, some significant possibilities of bugs (as all 'in-betweens' do), would lose the versioning the attribute model introduces (seems critical on low-information agents, which these will all be), etc. It's also possible that the data would make this very difficult, or make a huge mess by creating a bunch of duplicates of current agents (eg if many have been created since these were 'attribute-ified'). That doesn't seem much fun for lots of reasons, can we approach this in a more systematic way? As outlined above still makes sense to me, but I'm open to anything that involves keeping the model in sync with the expectations. Perhaps we also need some sort of firm timeline - it also doesn't seem reasonable to leave this hanging indefinitely.

@mkoo @ArctosDB/agents-committee HELP!!!!

**Comment by DerekSikes** [comment] 2024-01-24 21:07
Looks like UAM:Ento has 6199 records without agent collectors
Record Count: 6199
Cached: No
Datasource: user_login
Lazy: No
SQL:
SELECT guid
FROM flat
WHERE guid_prefix = 'UAM:Ento'
AND collectors IS NULL
ORDER BY GUID
LIMIT 10000 ;

**Comment by DerekSikes** [comment] 2024-01-24 21:17
and maybe this page needs editing (esp the part in bold)

READ THIS!
Read the Documentation

Do not use this form unless you are intimately familiar with Agent Documentation and Best Practice - Creating Meaningful Agents.
Catch up on GitHub

Review stop low-information agents, do more with verbatim agents and associated Issues and meeting notes before creating an Agent.

Comment on an existing Issue, open a new Issue, or become involved in issues and governance meetings if you wish to participate, need clarification, or just want to hang out with the cool kids.
Consider not creating an Agent

Agents which will act only in various collector roles seldom need to be created as Agents; simply use attribute verbatim agent. **No functionality will be lost under this method.**

**Comment by dustymc** [comment] 2024-01-24 21:21
Nothing of that page should survive implementation of the [roadmap](https://docs.google.com/document/d/1tSk344mJsIRYZ-BJcYfyaPEmbrFS-wSqZzJ5dO1E2EU/edit#heading=h.ei43n7pwmxwu).

**Comment by mkoo** [comment] 2024-01-31 19:28
This is a UAM:Ento request for convert verbatim agents to agents -- will require some in progress tasks to be completed first.

Not a dup exactly but will take care of #7135

**Comment by dustymc** [comment] 2024-03-05 17:59
@DerekSikes ( cc @mkoo ) two options here:

1. Say "go" and I'll create agents for the CSV file below, add them as collectors to the records, and remove the verbatim agent attribute. I think that's probably the safe pathway, none of these have any information beyond strings (that's how we got here) so there's just no way to be sure of anything, BUT there are some who have names suspiciously close to existing agents. (Which isn't a problem, just potentially needs eventual review and possible use of https://github.com/ArctosDB/arctos/issues/7356)
2. Do something more complicated that uses existing agents. I can do whatever, but will need more involvement. Talk to me before you invest any work if you want to do anything other than (1).

[cf_temp_pre_bulk_agent_download(6).csv.zip](https://github.com/ArctosDB/arctos/files/14499181/cf_temp_pre_bulk_agent_download.6.csv.zip)

**Comment by DerekSikes** [comment] 2024-03-05 19:05
Sounds good! THanks!

I see one name that is definitely a match to an agent, my neighbor: Christopher M. Harwood = Chris Harwood

Will the remarks be preserved? I hope so.

eg Hollingsworth with remarks = Collector from Alaska Lepidoptera Survey Volunteer dataset

**Comment by dustymc** [comment] 2024-03-06 01:35
done

**Closed by dustymc** 2024-03-06 01:35 UTC
Labels: Priority-Normal (Not urgent), Function-Agents, contact

**Comment by DerekSikes** [comment] 2024-03-06 01:45
thanks!

**Comment by AJLinn** [comment] 2024-03-14 15:43
How do other collections get this action done for our verbatim agents, some of which are collectors, others are creators? Can I make an issue for UAM:EH?

**Comment by dustymc** [comment] 2024-03-14 15:44
>make an issue

Yup.
