### ISSUE TITLE
Next available loan number pulls last loan number instead

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2850] opened 2020-06-29 19:09 UTC
In Transactions: Create Loan
Next Available Loan Number for MSB Mamm displays the last used loan, not the next available.
This risks duplication of loan numbers.
Priority High

**Comment by KyndallH** [comment] 2020-06-29 19:16
I checked for UAM:Mamm since I'm doing a loan right now - we are all good here!

**Comment by dustymc** [comment] 2020-06-29 19:29
Duplicate of https://github.com/ArctosDB/arctos/issues/1949 with some elements of https://github.com/ArctosDB/arctos/issues/1598

**Closed by dustymc** 2020-06-29 19:29 UTC
Labels: Function-Transactions, Priority-High
