### ISSUE TITLE
Request: Query Stats page text needs to state in monthly increments only

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7785] opened 2024-05-10 18:23 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

Dates are unusual when selecting a range for Query Stats

**To Reproduce**
1. Go to https://arctos.database.museum/info/queryStats.cfm
2. Click on 'Begin Date'
3. See weirdness

<img width="960" alt="Screenshot 2024-05-10 12 18 10" src="https://github.com/ArctosDB/arctos/assets/5725767/2e73b1dc-e333-430c-b4a9-2cbec174c554">

**Expected behavior**

I expect to get the normal calendar selection tool one gets in Arctos

![image](https://github.com/ArctosDB/arctos/assets/5725767/68f8c04c-5f6b-49fc-8763-87cb237c526b)

**Screenshots**

See above

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 125.0.0 (64 bit)

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment] 2024-05-13 23:00
This is an efficiency, not a bug.

**Comment by mkoo** [comment] 2024-05-16 04:47
well, to be more specific (or less mysterious), what I assume is the "efficiency" is just having monthly summaries so the dropdown is just yyyymm (no hyphen) (for maximum "efficiency" with characters!)

Then you get some quick stats (I use this for our annual reports) with a sum:
![Firefox_Screenshot_2024-05-16T04-38-28 368Z](https://github.com/ArctosDB/arctos/assets/2523089/51b2ef70-bdd5-40be-ba99-81806d4e71dc)

I dont think it's worth having anything more detailed than monthly stats rather than specific date ranges. But to make it easier to understand, perhaps adding a hyphen or spell out the month or first 3 letters (eg 2020 May, 2020 Jun) might be an improvement without sacrificing too much "efficiency"

**Comment by dustymc** [comment] 2024-05-16 15:31
@lkvoong and I could not make the scripts that gather the statistics perform with timestamp datatype. Integers are perfectly capable of representing dates in closed systems and do perform adequately (I presume due to how they're sorted in memory by the postgres optimizer, but we can likely get Lam to explain in detail if that's the point which needs clarification). If there's a need for timestamps then I think we'll need more hardware-or-something. If we need to transform to varchar then we'll probably need a lot more hardware-or-whatever.

If I've explained the wrong thing, or the right thing insufficiently, some background might help - the purpose of this question is not clear to me, maybe I'm way off base.

**Comment by Jegelewicz** [comment] 2024-05-20 22:43
If we do nothing - an explanation of what's going on right there on the page would at least help.

**Comment by mkoo** [comment] 2024-05-24 23:34
@dustymc Please add to the text blurb at top of page (I suggest you could start the text blurb with the following):
"Statistics for queries are available in monthly snapshots only."

**Comment by dustymc** [comment] 2024-05-28 13:47
> monthly snapshots only

<img width="124" alt="Screenshot 2024-05-24 at 16 36 13" src="https://github.com/ArctosDB/arctos/assets/5720791/a9f68e46-8abe-4ddc-a532-1a90a6ba9878">

Raw data are available.

**Comment by dustymc** [comment] 2024-08-27 17:51
Closing as inactionable; I don't know what needs to be and can be done, someone please reopen and clarify if I'm lost.

**Closed by dustymc** 2024-08-27 17:51 UTC
Labels: Priority-Normal (Not urgent), Display/Interface

**Comment by mkoo** [comment] 2024-08-28 16:44
there's no action item here save for some clarifying text
thx
