### ISSUE TITLE
Update Arctos collections map for website

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1595] opened 2018-07-03 18:46 UTC
Current map is out of date.
Is there a way to automate this so that when a collection is approved they are automatically added? Or add to mentor's tasks to update?

**Comment by mkoo** [comment] 2018-07-09 16:14
Currently probably more of a hassle to automate?! But maybe we can create
an easy to add form to populate the map....
let me look into that.
MK

**Comment by mkoo** [comment] 2018-07-09 20:56
OK, there is some broken links to the embedded map (partly because I didnt
set it up and partly Google's fault I'd like to say) so the best thing for
now is for you to add the new collections to this new spreadsheet for
mapping
<https://docs.google.com/spreadsheets/d/1hMIvp7yEWdCK09W-05Q60rUi7RMMG5bnsPDbHSSeFOI/edit#gid=0>,
which is also in the Arctos-Shared folder under Website. Once it's there I
will reload. I'll also look into a new non-Google method for this but not a
top priority
-thanks.

**Comment by Jegelewicz** [comment] 2018-07-09 21:30
I'll work on this!

**Comment by Jegelewicz** [comment] 2018-07-09 21:50
OK, I think all current collections with an MOU are on the sheet. I removed Cornell.

**Comment by dustymc** [comment] 2018-07-16 16:07
This is a partial duplicate of https://github.com/ArctosDB/arctos/issues/1554.

My vague plan was to require an address for institutions and use those data to create a map.

**Comment by mkoo** [comment] 2018-07-16 21:51
Well, for now, it's been updated. Keep adding institutions there and I can
update as needed. Alternatively we can build a little widgety thing as
Dusty suggests in the future.
Close?

**Comment by campmlc** [comment] 2018-07-16 22:23
I like the widgety thing idea. Separate issue?

**Closed** 2019-06-12 21:24 UTC
Labels: Display/Interface
