### ISSUE TITLE
Cannot create an agent because someone else with the same name already exists (but it's not the same person)

### ISSUE THREAD

**Issue by kmkocot** [ArctosDB/arctos#4530] opened 2022-04-08 23:55 UTC
I'm trying to create a new agent (Matthew Campbell: https://www.erskine.edu/staff-member/matthew-campbell/) but the problem is there is already an agent by the same name (https://arctos.database.museum/agents.cfm?agent_id=1018356) who is not the same person. I don't know 'my' Matthew Campbell's middle name or I would put it in.

# Error Text
```
There are potential problems with the agent you are trying to create.

    fatal: nocase preferred name match: Matthew Campbell [[ link ]](https://arctos.database.museum/agents.cfm?agent_id=1018356)
    advisory: name variant match: Matthew Campbell [[ link ]](https://arctos.database.museum/agents.cfm?agent_id=1018356)
    advisory: nocase first and last name match: Matthew Campbell [[ link ]](https://arctos.database.museum/agents.cfm?agent_id=1018356)
    advisory: nodots-nospaces match on agent name: Matthew Campbell [[ link ]](https://arctos.database.museum/agents.cfm?agent_id=1018356)

If you are absolutely sure that this agent is not a duplicate, you may click here to force creation

return to create agent form
```
When I click "click here to force creation" I get:

```
Something is missing!
May we suggest:

    Logging in and try again. Log in link to the upper right.
    On search pages, make sure you do not have values in fields that you do not mean to be there. Or try filling in fewer fields, the more likely to get a match.
    You may not have sufficient privileges to perform that operation. Consult with your supervisor or Arctos mentor.

This message has been logged as 8EBAF80E-472F-434C-9AA19C603107B124. Please [contact us](https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=contact&template=contact-arctos.md&title=error%20feedback) with any information that might help us to resolve this problem. For best results, include the error and a detailed description of how it came to occur in the Issue.
```

# Where it happened
I was trying to create a new Agent (Person)

# Steps to get there
Manage Data > Agents > Create Person
I entered "Matthew Campbell" into the Preferred Name box, Matthew in to the First Name box, Campbell into the Last Name box, and "Erskine College" into the Remarks box.

**Comment by dustymc** [comment] 2022-04-09 00:24
I'm calling this a duplicate of https://github.com/ArctosDB/arctos/issues/4524 - feel free to un-do that.

**Closed by dustymc** 2022-04-09 00:24 UTC
Labels: Error Messages, Error Explanation

**Comment by Jegelewicz** [comment] 2022-04-11 15:29
The current Matthew Campbell is an Arctos user - apparently with middle name A. according to his user profile. I added the middle initial to his preferred name - @kmkocot you should be able to create your Matthew Campbell now.
