### ISSUE TITLE
Verbatim Collector needs an upgrade

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4819] opened 2022-07-13 22:28 UTC
From #4164 

> Also, we should change "verbatim_collector" to something more general, "verbatim_agent" (or code it to reflect the original value selected, e.g. verbatim_preparator, verbatim_maker).

Today in Agent Committee we discussed this attribute and how it could be more robust. We looked at two different possibilities:

1. Create a "verbatim x" attribute for [every possible role a person or organization might play with regard to a catalog record](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollector_role). So we would have the following attributes: verbatim collector, verbatim preparator, verbatim creator, verbatim copyright holder, verbatim subject
2. Get rid of verbatim collector and instead use verbatim agent, BUT could we make "units" for this attribute be the roles given in [ctcollector_role](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollector_role) instead of trusting our happy fingers to type the correct role in the attribute remark?

We also want to recognize that this leaves out determiners of identification, event information, any other attributes and that we need to deal with verbatim information for those as well, but we will get to that.

**Comment by dustymc** [comment] 2022-07-18 15:17
Duplicate of https://github.com/ArctosDB/arctos/issues/1492

**Closed by dustymc** 2022-07-18 15:17 UTC
Labels: Priority-Normal (Not urgent), Function-Agents
