### ISSUE TITLE
Barcode vs Label vs Position sort order in Object Tracking?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4207] opened 2021-12-19 01:44 UTC
I thought I saw this issue raised again recently but can't find it. 
Can we discuss some sort of rational sorting of containers in object tracking - something that makes sense to humans?

1) Currently, positions, which don't have a barcode or label, sort utterly randomly even between one container and the next:
![image](https://user-images.githubusercontent.com/14808196/146660447-3de39b33-3590-4d51-a53c-d1d4bc7fe8f5.png)

Surely we can assign a numeric sort for position numbers and keep these consistent?

2) It's not clear to me whether the remaining container types are sorting by label or by barcode. Either way, Arctos sorts these as non-numeric, so we get the following:
![image](https://user-images.githubusercontent.com/14808196/146660587-7d58774e-aab6-4169-9208-12156d726278.png)

From a human perspective, it is extremely difficult to make sense of the object tracking hierarchy when this is the type of display we have to navigate.

Would it be possible for to have way to select the type of sort we want by collection or by container? Or drag and drop the display to sort in the way we prefer? Some sort of user control via the interface would be exceptionally helpful.

Priority: high. The more people using object tracking, and the more containers we add, the more difficult the interface is to navigate. We should come up with a coherent policy so we can at least provide adequate documentation for incoming collections who are starting to set up their object tracking.

**Comment by campmlc** [comment] 2021-12-19 01:45
And see first image above - why does G139 appear before G132, in either a barcode or label sort?

**Comment by Jegelewicz** [comment] 2021-12-19 14:21
Duplicate of #3050

**Closed by Jegelewicz** 2021-12-19 14:21 UTC
Labels: Priority-High (Needed for work), Function-ContainerOrBarcode, Display/Interface
