### ISSUE TITLE
Catalog Record page error messages

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6973] opened 2023-11-15 18:59 UTC
**Describe the bug**
Suddenly started getting error messages in the Catalog record page as below.
Error ID: 	3D5E6383-D1A0-42D6-A40EE6055C6B792D
<html>
<body>

ERROR_ID | 3D5E6383-D1A0-42D6-A40EE6055C6B792D
-- | --
ERROR_TYPE | java.io.IOException
ERROR_MESSAGE | org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections

</body>
</html>

</body>
</html>

**To Reproduce**
1. Search for a record or type in a url

**Screenshots**
![Screenshot 2023-11-15 11 54 50](https://github.com/ArctosDB/arctos/assets/14808196/383461e6-52e7-45ca-ab49-ef4628664664)

**Desktop (please complete the following information):**
Chrome

**Additional context**

**Priority**
High - impeding work and search function

**Comment by Jegelewicz** [comment] 2023-11-15 19:41
duplicate of #6970

**Closed by Jegelewicz** 2023-11-15 19:41 UTC
Labels: Bug
