### ISSUE TITLE
Order of Identifications

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#2406] opened 2019-12-06 21:58 UTC
Can you explain why 'Ardea alba' appears in the string of higher taxonomy classification beneath the species name for http://arctos.database.museum/guid/DMNS:Bird:16173? 
There clearly has been some disagreement over this taxa in the past and having another species name appear beneath the actual identification only adds to the confusion.
![image](https://user-images.githubusercontent.com/12507297/70359228-a09b7800-1838-11ea-81ec-966198fbfc6f.png)

**Comment by acdoll** [comment] 2019-12-06 22:03
Also, for a future enhancement, it would be great if we could manually order the identifications when we don't have a date of ID. The order can often be determined based on cross-outs/changes on tags which may not have a specific date indicated.

**Comment by dustymc** [comment] 2019-12-06 22:10
>explain why 'Ardea alba' appears i

You looked at it before the cache cleared, I think.

<img width="165" alt="Screen Shot 2019-12-06 at 2 08 50 PM" src="https://user-images.githubusercontent.com/5720791/70359931-f3256600-1831-11ea-8310-ba8289795bfc.png">

>order

New Issue - that's Major Surgery.

**Comment by acdoll** [comment] 2019-12-06 22:13
I'll try to be more patient in the future. And I figured the order idea could be a major change - just put a pin in that one for _someday_.

**Comment by Jegelewicz** [comment] 2021-12-13 14:54
Closing as duplicate of #3540

**Closed by Jegelewicz** 2021-12-13 14:54 UTC
Labels: Enhancement, Priority-Low (Wish list), Display/Interface
