### ISSUE TITLE
error feedback Error ID: 2C1C30AA-FC0A-4FDC-A516801D58AFAACF

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7154] opened 2023-12-31 22:47 UTC
Error ID: 2C1C30AA-FC0A-4FDC-A516801D58AFAACF
Trying to use bulk move container csv upload to move a csv list of container barcodes to a virtual loan container. Need help figuring out the error.

<html>
<body>

ERROR_ID | 2C1C30AA-FC0A-4FDC-A516801D58AFAACF
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: query returned no rows Where: PL/pgSQL function movecontainerbybarcode(character varying,character varying,character varying,character varying) line 69 at SQL statement
ERROR_DETAIL | Parameter types passed (4): CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR, CF_SQL_VARCHAR
ERROR_SQL | { call moveContainerByBarcode(?,?,?,?) }

</body>
</html>

[move container to DGR LOAN.zip](https://github.com/ArctosDB/arctos/files/13802328/move.container.to.DGR.LOAN.zip)

**Comment by campmlc** [comment] 2023-12-31 22:49
I was able to get this to work using csv paste mode, but not csv upload.

**Comment by dustymc** [comment] 2024-01-02 14:40
duplicate of https://github.com/ArctosDB/arctos/issues/4290

**Closed by dustymc** 2024-01-02 14:40 UTC
Labels: contact
