### ISSUE TITLE
Help merging localities

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6534] opened 2023-07-19 19:51 UTC
One of the promises we make is the ability to use previously georeferenced localities.  Right now in Arctos there are these two localities:

https://arctos.database.museum/place.cfm?action=detail&locality_id=10077936
https://arctos.database.museum/place.cfm?action=detail&locality_id=11631718

That share higher geography and specific locality, but only the first one has coordinates.

I'd like to move all the records using the second to the first and eliminate the one without coordinates as an unnecessary and lower quality duplicate.

The Check Dups function in locality search results does not seem to work. Selecting it gets me an error

<html><body>

ERROR_ID | 369222F2-25E2-4FCA-994944132D224FB3
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: syntax error at or near "<"   Position: 649
ERROR_DETAIL |  
ERROR_SQL | select 			LOCALITY_ID, 			GEOG_AUTH_REC_ID, 			SPEC_LOCALITY, 			DEC_LAT, 			DEC_LONG, 			MINIMUM_ELEVATION, 			MAXIMUM_ELEVATION, 			ORIG_ELEV_UNITS, 			MIN_DEPTH, 			MAX_DEPTH, 			DEPTH_UNITS, 			MAX_ERROR_DISTANCE, 			MAX_ERROR_UNITS, 			DATUM, 			LOCALITY_REMARKS, 			GEOREFERENCE_SOURCE, 			GEOREFERENCE_PROTOCOL, 			LOCALITY_NAME, 			getLocalityAttributesAsJson(locality_id)::varchar localityAttrs, 			ST_AsText(locality_footprint) as locality_footprint,             primary_spatial_data 			from 			locality 			where 			locality_id != 10077936 and  		 			 				GEOG_AUTH_REC_ID=10002172 and

</body>
</html>

Manage locality from catalog record search doesn't give me any options other than the locality the records are already in.

I suppose I can copy coordinates from the georeferenced locality to the ungeoreferenced one and wait for them to merge, but that seems like a kludgy way to do this?

Probably I am missing something so any advice on making this easier is appreciated!

**Comment by dustymc** [comment] 2023-07-19 19:55
Duplicate of https://github.com/ArctosDB/arctos/issues/6472

**Closed by dustymc** 2023-07-19 19:55 UTC
Labels: Priority-Normal (Not urgent), Function-Locality/Event/Georeferencing, Help wanted, Error Messages, Data Quality
