### ISSUE TITLE
can't save new records into the bulkloader

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2340] opened 2019-10-28 19:05 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

A lab tech of mine just reported this problem and I tried it under my own log in and a different collection and same issue - complete a new record to save into the bulkloader, click 'save as new record' and get a popup message 'edit template bad'

and this down below:
Error Executing Database Query.; [Macromedia][Oracle JDBC Driver][Oracle]ORA-01747: invalid user.table.column, table.column, or column specification ; INSERT INTO bulkloader ( COLLECTION_OBJECT_ID , LOADED , ENTEREDBY , CAT_NUM , OTHER_ID_NUM_5 , OTHER_ID_NUM_TYPE_5 , OTHER_ID_NUM_1 , OTHER_ID_NUM_TYPE_1 , ACCN , TAXON_NAME , NATURE_OF_ID , ID_MADE_BY_AGENT , MADE_DATE , IDENTIFICATION_REMARKS , VERBATIM_DATE , BEGAN_DATE , ENDED_DATE , HIGHER_GEOG , SPEC_LOCALITY , VERBATIM_LOCALITY , ORIG_LAT_LONG_UNITS , DEC_LAT , DEC_LONG , LATDEG , DEC_LAT_MIN , LATMIN , LATSEC , LATDIR , LONGDEG , DEC_LONG_MIN , LONGMIN , LONGSEC , LONGDIR , DATUM , GEOREFERENCE_SOURCE , MAX_ERROR_DISTANCE , MAX_ERROR_UNITS , GEOREFERENCE_PROTOCOL , EVENT_ASSIGNED_BY_AGENT , EVENT_ASSIGNED_DATE , VERIFICATIONSTATUS , MAXIMUM_ELEVATION , MINIMUM_ELEVATION , ORIG_ELEV_UNITS , LOCALITY_REMARKS , HABITAT , COLL_EVENT_REMARKS , COLLECTOR_AGENT_1 , COLLECTOR_ROLE_1 , COLLECTOR_AGENT_2 , COLLECTOR_ROLE_2 , COLLECTOR_AGENT_3 , COLLECTOR_ROLE_3 , COLLECTOR_AGENT_4 , COLLECTOR_ROLE_4 , COLLECTOR_AGENT_5 , COLLECTOR_ROLE_5 , GUID_PREFIX , FLAGS , COLL_OBJECT_REMARKS , OTHER_ID_NUM_2 , OTHER_ID_NUM_TYPE_2 , OTHER_ID_NUM_3 , OTHER_ID_NUM_TYPE_3 , OTHER_ID_NUM_4 , OTHER_ID_NUM_TYPE_4 , PART_NAME_1 , PART_CONDITION_1 , PART_BARCODE_1 , PART_LOT_COUNT_1 , PART_DISPOSITION_1 , PART_REMARK_1 , PART_NAME_2 , PART_CONDITION_2 , PART_BARCODE_2 , PART_LOT_COUNT_2 , PART_DISPOSITION_2 , PART_REMARK_2 , PART_NAME_3 , PART_CONDITION_3 , PART_BARCODE_3 , PART_LOT_COUNT_3 , PART_DISPOSITION_3 , PART_REMARK_3 , PART_NAME_4 , PART_CONDITION_4 , PART_BARCODE_4 , PART_LOT_COUNT_4 , PART_DISPOSITION_4 , PART_REMARK_4 , PART_NAME_5 , PART_CONDITION_5 , PART_BARCODE_5 , PART_LOT_COUNT_5 , PART_DISPOSITION_5 , PART_REMARK_5 , PART_NAME_6 , PART_CONDITION_6 , PART_BARCODE_6 , PART_LOT_COUNT_6 , PART_DISPOSITION_6 , PART_REMARK_6 , PART_NAME_7 , PART_CONDITION_7 , PART_BARCODE_7 , PART_LOT_COUNT_7 , PART_DISPOSITION_7 , PART_REMARK_7 , PART_NAME_8 , PART_CONDITION_8 , PART_BARCODE_8 , PART_LOT_COUNT_8 , PART_DISPOSITION_8 , PART_REMARK_8 , PART_NAME_9 , PART_CONDITION_9 , PART_BARCODE_9 , PART_LOT_COUNT_9 , PART_DISPOSITION_9 , PART_REMARK_9 , PART_NAME_10 , PART_CONDITION_10 , PART_BARCODE_10 , PART_LOT_COUNT_10 , PART_DISPOSITION_10 , PART_REMARK_10 , PART_NAME_11 , PART_CONDITION_11 , PART_BARCODE_11 , PART_LOT_COUNT_11 , PART_DISPOSITION_11 , PART_REMARK_11 , PART_NAME_12 , PART_CONDITION_12 , PART_BARCODE_12 , PART_LOT_COUNT_12 , PART_DISPOSITION_12 , PART_REMARK_12 , ATTRIBUTE_1 , ATTRIBUTE_VALUE_1 , ATTRIBUTE_REMARKS_1 , ATTRIBUTE_DATE_1 , ATTRIBUTE_DET_METH_1 , ATTRIBUTE_DETERMINER_1 , ATTRIBUTE_2 , ATTRIBUTE_VALUE_2 , ATTRIBUTE_REMARKS_2 , ATTRIBUTE_DATE_2 , ATTRIBUTE_DET_METH_2 , ATTRIBUTE_DETERMINER_2 , ATTRIBUTE_3 , ATTRIBUTE_VALUE_3 , ATTRIBUTE_REMARKS_3 , ATTRIBUTE_DATE_3 , ATTRIBUTE_DET_METH_3 , ATTRIBUTE_DETERMINER_3 , ATTRIBUTE_4 , ATTRIBUTE_VALUE_4 , ATTRIBUTE_REMARKS_4 , ATTRIBUTE_DATE_4 , ATTRIBUTE_DET_METH_4 , ATTRIBUTE_DETERMINER_4 , ATTRIBUTE_5 , ATTRIBUTE_VALUE_5 , ATTRIBUTE_REMARKS_5 , ATTRIBUTE_DATE_5 , ATTRIBUTE_DET_METH_5 , ATTRIBUTE_DETERMINER_5 , ATTRIBUTE_6 , ATTRIBUTE_VALUE_6 , ATTRIBUTE_REMARKS_6 , ATTRIBUTE_DATE_6 , ATTRIBUTE_DET_METH_6 , ATTRIBUTE_DETERMINER_6 , ATTRIBUTE_7 , ATTRIBUTE_VALUE_7 , ATTRIBUTE_REMARKS_7 , ATTRIBUTE_DATE_7 , ATTRIBUTE_DET_METH_7 , ATTRIBUTE_DETERMINER_7 , ATTRIBUTE_8 , ATTRIBUTE_VALUE_8 , ATTRIBUTE_REMARKS_8 , ATTRIBUTE_DATE_8 , ATTRIBUTE_DET_METH_8 , ATTRIBUTE_DETERMINER_8 , ATTRIBUTE_9 , ATTRIBUTE_VALUE_9 , ATTRIBUTE_REMARKS_9 , ATTRIBUTE_DATE_9 , ATTRIBUTE_DET_METH_9 , ATTRIBUTE_DETERMINER_9 , ATTRIBUTE_10 , ATTRIBUTE_VALUE_10 , ATTRIBUTE_REMARKS_10 , ATTRIBUTE_DATE_10 , ATTRIBUTE_DET_METH_10 , ATTRIBUTE_DETERMINER_10 , MIN_DEPTH , MAX_DEPTH , DEPTH_UNITS , COLLECTING_METHOD , COLLECTING_SOURCE , ASSOCIATED_SPECIES , LOCALITY_ID , UTM_ZONE , UTM_EW , UTM_NS , GEOLOGY_ATTRIBUTE_1 , GEO_ATT_VALUE_1 , GEO_ATT_DETERMINER_1 , GEO_ATT_DETERMINED_DATE_1 , GEO_ATT_DETERMINED_METHOD_1 , GEO_ATT_REMARK_1 , GEOLOGY_ATTRIBUTE_2 , GEO_ATT_VALUE_2 , GEO_ATT_DETERMINER_2 , GEO_ATT_DETERMINED_DATE_2 , GEO_ATT_DETERMINED_METHOD_2 , GEO_ATT_REMARK_2 , GEOLOGY_ATTRIBUTE_3 , GEO_ATT_VALUE_3 , GEO_ATT_DETERMINER_3 , GEO_ATT_DETERMINED_DATE_3 , GEO_ATT_DETERMINED_METHOD_3 , GEO_ATT_REMARK_3 , GEOLOGY_ATTRIBUTE_4 , GEO_ATT_VALUE_4 , GEO_ATT_DETERMINER_4 , GEO_ATT_DETERMINED_DATE_4 , GEO_ATT_DETERMINED_METHOD_4 , GEO_ATT_REMARK_4 , GEOLOGY_ATTRIBUTE_5 , GEO_ATT_VALUE_5 , GEO_ATT_DETERMINER_5 , GEO_ATT_DETERMINED_DATE_5 , GEO_ATT_DETERMINED_METHOD_5 , GEO_ATT_REMARK_5 , GEOLOGY_ATTRIBUTE_6 , GEO_ATT_VALUE_6 , GEO_ATT_DETERMINER_6 , GEO_ATT_DETERMINED_DATE_6 , GEO_ATT_DETERMINED_METHOD_6 , GEO_ATT_REMARK_6 , COLLECTING_EVENT_ID , SPECIMEN_EVENT_REMARK , SPECIMEN_EVENT_TYPE , LOCALITY_NAME , COLLECTING_EVENT_NAME , OTHER_ID_REFERENCES_1 , OTHER_ID_REFERENCES_2 , OTHER_ID_REFERENCES_3 , OTHER_ID_REFERENCES_4 , WKT_MEDIA_ID , ) values ( bulkloader_PKEY.nextval , 'waiting approval' , 'ffdss' , '' , '' , '' , '' , '' , '[UAMObs:Ento]UAM-2012.06-un-Ento' , 'Neonothrus' , 'coarse features' , 'unknown' , '' , 'test' , 'test' , '2019-10-28' , '2019-10-28' , 'North America, United States, Alaska' , 'test' , 'test' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'unknown' , '2019-10-28' , 'unverified' , '' , '' , '' , '' , '' , '' , 'unknown' , 'collector' , '' , 'collector' , '' , 'collector' , '' , 'collector' , '' , 'collector' , 'UAMObs:Ento' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , '' , 'collection' , '' , '' , '' , '' , '' , '' , '' , ) 

**To Reproduce**

**Expected behavior**

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. HIGH

**Comment by Jegelewicz** [comment] 2019-10-28 19:10
Duplicate of #2341

**Closed** 2019-10-29 14:10 UTC
Labels: Bug, Function-DataEntry/Bulkloading, Priority-High
