### ISSUE TITLE
make creating new accounts more user friendly

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#879] opened 2016-05-12 17:12 UTC
The following came out of discussion with Teresa Mayfield, who is managing UTEP collections and starting as a new Arctos user. Creating new accounts is confusing.

If you hit "Create Account" without entering a username and password, it takes you to:

http://arctos.database.museum/login.cfm?username=Username&badPW=true&err=That%20username%20is%20already%20in%20use.

...with "username" filled out in the "Username" field and the warning "That username is already in use"

This is confusing.

Instead of that warning and having "username" already filled it, it would be better to have a blank "Username" field (with 'username' just as tip in the field, but not actually entered in to the field. Similar to 'password' in the upper right at http://arctos.database.museum/

Then above "Lost your password," add the following sentence:

"Creating a new account? Enter a username and password before you hit "Create an Account"

Somewhere on that page, it would also be useful to have these tips because I always have to tell that to new users:

-- DO NOT INCLUDE a period in your username (e.g., arctos.database is not a valid username)
-- Passwords should be at least six characters, start with a letter, contain only A-Z, a-z, 0-9, and !$%&()`*+,-/:;?_., not contain the username, and consist of at least one letter, number, and special character

**Comment by dustymc** [comment] 2016-05-12 17:22
There are three issues addressing the same things open - I'm closing this as a duplicate of #878

**Closed by dustymc** 2016-05-12 17:22 UTC
Labels: Function-Users, Priority-High, Type-Form/Function
