### ISSUE TITLE
Feature Request - might be duplicate agent relationship

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5056] opened 2022-09-14 19:47 UTC
**Is your feature request related to a problem? Please describe.**

Sometimes there's a hint that agents might be duplicated but more investigation is needed.

**Describe what you're trying to accomplish** 

Merge or differentiate, but not too urgently.

**Describe the solution you'd like**

new relationship, new handlers

* creating relationship fires a notification
* XXXX time (3 months??) after relationship is created, auto-upgraded to 'bad duplicate of' (==new notification, etc.)

**Describe alternatives you've considered**

Use Issues

**Additional context**

@Jegelewicz @droberts49 

**Priority**

?

**Comment by Jegelewicz** [comment] 2022-09-14 22:15
I like it and I like the 3 month window.

New agent relationship

potential duplicate of - This agent appears to be a duplicate of the related agent. If the [not the same as](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship#not_the_same_as) relationship is not added within 90 days the relationship will be changed to [bad duplicate of](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship#bad_duplicate_of), marking the agents for merger.

Note that I also think we need to change the definition for [bad duplicate of](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship#bad_duplicate_of) and I suggest

This agent has been marked as a duplicate of the related agent. If the [not the same as](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship#not_the_same_as) relationship is not added within 14 days the agents will be merged.

**Comment by dustymc** [comment] 2022-09-14 22:51
I don't think its that clearcut, and we definitely don't want eg not that same as --> unknown. Adding whatever leads you to believe they're not the same - relationships, dates, addresses/identifiers - should clear everything up.

And from that, I think we should probably strive to remove the 'not the same as' relationship. I suggest the documentation be updated ("don't use this in lieu of actual data...") and then we can revisit "mañana" (in a couple years, when all other agent problems have been solved...)

**Comment by lin-fred** [comment] 2022-10-12 20:15
Arctos Committee:

Add the potential duplicate of relationship option for now with @Jegelewicz defintion:

potential duplicate of - This agent appears to be a duplicate of the related agent. If the [not the same as](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship#not_the_same_as) relationship is not added within 90 days the relationship will be changed to [bad duplicate of](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctagent_relationship#bad_duplicate_of), marking the agents for merger.

Update the 'not the same as relationship' definition with 'don't use this in lieu of actual data' @Jegelewicz (code table request?)

If we want to get rid of 'not the same as relationship' for the future-need something in the agent page that makes a remark that John Smith is not the same as John Smith - discuss next year.

**Comment by lin-fred** [comment] 2022-10-12 21:04
see #5158 to discuss further

**Closed by lin-fred** 2022-10-12 21:04 UTC
Labels: Enhancement
