### ISSUE TITLE
add disposition to parts in part locations view

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1424] opened 2018-02-05 23:17 UTC
We often get loan requests for a certain taxon. After searching for this taxon we often use the part locations view to track down the specimens... however, sometimes some of these specimens are already on loan. It would be nice to have the part dispositions tacked on to each part in the part location view so we can easily tell what's actually present vs not.

**Comment by dustymc** [comment] 2022-08-01 21:57
duplicate of https://github.com/ArctosDB/arctos/issues/1669

**Closed by dustymc** 2022-08-01 21:57 UTC
Labels: Blocked
