### ISSUE TITLE
Need to Separate Paleontology and Geology from ES

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3418] opened 2021-02-10 14:32 UTC
Greetings,

As discussed previously, ALMNH would prefer to separate out the Paleo and the Geo from the ES moniker. I understand this is problematic, but it's better than waiting until after the Geology data are added. We need to channel the Paleo into GBIF and iDigBio and can't do that until we get these separated.

Please advise...and thanks!
Mary Beth

**Comment by dustymc** [comment] 2021-02-10 16:14
Duplicate of https://github.com/ArctosDB/arctos/issues/3409

**Comment by mbprondzinski** [comment] 2021-02-10 16:25
Why am I

**Comment by mbprondzinski** [comment] 2021-02-10 16:27
why am I not receiving this thread?  I entered an issue 9 days ago and was ignored and now I see I wasn't notified about this.  I thought I was part of ALMNH????

**Comment by mbprondzinski** [comment] 2021-02-10 16:27
Adiel wants "Geo"

**Closed** 2021-02-10 18:50 UTC
Labels: contact
