### ISSUE TITLE
Flatten Part Locations Not Working?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1408] opened 2018-01-17 01:57 UTC
When I go to find the following list of barcodes in Find Container, and click Flatten Part Locations, nothing appears. But if I double click on any of the cryovials, I see cataloged specimen parts associated with those barcodes. And once I do that, if I click on Flatten Part Location again, any parts I have double clicked show up.

A6CE0,A6CE1,A6CE3,A6CE4,A6CE5,A6CE6,A6CE7,A6CE8,A6CE9,A6CEK,A6CEA,A6CEB,A6CEC,A6CED,A6CEE,A6CEF,A6CEG,A6CEH,A6CEI,A6CEJ,A6CEL,A6CEM,A6CEN,A6CEO,A6CEP,A6CEQ,A6CER,A6CES,A6CET,A6CEU,A6CEV,A6CEW,A6CEX,A6CEY,A6CEZ,A6CF0,A6CF1,A6CF2,A6CF3,A6CF4,A6CF5,A6CF6,A6CF7,A6CF8,A6CF9,A6CFA,A6CFB,A6CFC,A6CFD,A6CFE,A6CFF,A6CFG,A6CFH,A6CFJ,A6CFI,A6CGZ,A6CH0,A6CH1,A6CH2,A6CH3,A6CH4,A6CH5,A6CH6,A6CH7,A6CH8,A6CH9,A6CHA,A6CHB,A6CHC,A6CHD,A6CHE,A6CHF,A6CHG,A6CHH,A6CHI,A6CHJ,A6CHK,A6CHL,A6CHM,A6CHN,A6CHO,cut,cut,A6CHP,A6CHR,A4CPI,A4CT3,A6CHS,A4CMX,A4CIB,A4CJC,A4CNG,A4C1C,A4CJY,A4CFT,A4CHJ,A4C1T,A4C19,A3CFD,A3CIK,A3CLS

**Comment by dustymc** [comment] 2018-01-17 02:16
Duplicate of https://github.com/ArctosDB/arctos/issues/1329

**Closed by dustymc** 2018-01-17 02:16 UTC
