### ISSUE TITLE
Convert "age" data to "age class"

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#6315] opened 2023-05-19 17:02 UTC
Hey Dusty,
As discussed yesterday, in an effort to clean things up could you please do some moving for us? 
Move all values in "age" into "age class" that are currently compatible with controlled vocabulary in "age class" table.
Move all values from "age" that are numbers or numbers and text into "numeric age"
Thanks!

[MSB age_age class conversion.csv](https://github.com/ArctosDB/arctos/files/11518937/MSB.age_age.class.conversion.csv)

**Comment by dustymc** [comment] 2023-05-22 16:05
I'm not entirely clear on what's being asked, but I think this should probably be an ADDITIVE process - eg 

MSB:Mamm:327491 adult   15 Years 23 Days

seems like a very lossy conversion, it would be better to ADD 'adult' (actually it would be much better to convert to numeric age in days, and I'm probably not ever going to understand how or why that's seen as some insurmountable obstacle during data entry).

Related, one of the RANGES discussions strongly suggests that eg 'adult' is near-meaningless without method - is that an actual-age summary/conversion, skull sutures, pelage, tooth wear, reproductive condition, ??????

ANYWAY, if adding seems OK, there is an attribute loader which should easily handle your proposal.


While I was here, I went through all age data....

[temp_age.csv.zip](https://github.com/ArctosDB/arctos/files/11533310/temp_age.csv.zip)


and put anything that could be in age class in p_age_class, and anything that could be in numeric age in (p_n_age,p_n_ageunit).

There's probably more that could be recovered by a person.

These collections have something in those:


```


 guid_prefix | count 
-------------+-------
 ALMNH:Bird  |     1
 ASNHC:Bird  |     1
 ASNHC:Mamm  |     7
 CHAS:Bird   |     4
 CHAS:Mamm   |     1
 CHAS:Teach  |     8
 DMNS:Bird   |   732
 DMNS:Mamm   |    32
 MLZ:Bird    |    19
 MLZ:Mamm    |     1
 MMNH:Bird   |     1
 MMNH:Mamm   |   147
 MSB:Bird    |   401
 MSB:Mamm    |  6392
 MSB:Para    |     7
 MVZ:Bird    |  6470
 MVZ:Mamm    |   228
 MVZObs:Bird |   842
 NMMNH:Bird  |     3
 UAM:Bird    |     1
 UAM:Mamm    |    37
 UCM:Bird    |    47
 UCM:Mamm    |     9
 UMNH:Bird   |    11
 UMZM:Bird   |   504
 UMZM:Mamm   |  1658
 UNCG:Para   |    20
 UNR:Bird    |    38
 UTEP:Bird   |     5
 UWBM:Mamm   |    88
 UWYMV:Bird  |   103
(31 rows)


```
and users:

 @jrdemboski
 @amgunderson
 @jldunnum
 @catherpes
 @msbparasites
 @AdrienneRaniszewski
 @campmlc
 @barke042
 @adhornsby
 @ccicero
 @mkoo
 @cjconroy
 @jebrad
 @ewommack
 @sharonjansa
 @mvzhuang
 @acdoll
 @bryansmclean
 @lin-fred
 @ebraker
 @droberts49
 @kderieg322079
 @wellerjes
 @makaylaeasley
 @babogan
(25 rows)


It should be relatively easy to get those data into the attribute loaders as well, or let me know if I can help.

**Comment by Jegelewicz** [comment] 2023-05-22 16:33
Some of this would also benefit from life events - https://github.com/ArctosDB/arctos/issues/6115

**Comment by Jegelewicz** [comment] 2023-05-22 16:53
The counts above don't match the file - ALMNH Bird had two - so probably best for people to check them via search or looking at the attached file.

**Comment by jldunnum** [comment] 2023-05-22 17:40
That example and probably most of our numeric age data came from zoo animals and was entered or migrated from their database in whatever form they currently are. I would prefer to just get things in the correct places to start with and then we could think about other clean up.

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by dustymc** [comment] 2023-05-22 18:08
>ALMNH Bird had two 

The report is for things that can be directly converted. ALMNH:Bird has one of those, as reported, among two total records with ``age`` data. (But one would be an easy transformation, so maybe these data are worth more digging.)

```
Time: 34.657 ms
arctosprod@arctos>> select guid, attribute_value,p_age_class,p_n_age from temp_age where guid_prefix='ALMNH:Bird' order by p_age_class,p_n_age;
     guid     | attribute_value | p_age_class | p_n_age 
--------------+-----------------+-------------+---------
 ALMNH:Bird:2 | adult           | adult       | 
 ALMNH:Bird:5 | Adult           |             | 
(2 rows)

```

**Comment by campmlc** [comment] 2023-05-22 18:21
It would be good if we could discuss the MSB migration as all the zoo
animals recently were bulkloaded in a certain format and I'd like to make
sure we coordinate this. I'm in the field but can address when I get back.

**Comment by dustymc** [comment] 2023-08-01 15:27
Can I move anything or should this be closed?

**Comment by campmlc** [comment] 2023-08-01 15:45
I thought @jldunnum was requesting to add data, but not remove the older data? We have several thousand zoo tissues from living animals that could have metadata added to the attribute- e.g. the age date was taken from the ZIMS database on or near the date of catalog record entry, so we could add determination date. But that was a separately funded project and there are no staff or resources to address right now.

**Comment by dustymc** [comment] 2023-08-01 16:01
@jldunnum asked to move, not add. There are a few thousand records for which I could do that. If I'm going to do something, I'd like to do it once rather than once per collection. I'm not sure why the records for which I can't do that are involved.

**Comment by campmlc** [comment] 2023-08-01 16:04
It's only the zoo animals that may be a problem, but I'm happy for you to
move anything that can easily be moved.

**Comment by jldunnum** [comment] 2023-08-01 16:09
Yes my request was just to move data from "age" to "age class" . That won't fully clean up MSB data but will be a start

______________________________________________________________

Jonathan L. Dunnum Ph.D. (he, him, his)
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

Chair, Systematic Collections Committee, American Society of Mammalogists
Latin American Fellowship Committee, ASM

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by Jegelewicz** [comment] 2023-08-01 16:24
I just looked at ALMNH:Bird2 and ALMNH:Bird:5 and they both have age_class = adult, nothing in age. What am I missing?

**Comment by ccicero** [comment] 2023-08-01 16:28
I don't have time now to read this whole thread, but MVZ uses 'age' for birds instead of age class because the data are too messy to put into simple classes. It looks like what's being asked is data clean-up for specific collections, not eliminating 'age' as a field. Is that correct? We need to keep age as a text field.

**Comment by Jegelewicz** [comment] 2023-08-01 16:30
@jebrad I suggest that you let Dusty transform all of your age attributes that = "adult" to age class = adult.

**Comment by dustymc** [comment] 2024-02-16 18:03
Anything left should be redirected to life stage, age class is scheduled for removal, closing.

**Closed by dustymc** 2024-02-16 18:03 UTC
Labels: contact
