### ISSUE TITLE
Feature Request - re-add attribute "Value" as option for search results

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#7835] opened 2024-06-03 21:51 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
I regularly need to be able to see and download the attribute "value" when I do searches. After most of the attributes got squished into "Attribute Detail" I no longer have a usable way to download a group of items I'm sending out for loan with a detailed list of individual insurance values listed in a single clean column.

**Describe what you're trying to accomplish** 
I need to be able to search for a group of items, or produce my entire collection with a downloadable or printable view of the selection plus their individual values on the same line, without extracting from the entire attribute detail column that looks like this:

    "attribute_date": "2014-09-30",
    "attribute_type": "culture of origin",
    "attribute_units": null,
    "attribute_value": "Yup'ik",
    "attribute_method": null,
    "attribute_remark": null,
    "attribute_determiner": "unknown"
  },
  {
    "attribute_date": "2014-09-30",
    "attribute_type": "culture of use",
    "attribute_units": null,
    "attribute_value": "Yup'ik",
    "attribute_method": null,
    "attribute_remark": null,
    "attribute_determiner": "unknown"
  },
  {
    "attribute_date": "2014-09-30",
    "attribute_type": "description",
    "attribute_units": null,
    "attribute_value": "Drum head made of walrus stomach. Image of woman with lamp, standing next to four sleeping figures. All human figures are inside a circle. Around outside of circle are 13 wolves. All images on drumhead are painted in black ink. Diameter 76.5 cm.",
    "attribute_method": null,
    "attribute_remark": null,
    "attribute_determiner": "unknown"
  },
  {
    "attribute_date": "2014-09-30",
    "attribute_type": "materials",
    "attribute_units": null,
    "attribute_value": "Stomach Paint",
    "attribute_method": null,
    "attribute_remark": null,
    "attribute_determiner": "unknown"
  },
  {
    "attribute_date": "2005-09-11",
    "attribute_type": "value",
    "attribute_units": "US dollar",
    "attribute_value": "3000",
    "attribute_method": "appraisal",
    "attribute_remark": " Value has been based on a conversation with Joe Crusey at 09/10/2005 opening when he stated that \"all his appraisals that were done in '98 and prior should be double now\"",
    "attribute_determiner": "Joe Crusey"

**Describe the solution you'd like**
Other attributes have been added back into the search results option:
<img width="537" alt="Screenshot 2024-06-03 at 1 33 46 PM" src="https://github.com/ArctosDB/arctos/assets/17605945/4b9a3351-a61b-4c97-a5e4-9c2e6f3051f5">

Please add Value as a standalone attribute that can be displayed in the search results column and be downloaded into a sortable and tally-able CSV file (i.e., I need to be able to SUM that column to confirm the overall appraised value of a group of items).

**Describe alternatives you've considered**
A whole lot of more complicated downloads and data extractions in Excel/Sheets that I don't have the will to learn how to do...

**Additional context**
I used to be able to add one year's additions in my [spreadsheet like this](https://docs.google.com/spreadsheets/d/1-mpbIGmDYqSS47zE8x8qkENo_waPtTJH8eLHFr5QPmE/edit?usp=sharing), tally them up, and add them to my required annual insurance assessment to the university risk management. Now I don't even know how to start the process...

**Priority**
Critical - due in 2 weeks to university risk management.

**Comment by AJLinn** [comment] 2024-06-03 22:58
See also #7433 for my first cry for help with this issue back in February 2024.

**Comment by dustymc** [comment] 2024-06-03 23:38
> downloaded into a sortable and tally-able CSV file 

<img width="254" alt="Screenshot 2024-06-03 at 16 25 38" src="https://github.com/ArctosDB/arctos/assets/5720791/1deaadfb-c3a2-455b-b698-f0625d6023ff">

There are several download options there, perhaps one of them is what you're looking for.

I have no objections to adding this to the cache, but there are big-picture sustainability concerns which I'm unsure how to address. There are a finite number of possible columns, backups and replication are affected, it's just a "forever expense" that should be avoided if it can be (and paid if it must be, probably). @ArctosDB/arctos-working-group-officers help????


> February 2024

@mkoo @Jegelewicz that shouldn't happen, I'm completely overwhelmed in Issues (and suspect I'm not alone in that), can we meet up (and invite anyone willing to help!) and see if we can find some way to get the actionable/functional/whatever-this-is Issues to the top of the pile? (As a start, maybe I should close all of https://github.com/ArctosDB/arctos/issues?q=is%3Aopen+is%3Aissue+milestone%3Amystery a week after they're flagged or something; I'm up for anything, other than continually getting lost in the weeds of 455 issues, most of which I don't know how to address....)

**Comment by Jegelewicz** [comment] 2024-06-04 14:34
@AJLinn I am closing this as a duplicate of #7433

**Closed by Jegelewicz** 2024-06-04 14:34 UTC
Labels: Priority-Critical (Arctos is broken), Function-SearchOrDownload, Enhancement, Curatorial Search
