### ISSUE TITLE
Can't review items on a large loan

### ISSUE THREAD

**Issue by mgoliver** [ArctosDB/arctos#1285] opened 2017-10-02 21:11 UTC
I need to review the specimens that are on the loan UAM:Herb 2016.3.Herb in order to remove four items from it (they're duplicate records and need to be deleted). It contains 38651 items, but when I select "Review Items" nothing shows up in the list. The only option it gives me is to remove everything from the loan.
![screen shot 2017-10-02 at 1 05 32 pm](https://user-images.githubusercontent.com/28404497/31099570-f06632f0-a772-11e7-89f9-40f226684388.png)
![screen shot 2017-10-02 at 1 05 10 pm](https://user-images.githubusercontent.com/28404497/31099576-f3fb805a-a772-11e7-8856-537d9a56a8b8.png)

**Comment by dustymc** [comment] 2017-10-02 21:19
Loan size is not the problem - that's a data loan.

Duplicate of #959

I can remove the items - I need their GUID.

**Closed by dustymc** 2017-10-02 21:19 UTC

**Comment by mgoliver** [comment] 2017-10-02 21:23
Thanks, Dusty
UAM:Herb:244179
UAM:Herb:251511
UAM:Herb:251512
UAMb:Herb:10630
