### ISSUE TITLE
Allow multiple user accounts with different permissions for single agent

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3586] opened 2021-04-28 21:53 UTC
See #2636
Here are two actual examples of the problem we need a solution for - requiring different accounts for the same agent.
1) In DGR, students must have data entry, manage specimen and object tracking access to all collections whose tissues are archived in the division. This is MSB:Mamm, MSB:Bird, MSB:Herp, MSB:Fish, and MSB:Para. If any of these students also works in a different division, e.g. MSB:Bird, they may have been given additional permissions beyond this basic access - e.g perhaps they bulkload specimens or help with loans in that division. If so, then in the current scenario, they will have these advanced permissions across all the collections they have access to in DGR. This is not acceptable. They should be able to be given basic permissions for an account that has access to multiple divisions, but advanced permissions under a different login associated with the same agent name for a single division.

2) MSB and NMMNHS have a collaboration where students and staff assist with different curatorial projects across institutions. In order to give an NMMNHS staff member access to an MSB division, e.g. for object tracking, we currently have to allow them the same access privileges they have in their home institution, e.g transactions and/or manage collection. Again, unacceptable. We have managed a work-around by creating a "staff" agent with limited permissions to work across institutions. However, that means the actual agent doing the work does not get credit for the work they do, and it functionally means that a single agent has multiple login accounts with different permissions.

Priority: High

**Comment by dustymc** [comment] 2021-04-28 21:57
I don't think there are any technical problem with that, but it would require a fair bit of development, starting with un-doing the preferred name bits of #579 (comment).

**Comment by Jegelewicz** [comment] 2021-04-29 01:22
I assume you are talking about this:

> "Lasted edited by" agent should show the preferred name of the agent, not the login name. Login name is not useful. This is an issue for Specimen Detail page, anyplace else where "Last edited by" agent occurs.

and I don't get the problem. "showing" the preferred name doesn't mean that is what is stored, right?

**Comment by dustymc** [comment] 2021-04-29 14:36
>doesn't mean that is what is stored

Bit of both. Mine are usually username (it's easier to get), the most "coreward" example of using Agent is...

```
arctosprod@arctosutf>> \d coll_object
                               Table "public.coll_object"
          Column          |            Type             | Collation | Nullable | Default 
--------------------------+-----------------------------+-----------+----------+---------
 collection_object_id     | bigint                      |           | not null | 
 entered_person_id        | bigint                      |           | not null | 
 coll_object_entered_date | timestamp without time zone |           | not null | 
 last_edited_person_id    | bigint                      |           |          | 
 last_edit_date           | timestamp without time zone |           |          | 

```

I do think it would be USEFUL to have by-user data - maybe your A user can see stuff your B user can't and your A user makes more mistakes because of that or etc. - but your comment somehow has me thinking perhaps it's not so CRITICAL - it's still you, close enough, for now, maybe?

**Comment by Jegelewicz** [comment] 2021-04-29 15:57
> it's still you

Agree, it doesn't matter what permissions you had when you did something, it is still you...

**Comment by dustymc** [comment] 2022-02-18 16:40
duplicate of https://github.com/ArctosDB/arctos/issues/2636

**Closed by dustymc** 2022-02-18 16:40 UTC
Labels: Priority-High (Needed for work), Function-Agents, Function-Users
