### ISSUE TITLE
geolocate unhappy over https (was: geolocate not working?)

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1322] opened 2017-11-08 00:16 UTC
Or is it my computer/browser?

**Comment by dustymc** [comment] 2017-11-08 00:24
Seems to work for me - what specifically isn't working?

**Comment by AJLinn** [comment] 2017-11-08 00:34
I had a student who couldn't get it to work during data entry today. She was working on a mac using Firefox. I had her switch to Chrome and it worked fine.

**Comment by campmlc** [comment] 2017-11-08 00:35
I'm using Chrome, and the tool just spins when I click it.

**Comment by jtgiermakowski** [comment] 2017-11-08 06:59
Mariel et alia,

I've had this issue on some computers. It has to do with permissions of what scripts can run in the browser. It's hard to know what your particular setup is like because of extensions, cookies, etc. Usually there's some indication in the address bar about something not loading properly.  Do you have a screen shot (Left ALT + PrntScn will save it to Dropbox)?

Tom

**Comment by AJLinn** [comment] 2017-11-08 16:34
Thanks Tom - I'll take a look at the settings on Firefox on that particular computer - it's the only one in my lab that has this particular issue.
A

**Comment by campmlc** [comment] 2017-11-08 16:58
Nothing in the Chrome address bar - but I just tried it on a third computer
and it works, so this is something related to the browser/Windows version.

**Comment by gordonhlau** [comment] 2017-11-08 17:17
I actually had the exact same problem a while back, but eventually figured out what the issue is (on my end at least). If your browser shows the HTTPS secure connection, it won't work, and GeoLocate will be in a perpetual loading state. What I did was simply delete the https:// part of the URL, tried re-opening GeoLocate, and it's worked for me ever since.

**Comment by dustymc** [comment] 2017-11-08 17:22
@gordonhlau THANK YOU!

**Comment by campmlc** [comment] 2017-11-08 18:11
Well, I tried that, and it still didn't work. I deleted the https:// prefix
for the record and also for the locality edit page.  I also went into
Chrome settings and switched everything from ask to allow for arctos:
popups, plugins, flash etc. Still no go. But obviously it must be related
to something with the https? Any other ideas?

**Comment by jtgiermakowski** [comment] 2017-11-08 22:42
OK, we figured it out. On the right hand side of the address bar in Chrome there was an icon indicating that scripts were 'unsafe'. We allowed the scripts to run by accepting that risk. Pop-up window with GeoLocate came up just fine.

**Comment by campmlc** [comment] 2017-11-08 22:56
Thanks, everyone!

**Comment by campmlc** [comment] 2019-02-21 04:38
I am re-opening this issue because I don't think it is reasonable to have to tell my browser to load unsafe scripts every single time I want to use Geolocate, especially if I am working on a long list. But even more importantly, don't we need to be thinking about security and converting to https? My understanding is that we will no longer be able to link to sites that use https soon if we do not convert? What are the issues here?
@dustymc 
@mkoo

**Comment by campmlc** [comment] 2019-02-21 04:45
My understanding is that we do not have to pay for this anymore. We can use Let'sEncrypt?

**Comment by campmlc** [comment] 2019-02-21 05:12
This is a mixed content issue, not the certificate, probably an iframe for the map application.

**Comment by dustymc** [comment] 2019-02-21 05:15
switched geolocate to https

**Closed by dustymc** 2019-02-21 05:15 UTC
Labels: Enhancement, Function-Locality/Event/Georeferencing
