### ISSUE TITLE
Bulkload taxon relations Review and Load page 'delete' button does not delete

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#4793] opened 2022-06-29 00:33 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

I click 'delete for this user/status'

it brings me to a page to review what I'm deleting and then I click the button 'continue to delete' and then it goes to another page:

Delete Successful

but when I return to 'review and load' the things I supposedly just deleted are still there, undeleted.

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
high

**Comment by dustymc** [comment] 2022-06-29 00:34
duplicate of https://github.com/ArctosDB/arctos/issues/4792

**Closed by dustymc** 2022-06-29 00:34 UTC
Labels: Bug
