### ISSUE TITLE
Code Table values: new karyotype and other mammal parts

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#2596] opened 2020-04-17 05:02 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Jim Patton (JLP, MVZ) has media for karyotypes and other mammal parts that he wants loaded into Arctos. The media are not digitized and so cannot be added as media. However, he wants researchers to know that they exist, and thus wants to add them as a part in Arctos. Eventually they may be digitized, but that is a long way off if it ever happens. He is trying to clean up loose ends with his specimens, while he is still active. Because they are not actual media, the only option is to add them as a part for the specimen.

**Context**
Some parts already exist, but the associated "preservation method" does not. Eventually part and preservation method will be separated, but JPL wants to get this done now.

**Table**
Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm

**Value**
karyotype (digital image)
karyotype (35mm negative)
karyotype (mounted)
karyotype (photo print)
skull (35mm negative)
palatal rugae (35mm negative)
pes (35mm negative)
phallus (35mm negative)

**Definition**
karyotype (digital image) - Digital image of the karyotype.
karyotype (35mm negative) - 35mm negative of the karyotype.
karyotype (mounted) - Need to ask JLP.
karyotype (photo print) - Photo print of karyotype.
skull (35mm negative) - 35mm negative of the skull.
palatal rugae (35mm negative) - 35 mm negative of the palatal rugae, which refer to a series of transverse ridges on the anterior part of the palatal mucosa  
pes (35mm negative) - 35mm negative of the hind foot.
phallus (35mm negative) - 35mm negative of the phallus.

**Collection type**
Mamm

**Attribute data type**
free-text

**Attribute value**
N/A

**Attribute units**
N/A

**Part tissue flag**
No

**Other ID BaseURL**
N/A

**Priority**
High

**Comment by dustymc** [comment] 2020-04-17 16:07
All existing similar data are recorded as "media" - http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name&field=media

http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_attribute_part (developed as an apparently-failed attempt to quantify "tissue") could potentially be used to clarify; it carries more formality than remarks.

**Comment by Jegelewicz** [comment] 2020-04-17 16:22
After talking about this yesterday, this may be a part/preservation issue.

part = karyotype
preservation = 35mm negative

while that may seem strange for most parts, for karyotype this is kinda a thing.

**Comment by dustymc** [comment] 2020-04-17 16:44
"parts are things to which one can stick a barcode"

The part is the device - a hunk of fancy paper or a thumb drive or something, ``media``. Doing something else would just make everything inconsistent. The karyotype is information contained by that media-part. That said, I think we already have karyotype for legacy reasons and making that inconsistency slightly more complicated isn't the end of the world.

Maybe I can see the point of photographs and such as preservation methods (or something like it that lets a search for "pez" find pictures of feet), but it feels like a major shift in how we define parts; it's a move from "physical thing" to "some sort of representation" or something.

**Comment by Jegelewicz** [comment] 2020-04-17 17:04
I made the exact same argument in our meeting. I think the thing that swayed me in the direction of part/preservation was the ease of searching for everything "karyotype".

I suggested part = media with part remark = karyotype, but as Carla pointed out, people won't find that, especially because remarks are full of all kinds of stuff and searching them is iffy, especially for the uninitiated.

I did not suggest a part attribute, which would probably work better, but still might be confusing to those outside of Arctos.

part = media
preservation = 35mm negative
attribute type = part represented (controlled by part names)
attribute = karyotype

If we could ask people "do you want to include represented parts in PART_NAME = media" when they search part names, then they might get everything karyotype...

**Comment by campmlc** [comment] 2020-04-17 17:10
I thought the same thing about part and preservation as being an easy
solution, but we definitely do need to be able to search on karyotype. We
already have "karyotype (frozen)", karyotype (dry, slide), karyotype
(slide)", which include both preservation info and objects. The latter too
should be distinguished more - "dry" means fixed with methanol, vs a wet
mount. The problem is that we are combining too many things together - part
name, preservation, media, but all need to be searchable under karyotype.
How about using an ontology that can be searchable across levels, rather
than a flat list for part names etc?

**Comment by dustymc** [comment] 2020-04-17 17:24
>I suggested part = media with part remark = karyotype, but as Carla pointed out, people won't find that, especially because remarks are full of all kinds of stuff and searching them is iffy, especially for the uninitiated.

I absolutely agree, but doesn't MVZ have a tradition of doing exactly this with "tissue"?

> part attribute, which would probably work better, but still might be confusing to those outside of Arctos.

We're talking about moving preservation to attributes - I don't see how a more-appropriate data object in the same structure would be more confusing.

>we are combining too many things together

Yes, which inevitable means we can't find anything. This issue does that to the fundamental object in part-land!

>ontology that can be searchable across levels

Uhh - sure, example?

**Comment by campmlc** [comment] 2020-04-17 17:59
I'm trying to figure out if it is possible to have the search process for
"karyotype" as "part" pick up not only "karyotype" as part name but also
part = media, attribute = 35mm slide, attribute = karyotype or part =
tissue, part remarks = karyotype. This seems like a UI issue. Maybe add
options for narrow vs broad search?

**Comment by ccicero** [comment] 2020-04-17 18:01
Tissue is different. We put tissue type in remarks because we (MVZ) haven't had people asking for specific tissue types, for the most part. And if they do, we deal with it on the curatorial side. They just want to know what's available for tissue, just like people want to know what's available for karyotypes.

Part attribute is a confusing mish mash of things, and not a good option in my opinion. I agree about separating preservation method, but I'm not sure that I like it as an attribute (were we talking about that?).

The main thing is to make things findable for a broad range of users. "Give me all rodents in genus X with karyotype information" (in whatever format). That's best done through parts, which is what most people tend to search on. And these actually are physical things - a envelope with a negative, or a print, that could be barcoded if someone wanted to do that.

I don't think a typical user will find karyotype information this way:
part = media
preservation = 35mm negative
attribute type = part represented (controlled by part names)
attribute = karyotype

What about an option like "karyotype media" "skull media" "pes media" etc. - then put the method details in as a remark? I think that would satisfy the ability to find all things "karyotype" while not creating a lot of extra parts.

**Comment by dustymc** [comment] 2020-04-17 18:14
>broad search

Ah - yea, it's easy to build the UI up a bit, but big-picture "do something completely random, find it later" isn't a recipe for success. If we kept the part as "media" with "karyotype" in the part-attr-part table we'd have a very predictable and defensible way of finding those (and potentially "tissue" and etc.). I'm sure there are other options, but SOMETHING predictable which could be mapped to some 'any...' field in the UI could work.

>Part attribute is a confusing mish mash of things,

If it is, it's only because the data are in bad shape. Part attribute is a container, any number of "subcontainers" (the attributes themselves) of any specificity can be contained. The structure is there, if we're using it wrong then we should fix that!

>And these actually are physical things - a envelope 

Yes, at some point we squished a couple hundred "random physical things that are close to the specimen but not PART of the specimen" into 'media.' I think that's better for discoverability, but firing up a new part of everything that anyone might want to track with a specimen isn't exactly wrong either.

>"karyotype media" "skull media" "pes media".....while not creating a lot of extra parts.

That's a recipe for doubling the number of parts, right?

**Comment by campmlc** [comment] 2020-04-17 18:15
I think I would prefer to have media type and method as attributes, so we
don't add new parts even more ad infinitum than we do now.  We do have the
option of recording preservation separately as part attributes, which have
value, date, determined by, and remark. Possible to add media or methods
here?
And then, what we really need is a change to the UI so that the most
recent part preservation shows up in a field next to condition and
disposition, with a click history next to it. This is a display issue only
- doesn't need to affect the underlying data structure, but it would make
the most relevant info visible and searchable.

**Comment by dustymc** [comment] 2020-04-17 18:21
>Possible to add media or methods here?

I certainly wouldn't call that preservation, but I think it's an attribute of some sort.

>most recent part preservation shows up in a field next to condition and disposition,

There's more detail somewhere, but that's still a recipe for "most relevant" to say "it's great!!" with "rotten" and "in formalin for a few decades" buried.

>doesn't need to affect the underlying data structure

Correct and critical.

**Comment by ccicero** [comment] 2020-04-17 18:22
I'm not exactly sure what is being proposed now, but I think it's this:

part name = karyotype
part attribute = preservation method (including media type)
part table shows part name, condition, latest attribute added with a click history

I'd be ok with that, but I do think we need to do something better with the mish mash of what we have now in part attributes.

**Comment by dustymc** [comment] 2020-04-17 18:38
>part name = karyotype

For that one, whatever. For eg pes
* part name = media
* part attribute=http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_attribute_part
* part attribute value=pes
* search and display magic

It makes sense to me for "picture of a karyotype" and "picture of a foot" to be handled similarly, but we can revisit that later since we already have karyotype-parts.

>mish mash of what we have now in part attributes.

Example?

**Comment by ccicero** [comment] 2020-04-17 18:50
We also already have 'pes' as a part, so I don't see the different with karyotype.

'palatal rugae' would be a new part, but we do have 'palate' so it could be combined with that somehow. 

I still argue that having the 'part name' as an attribute is not going to be findable to many. So I really don't like that, and I'm sure that JLP won't either. Media is just too broad as a part name - might include audio recording, photograph in the field, photograph in the museum, representation of a part such as karyotype, etc.

Just look at the list of part attributes. Accession, locality/event stuff, Other ID - are those really attributes of parts? NK number is an other ID just for a tissue part, but it goes in as other identifier for the record. And there are things that I would argue are true attributes of parts such as tissue quality, surface area, preservation, etc.

**Comment by campmlc** [comment] 2020-04-17 20:09
I agree with this:

part name = karyotype
part attribute = preservation method (including media type)
part table shows part name, condition, latest attribute added with a click
history

And I also agree that the current part attribute table needs an overhaul
and a plan. This is where some sort of ontology could be applied - some
means of categorization, e.g. preservation attributes, method attributes,
identifier attributes, etc.

**Comment by dustymc** [comment] 2020-04-17 22:13
pes==physical biological thing

karyotype==some sort of nonbiological representation of some biological thing

OtherIDs are certainly valid part attributes - they're identifiers assigned to parts, not catalog records. That other stuff looks a lot like more otherIDs to me, let's call it evidence that we need better code table procedures!

> preservation method (including media type)

I'm still not getting this. WHY would we want to mix those obviously different types of data into the same bucket?

>current ... needs ... plan.

Yes.

>ontology

I'm up for anything, but you're going to have to be a lot more specific for me to understand what you're suggesting.

**Comment by Jegelewicz** [comment] 2020-04-17 22:16
Accession, locality/event stuff, 

is part of the weird (sorry my opinion) duct tape for Mexican wolves.

**Comment by campmlc** [comment] 2020-04-17 22:18
A karyotype is real thing. Just can't barcode chromosomes directly,
unfortunately.
Yes, we are using attributes for a weird mishmash of things. Needs
structure and organization and purpose.

**Comment by dustymc** [comment] 2020-04-17 22:33
>A karyotype is real thing

Of course it is, but it's not something a critter grows either - it's a representation of that, much like a 35mm slide containing a picture of a foot. At some point in the past we made a decision to lump all of those (except karyotype, apparently!) into "media."

To be clear I'm really not sure that "crayon on brown paper bag picture of the tip of the left ear" **isn't** something we want in part name, but I am sure that we as a community should be fully aware of the implications of opening that door before we do so. I don't think I've quite got my head wrapped around what those might be yet.

**Comment by campmlc** [comment] 2020-04-18 16:48
No, the cells containing chromosomes processed and fixed at metaphase in a
frozen suspension or mounted on a slide is a real thing - but we use the
term karyotype to refer to the chromosomes in whatever format. They are not
media.

**Comment by campmlc** [comment] 2020-04-18 16:50
On the same subject, DNA is not media either. These should be treated the
same.

**Comment by ccicero** [comment] 2020-04-18 18:04
I agree with Mariel. The other thing about media is that people won't think to look in parts for media, since there is a separate search field for media. FYI, I just tried searching for part_name='media' and it timed out. So what do we have as media in parts, if anything? And what are the associated remarks?

I think the cleanest is to keep the part simple (karyotype, pes, palate, etc., which mostly already exist), and then put the details in either attributes and/or remarks. This would also apply to things like 'karyotype (slide)' - again, separating the part name from the preparation/preservation/medium. So maybe we need to work on resolving and finalizing https://github.com/ArctosDB/arctos/issues/1460 - where are we with that???

**Comment by dustymc** [comment] 2020-04-18 18:31
>cells containing chromosomes 

OK, cells definitely fit in what we've been calling parts. Photos of those cells not so much.

> parts for media, since there is a separate search field for media

There's a data object Media for linking "things with URLs" and a specimen_part.part_name 'media' - http://test.arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name&field=media - for tracking physical bits. They're different things for different purposes.

>timed out

<img width="396" alt="Screen Shot 2020-04-18 at 11 10 42 AM" src="https://user-images.githubusercontent.com/5720791/79648186-4fe04800-8165-11ea-955f-908d58d77ad1.png">

Works for me, but the PG upgrade should make it faster. 

>parts, if anything? And what are the associated remarks?

```
create table temp_mediapart as
select guid_prefix,coll_object_remarks, count(*) c from specimen_part inner join cataloged_item on specimen_part.derived_from_cat_item=cataloged_item.collection_object_id inner join collection on cataloged_item.collection_id=collection.collection_id left outer join coll_object_remark on specimen_part.collection_object_id=coll_object_remark.collection_object_id
where part_name='media'
group by guid_prefix,coll_object_remarks order by guid_prefix,coll_object_remarks;
```

http://test.arctos.database.museum/Admin/CSVAnyTable.cfm?tableName=temp_mediapart

>keep the part simple

As above I'm not preemptively opposed to this, but it's a significant and fundamental change in what "part" means - that probably needs more exposure than here, somehow. We'll definitely want to loop the "cultural" folks into that conversation - naming the object depicted in part="media" as the part itself will potentially affect them more than most (and could spawn some useful conversations regarding the whole "what it is vs what its called" thing that's currently driving them to have ~nothing but 'object' parts.)

> #1460 - where are we with that???

Waiting for a development environment so we can respond to UI needs before forcing everyone into what's essentially a new model.

**Comment by campmlc** [comment] 2020-04-18 18:39
On maybe a similar vein, we have the need to tie parts to other tables. For
Mexican wolves, we desperately need a way to link parts and/or/orboth to
accessions. We can already kinda sorta link parts to specimen events, which
also need to be linked to accessions, rather than the sloppy way we do it
now which is to denormalize and copy all this info into specimen event
remarks and part remarks, and lose the accession link altogether.
Would linking parts to media be similar, and require a similar fix?
I realize this would need to wait for a new PG production environment.

**Comment by ccicero** [comment] 2020-04-18 19:27
I'm getting a 503 error, so can't check the data. 

We want to track physical bits as media without having the actual media digital, but we want to easily find different kinds of data associated with those media - it's a picture of a skull, it's a picture of a karyotype, etc. If you're searching for everything with 'skull' or 'karyotype' in parts, you're not going to get them if the part is just media and the type of 'part' is in a remark or attribute field.

**Comment by Jegelewicz** [comment] 2020-04-18 20:10
> it's a picture of a skull, it's a picture of a karyotype, etc.

This is the exact situation that art/ethnology collections are discussing in https://github.com/ArctosDB/arctos/issues/2362

which is why we need everyone involved in the discussion.

**Comment by Jegelewicz** [comment] 2020-10-15 17:56
See [working document](https://docs.google.com/document/d/10gvsABpVGRlNCUEDA4oeqP2kPO3A-1iH/edit).

**Comment by ccicero** [comment] 2021-09-03 02:40
I just realized that there may be an issue with just adding 'representation' as a part attribute. I added that for a bunch of mammal skulls. Most of the skulls were already in as parts, but some weren't (previous tissue only, I think the skull may be in South America but not sure). If you add a part attribute of representation, but don't  actually have the original part in the collection, what do you put for disposition? Having 'in collection' sounds like the skull is in the collection, but it's actually only the representation (35 mm negative). We can't currently distinguish what's in the collection, the actual physical bit (skull) and/or just the representation (negative). If we change the disposition for the skull to something else (e.g., transfer of custody), does that also imply that the representation has the same disposition?

**Comment by dustymc** [comment] 2021-09-03 02:56
>I added that for a bunch of mammal skulls.

Adding the attribute is a "this is not actually a skull" declaration.

>Having 'in collection' sounds like the skull is in the collection, but it's actually only the representation (35 mm negative).

That's where we ended up. You have a representation of the skull in the collection (or lost or on loan or whatever - in any case the reference is still to the negative).

If you have the skull and some representation of it (or many of them), you should have multiple 'skull' parts with n-1 of them declared representations.

**Comment by ccicero** [comment] 2021-09-03 05:05
I don't think that's clear to the user. For example, in this record, I would think this means that there is a skull in the collection + different representations of that skull. Not that the representations are the only thing in the collection.
https://arctos.database.museum/guid/MVZ:Mamm:99685

I'm rethinking this and maybe 'representation' really belongs in 'preservation' - tied directly to the part and its disposition so it's clear. If we do something like that, then it will be much more clear when you have different scenarios, e.g., 

**physical skull in the collection + skull representation in collection**
skull A - in collection
skull B - in collection with preservation = representation

**only representation in collection**
skull A - transfer of custody
skull B - in collection with preservation = 'representation'

**Comment by Jegelewicz** [comment] 2021-09-03 14:12
Preservation is still just an attribute. 

Will cultural collections use preservation=representation? I think maybe not because their reproductions may have their own special preservations attributes

Being a representation is not a form of preservation IMO.

**Comment by dustymc** [comment] 2021-09-03 14:21
>clear to the user.

Well I'm a user and it's clear to me...

These are complicated data. Treating the representations as part=``media`` is simple and probably clear to more users, but gives up some data. This approach carries more information, which requires more complexity, which might be lost on some users. We absolutely need clear documentation, but if we're going to embrace the complexity (and we should!) then users might just have to read the docs to really know what we're up to.

Preservation is exactly the same structure as representation. As @Jegelewicz says, putting this there means your conservator doesn't have a logical place to put '35mm negative storage juice' (and preservation is already overloaded). That could still work, but it seems less precise to me.

The UI can always be better, and we should probably spend some time figuring out what this is going to look like in DWC and such, but this does seem like a defensible and accessible way to say "image of a skull" to me.

**Comment by ccicero** [comment] 2021-09-03 15:57
More thoughts on this: It occurs to me that these aren't representations of the skull but rather of the skull elements. So rather than have the part name = skull, and have multiple skulls if the skull + its representation are in the collection (that doesn't seem right to me), the part names should be the represented elements themselves in some form + the actual skull if it's present. So for example:

https://arctos.database.museum/guid/MVZ:Mamm:99685

should be
part_name = 'skull'
part_name = 'palate' with representation attribute remarks = 'Posterior palate.'
part_name = 'palate' with representation attribute remarks = 'Incisive foramina.'
part_name = 'maxilla' with representation attribute remarks = 'Infraorbital canal.' ??? This one is less clear, but seems better to use 'maxilla' than create a new part for the canal? https://en.wikipedia.org/wiki/Infraorbital_canal

Does that make sense to others?

**Comment by Jegelewicz** [comment] 2021-09-03 16:22
@ccicero that all looks reasonable to me, especially the infraorbital canal example! BUT
There are attributes for the anatomical direction as well. Suggest something like this for that palate:

part_name | part condition | part remark 
 -- | -- | -- 
palate | partial | posterior palate 

part attribute | part attribute value | part attribute remark 
 -- | -- | -- 
representation | 35mm negative | shows posterior palate 
anatomical direction reference, | posterior |

**Comment by dustymc** [comment] 2021-09-03 16:23
>aren't representations of the skull but rather of the skull elements.

I think that's almost always going to be a little subjective - there's some arbitrary point where there's enough skull showing that it's more than 'palate.' (Not different than how a busted-up skull would be treated, really.)

> multiple skulls

You might end up with 500 of them: one bony-bit and 499 photographs, CT scans, casts, artistic models, ...... 

You should have an equal number of parts and "things to which one might stick barcodes" - the current catalog record suggests there's one physical representation-thing, the data above suggest 3. (That's all REALLY theoretical - it doesn't survive three images on a thumb drive - but maybe a somehow useful way to look at things anyway....) I think the example above is more accurate, whether you call the parts 'skull' or some component thereof.

>create a new part for the canal?

We definitely haven't figured out what's a part and what isn't, but the idea of parts for unoccupied spaces makes my head hurt so I tentatively support 'maxilla' for that!

**Comment by ccicero** [comment] 2021-09-03 21:30
@Jegelewicz Thanks. I like the addition of 'partial' and the remarks/attributes.

@dusty Having multiple parts for something like skull makes my head hurt. That will be super confusing to a user, especially in specimen results or downloads, i.e., mouse with skull, skull - ??? This is especially true when there's no additional information to explain why there are multiple skulls. It's true that you could have the bony skull and a representation of the entire skull. But these data will only make sense if there's a clear association between each part and detail about that part (i.e., it's a representation and not the bony piece, or for tissue it's liver vs muscle vs kidney etc.) Right now we don't have that - this relates to [JSON issue](https://github.com/ArctosDB/arctos/issues/2693).

**Comment by dustymc** [comment] 2021-09-04 01:31
I agree, parts are more than strings and should be represented as data objects - but ya'll don't like JSON and I don't know of a better alternative....

Maybe we should at least have better smooshed-up strings; I'm open to ideas.

**Comment by dustymc** [comment] 2022-02-15 16:58
This is addressed by https://arctos.database.museum/info/ctDocumentation.cfm?table=CTPART_PRESERVATION

**Closed by dustymc** 2022-02-15 16:58 UTC
Labels: Priority-High (Needed for work), Function-CodeTables
