### ISSUE TITLE
Session Expires: Add Part to Loan via Barcode

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#2994] opened 2020-08-03 19:17 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When adding parts to a loan via barcode, even if you are working, your session will expire on you.

**To Reproduce**
1. From a loan, select "Add Items by part barcode"
2. Scan tissue, click add to loan, repeat over and over and over again.
3. Do step 2 for 30 minutes.
4. Get logged out! #@$!!@#@
5. The timer is fixed so you can't see the timer count down as you add items and are farther down on the page.

**Expected behavior**
Not to log me out while I'm working. Bonus if that timer was visible on the screen you are working on instead of stuck at the top. For a good example of that, go to loan 2020.007 Mamm. I have 200 samples already added so have to scroll down a bit to start adding tissues. You don't see the session expiring countdown while working. 

**Screenshots**
![Screen Shot 2020-08-03 at 10 51 42 AM](https://user-images.githubusercontent.com/16887896/89218320-519a1400-d57a-11ea-8395-81b246f79eb6.png)
![Screen Shot 2020-08-03 at 10 14 26 AM](https://user-images.githubusercontent.com/16887896/89218325-52cb4100-d57a-11ea-9d23-4153854c7020.png)

**Priority**
Medium - I have an okay workaround. I open another tab with Arctos and try to remember to refresh that screen every few minutes so it doesn't log me out on the other page.

**Comment by dustymc** [comment] 2020-08-03 19:21
Merge-->https://github.com/ArctosDB/arctos/issues/2759

**Comment by KyndallH** [comment] 2020-08-03 19:25
This is a very different issue. I'm in Arctos. I'm WORKING. I'm scanning a barcode and clicking "add to loan" and it doesn't reset the timer to 30. When I scan something in or click "add to loan" my timer should reset to 30 minutes. Right? It isn't because I'm inactive for 30 minutes.

**Comment by dustymc** [comment] 2020-08-03 19:26
Oh yes that's different - may be built in to Lucee (???), I can investigate.

**Comment by dustymc** [comment] 2020-08-04 16:06
This does seem like a lucee "bug" (or unexpected behavior anyway) involving database session management not properly interacting with "remote" calls. DB sessions are necessary for containerization/clustering. I don't have an immediate solution; #2759 isn't a fix, but might mitigate anyway.

Full statelessness would fix this and some other similar issues but I don't think that's something we can realistically consider at this time; it would involve rebuilding most everything.

**Comment by Jegelewicz** [comment] 2021-12-06 22:56
@KyndallH @dustymc is this still an issue?

**Comment by Jegelewicz** [comment] 2022-05-13 21:56
I'm guessing this is resolved since it has been two years - closing.

**Closed by Jegelewicz** 2022-05-13 21:56 UTC
Labels: Priority-Normal (Not urgent)
