### ISSUE TITLE
Automatic assignment higher hierarchy for geological time scale units

### ISSUE THREAD

**Issue by aklompma** [ArctosDB/arctos#3790] opened 2021-07-30 20:38 UTC
To save a lot of time when entering data, would it be possible to create a feature that recognizes that say when entering the Santonian Stage/Age, it is part of the Upper Cretaceous Series/Epoch, which in turn is part of the Cretaceous System/Period, and in turn part of the Mesozoic Erathem/Era. Ideally, when entering Santonian as a stage/age first, it would be fantastic if the the Series/Epoch, System/Period, and Erathem/Era fields would be automatically populated.
The full (hierarchical) geological timescale can be found here: https://stratigraphy.org/ICSchart/ChronostratChart2021-07.pdf

**Comment by dustymc** [comment] 2021-07-30 20:50
I don't think I'd favor returning to hierarchical assertions.

Pulling accompanying (including hierarchical) data and searching by it is https://github.com/ArctosDB/arctos/issues/2244

I believe this can be considered a duplicate of https://github.com/ArctosDB/arctos/issues/2244, but I'll let you make that determination.

**Comment by aklompma** [comment] 2021-07-30 21:04
It does not seem to be the same to me....I am just asking to autopopulate existing lithostratigraphic in Arctos based on a single entry to save hundred of hours of work in the long run.

**Comment by Jegelewicz** [comment] 2021-07-31 01:13
@aklompma I am going to loop in @Nicole-Ridgwell-NMMNHS to make sure I don't tell you something that isn't true, but I believe that you only need to enter the Stage/Age because our search function includes the chrono hierarchy so that if someone searches the System/Period that Stage/Age is included in, they will get it.

**Comment by Nicole-Ridgwell-NMMNHS** [comment] 2021-08-02 15:31
Yes, we added metadata to all the chronostratigraphy so that you only have to enter the lowest chronostratigraphic level. See for example the code table for [Stage/Age](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctchronostrat_stage_age). If you only enter lowest level, searches at a higher level will find your data. Maybe we can do something with the UI to make that a little more obvious?

**Comment by Jegelewicz** [comment] 2021-08-02 15:34
> Maybe we can do something with the UI to make that a little more obvious?

Let's start with this:

searches of a group will find all groups nested within it

Edit away!

**Comment by dustymc** [comment] 2021-08-02 15:34
What are the goals?

If it's to make an assertion, then I think you'll just have to make assertions. (I could certainly help get those into the bulkloader format.)

If it's discoverability, the metadata exist for that (and in such a way that it doesn't confound assertions and other stuff).

If it's something else, I need more information. 

The issue templates are useful: https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Enhancement&template=feature_request.md&title=Feature+Request+-+

**Comment by aklompma** [comment] 2021-08-06 14:02
Great to hear that say "Maastrichtian" records will show up if people just search for "Cretaceous" even if "Cretaceous" is not entered when creating the record.

It would be great that if the higher hierarchy also shows up when clicking on the record itself in such cases.

**Comment by Nicole-Ridgwell-NMMNHS** [comment] 2021-08-06 14:38
> searches of a group will find all groups nested within it

This is good. I would just replace group with unit. 

searches of a unit will find all units nested within it.

> It would be great that if the higher hierarchy also shows up when clicking on the record itself in such cases.

How would you want that to look? At the moment, when you are looking at the record, chronostratigraphy has a define link next to it which goes to the code table and the metadata column allows you to see where that unit is in the hierarchy.

Certainly having that hierarchy data more visible would be useful if we want non-researchers to browse through our data. For example, the average person is not going to recognize the word Kimmeridgian, but they would recognize the word Jurassic and they're probably not going to click on that define link.

**Comment by Jegelewicz** [comment] 2021-08-06 17:02
> the average person is not going to recognize the word Kimmeridgian, but they would recognize the word Jurassic and they're probably not going to click on that define link.

Maybe "define" isn't the best term right there? What if it was something like "view hierarchy" or "view chronostratigraphy"?

**Comment by Jegelewicz** [comment] 2021-08-06 17:04
BTW, I changed the default text in the Chronostrat field from "Chronostratigraphy "to "searches of a chronostratigraphic unit will find all units nested within it". It won't show up until Dusty pulls it and that will be whenever he does that, but you guys can keep your eyes peeled for the change and let me know if it doesn't work.

**Comment by dustymc** [comment] 2021-08-09 14:54
>Maybe "define" isn't the best term right there? 

Could be, but it's consistent and that is important. If something should change, it needs to be discussed by itself and the change needs made everywhere.

**Comment by Jegelewicz** [comment] 2021-08-09 18:07
@dustymc no changes to define - instead I changed default text in the search box - OK?

**Comment by dustymc** [comment] 2021-08-09 18:18
Yep, no problem with that. 

We're obviously not making a clear distinction between asserted and derived data, and there's no current documentation

<img width="915" alt="Screen Shot 2021-08-09 at 11 17 38 AM" src="https://user-images.githubusercontent.com/5720791/128754323-171bce74-4e07-4add-b7e6-7851189538f6.png">

There should be.

**Closed** 2022-02-17 16:27 UTC
Labels: Enhancement
