### ISSUE TITLE
Remove probably missing "scientific name"

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2171] opened 2019-07-16 21:52 UTC
Can we remove "scientific name" from possibly missing? We can't create it.

![image](https://user-images.githubusercontent.com/5725767/61332489-97563400-a7e1-11e9-9642-296f7f80f339.png)

**Comment by dustymc** [comment] 2019-07-26 16:15
@Jegelewicz I need a link - I can't see where that's leaking through.

**Comment by Jegelewicz** [comment] 2019-07-27 16:01
http://arctos.database.museum/editTaxonomy.cfm?action=editClassification&taxon_name_id=2063452&name=Bufo&classification_id=2063452

![image](https://user-images.githubusercontent.com/5725767/61996771-77cad100-b055-11e9-8ac9-5bcc4ba7aebf.png)

its at the bottom when you are editing

**Comment by sharpphyl** [comment] 2019-07-27 16:22
Dusty, I'm not sure if this is what you're looking for, but the verbiage appears whenever you edit a taxon name.  For example:

http://arctos.database.museum/editTaxonomy.cfm?action=editClassification&taxon_name_id=10954437&name=Eremina%20duroi&classification_id=08DD53B7-9F2E-DF49-7C720A7308F9F7BE

A the bottom of the classification, you'll see a red "possibly missing" block.  

![Screen Shot 2019-07-27 at 10 02 57 AM](https://user-images.githubusercontent.com/15368365/61996790-c11b2080-b055-11e9-84db-e6d9c5504a2a.png)

Of course, higher up, we state: "Scientific_name will be auto-generated; anything you do here will be over-written."  There's not even an option to change the Scientific Name anymore, so the alert is meaningless.

The verbiage changes a bit depending on the taxon name classification level.  This is a genus:

http://arctos.database.museum/editTaxonomy.cfm?action=editClassification&taxon_name_id=10960113&name=Eremina&classification_id=aphiaid::996436 

The red block suggests that I add a species, etc.  which, is a bit absurd even though I can see how the code generates this statement.

![Screen Shot 2019-07-27 at 10 07 08 AM](https://user-images.githubusercontent.com/15368365/61996830-67672600-b056-11e9-91a6-716106fb1b93.png)

So I would suggest that we eliminate this red block entirely on all "edit taxa" screens as there seems little need to suggest that a lower level classification be added if the taxon name appears in the lowest classification frame.  For me it's clutter that can deflect attention from the data in the nearby red box which is important to read.

**Comment by sharpphyl** [comment] 2019-07-27 16:24
Sorry, Teresa.  Your comments and mine went up at almost the same time.  I think we're saying the same thing but I'm suggesting that we totally get rid of this alert.  For us to suggest that someone add a species name to a genus taxon name, seems odd.

**Comment by Jegelewicz** [comment] 2019-07-27 16:27
Thanks Phyllis! Why are you working on Saturday? I'm about done for a while - really appreciate your contributions!!!!

**Comment by sharpphyl** [comment] 2019-07-28 01:15
When you're retired, you seldom know what day it is.  Saturday is as good a day as any to check my notifications.

**Comment by dustymc** [comment] 2019-07-30 16:13
Thanks - gone.

The suggestions come from classifications not getting the data they need to function as intended. If it ever works, I think it's probably worth keeping. I could be convinced that none of this stuff works and anything that comes out of that form is just going to be a mess and there's nothing we can do about that.

We so need that strategic plan....

**Comment by sharpphyl** [comment] 2019-07-31 01:35
Dusty, it still shows a "possibly missing subspecies" when the taxon name is being used as a species.  Here's an example:

![Screen Shot 2019-07-30 at 7 23 51 PM](https://user-images.githubusercontent.com/15368365/62176765-e5018f00-b2ff-11e9-88fa-b323abbac08b.png)

We don't really want a subspecies on a species taxon record, do we?

Also, I really like that on this record for _Achatinella apexfulva_ it suggests that I add the author.  

![Screen Shot 2019-07-30 at 7 34 01 PM](https://user-images.githubusercontent.com/15368365/62177125-0747dc80-b301-11e9-956d-1196ee30b428.png)

But that also takes us back to issue #1707 where we suggested that all the metadata fields appear upon creating a new taxon name and let the user delete (or auto-delete) the ones they don't want to use.  Positive steps like these tend to increase user "participation" more than just suggesting that they add the author, taxon status, source, etc.

**Comment by sharpphyl** [comment] 2019-07-31 01:41
See also #1816 - same issue but slightly different suggestion.

**Comment by dustymc** [comment] 2019-07-31 14:50
>We don't really want a subspecies on a species taxon record, do we?

If I could tell that - if taxonomy was that predictable - the form wouldn't exist. I'm asking you in the most unobtrusive yet visible way I could think of to consider the possibility that you're missing something that should exist in most records, and does not exist in this particular record. That's it. I understand that "not most" is still hundreds of thousands of records, I could still be convinced that none of this stuff works and anything that comes out of that form is just going to be a mess and there's nothing we can do about that.

A small "this might be an issue" notification seems to me like much better UI than making you delete a bunch of stuff in those hundreds of thousands of less-typical records, but whatever - I'm up for anything at this point.

This is one of those "conflicting directions" I mentioned in one of my pleas for that strategic plan. There's a form that causes lots of problems, I assume we'd want it to not cause so many problems, and we also don't want any notification when a situation that's been problematic in the past exists. I don't feel like I can address anything without "un-addressing" something else; I don't know what we're trying to do here, and it's impossible to write good code without that.

**Comment by Jegelewicz** [comment] 2019-07-31 15:21
> If I could tell that - if taxonomy was that predictable - the form wouldn't exist. I'm asking you in the most unobtrusive yet visible way I could think of to consider the possibility that you're missing something that should exist in most records, and does not exist in this particular record.

But you can tell that - only trinomial names should include a subspecies and FWIW, subspecies does NOT exist in most records....

**Comment by sharpphyl** [comment] 2019-08-04 17:35
I'd totally understand if it alerted me that the classification was missing kingdom or phylum - in fact that would be a good upgrade - but we use subspecies infrequently and, as Teresa says, it would be a trinomial name.  If I've entered a binomial, then there's no subspecies in the taxa I work with.

**Comment by Jegelewicz** [comment] 2019-10-16 21:25
Revisiting the above. Can we only have the "possibly missing subspecies" message when the name is a trinomial and there is no subspecies?

![image](https://user-images.githubusercontent.com/5725767/66960169-2cf3a080-f029-11e9-8c0b-2e240e047768.png)

**Comment by sharpphyl** [comment] 2020-10-21 21:57
This has been addressed in #2695.  See https://drive.google.com/drive/u/0/folders/1gQdI-qWCDFAe6yJSkWkUKlXLAX5KYwLp.  

@Jegelewicz  I recommend closing and moving this issue in the taxon project list into the Completed or Proposed to Close column.

**Closed** 2020-10-22 19:34 UTC
Labels: Awaiting PG, Display/Interface, Function-Taxonomy/Identification, Priority-Normal
