### ISSUE TITLE
Pick lists for Non-Classification terms controlled by a code table

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1812] opened 2018-11-25 23:46 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
When entering or editing classifications, the Non-classification terms "nomenclatural_code" and "taxon_status" are controlled by a code table, however, there is no pick list offered for them so unless you know exactly what to enter, your edits may fail if you mis-type or enter a term not in the related code table.

**Describe the solution you'd like**
Upon selecting "nomenclatural_code" or "taxon_status" as a non classification term, I would like to be able to pick from a list of the accepted options in the related code table.

**Describe alternatives you've considered**
I open a bunch of windows so that I have the two code tables open while working with classifications or memorize the terms for each.

**Additional context**

![image](https://user-images.githubusercontent.com/5725767/48986328-bbd59280-f0d0-11e8-93a4-e5a35cc1320c.png)

**Priority**
I would like to have this resolved by date: It would be great if we could implement this before the taxonomy webinar, but it isn't crucial.

**Comment by sharpphyl** [comment] 2018-11-26 03:54
It looks like you and I filed almost the same issue within a few minutes of each other.  Check out #1816 and see what you think.

**Comment by dustymc** [comment] 2019-01-30 16:46
duplicate of #1816

**Closed by dustymc** 2019-01-30 16:46 UTC
Labels: Function-DataEntry/Bulkloading, Function-Taxonomy/Identification
