### ISSUE TITLE
Feature Request - Bulk Unload Agent Role

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#6389] opened 2023-06-07 20:05 UTC
The specimen Agent Role Bulkloader (for collectors) works well, but often a record was originally uploaded with a dummy collector called "unknown". There is no way to bulk delete these dummy agents before adding the correct collectors, and the "unknown" collector is still collector 1 (e.g. [UAM:Herb:250362](https://arctos.database.museum/guid/UAM:Herb:250362)). This situation requires a subsequent manual deletion of the dummy collectors.

Solution: A Bulk Unload Agent Role tool, as exists for [Bulk delete other ID](https://arctos.database.museum/tools/BulkDeleteOtherId.cfm). This would take just a single-column list of GUIDs, causing deletion of all agents for a specimen.

**Comment by camwebb** [comment] 2023-06-08 15:16
I agree more control over what gets deleted would increase the utility. The submitted CSV could have three columns: GUID, role, agent name. There is a small addition cost to preparing the CSV: an additional SQL query to get the full agent list for a GUID. If most users will just be deleting all agents prior to a bulkload then the additional facility/cost is not needed, but... not knowing how many other users would prefer more control, it makes sense to build in the additional control. I'd be happy with either solution.

**Comment by Jegelewicz** [comment] 2023-06-12 22:24
This is a duplicate of #5104 so I'm closing this issue.

**Closed** 2023-06-12 22:28 UTC
Labels: Priority-Normal (Not urgent), Enhancement
