### ISSUE TITLE
Extras in Higher Geography - Ocean, Island Group, Island, Feature, Sea, Quad, and Drainage

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4811] opened 2022-07-08 17:04 UTC
While working on the cleanup in #4809 I came across this locality:

https://arctos.database.museum/place.cfm?action=detail&collecting_event_id=11135812

![image](https://user-images.githubusercontent.com/5725767/178037384-8beff47d-16f5-462a-8a66-0aa13bc7d58a.png)

and I figured - hey, while I'm here I can just georeference this thing! So I used the nifty Geolocate button, but I get nothing because part of what Geolocate refers to as Locality "Gila Cliff Dwellings National Monument" we have tucked up in higher geography. And what gets placed in locality "No specific locality recorded." is NOT a locality (see also https://github.com/ArctosDB/arctos/discussions/4807#discussioncomment-3107732) so Geolocate will never find any coordinates for it. While I was able to just replace "No specific locality recorded." with Gila Cliff Dwellings National Monument in locality for Geolocate to get some coordinates, it made me think twice about how we are handling everything in higher geography except Continent, Country, State, and County.

The rest of the world expects to find all the other stuff (Ocean, Island Group, Island, Feature, Sea, Quad, and Drainage) somewhere else.

[Island Group](https://dwc.tdwg.org/terms/#dwc:islandGroup)
[Island](https://dwc.tdwg.org/terms/#dwc:island)
Ocean/Sea [dwc:waterBody](https://dwc.tdwg.org/terms/#dwc:waterBody)
Feature - IMO everything in here is really part of locality
Quad - is just another kind of County for Alaska, but for everything else, maybe it is just a feature?
Drainage - OOF, this is a tough one, but I think it is waaaayyyy bigger than Arctos, however maybe just another kind of feature?

The things we put in higher geography that don't jive with DarwinCore end up missing at GBIF 

![image](https://user-images.githubusercontent.com/5725767/178036931-d8bb6c39-7529-4847-a0a1-0b66c1f18a73.png)
![image](https://user-images.githubusercontent.com/5725767/178037018-26150b67-d2d7-482d-bad1-db4a958868ab.png)

Anyone downloading from GBIF and using Continent, Country, State, County, Locality will never see the "Gila Cliff Dwelling National Monument that we have buried in our higher geography. It's there, but who is going to look there?

AND Arctos now thinks the coordinates assigned are not appropriate because they don't match "Catron County", but Catron County IS NOT the most specific locality!

![image](https://user-images.githubusercontent.com/5725767/178036770-a66775d0-b53f-4040-83e6-93775d0d60e4.png)

I can see a bunch of paths forward and I would appreciate other's input. I hope that we won't just continue as we are doing now, because I don't think it works well for data sharing or analysis, even using a download directly from Arctos).

**Comment by sharpphyl** [comment] 2022-07-11 18:33
> Ocean/Sea [dwc:waterBody](https://dwc.tdwg.org/terms/#dwc:waterBody)

Yes, please!  [#2876](https://github.com/ArctosDB/arctos/issues/2876)

**Comment by dustymc** [comment] 2022-07-18 19:38
>GADM, and then we have EEZs and a couple of other reference layers

Thanks, I can get those easy enough.

>ou can call a lookup API to reverse geocode a lat/lng into what that appears in e.g. GADM.

Yep, I make use of that, the problem is that we don't deal in lat/lng. What I need is "find the smallest 'authority shape' which encloses this 'determination shape'" (https://github.com/ArctosDB/arctos/issues/3114 would do that, https://github.com/ArctosDB/arctos/issues/4289 should be easy/natural with that kind of data).

**Comment by dustymc** [comment] 2022-08-09 18:33
The geography is a mess because https://github.com/ArctosDB/arctos/issues/4836, the services..
<img width="511" alt="Screen Shot 2022-08-09 at 11 31 32 AM" src="https://user-images.githubusercontent.com/5720791/183734890-f8909295-7377-405b-abff-017a4a1050a8.png">
... have come up with a reasonable georeference. I think this is just symptoms of other documented problems, tentatively closing.

**Closed by dustymc** 2022-08-09 18:33 UTC
Labels: Priority-Normal (Not urgent), Function-Locality/Event/Georeferencing, Aggregator issues, Data Quality
