### ISSUE TITLE
2 transaction_ids for a single Accession?

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#2999] opened 2020-08-04 22:10 UTC
OK, this is weird: has anyone else been able to create two transactional_ids from a single accession number? The answer should be-- no, that would be crazy!
However I have two (most of you will not be able to see these) where both are assigned to the same Accession (15569)

 - https://arctos.database.museum/editAccn.cfm?action=edit&transaction_id=21125837

 - https://arctos.database.museum/editAccn.cfm?action=edit&transaction_id=21125836

Only the latter has my cat_item attached to it but accession metadata is most complete (and different) in the former link.

How is that allowed in Arctos? This seems like a bug (not a feature)! I could delete one but not sure which. And just to continue complaining, the auto-increment number is still not working in Accession. We can discuss this Thursday too.

**Comment by dustymc** [comment] 2020-08-04 22:12
Duplicate of https://github.com/ArctosDB/arctos/issues/1598

**Closed by dustymc** 2020-08-04 22:12 UTC
Labels: Bug, Function-Transactions, Priority-Critical
