### ISSUE TITLE
Add url links to Reciprocal Relationships download

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6511] opened 2023-07-06 23:05 UTC
The Reciprocal Relationships download tool at https://arctos.database.museum/info/unreciprocated_relationships.cfm provides a csv of all unreciprocated relationships between collection objects, but there is no way currently to check or verify these prior to loading them, or to parse them by project or agent or accession. We used to receive email notifications which included live links for the guids being proposed for linkage, to allow for curatorial review. 
I'd like to request that the reciprocal relationships tool minimally add in these urls as live links to the download. Ideally, I'd like the download file to include additional metadata on who asserted the relationship, on what date, etc. prior to loading, so we can sort on relationships entered by a particular student or for a particular project and load smaller subsets as these are checked and verified. 
Even better - could this check process with live links be incorporated into the component loader system?

Example of current data download from tool:

[PendingReciprocalRelations (7).zip](https://github.com/ArctosDB/arctos/files/11973093/PendingReciprocalRelations.7.zip)

**Comment by campmlc** [comment] 2023-07-06 23:20
If I use the component loader to load these relationships, I don't have most of the metadata to fill in the fields below. What would be ideal is to get this metadata in the Pending Reciprocal Download?

<html>
<body>
<h3 style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">efinitions and Documentation</h3>

Field | Required? | Documentation
-- | -- | --
guid | conditionally | (GUID), (UUID), or (guid_prefix,existing_other_id_type,existing_other_id_number) may be used to select a catalog record to which an identifier will be added.
uuid | conditionally | (GUID), (UUID), or (guid_prefix,existing_other_id_type,existing_other_id_number) may be used to select a catalog record to which an identifier will be added.
guid_prefix | conditionally | (GUID), (UUID), or (guid_prefix,existing_other_id_type,existing_other_id_number) may be used to select a catalog record to which an identifier will be added.
existing_other_id_type | conditionally | (GUID), (UUID), or (guid_prefix,existing_other_id_type,existing_other_id_number) may be used to select a catalog record to which an identifier will be added. Accepts value from ctcoll_other_id_type.
existing_other_id_number | conditionally | (GUID), (UUID), or (guid_prefix,existing_other_id_type,existing_other_id_number) may be used to select a catalog record to which an identifier will be added.
new_other_id_type | yes | ctcoll_other_id_type
new_other_id_number | yes | value of new identifier type
new_other_id_references | yes | ctid_references
issued_by | no | Agent who issued the identifier
remarks | no | Remarks concerning the identifier
status | no | use to group records for review or set to autoload for loading without review

<br class="Apple-interchange-newline">
</body>
</html>efinitions and Documentation
Field	Required?	Documentation
guid	conditionally	(GUID), (UUID), or (guid_prefix,existing_other_id_type,existing_other_id_number) may be used to select a catalog record to which an identifier will be added.
uuid	conditionally	(GUID), (UUID), or (guid_prefix,existing_other_id_type,existing_other_id_number) may be used to select a catalog record to which an identifier will be added.
guid_prefix	conditionally	(GUID), (UUID), or (guid_prefix,existing_other_id_type,existing_other_id_number) may be used to select a catalog record to which an identifier will be added.
existing_other_id_type	conditionally	(GUID), (UUID), or (guid_prefix,existing_other_id_type,existing_other_id_number) may be used to select a catalog record to which an identifier will be added. Accepts value from [ctcoll_other_id_type](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type).
existing_other_id_number	conditionally	(GUID), (UUID), or (guid_prefix,existing_other_id_type,existing_other_id_number) may be used to select a catalog record to which an identifier will be added.
new_other_id_type	yes	[ctcoll_other_id_type](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcoll_other_id_type)
new_other_id_number	yes	value of new identifier type
new_other_id_references	yes	[ctid_references](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references)
issued_by	no	Agent who issued the identifier
remarks	no	Remarks concerning the identifier
status	no	use to group records for review or set to autoload for loading without review

**Comment by dustymc** [comment] 2023-07-06 23:23
I believe that this is a duplicate of https://github.com/ArctosDB/arctos/issues/6248.

**Comment by campmlc** [comment] 2023-07-07 14:53
Yes, but I'd like to be able to see the " issued by" and date of the person
who asserted the original relationship - rather than blindly loading stuff
created by other people. Surely we have that info?

**Closed** 2023-08-30 00:20 UTC
Labels: Priority-Normal (Not urgent), Function-SearchOrDownload, Function-Relationship, Component Loader
