### ISSUE TITLE
attribute details not working

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5702] opened 2023-02-23 00:21 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I performed a search for a specific attribute and I can see that in results, but I expect "attributedetails" to summarize in JSON all attributes. Maybe that isn't what is supposed to happen?

**To Reproduce**
1. Here is my search (logged in as a public user) - https://arctos.database.museum/search.cfm?attribute_type_1=endoparasite%20examination&attribute_value_1=no

**Expected behavior**
If there is an attribute, shouldn't there also be attributedetail?

**Screenshots**
Here is what I see

![image](https://user-images.githubusercontent.com/5725767/220793996-4a0d5dc6-730f-4c1c-8f0a-6eaaca9b3d29.png)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by dustymc** [comment] 2023-02-23 00:43
Can't reproduce.

<img width="1686" alt="Screenshot 2023-02-22 at 4 43 10 PM" src="https://user-images.githubusercontent.com/5720791/220796478-d8f44072-c888-4cb0-8cf3-2473f513b6e6.png">

**Comment by Jegelewicz** [comment] 2023-02-23 21:04
My initial attempt was in Chrome, logged in as my public user profile.

This attempt is in Firefox as an anonymous user.

![image](https://user-images.githubusercontent.com/5725767/221029792-d6423cee-84ab-4a29-8a7c-c7fcfe727b9b.png)

Same result.

**Comment by Jegelewicz** [comment] 2023-02-23 21:06
This is tagged as "need more information" - what else can I provide? If it isn't working for me, it probably isn't working for somebody else, but I guess we can just wait to see if anyone ever uses this or has an issue.

**Comment by dustymc** [comment] 2024-01-22 21:10
Closing, I think what I needed is in https://github.com/ArctosDB/arctos/issues/7320, will address from there.

**Closed by dustymc** 2024-01-22 21:10 UTC
Labels: Function-SearchOrDownload, Bug
