### ISSUE TITLE
UI - Collection details header

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5557] opened 2023-01-27 15:33 UTC
Can we make the link text selected in manage collection change these too?

![image](https://user-images.githubusercontent.com/5725767/215124840-27744fbc-17ef-443e-9643-229a0baaefe0.png)

**Comment by dustymc** [comment] 2023-01-27 15:53
I think this is a duplicate of https://github.com/ArctosDB/arctos/issues/5509?

**Closed by dustymc** 2023-01-27 15:53 UTC
Labels: Priority-Normal (Not urgent), Display/Interface
