### ISSUE TITLE
Attribute - gonad weight

### ISSUE THREAD

**Issue by fsjmm1** [ArctosDB/arctos#2716] opened 2020-06-01 17:02 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Goal**
Get a new attribute added - gonad weight

**Context**
Many collections weigh the gonads of their specimens when they prepare them

**Table**
ctattribute_code_tables

**Value**
CTWEIGHT_UNITS

**Definition**
The weight of the specimen's gonads.

**Collection type**

**Attribute data type**
weight

**Attribute units**
CTWEIGHT_UNITS

**Part tissue flag**
N/A

**Priority**
Normal

**Comment by dustymc** [comment] 2020-06-01 17:08
@fsjmm1 what collection type(s) is this for?

Otherwise I have no objections.

**Comment by Jegelewicz** [comment] 2020-06-01 17:17
See #2713 do we also need "left gonad weight" and "right gonad weight"? The bird people have the attribute "gonad" - what the heck is that?

**Comment by dustymc** [comment] 2020-06-01 17:33
>what the heck is that?

With no control and no definition nobody knows, but I'd expect "remarks about gonad." 

I'm not sure that's what's actually there...

```

arctosprod@arctos>> select * from attributes where attribute_type ='gonad';
 attribute_id | collection_object_id | determined_by_agent_id | attribute_type | attribute_value | attribute_units |  attribute_remark   | determination_method | determined_date 
--------------+----------------------+------------------------+----------------+-----------------+-----------------+---------------------+----------------------+-----------------
     11572318 |             21527923 |               21249550 | gonad          | 5               | mm              | Left testis (flesh) |                      | 1984-04-27
     18134876 |              2538415 |                1011115 | gonad          | 25              | mm              | ovary 25 x 15 mm    |                      | 1996-05-14
     18134899 |              2538415 |                1011115 | gonad          | 15              | mm              | ovary 25 x 15 mm    |                      | 1996-05-14
(3 rows)

Time: 1.386 ms
```

**Comment by Jegelewicz** [comment] 2020-06-01 19:56
Looks like unformatted measurements?

**Comment by dustymc** [comment] 2020-06-01 20:04
Yes but no? I can see some value in "random things about gonads" - users can discover there's SOMETHING there and etc. - but I have no idea how to balance the value of that with the cost of maintaining the multitude of attributes that approach could lead to.

**Comment by campmlc** [comment] 2020-06-01 20:11
What institutions/records?
MSB puts most of this including testes measurements in attribute
"reproductive data", but that rarely includes ovary measurements. Could,
though. But not very standardized or searchable, especially when what is
entered is "PLSC=1R2L" and someone has to know that means "placental scars,
1 right uterine horn, 2 left uterine horn"

**Comment by dustymc** [comment] 2020-06-01 20:21
Ah excellent point (and yet another reason to avoid having too many THINGS; they get hard to find). Is it really necessary to split "reproductive data" and "gonad," where both are free-text?

@campmlc  as above it doesn't necessarily have to be searchable to be useful. A user will never find all the variations of "PLSC" in remarks (if they were all in the same remarks, which would be exceedingly unlikely, that'd be ~3.5M "rows" to sort). Manually digging through the "something about repro" "field" is a bit more plausible - there are "only" 264800 of those, and you might get rid of ~half by including sex in the query.

**Comment by fsjmm1** [comment] 2020-06-02 17:41
@dustymc it's for fish collections, but I could see any collection that includes gonad data potentially being interested in using this attribute.

**Comment by Jegelewicz** [comment] 2020-06-02 18:16
Perhaps our attribute should be "weight" and we could use the part name table to designate WHAT was weighed (not a part attribute, just another use of the controlled part name vocabulary)? This would mean that in addition to "value" and "units" we would have some new field "applies to part" or could this just be "method"?

**Comment by dustymc** [comment] 2020-06-02 18:22
>we would have some new field "applies to part"

That's just part_attributes. I think this is probably the most technically correct viewpoint, but it's also not something I think should hold up progress - it's a major potential refactor somewhere down the line, where we'd also move 50 different things to "length" or something.

Among other things, I think that'd spawn a million "this adult male turkey claims to weigh 2 grams" sorts of issues which isn't something we can deal with right now. (Current attribute "weight" should perhaps be "body weight.")

**Comment by ewommack** [comment] 2020-06-02 19:20
Maybe "body weight" and another attribute called "part weight", and you can define the part name somewhere?

**Comment by dustymc** [comment] 2020-06-02 19:26
>you can define the part name somewhere

You could simply add a part attribute of "weight" and attach it to specific parts, rather than trying to denormalize (and complicate!) cataloged item attributes.

**Comment by Jegelewicz** [comment] 2020-06-02 19:39
> You could simply add a part attribute of "weight" and attach it to specific parts, rather than trying to denormalize (and complicate!) cataloged item attributes.

This is my preferred method, but I a feel like people won't like it. See https://github.com/ArctosDB/arctos/issues/2713#issuecomment-636889389

> Given the discussion about how many bones we should include in parts, maybe these attributes should be part attributes?

**Comment by dustymc** [comment] 2020-06-02 19:52
>people won't like it

Yea hence "major potential refactor" - maybe they will after we get preservation all spiffied up.

**Comment by fsjmm1** [comment] 2020-06-03 15:37
You could also just add gonad weight.

**Comment by campmlc** [comment] 2020-06-03 15:41
I assume this is holding up progress, so I would recommend we either add
gonad weight as an attribute, and then deal with attributes in bulk at some
point in the future, or just suggest that in this case the information be
entered in "reproductive data".

**Comment by dustymc** [comment] 2020-06-03 15:44
"reproductive data" is free-text and would be lossy.

**Comment by campmlc** [comment] 2020-06-03 15:48
Then we have an awful lot of lossy data. Eventually, this is going to need
to be fixed. However, parsing it out into multiple attributes makes data
entry much slower and more complicated. We are only allowed 10 attributes
without going to the "extras" route, which inevitably loses data.

**Comment by dustymc** [comment] 2020-06-03 15:58
>have an awful lot of lossy data

Yes, we do, many of these free-text fields exists to deal with that coming out of legacy systems (which almost never have datatype control). I definitely don't see that as a reason to lose more!

>parsing it out into multiple attributes makes data entry much slower and more complicated

If that's something I can help with, PLEASE open an issue. 

Almost all of Arctos has that general pattern - there's a way to produce low-quality data very quickly, and there are ways to produce Research Grade data with a bit of up-front investment (looking up the county, figuring out the taxonomy, translating the measurements from whatever the collector gave you, etc.).

>only allowed 10 attributes

https://github.com/ArctosDB/arctos/issues/2178

>inevitably loses data.

I fail to see the inevitability there.

**Comment by Jegelewicz** [comment] 2020-06-03 16:08
I don't have a problem adding gonad weight right now, but I will leave this issue open for the larger parts/attributes discussion that we will have (hopefully soon).

**Comment by Jegelewicz** [comment] 2020-06-03 20:39
Attribute has been added

**Comment by Jegelewicz** [comment] 2020-06-03 20:41
Actually, just closing, it will be here if we need it.

**Closed by Jegelewicz** 2020-06-03 20:41 UTC
Labels: Function-CodeTables
