### ISSUE TITLE
Setting default agents and shipping addresses in loans

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#7896] opened 2024-06-25 16:32 UTC
I've requested this a couple times now but don't recall the issue numbers. Never received a yes or no on this ask. For all transactions in MSB mammals Joe Cook and I will be the agents and the shipped from address will be mine. Can we get the ability to preselect these please. Will save a good deal of time. Thanks

**Comment by Jegelewicz** [comment] 2024-06-25 21:13
duplicate of #7384

**Closed by Jegelewicz** 2024-06-25 21:13 UTC
Labels: contact
