### ISSUE TITLE
Deleting As entered coordinates from a cloned event?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3718] opened 2021-07-07 19:47 UTC
Possible to clone an event with coordinates and delete the coordinates from the new event? Right now the as entered coordinates are not editable. 
I'd like to be able to clone an event and locality for a record with locality access = private, and modify the private event and locality to use for public access. But I cannot remove the coordinates from the original collecting event.
Alternatives: 
Create a new event from scratch.

**Comment by Jegelewicz** [comment] 2021-07-07 22:35
I just encountered this and ended up needing to create a new collecting event.

**Comment by campmlc** [comment] 2021-07-07 22:42
Yes, doesn't look like cloning the event without preexisting coordinates is
possible. So the work around I found was to clone the locality, then go to
edit the locality, and the click new event from the locality edit page. But
that means having two tabs open and copying event info by hand into the new
event.
Also not clear how to create events from scratch without the bulkloader.
Going to Edit Locality to do so is not intuitive.  We have a Create
Locality Tool under Location, and a Find Event tool. Can we get a Create
Event Tool?

**Comment by Jegelewicz** [comment] 2021-07-07 22:53
The problem is that an "event" is really two things - "collecting" event and "specimen" (ugh) event and the verbatim coordinates are down in the "collecting" event. We managed to make it work yesterday using the fork-edit thing (at least I think we did!)

**Comment by campmlc** [comment] 2021-07-07 22:56
This really requires not just dense pages of documentation but a detailed,
simplified workflow, e.g. "So, you need to clone an event, or encumber a
locality. or ? . . .  Step 1): . . .  "

**Comment by dustymc** [comment] 2021-07-07 23:04
I think cloning should just not carry over the as-entered data. Objections?

**Comment by campmlc** [comment] 2021-07-07 23:18
That would certainly work in this case. Not sure what problems it might
incur. Could there be an option to include/exclude?

**Comment by Jegelewicz** [comment] 2021-07-07 23:25
> option to include/exclude

Seems like the safest bet.

**Comment by dustymc** [comment] 2021-07-07 23:35
I'm struggling to think of a use case where manually creating a new collecting event while also bringing along what we're now calling "as-entered" data is any form of correct. Help?

**Comment by campmlc** [comment] 2021-07-07 23:43
Well, I couldn't immediately think of a situation where we might need it,
but then, there are a lot of different collections and I'd hate to mess up
someone else's workflow.

**Comment by AJLinn** [comment] 2021-07-08 02:55
> manually creating a new collecting event while also bringing along what we're now calling "as-entered" data is any form of correct.

In the EH collections, we might have an event where the creation event might be the same as the collecting event (e.g., someone made an object at a workshop or for a collector and the museum/donor purchased it directly from the person as they finished it). That would retain the same date & location information. (https://arctos.database.museum/guid/UAM:EH:UA2005-003-0001) 

MANY times we'll have very similar creation and use events, where an object is made in a community by a certain date, used from that creation date to another year, but at the same place, then collected at the same place but years later. All of the location info would be the same, only the dates might be adjusted (we'd use Fork-Edit ❤️ and by keeping the coordinates that's one step we don't have to take again).

That said... we also have situations where all three locations and dates/date-ranges are totally different, sometimes not known, so we need to be able to change or delete info along the way.

Does that make sense? Hopefully this is what you're talking about... ;-)

**Comment by atrox10** [comment] 2021-09-21 22:13
We just had this issue, or similar one with a Herp Specimen, where the wrong coordinates were uploaded by mistake, and I can't change the "as entered" verbatim coordinates, even though we didn't want to enter them wrong. I ended up fixing the locality, cloning the collecting event with the wrong "as entered" coordinates and adding that collecting event to the specimen. But the new cloned collecting event now has nothing for the "as entered" coordinates. When did get rid of the ability to edit verbatim coordinates?  This is my specimen - https://arctos.database.museum/guid/MVZ:Herp:291677

**Comment by dustymc** [comment] 2021-09-21 23:25
https://github.com/ArctosDB/arctos/issues/2930

**Comment by atrox10** [comment] 2021-09-22 02:20
Okay, I see, so basically the "as entered" just go away in the new cloned collecting event and that's the way to deal with it, since I didn't like my wrong "as entered" coordinates. Technically they were "as entered", they just weren't verbatim. Anyway, the verbatim coordinates are in my verbatim locality so that works. Thanks, I can close this.

**Closed by atrox10** 2021-09-22 02:20 UTC
Labels: Function-Locality/Event/Georeferencing
