### ISSUE TITLE
Request - bulk unload part attributes function?

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#8105] opened 2024-09-11 19:42 UTC
Help us understand your request (check below):
- [ ] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ ] a new barcode series
- [ ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [ ] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [ ] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [x] other

**Describe what you're trying to do** 
Is there a tool to bulk-unload attributes from parts? I thought there was, but I'm only finding "Un-Bulkload" for catalog record attributes.

I'm trying to remove outdated location information; the problem is that the previous location information does not have a date attached to it and is showing up in search results. The more recent location has a date attached to it, but is not showing up in search results, which is leading to some confusion about where the specimen actually is.

**Comment by dustymc** [comment] 2024-09-12 00:17
duplicate of https://github.com/ArctosDB/dev/issues/36

**Closed by dustymc** 2024-09-12 00:17 UTC
Labels: Help wanted
