### ISSUE TITLE
Bob Smith

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#896] opened 2016-06-13 15:58 UTC
The agent Burt Smith includes the aka's "Bill Smith" and Bob Smith".  Was there really one person with all of these names?  I have a collector named Bob Smith and I added an agent for him with the aka Smith, Bob (UTEP) to distinguish him from what appears to be a B. Smith garbage can called Burt Smith.  I am unsure if this was the correct way to handle this conundrum.

**Comment by dustymc** [comment] 2016-06-13 17:53
I think I would recommend flagging Burt/Bill/Bob/B. as a bad duplicate of - well, something! - unknown maybe, or perhaps new agent B. Smith. That will notify the collections which use the agent, and insert a verbatim collector attribute if they do nothing. 

A "not the same as" relationship from known agents to anything which MIGHT be seen as a duplicate of them is always useful. An agent status ("alive") is very likely to be useful in the future too; it's a bit more evidence linked directly to the agent, rather than via specimens, and will be useful if at some point "Bob Smith" has been attributed to eg, specimens collected 100 years apart.

@ccicero

**Comment by ccicero** [comment] 2016-06-13 21:27
I'm almost certain that Burt Smith who collected one MVZ mammal in 1910 is different than the Burt Smith who collected three UWBM herps in 1950. I have no idea where those 'aka' values came from. My inclination would be to remove the 'aka' - but first I will email Adam Leache at UWBM to see if he can check on the collector for the UWBM herps. 

I would not flag them as bad duplicates of 'unknown' - but adding the 'not the same as' relationship is helpful.

**Comment by Jegelewicz** [comment] 2016-06-13 22:05
I added the 'not the same as' relationships to both for now.

**Comment by mkoo** [comment] 2016-08-01 19:34
Closing for now. Reopen if Burt/Bob/Bill shows up!

**Closed by mkoo** 2016-08-01 19:34 UTC
