### ISSUE TITLE
search by Superfamily & summarize results by Superfamily please

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#2901] opened 2020-07-10 18:16 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

Superfamily is a frequently used rank in invertebrates that we currently are not able to search on or summarize results by

** Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

Search on the rank superfamily & summarize results by superfamily

**Describe the solution you'd like**
How might we accomplish your goals?

A search field in the taxonomy search pane & an option in the summarize results by list

**Describe alternatives you've considered**

Searching by order then cross referencing all families by a publication or other source that tells one which families belong to the superfamily of interest.

**Additional context**

**Priority**
Please assign a priority-label.
medium

**Comment by dustymc** [comment] 2022-02-16 16:04
duplicate of https://github.com/ArctosDB/arctos/issues/1742

**Closed by dustymc** 2022-02-16 16:04 UTC
Labels: Priority-Normal (Not urgent), Function-SearchOrDownload, Enhancement
