### ISSUE TITLE
Help interpreting collection event change report

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3281] opened 2020-12-07 19:19 UTC
I need some help interpreting the following report. From my perspective it appears that the collecting events for the specimens listed have been changed. However, that doesn't make sense when I look at other data sources, e.g. the birth date of these animals,  which in most cases is after the date of the supposed changed event. Does this log show us events that have been cloned and modified? If so, can we have a means of designating that in the form to distinguish from original events that were altered?
Otherwise, I spend a lot of time trying to figure out what happened here that could be used more effectively elsewhere.

**Comment by campmlc** [comment] 2020-12-07 19:21
![image](https://user-images.githubusercontent.com/14808196/101395092-b053ff00-3886-11eb-9998-79fcf02786bd.png)

**Comment by campmlc** [comment] 2020-12-07 19:22
![image](https://user-images.githubusercontent.com/14808196/101395177-d24d8180-3886-11eb-948b-3ddb0f792885.png)

**Comment by dustymc** [comment] 2020-12-07 20:37
I don't know how say this better than the documentation does.

Appropriateness for use of the events is outside the scope of the report.

I can't know what tools are used to create or change events.

If some other event was altered in some way, it should be in the report as well.

**Comment by campmlc** [comment] 2020-12-07 20:39
Is there any way to determine whether an event ID was cloned from another
event?

**Comment by Jegelewicz** [comment] 2020-12-08 20:50
@dustymc the issue here is that the person doing data entry is cloning and then editing the cloned event. But this report doesn't allow Mariel to see that it was the cloned event (and not the original) that was edited. I can see a couple of solutions and @campmlc and I talked about them, but wanted to see if you have any other options.

1. name all of your events - not really feasible unless she can somehow do that in bulk, which I think we could, but I am also not sure that doing so wouldn't mess with event merging functionality that she may want. In any case, I am uncertain if the names would show up on this report so that she could just scan for "clone of" to ensure that only the cloned events were edited.

2. create some sort of notation on all cloned events to show they were cloned - something in the history? an actual link to the original event? (sounds like blockchain...), a simple field that says "this event is a clone"?

3. validate events - for all events she really does not want changed, make the specimen event status "verified". Some of the same issues as 1, but would mean that anyone doing data entry would not be able to alter the original event. One caveat - these are the infamous Mexican Wolves any of which may include any number of "verified" events. Can you have more than one "verified" event on any given record?

I think that's all I've got. Other ideas or ways to help Mariel not have to go look at every event on this report to ensure it indeed was the cloned event would be appreciated!

**Comment by dustymc** [comment] 2020-12-08 20:55
I'm lost. SOME event that's used for those specimens was edited; I'm not understanding how anything else is important/relevant.

There are tools to bulk-name.

Naming prevents merge.

Cloning just saves some typing and avoids a chance to pick the wrong locality and such; I'm still not seeing why/how that possibly matters, maybe same confusion as above.

Any number of events may be in any state.

**Comment by Jegelewicz** [comment] 2020-12-08 21:02
> I'm lost. SOME event that's used for those specimens was edited; I'm not understanding how anything else is important/relevant.

Here is an example:

Event 11768182 was actually created by cloning event 10221581, then editing as reflected in the report above. But without doing a search on all sibling events of 11768182, I don't know if it was a cloned event or it was the original - and which one makes a difference because they are attached to different objects. Does that help?

**Comment by dustymc** [comment] 2020-12-08 21:13
Still lost. 

"Cloned" has nothing to do with anything beyond saving some typing (which can all be immediately changed). I think perhaps you're suggesting there's something beyond that, but there's not.

**Comment by campmlc** [comment] 2020-12-08 21:19
I need to know if a student cloned an existing event and edited it (that's
OK) or editing an existing event (that's not OK). If the former, and if the
notification report says "cloned from event #x", I don't need to spend
hours trying to track down what happened. If the latter, there goes my
morning.

**Comment by Jegelewicz** [comment] 2020-12-08 21:19
Well I left out a step - in order to determine which event is the original, she has to visit the catalog records associated with both to make sure that the appropriate event was edited.

**Comment by Jegelewicz** [comment] 2020-12-08 21:25
What about tracking "creation date" of an event - does that happen? If Mariel could see that an event was created (whether through cloning or any other method) on the same day the edits shown here took place, then she could feel confident that the student did not alter the wrong event. Maybe?

**Comment by dustymc** [comment] 2020-12-08 21:33
"Cloning" creates an event, which is a logged action. https://arctos.database.museum/info/collectingEventArchive.cfm?collecting_event_id=11768182 popped in to existence right before it was edited. Is that what you're asking for??

10221581 seems to have been merged so I'm not sure what it looked like.

It's possible to "edit" an event in any number of ways - eg, by replacement. Perhaps that's the point of confusion?

I don't track create date, but I do have edit date and create is the first "edit" if that's somehow useful - it's in the change log.

**Comment by Jegelewicz** [comment] 2020-12-08 21:34
> "Cloning" creates an event, which is a logged action. https://arctos.database.museum/info/collectingEventArchive.cfm?collecting_event_id=11768182 popped in to existence right before it was edited. Is that what you're asking for??

YEAH! I think that would help.

**Comment by Jegelewicz** [comment] 2020-12-08 21:40
> I don't track create date, but I do have edit date and create is the first "edit" if that's somehow useful - it's in the change log.

How does Mariel see that first edit date? I assume the date circled here is the date of the change from the line it is on, to the line above...

![image](https://user-images.githubusercontent.com/5725767/101544650-42313a00-3963-11eb-8676-199ff5df6d77.png)

**Comment by campmlc** [comment] 2020-12-08 21:47
Yes, but I need to know the creation date of 11768182. That would tell me
it was created yesterday (presumably by clone), and then edited yesterday.
It would also be extremely helpful to know, if there is a clone, what the
source event ID was that the clone was created from, in order to make sure
that nothing inappropriate was changed.

**Comment by dustymc** [comment] 2020-12-08 21:50
>see that first edit date

You circled it.

Yes that's the date it left that state.

>creation date 

Bottom row.

>what the source event ID 

It's apparently been deleted, which is expected behavior. Maybe that's the source of some confusion here??

**Comment by campmlc** [comment] 2020-12-09 00:10
What is the event the clone was copied from? If there was an event from
2095 that was deleted, and the date was changed to 2019, then that is a
problem.

**Comment by campmlc** [comment] 2020-12-09 00:10
2005

**Comment by dustymc** [comment] 2020-12-09 00:26
Nevermind, it was probably https://arctos.database.museum/place.cfm?action=detail&collecting_event_id=10221581 which is the only event with that date interpretation (thankfully!). It's not deleted, it just doesn't have an edit history.

There are sometimes thousands of events merged - which involves deletion - in any given day. It's not a problem.

Again, there's often very little relationship between a "source" event and the result. Maybe they didn't want to pick a locality. Maybe that's the only path they know of to make an event. Maybe they just like that particular button. There's no way to know, and no reason to think it's anything other than an arbitrary way to end up with something that can then be used in various ways. I can think of no possible way in which knowing anything about the process, including where it might have started, could be informative.

**Comment by campmlc** [comment] 2020-12-09 01:21
So we are back to square one with me having to sleuth every change, and no
resolution to the original problem.
Given the notification below: Why was the original date changed from 2005
to 2019? 2005 was before this wolf was born. Why is a 2005 event being
changed to 2019? Was the 2005 event cloned and then changed to 2019? If so,
how can I check the original 2005 event to make sure it was not changed?
What was the original event ID?  How do I know for certain that this is a
clone that has been edited? Should I just throw up my hands because I have
no way to resolve this, much less the other 9 events in this notification?
ChangeDateUserIDEventIDLocalityIDVerbatimLocalityEventNameVerbatimDate
BeganDateEndedDateRemarkAttributes
currentData -n/a- 11768182
<https://arctos.database.museum/Locality.cfm?action=editCollEvnt&collecting_event_id=11768182>
specimens
<https://arctos.database.museum/SpecimenResults.cfm?collecting_event_id=11768182>
media (0)
<https://arctos.database.museum/MediaSearch.cfm?action=search&collecting_event_id=11768182>
10170320
<https://arctos.database.museum/editLocality.cfm?locality_id=10170320>
Sevilleta
Wolf Management Center; Socorro, NM 7-1-2019 2019-07-01 2019-07-01 Accession
2019.085.Mamm no
{ts '2020-12-06 14:14:55'} Serina S. Brady 11768182 10170320
<https://arctos.database.museum/editLocality.cfm?locality_id=10170320>
Sevilleta
Wolf Management Center; Socorro, NM 2005? 2005-01-01 2005-12-31

**Comment by Jegelewicz** [comment] 2020-12-09 15:29
@campmlc I'm going to make a suggestion for avoiding this. Don't clone the event. I don't know what the workflow is here, but what you are really after is the locality, so just pick it and create the event from scratch. If that doesn't make sense in the workflow, then I probably need the workflow to see if there is something else that might work.

**Comment by Jegelewicz** [comment] 2021-07-08 16:41
@campmlc is this still a problem?

**Closed** 2021-10-21 19:52 UTC
Labels: Function-Locality/Event/Georeferencing
