### ISSUE TITLE
data cleanup: bird banding data

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#4733] opened 2022-06-02 22:45 UTC
@dustymc @lkvoong Can you please help cleanup some data for MVZ:Bird?

1) The attached file has a list of 562 specimens with identifier type of 'USFWS: U.S. Fish and Wildlife Service' and values that are bird band numbers. The  identifier type is incorrect, it should be 'USGS Bird Banding Laboratory (BBL)' - please update these records with the BBL identifier type.

[MVZ_Bird_USFWSids.csv](https://github.com/ArctosDB/arctos/files/8828225/MVZ_Bird_USFWSids.csv)

2) These 562 specimens + an additional 339 MVZ:Bird specimens that already have 'USGS Bird Banding Laboratory (BBL)' identifiers have data entered inconsistently for the band number in the prefix-integer-suffix fields. The band number consists of a prefix and integer, e.g., 1313-99912 should be entered as:
prefix: 1313-
integer: 99912

Can you please make sure that all values associated with BBL numbers for MVZ:Bird are entered in the prefix and integer field, using the hyphen as a separator (hyphen goes with the prefix)?

This issue may extend beyond just MVZ:Bird, so it's probably worth checking other collection data as well. But I'd like to get this fixed for MVZ:Bird.

Thanks!

**Comment by Jegelewicz** [comment] 2022-06-02 23:20
I can probs get this fixed with the other identifier bulkloader if you guys have more pressing stuff to do. Just assign it to me if you want.

**Comment by dustymc** [comment] 2022-06-03 00:18
@Jegelewicz that'd be awesome. The splitter default is backwards, you'll have to use [square brackets](https://handbook.arctosdb.org/documentation/other-identifying-numbers.html#bulk-loading-rules) to get the desired result. Let us know if that's too much to deal with and we'll get it at the table level.

```
arctosprod@arctos>> select split_other_id('1313-99912');
                 split_other_id                  
-------------------------------------------------
 {"prefix":null,"number":1313,"suffix":"-99912"}
(1 row)

Time: 28.975 ms
arctosprod@arctos>> select split_other_id('1313-[99912]');
                 split_other_id                  
-------------------------------------------------
 {"prefix":"1313-","number":99912,"suffix":null}
(1 row)

```

**Comment by Jegelewicz** [comment] 2022-06-03 02:11
It'll be a week or so - but I'll probably work on this while I'm at SPNHC.

**Comment by Jegelewicz** [comment] 2022-06-04 15:53
USFWS: U.S. Fish and Wildlife Service ids have been deleted

**Comment by Jegelewicz** [comment] 2022-06-04 15:54
USGS Bird Banding Laboratory (BBL) ids are in the loader awaiting #4730

**Comment by Jegelewicz** [comment] 2022-06-04 15:56
File used to do this.
[MVZ_Bird_USFWSids.xlsx](https://github.com/ArctosDB/arctos/files/8838206/MVZ_Bird_USFWSids.xlsx)

**Comment by ewommack** [comment] 2022-06-09 19:20
Whoohoo! Thanks Carla.

**Comment by Jegelewicz** [comment] 2022-06-11 05:48
@ccicero I cannot load these as I don;t have access to the collection. You can download from the tool and re-load them.

**Comment by ccicero** [comment] 2022-06-27 19:55
@Jegelewicz Thanks Theresa! I can upload but have a question:

Currently there are 0 MVZ:Bird records with id type of USFWS, and 339 with BBL ids.

The file you sent has 562 ids with data as 
![image](https://user-images.githubusercontent.com/967275/176024025-b64acc33-3151-41dd-a67f-35eafefcaf46.png)

The other ID type for those should be 'USGS Bird Banding Laboratory (BBL)'

Do I just replace ' USFWS: U.S. Fish and Wildlife Service' in the othercatalognumbers and other ID type columns with 'USGS Bird Banding Laboratory (BBL)' - and this will restore the 562 records that previously had USFWS ids but with the correct ID type?

Presumably this formats those 562 records correctly, but there are still the other 339 records currently with BBL ids that may not be formatted correctly. How do we check/fix those?

**Comment by Jegelewicz** [comment] 2022-06-27 21:40
@ccicero that was the file I used to get rid of the incorrect USFWS numbers - the new BBL stuff is hanging out in the [other id loader tool](https://arctos.database.museum/tools/BulkloadOtherId.cfm) - you can download as csv from there and load them yourself (I cannot do this because I don't have access to the collection).

> there are still the other 339 records currently with BBL ids that may not be formatted correctly. How do we check/fix those?

I think we will need @dustymc to help get them?

**Comment by ccicero** [comment] 2022-06-27 23:14
@Jegelewicz Ah, got it, thanks! Data are in the process of loading. I'll delete your's once mine are loaded.

This brings up another question. I'm currently working on a bulkloader for 800+ Prairie Falcon blood samples with band numbers. Can I use the 'bracket' format to make sure that the values go into prefix and integer fields? There's currently no way to specify the prefix/integer/suffix field in the 'OTHER_ID_NUM_1' column. Or do I need to upload these identifiers separately in that format?

**Comment by ccicero** [comment] 2022-06-27 23:21
@dustymc Thanks! Wasn't aware of that.

**Comment by ccicero** [comment] 2022-06-28 16:16
@dustymc @Jegelewicz All 562 records loaded successfully, thanks! I deleted the pending 562 records in the bulkloader under Teresa's username.

Dusty, can you please check to see that all MVZ:Bird records with other ID type of 'USGS Bird Banding Laboratory (BBL) now have the numbers formatted as 1234-[56789] where '1234-' is in the prefix field and [56789] is in the integer field? If not, can you update those records to be formatted correctly? The ones I just uploaded should be correct, but there were an additional 339 BBL records that were entered previously and may not be formatted as such. Thanks!

**Comment by dustymc** [comment] 2022-06-28 16:50
@ccicero can you send me whatever final file you uploaded? There are some records with strange data, hopefully that's a formatting thing and not a bug. 

I'll shuffle things around after I figure out how they got like they are - I think its all yours other than one DMNS (DMNS:Bird:49836) @acdoll

**Comment by dustymc** [comment] 2022-07-18 20:42
ping @ccicero

**Comment by dustymc** [comment] 2022-08-09 18:10
@ccicero I could use some data here....

**Comment by ccicero** [comment] 2022-08-12 00:14
@dustymc sorry, I'll get this to you on Monday.

**Comment by ccicero** [comment] 2022-08-15 22:39
@dustymc Here is the file with the falcon data that I uploaded last. The other MVZ records are ones that I uploaded earlier or entered manually (and not always consistently). Thanks!

[DougBell_PRFA_blood_bulkloader_forArctos_CURRENT_toupload.csv](https://github.com/ArctosDB/arctos/files/9340299/DougBell_PRFA_blood_bulkloader_forArctos_CURRENT_toupload.csv)

**Comment by dustymc** [comment] 2022-08-16 00:26
Thanks, got it, but I'm not sure what to do about it. 

Your data contains ``1156-[02411]`` - a leading zero in the integer portion. Thats of course dropped when its forced to integer datatype, then when it tries to recombine to make display value that doesn't match the input so it falls back to the raw input, which in this case contains the markup. I suppose that should just error, or the markup thing should be considered a failed experiment, or the loader should be rebuilt with 3 (prefix, integer, suffix) columns, or ????

https://arctos.database.museum/guid/MVZ:Bird:194753

Big-picture, I'm very open to ideas - what we have obviously has some flaws.

More focused, what would you like me to do with these data? The number-bits have to parse out to integers, those cannot be padded.

**Comment by dustymc** [comment] 2023-01-31 14:40
Abandoned?

**Closed by dustymc** 2023-01-31 14:40 UTC
Labels: Priority-Normal (Not urgent), Type-Data/Database, Data Quality

**Comment by ewommack** [comment] 2023-01-31 21:05
> Your data contains 1156-[02411]

I can talk about the integer -> since the banding numbers are sequential the leading integer becomes important to be able to tell if you are working with bird 02411 from band size 1156. Otherwise you get bird 2411 from band size 1156, which can't be correct because the ID numbers have to have 5 numbers, so suddenly it becomes did you forget to include the first number (12411, 22411, etc) or the last (24111, 24112, etc). I'd have to dig a bit into the number use history at the BBL, but if we start dropping numbers we may jump into different decades or band types. Band numbers are predictably certain numbers of #s that you find in sequence.

Is there anyway to handle that leading zero @dustymc?
