### ISSUE TITLE
Remove Curatorial Pane from Public Search

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2858] opened 2020-07-01 19:22 UTC
The public search view includes curatorial info such as last edited and entered dates etc. However, data entered in these fields do not display in search results. It is misleading, however, as users may think they are getting results from the extra fields.

Recommend removing this pane, but keeping the option of searching on a range of dates that the items may have been cataloged. I have to search for specimens cataloged prior to Sept 2019 across all Arctos collections to find references for a paper, and I cannot do this logged in.

**Comment by AJLinn** [comment] 2020-07-01 19:45
Cultural collections place a great deal of contextual information in the Remarks field. If the curatorial pane is removed we need to keep Object Remarks available somewhere.

**Comment by dustymc** [comment] 2020-07-01 19:52
Duplicate of https://github.com/ArctosDB/arctos/issues/1563 and https://github.com/ArctosDB/arctos/issues/2179, and definitely not a bug

**Comment by campmlc** [comment] 2020-07-01 19:53
What is a bug is t

**Comment by campmlc** [comment] 2020-07-01 19:56
This pane contains fields which do not show up in search results. I cannot use this as a public user to search for a range of catalog entry dates. We should remove any fields that are not actually searchable. It may not be a bug, but it is a problem that cost me considerable time and resulted in incorrect search returns.

**Comment by dustymc** [comment] 2020-07-02 13:44
>This pane contains fields which do not show up in search results.

So do all the others.

>I cannot use this as a public user to search for a range of catalog entry dates. 

<img width="1343" alt="Screen Shot 2020-07-02 at 6 42 53 AM" src="https://user-images.githubusercontent.com/5720791/86366228-63149700-bc2f-11ea-8f40-22ec2dd85e11.png">

<img width="1353" alt="Screen Shot 2020-07-02 at 6 43 55 AM" src="https://user-images.githubusercontent.com/5720791/86366269-6f005900-bc2f-11ea-8b65-b532b707a7aa.png">

??????????????????

**Comment by campmlc** [comment] 2020-07-03 05:44
These search terms do not show up in the Show/Hide Search Terms pane. Are
they hidden for some reason?

**Comment by campmlc** [comment] 2020-07-03 06:00
I think I see the problem. The catalog date requires a range. I only need to find items cataloged prior to last September. But to find these, I have to make up an imaginary start date, e.g. 1800-01-01. Any reason why we can't just enter the end date?

**Comment by campmlc** [comment] 2020-07-03 06:02
It is also problematic that when I enter only an end date for the entered date, nothing happens. There is no prompt to say "you must enter a starting range for entered date".  If I weren't using show/hide search terms, I wouldn't know that my search had failed for that parameter.

**Comment by dustymc** [comment] 2021-04-28 14:33
independent dates in next release

**Closed** 2021-04-30 01:45 UTC
Labels: Bug, Display/Interface, Enhancement, Function-SearchOrDownload
