### ISSUE TITLE
List of names missing classifications by collection

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3541] opened 2021-03-25 17:51 UTC
It would be helpful to have a list of names missing classifications by collection, so collections can either add to Arctos or prefer a different source.

**Comment by campmlc** [comment] 2021-03-25 19:37
#1761

**Comment by campmlc** [comment] 2021-03-25 19:38
#3538

**Comment by dustymc** [comment] 2021-03-25 19:53
The easiest way is to look for blanks in FLAT. Reports/WriteSQL and something like...

```
select scientific_name from flat where guid_prefix='MSB:Mamm' and phylum is null group by scientific_name order by scientific_name
```
produces

```
Alces americanus
 Chaerephon pumilus
 Cratogeomys castanops parviceps
 Cratogeomys castanops perplanus
 Cratogeomys castanops pratensis
 Cratogeomys goldmani
 Dipodomys merriami insularis
 Gerbilliscus validus
 Hypsugo alashanicus
 Idionycteris phyllotis hualapaiensis
 Lepus townsendi
 Lophostoma
 Microtus pennsylvanicus pennsyvanicus
 Myodes smithii
 Neoromicia nanus
 Neoromicia tenuipinnis
 Pekania pennanti
 Peromyscus maniculatus bairdi
 Sorex monticola
 Sylvilagus nuttalli
 Sylvilagus nuttalli cf.
 Tamias quadrivittatus rufus
 unidentifiable
 Urocitellus brunneus brunneus
 Urocitellus canus vigilis
 Urocitellus elegans nevadensis
 Urocitellus mollis idahoensis
 Urocitellus mollis mollis
 Urocyon cineroargenteus
```

It's possible to write something more comprehensive, but 

1. It would be very complicated in the tiered source preference model, and
2. It would not be very informative - "has classification" and "has classification with expected data" are wildly different things, the SQL above is looking for "expected data."

You can find available columns with

```
select * from flat where 1=2
```

and I'm happy to help with SQL if something specific isn't working as expected.

**Comment by dustymc** [comment] 2021-03-25 20:34
Any misspellings should be nominated for quarantine - you can use the Issue template at https://github.com/ArctosDB/arctos/issues/new?assignees=&labels=Quarantine&template=taxon-name-quarantine-request.md&title=Quarantine+Taxon+Name+-+ and check existing requests at https://github.com/ArctosDB/arctos/labels/Quarantine

@cjconroy here's the same query for MVZ:Mamm:

```
arctosprod@arctos>> select scientific_name from flat where guid_prefix='MVZ:Mamm' and phylum is null group by scientific_name order by scientific_name
arctos-> ;
           scientific_name           
-------------------------------------
 Gardnerycteris crenulatum
 Neacomys amoenus
 Neacomys rosalindae
 Neacomys vargasllosai
 Octodon ricardojeda
 Pekania pennanti
 Pekania pennanti columbiana
 Pekania pennanti pacifica
 Pekania pennanti pennanti
 Rhinolophus lobatus
 Sorex monticola alascensis
 Sorex monticola elassodon
 Sorex monticola isolatus
 Sorex monticola longicaudus
 Sorex monticola malitiosus
 Sorex monticola mixtus
 Sorex monticola monticola
 Sorex monticola obscurus
 Sorex monticola setosus
 Sorex monticola shumaginensis
 Spilogale angustifrons angustifrons
 Spilogale angustifrons elata
 Spilogale gracilis amphialus
 Spilogale gracilis arizonae
 Spilogale gracilis latifrons
 Spilogale gracilis lucasana
 Spilogale gracilis martirensis
 Spilogale gracilis microdon
 Spilogale gracilis microrhina
 Spilogale gracilis olympica
 unidentifiable
 Urocitellus brunneus brunneus
 Urocitellus canus canus
 Urocitellus canus vigilis
 Urocitellus elegans nevadensis
 Urocitellus mollis artemesiae
 Urocitellus mollis idahoensis
 Urocitellus mollis mollis
(38 rows)
```

**Comment by campmlc** [comment] 2021-03-25 20:39
Thanks!

**Comment by dustymc** [comment] 2021-03-25 20:42
>either add to Arctos or prefer a different source.

For the sake of clarity, "prefer an **additional** source" is also a possibility.

**Comment by dustymc** [comment] 2021-04-08 13:50
Duplicate of https://github.com/ArctosDB/arctos/issues/1894

**Closed by dustymc** 2021-04-08 13:50 UTC
Labels: Function-Taxonomy/Identification
