### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2719] opened 2020-06-02 15:41 UTC
Attempted to bulkload records this morning. Browser spun for a long time then got:

![image](https://user-images.githubusercontent.com/5725767/83540228-40b71e80-a4b5-11ea-9aa9-ea4222648d57.png)

**Comment by dustymc** [comment] 2020-06-02 15:43
Send me your CSV - I'll hijack your issue in a bit...

**Comment by Jegelewicz** [comment] 2020-06-02 15:45
[L-2600_2799.zip](https://github.com/ArctosDB/arctos/files/4718202/L-2600_2799.zip)

There are probably taxon issues in this....

**Comment by Jegelewicz** [comment] 2020-06-02 15:46
Also, can't even get https://arctos.database.museum to open up now.

**Comment by dustymc** [comment] 2020-06-02 15:55
Try https://arctos.database.museum/login.cfm?action=signOut - I don't completely understand that yet, but it seems to somehow 500 your session - make a new one (by logging out/in) and it should be happy.

**Comment by dustymc** [comment] 2020-06-02 16:30
@Jegelewicz they're https://arctos.database.museum/Bulkloader/BulkloadSpecimens.cfm

**Comment by Jegelewicz** [comment] 2020-06-02 16:35
Just got a text from @lin-fred that our stuff is mixed up? I am getting the browser spin problem. Will log out and log back in, but we can't have that be the norm....

**Comment by Jegelewicz** [comment] 2020-06-02 16:36
And that's not working either... I can't get in.

**Comment by dustymc** [comment] 2020-06-02 16:38
Just delete and let me know when it's safe to reload. The table was empty a half-second or so before I loaded, apparently that was too much buffer!

**Comment by Jegelewicz** [comment] 2020-06-02 16:38
OK, used your link ad got back in. It appears that something has gone awry:

![image](https://user-images.githubusercontent.com/5725767/83545934-2bde8900-a4bd-11ea-90b8-7c1464b7c9a3.png)

**Comment by Jegelewicz** [comment] 2020-06-02 16:40
@lin-fred says

> I've noticed the bulkloader is super slow when uploading a file? I have 400 records and it's taking a few minutes to load it. So in that time either someone else loads items as well.

That needs fixing?

**Comment by Jegelewicz** [comment] 2020-06-02 16:42
OK, all deleted and @lin-fred waiting to hear from me before bulkloading. Of course anyone else could be using this thing....

**Comment by campmlc** [comment] 2020-06-02 16:45
Yes, this was a problem before - on my very first bulkload in 2012, I
loaded simultaneously with someone in Alaska and the data file was
merged/corrupted.
Any way to create a queue, or prevent simultaneous load?

**Comment by lin-fred** [comment] 2020-06-02 16:50
Thanks all,

To reiterate, since I started bulkloading yesterday. It takes quite a while for the file to load. I will try measuring how much time it is taking. So when this happens, it looks like the bukloader is empty, but really I'm sitting here staring at it for a minute or two - and of course that's always when everyone else also decides to load things. I usually didn't run into this problem much before - things would load fast enough that it was generally obvious when someone was using it (except on that rare occasion when we'd upload almost at the same time).


> Any way to create a queue, or prevent simultaneous load?

Something like this could work, some sort of queue that you get automatically signed into when you upload, so that no matter how long it takes for your data to load, you show up in the queue?

Also I got that 505 network error yesterday, but I got a phone call and by the time I got back it was working again.

**Comment by dustymc** [comment] 2020-06-02 17:19
>Any way to create a queue, or prevent simultaneous load?

Sure, just (much?) more complexity - new Issue please.

@Jegelewicz sorry misread the above - your stuff is there again

**Comment by lin-fred** [comment] 2020-06-02 17:57
speaking of...
![image](https://user-images.githubusercontent.com/19802479/83553258-2fc3d880-a4c8-11ea-90d0-05423145a1e2.png)

**Comment by dustymc** [comment] 2020-06-02 18:03
How do I recreate?

**Comment by lin-fred** [comment] 2020-06-02 18:08
I don't know, its when I click to go to the bulkloader, it just spins, and eventually gives me this error, and then I can't connect to Arctos whatsoever - it just happens for awhile. Yesterday it just started working at some point.

I am using Chrome on a windows 10 system. I don't know what else to give you

**Comment by Jegelewicz** [comment] 2020-06-02 18:13
I just went to the [code table list](https://arctos.database.museum/info/ctDocumentation.cfm) it worked fine, then selected ctspecimen_part_name and my browser is spinning...

**Comment by dustymc** [comment] 2020-06-02 18:32
@lin-fred try https://github.com/ArctosDB/arctos/issues/2719#issuecomment-637643402 and see https://github.com/ArctosDB/arctos/issues/2720 for what I suspect is the cause

**Comment by lin-fred** [comment] 2020-06-02 18:59
Thanks I will try that next time

**Comment by Jegelewicz** [comment] 2020-06-02 20:33
@dustymc I went to validate stuff you loaded:

![image](https://user-images.githubusercontent.com/5725767/83566900-f5653600-a4dd-11ea-8fab-6c6b0552a87b.png)

**Comment by dustymc** [comment] 2020-06-02 21:05
@Jegelewicz thx they're validated and the validator is a bit smarter.

**Comment by Jegelewicz** [comment] 2020-06-02 22:09
![image](https://user-images.githubusercontent.com/5725767/83574715-40d21100-a4eb-11ea-9227-f448b8d3f22b.png)

Hit "fix/view with Arctos tools"

get

![image](https://user-images.githubusercontent.com/5725767/83574773-5e06df80-a4eb-11ea-9573-0a92d6a64c76.png)

**Comment by Jegelewicz** [comment] 2020-06-03 14:51
@dustymc in the mean time - my option is to download, fix then get you to upload again?

**Comment by dustymc** [comment] 2020-06-03 15:04
Or there should be a 'load anyway' link, and then deal with them in the bulkloader

**Comment by Jegelewicz** [comment] 2020-06-03 15:13
Too late, I already downloaded and deleted.

Should I try to bulkload again myself?

**Comment by dustymc** [comment] 2020-06-03 15:24
Sure, let me know when you're about the click the button, maybe I'll see something interesting in my shiny new server-admin-thingee.

**Comment by Jegelewicz** [comment] 2020-06-03 16:22
So, if my session times out and I go to log in again, browser just spins....

**Comment by Jegelewicz** [comment] 2020-06-03 19:07
@dustymc I have used the sign out link twice and still cannot log in. Any suggestions?

**Comment by lin-fred** [comment] 2020-06-03 19:10
> @dustymc I have used the sign out link twice and still cannot log in. Any suggestions?

I am actually having this same issue right now as well

**Comment by ewommack** [comment] 2020-06-03 19:16
If my browser has been spinning over the past two days after I enter my log in info, I'll go and open another Arctos Tab and for some reason that one will load quickly while the other one continues to spin. In the new tab I'll be logged in.

I'm not sure why it works, but it has been. 
I'm on Chrome.

**Comment by dustymc** [comment] 2020-06-03 19:32
Possibly your browser has something fatal cached; you could try to clear cookies and data for Arctos. The session and connection counts looks well within the limitations today, which doesn't mean something else isn't being weird. The few times I've experienced this the new tab trick has worked for me.

**Comment by Jegelewicz** [comment] 2020-06-03 20:32
OK here is the solution.

1. Log in and browser spins.
2. Open a second tab and BOOM! I am logged in and Arctos is ready to go.

No way we should expect people to do this over and over again. We really need to figure out why this is a thing.

**Comment by dustymc** [comment] 2020-06-03 20:48
Yes we do. I just moved a bunch of heavy-use connections from PG into the DB, which will hopefully help, but I don't fully understand what's going on so I'm not completely sure what to do about it either.

Unless ya'll direct me elsewhere, once I can stop changing things in production and get back to test I intend to work on the stuff that'll let us cluster. The architecture is now built for that and I have an extra server (the one that was running ColdFusion in production last week) hanging around - I'm thinking that having redundant servers sharing the front end load would be a Really Good Thing. (We need kubernetes to get very serious about that, but I can probably manually juggle two servers for a while...)

**Comment by lin-fred** [comment] 2020-06-04 14:52
> OK here is the solution.
> 
> 1. Log in and browser spins.
> 2. Open a second tab and BOOM! I am logged in and Arctos is ready to go.

That only seems to work sometimes, and then the signout method seems to work sometimes, but then sometimes I just can't connect

**Comment by campmlc** [comment] 2020-06-04 16:33
I asked my neighborhood SysAdmin and was told "we've spent the last year
trying to get away from Tomcat and Java, trying to replace with Python and
EnginX."

**Comment by campmlc** [comment] 2020-06-04 16:37
To keep Tomcat running, I'm told you have to greatly increase the memory.

**Comment by dustymc** [comment] 2020-06-04 21:30
I'm up for absolutely anything at this point. A consultant would need access to TACC's systems, I'm no sure how they'd feel about some random person having that.

Given my experiences with tomcat, and the terrifyingly familiar experiences of those I've asked about this, some solid references would be in order.

We're running the tomcat that comes bundled with Lucee, which probably changes what the ideal consultant would look like.

Ditching (most of?) tomcat is also an option - I'm not emotionally attached to the current architecture, we could add apache or nginx and mod_cfml to the mix. 

We could get away from Java, but not in a year. We had that discussion early in SABI planning, I doubt it makes sense to revisit now.

The system has 16G  of RAM with ~12 dedicated to tomcat and consistently uses <~20% of it; I can't see evidence of that being the problem.

https://lucee.org/get-support.html might be a source of support as well.

**Comment by Jegelewicz** [comment] 2020-06-04 23:06
I don't want to be the complainer, but this is starting to bring me down. I think I have spent about an hour a day either watching my browser spin or logging out and logging back in and opening new tabs of Arctos. If I am the only one having this issue, then I'll just take a week off and hope that whatever goblin is living in my computer decides to move out.

**Comment by jldunnum** [comment] 2020-06-04 23:07
No, has shut me down today as well...

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by Jegelewicz** [comment] 2020-06-07 20:47
@dustymc some more observations.

I worked all day yesterday adding taxa and classifications and never once had this issue - however, I was also NEVER once kicked off due to my session expiring.

This afternoon, I did some stuff then went off on another project. When I came back, my session had expired. I log back in and I get the spinning browser.

So, something about session timing out seems to trigger the problem and with the shorter session time (30 mins) it would also be more likely?

**Comment by dustymc** [comment] 2020-06-09 22:36
I have an experiment which may solve this, I'll need about 10 minutes of down time to implement. I'll try to find some quiet time this evening unless someone wants to coordinate something sooner.

**Comment by dustymc** [comment] 2020-06-10 03:05
implemented

**Comment by Jegelewicz** [comment] 2020-06-11 13:28
I logged in this morning, worked for a half hour or so and logged out.

Realized there was one more thing I needed to do, so logged back in and get the spinning browser.

![image](https://user-images.githubusercontent.com/5725767/84390662-236d0900-abb5-11ea-873e-b59dce399855.png)

**Comment by dustymc** [comment] 2020-06-11 13:38
I'm bouncing while you're watching it spin. My setting obviously didn't entirely work, although maybe it helped. I have more in the queue, but I can't implement until uploads and sessions are tested, and I need another VM to really make use of those changes.

**Comment by lin-fred** [comment] 2020-06-11 19:44
It seems you're working on other implements to help, but as a heads up I am also getting the spinning load of death

**Comment by Jegelewicz** [comment] 2020-06-12 16:59
This morning, I worked for a couple of hours and somewhere in there my session timed out. Left for lunch, returned, logged in and spinning browser of death is what I've got. (Thanks for that one @lin-fred ). It finally got somewhere, but I had to open a new tab.

**Comment by dustymc** [comment] 2020-06-12 17:34
Blargh, thanks, I'll keep digging. Sessions are now being managed in the DB, my next scheduled major experiment requires a new VM.

**Comment by campmlc** [comment] 2020-06-12 19:16
I'll email Chris, then, since no one else has?

**Comment by Jegelewicz** [comment] 2020-06-15 13:50
This morning, I performed some searches as a public user, then later logged in and got the spinning browser. Opened another tab and I was logged in and able to work.

So, not tied to a username, but an IP address? (That's me talking like I know anything - I have no idea...)

**Comment by jldunnum** [comment] 2020-06-15 14:24
I was able to get in immediately as both public and logged in first time, which hasn't been the case lately.


______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by sharpphyl** [comment] 2020-06-15 15:45
I got the spinning browser (and have ever since the conversion) but then if I open another tab or select Search it tells me I'm already logged in and works fine.

**Comment by campmlc** [comment] 2020-06-22 17:23
Status report on this issue? What do we still need for resolution?

**Comment by campmlc** [comment] 2020-06-22 17:23
Need summary of critical issues for SC meeting June 23.

**Comment by dustymc** [comment] 2020-06-22 17:34
>Status report 

Something still isn't working correctly. I'm currently thinking it's a network issue (Chris may have a patch for that ~today) but I'm more or less guessing at this point.

I think I'm ~99% to having code that can run in a cluster, and I just heard from TACC that they've opened that firewall - that may be running in test before I hit save here.

* That's not a fix, but it might act like one anyway
* It's still a little wonky because the second instance is built on top of the old webserver VM.

>What do we still need for resolution?

If my network theory doesn't pan out, I think a consultant makes the most sense. I still don't know what precisely we need, or how they'd be allowed to access TACC, or any other details, I just know that this doesn't seem to be something that I or TACC have had much luck tracking down.

**Comment by Jegelewicz** [comment] 2020-06-23 15:55
see #2810

**Comment by dustymc** [comment] 2020-06-24 16:22
tentatively closing - it's looking like this was a network problem being amplified by tomcat's response to sleeping connections.

**Closed by dustymc** 2020-06-24 16:22 UTC
Labels: Function-DataEntry/Bulkloading
