### ISSUE TITLE
BUG?  New taxon creates genus regardless of classification of new taxon

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#1272] opened 2017-09-18 17:08 UTC
For several weeks when I add a new taxon, the name is inserted as a genus even if the taxon is a superfamily etc.  Is this a  BUG?  If I don't delete the line, it shows up in the first position above Kingdom on the taxon page.  I'm sure I've missed deleting it on several and don't know how to find and clean them up.  Can this feature be eliminated and just upload what's in our selected (usually WoRMS) source?

![screen shot 2017-09-18 at 11 00 19 am](https://user-images.githubusercontent.com/15368365/30554390-9f2facfc-9c61-11e7-9250-dbaf6216c84a.png)

**Comment by dustymc** [comment] 2017-09-18 17:37
Duplicate of #1188

**Closed by dustymc** 2017-09-18 17:37 UTC
