### ISSUE TITLE
Cannot Log In

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#3796] opened 2021-08-03 15:38 UTC
I am unable to log into Arctos. I have entered my username and password into both the log in space in the upper left corner and on the page itself. I get back a red notice that reads "Authentication failed. Additional Information: Connect failed.". I attempted changing my password, to see if that may have been part of the issue, and received the new temporary password almost immediately without issue, but I am still unable to sign in. 

![Screen Shot 2021-08-03 at 10 37 26 AM](https://user-images.githubusercontent.com/56844074/128044422-549a51bc-f3a7-43cf-af8a-e568d434e73e.png)

**Comment by Jegelewicz** [comment] 2021-08-03 15:41
duplicate of #3797

**Closed by Jegelewicz** 2021-08-03 15:41 UTC
Labels: Arctos Down, Bug
