### ISSUE TITLE
Borrow date problems

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#1263] opened 2017-09-08 23:39 UTC
What does this mean in the Borrow form? I’m trying to update the dates. It’s my first Borrow record.

> An error occurred while processing this page! 
> Error Executing Database Query. 
> [Macromedia][Oracle JDBC Driver][Oracle]ORA-01830: date format picture ends before converting entire input string

I’m trying to update the dates in the Received / Due / Lender’s Loan Date fields and I keep getting it. Not sure why there are time codes in the Received Date field either.

![ss_borrow1973-002](https://user-images.githubusercontent.com/17605945/30234646-a9e0fac4-94ab-11e7-9618-224ad2a7b966.jpeg)

**Comment by Jegelewicz** [comment] 2017-09-09 17:56
You need to get rid of the part of the date that represents time, then I think it will work. Can we stop the system from adding the time so this won't be a problem?

"Reality is an illusion, albeit a very persistent one." Albert Einstein

**Comment by AJLinn** [comment] 2017-09-09 17:57
Yeah, I try to remove the time bit, save, then change the date in the Due Date field and I get the error/burning up computer. Must be something else?

**Comment by Jegelewicz** [comment] 2017-09-09 18:03
Bummer. I have had this problem too, but it was probably a year ago and I don't remember how or if it was resolved.  Sorry I can't be more helpful!

"Reality is an illusion, albeit a very persistent one." Albert Einstein

**Comment by dustymc** [comment] 2017-09-11 15:55
Duplicate of #1125

I'll reprioritize that Issue.

**Closed by dustymc** 2017-09-11 15:55 UTC
