### ISSUE TITLE
Need Help with Arctos Error - bulkloader requiring dates on attributes?

### ISSUE THREAD

**Issue by Nicole-Ridgwell-NMMNHS** [ArctosDB/arctos#5674] opened 2023-02-16 20:07 UTC
# Error Text
ATTRIBUTE_DATE_2 is invalid

# Where it happened
Bulkloader, both when I validated the data and when I pushed them to the bulkloader anyway and tried to load them.

Here is my data (also accessible from Browse/Edit)
[Jenks_82186-82219.xlsx](https://github.com/ArctosDB/arctos/files/10760256/Jenks_82186-82219.xlsx)
[Jenks_82186-82219.csv](https://github.com/ArctosDB/arctos/files/10760258/Jenks_82186-82219.csv)

I didn't include a column for ATTRIBUTE_DATE_2 because I have no data for that column. I've also tried adding in a blank column for that field and got the same error.

Attribute 2 in this dataset is width. The donor measured the diameter of these fossils and gave that data to us when we acquired the collection, I have no idea when the measurements were taken, and I try not to make up data.

Per https://arctos.database.museum/tools/BulkloadAttributes.cfm?action=ld date is not a required field.

**Comment by Jegelewicz** [comment] 2023-02-16 23:26
Duplicate of https://github.com/ArctosDB/arctos/issues/4184

**Closed** 2023-02-16 23:27 UTC
Labels: Function-DataEntry/Bulkloading, Error Messages, Error Explanation
