### ISSUE TITLE
finalize locality sharing discussion

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ArctosDB/arctos#740] opened 2015-08-25 00:41 UTC
```
https://groups.google.com/forum/#!topic/Arctos/8tAGdoG-PME
```

Original issue reported on code.google.com by `dust...@gmail.com` on 21 Jul 2015 at 3:10

**Comment by dustymc** [comment] 2016-05-31 14:58
Duplicate of #729

**Closed by dustymc** 2016-05-31 14:58 UTC
Labels: Function-Locality/Event/Georeferencing, Priority-High
