### ISSUE TITLE
Code Table Request - Collection object needs re-imaging

### ISSUE THREAD

**Issue by camwebb** [ArctosDB/arctos#6432] opened 2023-06-22 16:03 UTC
## Initial request

**Goal**: Add the capacity to batch flag, and batch unflag, collection objects (or media) that need to be reimaged (see Context)

**Proposed Value**: 

~~Collection object attribute: `needs reimaging`~~

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctprocessing_history new value `needs reimaging`

**Proposed Definition**:

```
Media for this record are of poor quality and the object should be reimaged. https://github.com/ArctosDB/arctos/issues/6432 
```

**Context**: We often encounter poor images of specimens, either too low resolution, or out of focus. We need to flag these cases somehow in a way that those flags can be _batch deleted_ once the media are reimaged. While there are several places to add searchable text flags manually (e.g. in specimen remarks, in media comments) these remarks must be deleted manually too. The only batch options appear to be:

 * Create a dummy project, add GUIDs to project, delete project when images fixed. Drawback: no fine control on which images have been fixed.
 * Add a new specimen-level attribute that can then be bulk _unloaded_. This seems to be the best quick option.

Another option would be to add a searchable comment to the media record, and then have a way to _batch delete_ media metadata records for the poor quality, depreciated media, but this would require a new batch unloader.  And there is value to adding the flag at the level of the collection object rather than the media: having a single bad media does not necessarily mean that action is required for the whole object.

Apologies if I have missed prior discussion and solution of this matter.

**Table**: 

~~`ctattribute_type`~~

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctprocessing_history

**Collection type**: All

**Priority**: Medium - we need this now, but it's not mission critical.

**Example Data**:  [GUID](https://arctos.database.museum/guid/UAM:Herb:67057), [media](https://arctos.database.museum/media/10181224)

**Available for Public View**: Yes

**Project**: Add the issue to the [Code Table Management Project](https://github.com/ArctosDB/arctos/projects/13#card-31628184).

## Approval

- [x] Code Table Administrator[1] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] Code Table Administrator[2] - check and initial, comment, or thumbs-up to indicate that the request complies with the how-to documentation and has your approval
- [x] DBA - The request is functionally acceptable. The term is not a functional duplicate, and is compatible with existing data and code.
- [x] DBA - Appropriate code or handlers are in place as necessary. (ID_References, Media Relationships, Encumbrances, etc. require particular attention)

**Comment by dustymc** [comment] 2023-06-22 16:07
More or less a duplicate of https://github.com/ArctosDB/arctos/issues/6325

Suggest processing history [[ link ]](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type#processing_history) / https://arctos.database.museum/info/ctDocumentation.cfm?table=ctprocessing_history instead.

**Comment by camwebb** [comment] 2023-06-22 23:19
> More or less a duplicate of https://github.com/ArctosDB/arctos/issues/6325

That issue is about verifying that the image is of the correct object. This new one is a poor image quality flag.

> Suggest processing history CT

Agree - that would be a better CT for it.

We can, of course, keep track of these data issues externally, and if there is likely to be little need/support for this addition, please feel free to close the Issue.

**Comment by mkoo** [comment] 2023-07-05 17:11
This seems like a useful curatorial request. If added to Processing history CT, how best to access easily? 

Maybe we can have a new Status & Stats link to processing history so we can select a collection and find all records that needs re-imaging or is imaged etc? Also bulk updates is key too!

**Comment by AJLinn** [comment] 2023-07-05 17:40
I would find this took extremely useful as well. We have images taken in the early days of digital photography (1990s) and they are terrible quality. I'd love a flag for 'new image required'. Doesn't this make most sense to be a part attribute for the media part? Seems like under the Value column we could have a pick list for actions? We have something similar under preservation need:https://arctos.database.museum/info/ctDocumentation.cfm?table=ctpart_preservation_need
<img width="1127" alt="Screenshot 2023-07-05 at 9 39 03 AM" src="https://github.com/ArctosDB/arctos/assets/17605945/d42d67de-05d7-4df3-9c9d-659950a1c4e9">

**Comment by mkoo** [comment] 2023-07-05 18:04
Oh, even better@AJLinn !
I havent used that for part attributes but makes a lot of sense

**Comment by dustymc** [comment] 2023-07-05 18:40
>part attribute for the media part

The media part can only defensibly be a thumb drive or print or something else to which one might stick a barcode, so no. (Yea, I know that's not always the case, but pretending I don't see what's going on and building off the indefensible structure are different things. https://github.com/ArctosDB/arctos/discussions/5378 is a start of a conversation regarding how we might have nonshameful digital parts.)

I still think https://arctos.database.museum/info/ctDocumentation.cfm?table=ctprocessing_history looks like the place for this.

**Comment by Jegelewicz** [comment] 2023-07-05 18:41
> part attribute for the media part

I am guessing that @camwebb doesn't have such a thing as a media part, however, this could still be a preservation need for his "whole organism" parts.

**Comment by camwebb** [comment] 2023-07-07 03:17
On balance, for us, `ct_processing_history` is prob the best place for this. We don't have a very complex media landscape. A single photograph, then DNG and JPG. So the flag is best for the whole collection.

**Comment by dustymc** [comment] 2023-07-07 13:10
> for us, ct_processing_history is prob the best place for this.

Request edited accordingly.

**Comment by Jegelewicz** [comment] 2023-08-10 22:26
@ArctosDB/arctos-code-table-administrators anyone else willing to check a box?

**Comment by campmlc** [comment] 2023-08-10 23:37
I checked.

**Comment by Jegelewicz** [comment] 2023-08-11 14:29
added

**Closed by Jegelewicz** 2023-08-11 14:29 UTC
Labels: Function-CodeTables
