### ISSUE TITLE
Arctos Down - Spinning browser of doom

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#7600] opened 2024-03-22 20:45 UTC
Please complete to the best of your ability.

## Unplanned Outage
 - Date and time: Just started about 2:42pm MDT
 - Describe the outage: Every Arctos window or tool I try to open spins interminably. But I have internet (Chrome) and other websites open.

## Communication after outage
- [ ] Unpin this issue
- [ ] Banner updated @jegelewicz @mkoo
- [ ] Email sent to AWG 
- [ ] Tweet @lin-fred (@mkoo backup)
- [ ] Close this issue when above are complete

**Comment by Jegelewicz** [comment] 2024-03-22 20:49
duplicate of #7599

**Closed by Jegelewicz** 2024-03-22 20:49 UTC
Labels: Priority-Critical (Arctos is broken), Arctos Down
