### ISSUE TITLE
Bulkload Agents tool and Agent Preload Thingee

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#926] opened 2016-09-02 02:47 UTC
Some issues with bulkloading agents: 
I am having difficulty with the Arctos tools that screen for duplicate agents. When I upload a file to Bulkload Agents and view the results in Agent Preload Thingee to screen for existing agents, the screening tool only finds exact matches if they are in the beginning of the list of similar agent names.
The tool fails to catch exact matches, and  not all potential preferred name conflicts are displayed in the download and preload screen results.

In the case example attached here, the Agent Preload Thingee and download of the agent bulkload data only displays checks against preferred name through C. M. Thompson, but there are many other Thompsons in the agent table that are not checked against. It looks like Arctos only checked the first 18 for possible matches. Since the others aren't screened, it didn't catch an exact preferred name match farther down this list.  I assume all is OK until I attempt to bulkload and get an error. Then I have to correct, reload, let it scan through the list again until it hits the next agent with this same problem, etc. ad infinitum.

This problem is impeding/drastically slowing the bulkload of an additional 200,000 records.

![screenshot 2016-08-28 10 06 25](https://cloud.githubusercontent.com/assets/14808196/18190741/15d0a5b2-7082-11e6-8f20-4ae7d99f6410.png)

![screenshot 2016-08-28 10 09 15](https://cloud.githubusercontent.com/assets/14808196/18190676/b167f738-7081-11e6-8f6b-e7bbd1b7060e.png)

![screenshot 2016-08-28 10 06 07](https://cloud.githubusercontent.com/assets/14808196/18190689/c49fc38a-7081-11e6-96ca-ace740a50fdb.png)

**Comment by dustymc** [comment] 2016-09-02 15:30
Something - probably Excel - is truncating what you're seeing in Excel. The forms work, or did the last time I used them.

There's very little information in what you're providing, and given scant enough information both people and computers end up at fairly random places. Can the lower-quality stuff (single-"word" and "word"-plus-initials maybe) be entered as verbatim collector instead? 

A very quick scroll through the recent creations make me suspect that these are fairly low-effort. Low-data agents reduce the value (eg, probability of getting a correct answer) of everything else in Arctos, and cleaning up over the coming months and years will cost everyone a lot of time and effort. (That's still true if someone close to the originating collection HAS looked over them, but sometimes there's just no avoiding that situation.) Verbatim collector (and we can add similar attributes if that's somehow too specific) exists in part to avoid that situation.

**Comment by campmlc** [comment] 2016-09-02 18:10
The problem is not in Excel - I get the truncated version also when I view
the Agent Preload Thingee results in Chrome.

 It is true that the problems seem to occur with the abbreviated names,
e.g. last name only. I loaded these as agents because other collections
have done the same, and I think will continue to do the same in the future.
It may be that having an agent named "Thompson" with specimens in many
different collections may actually be useful in eventually sorting out who
a particular Thompson was, even if the agent itself is likely to represent
multiple individuals.

**Comment by dustymc** [comment] 2016-10-05 17:26
>The problem is not in Excel - I get the truncated version also when I view the Agent Preload Thingee results in Chrome.

Hmmm - I'll investigate this. There may be reason to limit the number of returns, but that should probably be explicit and the important stuff should be prioritized.

See #882 re: low-data agents.

**Comment by Jegelewicz** [comment] 2018-07-19 22:29
Was there a resolution to this?

**Comment by Jegelewicz** [comment] 2021-07-23 20:12
Tentatively closing as duplicate of #3698 and #3700

**Closed by Jegelewicz** 2021-07-23 20:12 UTC
Labels: Function-Agents, Function-DataEntry/Bulkloading
