### ISSUE TITLE
Add tool to bulkloader Controls to load non-DELETE records

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6091] opened 2023-04-04 17:08 UTC
Request to add the option to the Controls menu in Browse and Edit to select only those records that are not marked "DELETE" to load.
Reason: Since there is at least a 30 min wait for deleting records, each new upload of the same data requires a significant wait- long enough to disrupt workflow. 
I'd like to be able to download problems, fix the file, re-upload, and mark to load, even if there are existing records marked DELETE in the table. This would significantly decrease the time required to edit and load records.
Priority: High. Should be part of the overall bulkloader update.

**Comment by dustymc** [comment] 2023-04-04 22:06
duplicate of https://github.com/ArctosDB/arctos/issues/4354

**Closed by dustymc** 2023-04-04 22:06 UTC
Labels: Function-DataEntry/Bulkloading
