### ISSUE TITLE
New Low Quality Data Report

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2165] opened 2019-07-15 18:26 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html
From last Taxonomy Committee Meeting

**Is your feature request related to a problem? Please describe.**
We know there are taxa with inconsistent classifications (two species in the same genus with different higher classifications).

**Describe the solution you'd like**
An addition to Low Quality data reporting when all of a genus are not in same family, etc. so we can investigate?

**Describe alternatives you've considered**
Hunt and peck, find by serendipity

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment] 2019-07-15 19:01
This is more or less a duplicate of https://github.com/ArctosDB/arctos/issues/1699, and of course is a symptom of https://github.com/ArctosDB/arctos/issues/1698.

I do have a sliver of remaining hope that I can find some inconsistencies via #1699, but I think it will always be exceptionally difficult to find inconsistencies in a model designed to accommodate inconsistencies.

**Closed** 2019-09-13 22:58 UTC
Labels: Enhancement, Function-Taxonomy/Identification, Priority-Normal
