### ISSUE TITLE
Date field in borrow is adding time

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#1219] opened 2017-07-27 22:57 UTC
Received date - This causes edits to fail until you go and manually remove the time portion of the field.
![screenshot 2017-07-27 16 52 34](https://user-images.githubusercontent.com/5725767/28695485-9f33dadc-72ec-11e7-9513-558f70e82fb1.png)

**Comment by dustymc** [comment] 2017-07-27 23:18
Duplicate of #1125

**Closed by dustymc** 2017-07-27 23:18 UTC
