### ISSUE TITLE
Using the hierarchical editor

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2305] opened 2019-10-14 16:26 UTC
@ArctosDB/taxonomy will be using this issue to discuss use of the tool and begin development of how-to documentation.

**Comment by Jegelewicz** [comment] 2019-10-14 17:01
See Test Drive at https://docs.google.com/document/d/0B6A3B271M_PoYTFvbUNTZW1vSGhyWnZURlJfQVd0cHFoWThn/edit

**Comment by dustymc** [comment] 2019-10-14 19:07
The managed_by thing should be fixed - I missed patching it into a tool. (See: need dev environment!!)

Adding ranks to the pull thing isn't much problem, just needs an issue. You can probably do what you want from ../name/... and 'seed..' now.

I'm pretty resistant to doing magic things (especially when they'd effectively make this into a single-user environment), but we could talk about some sort of "edit everything" option, or you can edit everything in the CSV before you reload.

The " feature to update datasets " bit doesn't make much sense to me. If you're managing exclusively in the editor then you'd never want to overwrite your master copy, and if you're not then "updating" by pulling CURRENT stuff (not somehow refreshing whatever bits and pieces are still at some intersection) makes sense to me.

Practically, I don't have a history of how you ended up wherever you are; this would need to be a LOT more complicated (or perhaps less capable, which is also more complicated) to get there.

This thing is capable of dealing with fairly large datasets, but the idea has always been to pull something relatively small, make some changes, push those back to Arctos, and delete the hierarchical data. (Or to manage exclusively from the hierarchical tool, but nobody's set up a source for that.) I'm not sure what actually happens, but I don't think it's that.

There's some fairly sophisticated code trying to make hierarchies out of something that's very explicitly not hierarchical. Strange errors falling out of that isn't very surprising. Given specifics, I might be able to do something more useful.

I'm not seeing zeroes on http://arctos.database.museum/tools/taxonomyTree.cfm?action=manageDataset&dataset_name=Pulmonata%20-%20PMS - maybe something was still processing?

>new tab 

I generally prefer to leave that up to users, but I'm nowhere near consistent either. I think this needs discussed as global Arctos development guidelines (which would be awesome) and not just in the context of this one app.

>Are “records” taxon terms? 

No, names.

>how can they be imported but not in Arctos?

99% of these involve the single-record tool adding something "interesting" somewhere in what could have been a hierarchy.

>while it accepts the aphidID

That's just going to overwrite whatever you're doing here (and potentially de-hierarchy your hierarchy). Trying to manage names that are managed externally is just going to lead to frustrations like those caused by the single-record editor.

>It is nice to know that working with WoRMS (via Arctos) I can delete invalid taxa and just not fuss with them.  Big improvement for me but not for anyone working with the Arctos source.  

I'm not sure what this means, but I suspect there's some fundamental misunderstanding of something by one of us involved!

>still exceedingly complex

It's only complex if you're starting with non-hierarchical data, which usually gets that way from the single-record tool. If you're managing things solely in this tool, you should have to deal with the garbage exactly once, and every subsequent update should be very simple. This looks very much like a case of missing or misunderstood procedures from here. I might be able to suggest something if you'd tell me what you're trying to do in detail.

**Comment by Jegelewicz** [comment] 2019-10-16 21:18
@dustymc today @ArctosDB/taxonomy discussed being able to pull a csv of all classifications from a name search.

So, I search "Bufo" and get results:
![image](https://user-images.githubusercontent.com/5725767/66959399-80fd8580-f027-11e9-9ebd-a5ea241afaf2.png)

Could we have a button "Download CSV of all Arctos classifications in search results"? (And one for Arctos Plants, Arctos via Worms) We are thinking that such a csv would be easy to manipulate for consistency and then we could use the classification bulkload tool to upload the cleaned classifications.

**Comment by dustymc** [comment] 2019-10-17 04:21
Depends on the format. One term per row wouldn't be overly difficult. One term per column would - things like unranked terms and multiple terms of the same rank would be very difficult to flatten.

**Closed** 2020-10-01 15:02 UTC
Labels: Function-Taxonomy/Identification, Priority-Normal

**Comment by sharpphyl** [comment] 2020-10-21 21:29
@Jegelewicz   Let's either delete this from the Committee list or move it to the Propose to Close or Implemented or No Action Recommended column.  I think we discussed it adequately in our meeting today.
