### ISSUE TITLE
Help with Dates on Herbarium Labels

### ISSUE THREAD

**Issue by wellerjes** [ArctosDB/arctos#4186] opened 2021-12-11 16:49 UTC
I'm trying to change our herbarium labels to include more specific information about dates (began date, a date range, as well as verbatim date). I have tried copying similar codes from (working) reports I've downloaded to ColdFusion, but whenever I upload a new .cfr with this information, it tells me that what I've entered is "not a valid ColdFusion expression" (it's always in line 156, no matter what change I make; it was originally telling me that the issue was with higher geography, but I think I fixed that by adding "flat" to the beginning in ColdFusion). I've tried the "Test SQL" button in the report printer and that does not give me any errors. Do I need to change something in properties for the text box? Do I need to copy more information from the Handler on the report printer page? I'm looking at a bird skeleton label for reference, but the only part I want to carry over is the date information.

I am looking for something similar to this, copied this from the ASNHC_bird_skel_label_2:
IIF (BEGAN_DATE EQ ENDED_DATE, DE(DateFormat(BEGAN_DATE, "dd mmmm yyyy")), DE(verbatim_date))

My most recent test file is ChasHerbLabelTest2 (CHAS_label_herb_date_test2.cfr); the original herbarium label is CHAS_label_herb (CHAS_label_herb.cfr)

Thanks for your help!

**Comment by acdoll** [comment] 2021-12-13 17:00
In you coldfusion report, I think you need 'collecting_date' instead of 'verbatim_date'. Or you need to add just a plain 'verbatim_date' to the handler without the CASE WHEN modifier.

**Comment by dustymc** [comment] 2021-12-13 17:32
Bigger-picture, doing this sort of manipulation in CFML is not going to be available in the future. I highly recommend moving this into the SQL rather than trying to fix CF.

Additionally, formatting an ISO8601 date in that manner is not going to be predictable - I believe you'll get SOMETHING in all of the components with that operation, even if there's nothing in the data.

I can help with the SQL if you'll let me know more about what you want. Below is what I think you might be looking for; it'll return a "column" called "formatted_date" which can be used in the reporter (or you can alias it as any other valid column name):

```
select began_date,ended_date,verbatim_date,
case 
when isdate(began_date)=1 and length(began_date)=10 and began_date=ended_date then to_char(began_date::date,'DD FMMonth YYYY')
else verbatim_date
end as formatted_date
from collecting_event where collecting_event_id between 11856591 and 11856691
;

 began_date | ended_date | verbatim_date |  formatted_date   
------------+------------+---------------+-------------------
 1976       | 1976       | 1976          | 1976
 1967-02-20 | 1967-02-20 | 2-20-1967     | 20 February 1967
 2005-11-15 | 2005-11-15 | 11/15/05      | 15 November 2005
 1969-06-24 | 1969-06-24 | 6/24/69       | 24 June 1969
 2005-10-25 | 2005-10-25 | 10/25/05      | 25 October 2005
 1973-09-25 | 1973-09-25 | 73-9-25       | 25 September 1973
 1969       | 1969       | 1969          | 1969
 2008-09-20 | 2008-09-20 | 20-Sep-2008   | 20 September 2008
 1976-05-12 | 1976-05-12 | 5-12-'76      | 12 May 1976
 1976-10-15 | 1976-10-15 | Oct. 15, 1976 | 15 October 1976
 1976-10-07 | 1976-10-07 | 10/7/76       | 07 October 1976
 2005-09-06 | 2005-09-06 | 9-6-05        | 06 September 2005
 1974-10-23 | 1974-10-23 | 10-23-74      | 23 October 1974
 1970-09-25 | 1970-09-25 | 70-9-25       | 25 September 1970
 1976       | 1976       | 1976          | 1976
 1968-05-07 | 1968-05-07 | 5/7/68        | 07 May 1968
 2011-03-01 | 2011-03-01 | 3/1/11        | 01 March 2011
 2011-02-15 | 2011-02-15 | 2/15/11       | 15 February 2011
 1976-10-05 | 1976-10-05 | Oct. 5, 1976  | 05 October 1976
 2005-03-10 | 2005-03-10 | 3/10/05       | 10 March 2005
 1975-02-17 | 1975-02-17 | 2/17/75       | 17 February 1975
 2011-02-15 | 2011-02-15 | 2/15/11       | 15 February 2011
 1969-06-24 | 1969-06-24 | 1969-06-24    | 24 June 1969
 2005-02-09 | 2005-02-09 | 2-09-05       | 09 February 2005
 1966-06    | 1966-06    | June, 1966    | June, 1966 
 2007-10-02 | 2007-10-02 | 10/2/07       | 02 October 2007
 2003-08-11 | 2003-08-11 | 8/11/03       | 11 August 2003
 1969-06-24 | 1969-06-24 | 6/24/69       | 24 June 1969
 2003-10-02 | 2003-10-02 | 10'2'03       | 02 October 2003
 2008-08-25 | 2008-08-25 | 8/25/08       | 25 August 2008
 1999-08-06 | 1999-08-06 | 6 Aug 1999    | 06 August 1999
 2011-03-31 | 2011-03-31 | 3/31/2011     | 31 March 2011
 1969-06-24 | 1969-06-24 | 6/24/69       | 24 June 1969
 2003-09-18 | 2003-09-18 | 9-18-03       | 18 September 2003
 2008-08-26 | 2008-08-26 | 8/26/08       | 26 August 2008
 1969-01-22 | 1969-01-22 | 1/22/69       | 22 January 1969
 2011-03-01 | 2011-03-01 | 3/1/11        | 01 March 2011
 2006-02-21 | 2006-02-21 | 2/21/06       | 21 February 2006
 2003-04-09 | 2003-04-09 | 4/9/2003      | 09 April 2003
 2003-10-02 | 2003-10-02 | 10-2-03       | 02 October 2003
 2011-02-17 | 2011-02-17 | 2/17/11       | 17 February 2011
 2007-08-07 | 2007-08-07 | 8/7/2007      | 07 August 2007
 1971-02-27 | 1971-02-27 | '71-2-27      | 27 February 1971
 2003-08-11 | 2003-08-11 | 8/11/03       | 11 August 2003
 2011-02-17 | 2011-02-17 | 2/17/2011     | 17 February 2011
 1976-12-06 | 1976-12-06 | 12-6-76       | 06 December 1976
 1998-07-10 | 1998-07-10 | 7/10/98       | 10 July 1998
 2011-03-31 | 2011-03-31 | 3/31/11       | 31 March 2011

```

**Comment by wellerjes** [comment] 2021-12-14 17:52
Thanks for this info! Do you have a recommendation on an alternative to ColdFusion? Or recommendations on where to learn basic SQL? I have some basic knowledge of HTML, but I'm confused about where to pull the column names that will match in reports (I tried the column names from the Bulkloader Builder, but these do not seem to match).

@dustymc - Yes, your example is what I would like to include. Where should I enter this in the SQL? Also, if the began date and ended date are different, what would that look like?

Thanks!

**Comment by Jegelewicz** [comment] 2021-12-14 17:57
@wellerjes use the Write SQL option in the Reports and Services menu option - let me know if you have trouble locating it - here's a direct link - https://arctos.database.museum/tools/userSQL.cfm

**Comment by dustymc** [comment] 2021-12-14 18:05
>alternative

https://github.com/ArctosDB/internal/issues/37


>basic SQL?

@Jegelewicz  beat me to it, as usual - click the "cheat sheet" link.

>where to pull the column names

FLAT for simple stuff, or ....

<img width="369" alt="Screen Shot 2021-12-14 at 10 01 03 AM" src="https://user-images.githubusercontent.com/5720791/146054261-9e768e42-2801-43f3-befc-450239ba91a1.png">

for real tables, or let me know what you need (there's often complexity around various things, there are very few 1:1 relationships in Arctos).

> the began date and ended date are different

"else verbatim_date" in what I wrote, that could be adjusted in any way

> Where should I enter this in the SQL

For a report, in the report SQL - you can just insert the case blurb as a "column"

```
select
something,
somethingelse,
case 
when isdate(began_date)=1 and length(began_date)=10 and began_date=ended_date then to_char(began_date::date,'DD FMMonth YYYY')
else verbatim_date
end as formatted_date,
morestuff
from table where.....
```

and your report will have available columns/keys

* something
* somethingelse
* formatted_date
* morestuff

**Comment by wellerjes** [comment] 2021-12-14 18:29
Thank you for the resources!

I entered the new SQL in and am now getting the following ERROR: syntax error at or near ","
How do I narrow down which comma it is referring to? I tried Ctrl + F to determine if there are any extra spaces at the end of a line and removed them, but am still getting this error. (I'm working in the report named "ChasHerbLabelTest2")

**Comment by dustymc** [comment] 2021-12-14 18:36
```
locstring,
FROM
```
No comma after the last "column."

SQL generally ignores extra whitespace characters.

**Comment by wellerjes** [comment] 2021-12-14 18:44
I removed the comma after locstring and am getting the same error. In SQL Test, it says the syntax error at or near "," Position: 1459

**Comment by dustymc** [comment] 2021-12-14 19:01
```
 from collecting_event where collecting_event_id between 11856591 and 11856691
```

That was looking for the example above, I removed it and it dumps data.

The SQL at the top of the dump is useful if there are other problems.

**Comment by wellerjes** [comment] 2021-12-14 19:57
Thank you!

I pulled some labels and it's almost there. The dates only apply to the first four labels, then revert back to the verbatim date issue. Is there a reason it is not applying to the entire selection? (see attached)
[Herbarium Label Examples.pdf](https://github.com/ArctosDB/arctos/files/7714336/Herbarium.Label.Examples.pdf)

I also am having am having an issue with the locality not showing up correctly: flat.higher_geog
It still works on the original herbarium label, but when I try to copy the SQL over to my test label, it still doesn't pull the information. It may be related to the changes I made when I was trying to fix it in ColdFusion.

**Comment by dustymc** [comment] 2021-12-14 20:32
I need to know how you're getting there to be able to debug - I'm seeing all dates in a search, but your records might be different. Easiest is to save your search.

Ditto on the geography, but maybe you're concatenating NULLs which returns NULL with ``||`` in PG - try this for "locstring" - concat and concat_ws ignore nulls:

```
 TRIM(
    TRIM(leading ',' FROM 
        concat_ws(', ',
        CASE WHEN flat.higher_geog = 'no higher geography recorded' THEN '' ELSE 
        REPLACE(flat.higher_geog,'North America, United States','USA') 
        END , flat.spec_locality
        )
    )
) locstring
```

The other common issue is the reporter behavior when things don't fit - I believe the default is to display nothing if there's overflow, but there should be some setting to change that. Confirm any apparently-missing data is in the dump, then you know it's  available to the reporter.

**Comment by wellerjes** [comment] 2021-12-14 21:00
I realized what's happening with dates, the ones that I was confused about are the ones that have a range, so it's defaulting to verbatim. Those were at the end of the search, so (to me) it looked like it was only applying to part of the document.

> I need to know how you're getting there to be able to debug
I was working from a saved search, but I pulled the same information from the beginning and am having the same issue with geography (even with the new TRIM). There is plenty of room on the label for it to spill over onto the next line if it needs to.

**Comment by wellerjes** [comment] 2021-12-14 21:16
Is there a way to just pull higher geography/specific locality without any parameters? 
![Screenshot 2021-12-14 151510](https://user-images.githubusercontent.com/93737929/146080424-df7e13bf-25dc-4481-8d6a-f070cdccb131.jpg)
Example from DMNS-mamm_box_label; this just says "select higher_geog"

**Comment by dustymc** [comment] 2021-12-14 22:32
>added

I don't see it.

I added

,
flat.spec_locality,
flat.higher_geog,

and...

<img width="1006" alt="Screen Shot 2021-12-14 at 2 32 16 PM" src="https://user-images.githubusercontent.com/5720791/146089885-71c061af-0053-4495-9493-2db7712fc0ef.png">

**Comment by wellerjes** [comment] 2021-12-14 22:33
It runs okay in the SQL Test, but as soon as I try to the pull the report, there's an error.

![Screenshot 2021-12-14 163132](https://user-images.githubusercontent.com/93737929/146089822-8fe3ec55-37b0-4bbf-a1a4-f8022c297800.jpg)
I made some kind of progress (by which I mean there is a new, different error).

**Comment by dustymc** [comment] 2021-12-14 22:36
There's no longer a "column" called "locstring" in the data - remove it from the template, or alias something else eg

```
higher_geog as locstring
```

**Comment by wellerjes** [comment] 2021-12-14 23:10
Thanks! That fixed the geography issue. The dates have reverted back to verbatim, I must have accidentally deleted something when I was trying to fix the higher geography. It shows up fine in Test SQL, but not when I run the report.

This is the code, which is the same as above:
> CASE WHEN isdate(began_date)=1 and length(began_date)=10 and began_date=ended_date then to_char(began_date::date,'DD FMMonth YYYY') ELSE verbatim_date END as formatted_date

Do I need to rearrange how the columns are arranged under SELECT? Or do the dates need to have "flat" in front? (flat.began_date, etc.). Sorry for the confusion and thank you so much for your help!

**Comment by dustymc** [comment] 2021-12-14 23:14
Order doesn't matter, and you'll get an error if something's ambiguous. I can only guess without knowing what data you're looking at, but my dump still seems to be working as intended.

**Closed** 2022-01-25 01:36 UTC
Labels: Help wanted, Error Messages
