### ISSUE TITLE
Feature Request - Make Nature of ID an attribute of identifications

### ISSUE THREAD

**Issue by genevieve-anderegg** [ArctosDB/arctos#4829] opened 2022-07-15 18:29 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
If an identification is confirmed or supported in multiple ways (e.g., revised taxonomy, features), then multiple identifications need to be created to support that information, which is confusing when the same specimen is identified as the same taxa multiple times

**Describe what you're trying to accomplish** 
Make the identifications of a record less confusing when there are multiple identifications.
See #4094 and #4735

**Describe the solution you'd like**
Nature of id should be attribute of identifications, and there should be identification attributes just like every other part of the catalog record. This would make it possible to attach multiple attributes to add to an identification, instead of needing to create multiple identifications of the same taxon for a specimen if the identification was confirmed or created by multiple agents/sources.

Example: https://arctos.database.museum/guid/DMNS:Inv:1016
The legacy ID of the specimen was _Cypraea lynx_, which was synonymized and changed to _Lyncina lynx_. A student, Carol Cochran, updated the specimen identification based on the taxon change and then also confirmed the ID herself (physically examining the shell). Thus, the new ID _Lyncina lynx_ is confirmed in two ways; by the taxonomy update, and by in-person examination. Because this was confirmed in two ways, two identifications were added with different Nature of IDs, which is confusing.
Change Nature of ID as an attribute of an identification, and allow for multiple Nature of ID’s to be added so that it is clear when a single identification was confirmed in multiple ways, instead of having to add multiple identifications to the same record with the same taxonomy. 
This change can also help remove information that would otherwise be stored in remarks, as in https://arctos.database.museum/guid/DMNS:Inv:34528 . Instead of having the information that P. Sharp confirmed the ID in the remarks, this information could be added as another Nature of ID attribute to the same identification on the record
Related: Change the legacy and deprecated ID as per issue #4828

Before:
![Github issue](https://user-images.githubusercontent.com/83782023/179287715-0fe96a7e-3530-4fc0-a95d-849b22ca971f.png)

After:
![Slide2](https://user-images.githubusercontent.com/83782023/179287755-6a51e5f6-9200-45e5-9a4e-57c773226256.PNG)

**Comment by genevieve-anderegg** [comment] 2022-07-15 18:30
@sharpphyl @Jegelewicz

**Comment by Jegelewicz** [comment] 2022-07-15 18:57
I'm on board with identification attributes. They work well everywhere else, why not here?

**Comment by sharpphyl** [comment] 2022-07-15 23:13
Totally support this approach.

**Comment by wellerjes** [comment] 2022-07-16 14:13
Agreed!

**Comment by dustymc** [comment] 2022-07-18 16:49
>two identifications were added with different Nature of IDs

Yay! Entirely correct!

>which is confusing.

Are we trying to solve some UI problem, or is there an actual structural issue?

The suggested structure seems like a decent idea, and might (in conjunction with https://github.com/ArctosDB/arctos/issues/3540) provide a better mechanism to support things like https://github.com/ArctosDB/arctos/issues/4805.

Using the structure to create Franken-ifications sounds like the exact opposite of Research Grade to me.

Do note that an attribute-like structure would allow any number of whatever gets moved to it, and zero is a number. It seems that we have some desire to require things like nature of ID, and this would potentially make that impossible. (But we can still probably-usually-successfully make less-robust "requirements.")

**Comment by wellerjes** [comment] 2022-08-17 15:47
I think it's a UI problem. Too many identifications that are almost the same is confusing.

I am running into the same problem as @genevieve-anderegg. A volunteer looked at the specimen and confirmed its identification, which happens to have revised taxonomy. Having two separate entries to distinguish the identification and the revision makes whichever one comes second on the list look invalid. And if they aren't separated, which should appear first, revised taxonomy or features?

**Comment by dustymc** [comment] 2022-08-17 16:31
>UI problem

Suggest that be addressed in conjunction with https://github.com/ArctosDB/arctos/issues/3540, but if something as simple as better-defined borders adds clarity I could do that very quickly.

> which should appear first,

Currently: whichever one (exactly one) you accept (probably for arbitrary reasons that we'll try not to think about...).

With https://github.com/ArctosDB/arctos/issues/3540: they can be equal, which is almost certainly a better representation even for simple "dead rat" scenarios - AgentA did X and got TaxonZ, AgentB got TaxonZ using Y, etc., etc., etc. - lots of agreement (disagreement, whatever) using lots of species hypotheses (taxon concepts, whatever you want to call them), this critter is well within (nowhere near, whatever) the taxon circumscription, that makes it useful for lots of things, yay science. I'm not sure how to best visualize that, but figuring it out seems very worthwhile.

Losing that information by cramming it all into one identification that can't possibly adequately represent the situation seems "suboptimal" - or a bit less optimistic if we consider that also isn't capable of things like giving the identifiers proper attribution for their work.

**Comment by Jegelewicz** [comment] 2022-08-25 23:15
From AWG August Issues Meeting

Proposed change to the way Nature of ID looks -> when you have more than two Nature of IDs on one object it start looking funny odd in the field, the info goes into remarks currently

So would like to be able to pick more than one Nature of ID with the same taxonomy. 

But this doesn’t fit in the model at the moment

One question is how would it be required a Nature of ID with multiples that you can select for Nature of ID? How many do you require, can we require none?

Meeting members seem happy with having non-required.

So instead it would be able to add Nature of ID under attributes

Add onto issue that take out unknown in Nature of ID code table.

**Comment by campmlc** [comment] 2022-11-01 22:14
Sio are we proposing nature of ID as an identification attribute, with date and determiner?

**Comment by dustymc** [comment] 2022-11-02 15:54
https://github.com/ArctosDB/arctos/issues/3540 is holding some things up, it will require rewriting the UIs, this will require rebuilding the same UIs, lets couple them if possible. Here's an initial proposal, please fix whatever I get wrong....

Current table:

```
                             Table "core.identification"
          Column           |          Type           | Collation | Nullable | Default 
---------------------------+-------------------------+-----------+----------+---------
 identification_id         | integer                 |           | not null | 
 collection_object_id      | integer                 |           | not null | 
 nature_of_id              | character varying(30)   |           | not null | 
 accepted_id_fg            | integer                 |           | not null | 
 identification_remarks    | character varying(4000) |           |          | 
 taxa_formula              | character varying(25)   |           | not null | 
 scientific_name           | character varying(255)  |           | not null | 
 publication_id            | integer                 |           |          | 
 made_date                 | character varying(22)   |           |          | 
 identification_confidence | character varying(30)   |           |          | 
 taxon_concept_id          | integer                 |           |          | 
```
post-update (just missing nature_of_id but maybe some other stuff should be attributes as well?)


```
                             Table "core.identification"
          Column           |          Type           | Collation | Nullable | Default 
---------------------------+-------------------------+-----------+----------+---------
 identification_id         | integer                 |           | not null | 
 collection_object_id      | integer                 |           | not null | 
 accepted_id_fg            | integer                 |           | not null | <!--- this will become a nonunique rank for #3540
 identification_remarks    | character varying(4000) |           |          | 
 taxa_formula              | character varying(25)   |           | not null | 
 scientific_name           | character varying(255)  |           | not null | 
 publication_id            | integer                 |           |          | 
 made_date                 | character varying(22)   |           |          | 
 identification_confidence | character varying(30)   |           |          | 
 taxon_concept_id          | integer                 |           |          | 
```

plus new table identification_attributes

* localkey
* identification_id references identification(identification_id)
* attribute_type references new code table initial value 'nature of ID'
* attribute_value (works like other attributes, when type is nature this will reference https://arctos.database.museum/info/ctDocumentation.cfm?table=ctnature_of_id)
* attribute_units (not sure this will be used but let's don't preclude 'id as X because of Y measurement')
* determiner references agent(agent_id)
* remark
* method
* date


I think this would also provide a "lite" path to https://github.com/ArctosDB/arctos/issues/3288 (WHATEVER can be an ID attribute, no need to muck up nature) and https://github.com/ArctosDB/arctos/issues/4805 (terms - potentially free-text in any language - linked to a specific identification with a bit of their own metadata), and even https://github.com/ArctosDB/arctos/issues/5025 (not all X are called Y, but this one is).

Once that is (mostly) ironed out, we'll need to figure out how it looks in the bulkloader/data entry screen - https://github.com/ArctosDB/arctos/issues/5193. Each ID attribute (as proposed) would require the usual 7 columns, there's no limit on how many can exist.

And my initial reservations still apply: This has potential for serious misuse, in the form of not giving Agents proper attribution and severely limiting discoverability. "Yea yea this agrees" is a very poor substitution for an identification, but maybe that's still better than cramming it into remarks....

**Comment by Jegelewicz** [comment] 2022-11-10 23:43
@camwebb suggests that we are only allowed one Type of ID per identification - concept, name, LSID, or perhaps other name identifiers that we might encounter.

It was noted that currently one could easily provide an identification name that is in conflict with the taxon concept, both of which appear in the same identification - which takes priority? Wouldn't it be better to just USE the concept identification?

Anyway, today we think we see how this, #4776, and #3540 all kind of go together. Apologies if any of this seems nuts - I'm trying to distill an hour-long conversation into something useful!

**Comment by dustymc** [comment] 2022-11-11 00:40
>name that is in conflict with the taxon concept,

... and a sensu publication putting it in some third and wildly different category.

> which takes priority? 

That would be up to the user to decide. I would suggest that a savvy user would see that as an indication of the likely quality of the dataset as a whole ... and run.

>this, https://github.com/ArctosDB/arctos/issues/4776, and https://github.com/ArctosDB/arctos/issues/3540

...and https://github.com/ArctosDB/arctos/issues/4805 and https://github.com/ArctosDB/arctos/issues/5025 and some more....

>all kind of go together

Yes, and together solve some otherwise sorta-untouchable problems. I think it will be a HUGELY powerful system, but - as above and elsewhere - it will also be one which can be used to produce ~~utter garbage~~ slightly less than ideal data. 

I'm trying to get comfortable with the idea that that's not Arctos' problem, a process that largely started with https://github.com/ArctosDB/arctos/issues/4289. That idea should probably be documented somewhere.....

**Comment by Jegelewicz** [comment] 2022-12-01 23:29
[AWG gives the green light to this on 2022-12-01](https://docs.google.com/document/d/1zPuqUgNdsxU7xbTxU8bP0tez8BDtpxSDCNsEGMlY5TA/edit?usp=sharing).

**Comment by Jegelewicz** [comment] 2022-12-01 23:30
@dustymc I don't know how to use the milestones anymore - should anything approved for implementation also be next task?

**Comment by dustymc** [comment] 2022-12-02 16:57
>approved for implementation also be next task

I think there's some gray area in there, but the two criteria (I know how to do it, The Community wants it) of next task have been met so this one at least is good.

**Comment by dustymc** [comment] 2023-03-17 16:05
Last-minute request: are there any objections to moving identification_confidence to identification_attributes as well? Many records won't have this (so no need to have a place for it), seems obvious that it could benefit from method and such when it is used. I'm going to pretend that we all agree that this is a good idea unless someone chimes in very soon....

**Comment by campmlc** [comment] 2023-03-17 16:14
I agree

**Comment by dustymc** [comment] 2023-03-17 16:27
@DerekSikes knowing a bit more about how you use confidence (and nature of ID, and any other potential attributes) in that context would be useful. Maybe the form will need a bit more work than anticipated, but I can't imagine how this would be very disruptive: you fill in a couple more fields (determiner, method, etc.) if you want/need them, and (unlike now) you have the option to ignore things that you can't or don't want to stuff into a pigeonhole.

**Comment by DerekSikes** [comment] 2023-03-17 16:35
so we have to fill out determiner twice? Once for the ID and again for the id confidence? But this seems optional so I can leave those blank... complexity creep

**Comment by DerekSikes** [comment] 2023-03-17 17:07
But... I can see that often the person entering the information about ID confidence might not be the person who did the ID, so it's an assertion based on some assumptions etc. thus, I agree. When will we have a georeferencedby attribute?

**Comment by dustymc** [comment] 2023-03-17 17:15
>thus, I agree.

Still seems kinda wonky to me, but there was a decision made in an open meeting and it seems to me that that should carry some weight (or we should have a lot fewer meetings, or SOMETHING - about anything other than how things have been working lately would be nice!).

>When will we have a georeferencedby attribute?

[October 5, 2022](https://github.com/ArctosDB/arctos/issues/5120#issuecomment-1269056594) - but it will stop being weirdly parallel with the flat version in locality with https://github.com/ArctosDB/arctos/issues/5331, of which this is one component. I'm starting on that now, but won't lock in https://github.com/ArctosDB/arctos/issues/5193 until after the AWG group meeting on 2023-03-23. I hope to be in production ~a week after that.

**Comment by dustymc** [comment] 2023-03-22 01:47
I've got the attributes mapped as 

	'nature of identification',
	'identification confidence',

alternative terms welcome.

**Comment by ewommack** [comment] 2023-05-16 21:21
The Diversity Committee would like to see this attribute creation go forward. We are potentially interested in adding one, depending on the way it is displayed and handled in the detailed record page and in data handling.

**Comment by dustymc** [comment] 2023-05-16 21:28
Can confirm that the development team would also desperately like to see this move, and has been panicking at the blockage of the [package issue](https://github.com/ArctosDB/arctos/issues/5331) for several weeks now.

We would also like to emphasize that there is still no [clear path forward ](https://github.com/ArctosDB/internal/issues/258)at this time.

**Comment by campmlc** [comment] 2023-06-05 19:11
I support moving forward with making identification confidence and nature of ID into attributes of identifications.

**Closed** 2023-07-21 23:21 UTC
Labels: Priority-Normal (Not urgent), Function-Taxonomy/Identification, Enhancement, Display/Interface, testable
