### ISSUE TITLE
Parts table/download selection issue

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/arctos#4323] opened 2022-02-11 23:00 UTC
The parts table has some trouble when selecting multiple parts to include or exclude. It seems to works sometimes, but not others. When I select the following:

![image](https://user-images.githubusercontent.com/12507297/153682206-4b538efa-0301-46fe-a6da-bb2cb552bbf9.png)

it only returns the muscle samples:

![image](https://user-images.githubusercontent.com/12507297/153681738-d008dd0f-2400-47cd-9c62-6b933393f6d6.png)

same weirdness with the exclude option. I'm pretty sure it has something to do with parts that have a comma in the name ("skin, study" or "heart, liver"). When you select just one of those comma separated names, you often get no results.

**Comment by dustymc** [comment] 2022-02-11 23:15
Duplicate of https://github.com/ArctosDB/arctos/issues/3645 caused by https://github.com/ArctosDB/arctos/issues/3654

**Closed by dustymc** 2022-02-11 23:15 UTC
Labels: Bug

**Comment by campmlc** [comment] 2022-02-12 01:18
Yes, this is a known problem. As far as I know, there has been no solution
proposed except to split all combo parts, which would be a huge undertaking
and massively affect data entry and parts tracking without major changes to
the interface. I wish there were some easier resolution. At least an error
message when a combo part is present, because bnow you could download and
not realize you weren't getting all parts. I bypass by downloading
everything and sorting out the parts in Excel, but that has a lot of
drawbacks.

**Comment by dustymc** [comment] 2022-02-23 15:41
> As far as I know, there has been no solution proposed 

Please read https://github.com/ArctosDB/arctos/issues/3654, there are several potential solutions offered.
