### ISSUE TITLE
Taxonomy search for "contains" (%) isn't working

### ISSUE THREAD

**Issue by sharpphyl** [ArctosDB/arctos#3029] opened 2020-08-19 17:24 UTC
Pre-PG I could search for a taxonomic term containing a string with the % command.  Lately, it doesn't seem to be working. A search for anything containing "pulcherimma" shows no results. 

<img width="520" alt="Screen Shot 2020-08-17 at 11 29 02 AM" src="https://user-images.githubusercontent.com/15368365/90668746-c5405000-e20d-11ea-9b9b-571265da3925.png">

There are several names that contain pulcherrima.

<img width="628" alt="Screen Shot 2020-08-17 at 11 29 24 AM" src="https://user-images.githubusercontent.com/15368365/90668716-bb1e5180-e20d-11ea-98e7-9ea06406b2fb.png">

<img width="519" alt="Screen Shot 2020-08-19 at 11 23 00 AM" src="https://user-images.githubusercontent.com/15368365/90669134-60d1c080-e20e-11ea-8497-13699baa5066.png">

**Expected behavior**
I expect to get everything with the search string.

**Desktop (please complete the following information):**
 - IOS Catalina 10.15.6
 - Safari and Firefox return the same results

**Comment by Jegelewicz** [comment] 2020-11-26 13:52
Dupe of #3230

**Closed by Jegelewicz** 2020-11-26 13:52 UTC
Labels: Bug, Function-SearchOrDownload, Function-Taxonomy/Identification
