### ISSUE TITLE
Needing to request a new password everytime I log in

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#2791] opened 2020-06-15 18:37 UTC
** Please use the "Report Bad Data" link where available to ensure the correct Curator receives your message. **

** Outages should be reported to the contacts listed at https://arctosdb.org/arctos-down/ **

** Arctos Documentation is http://handbook.arctosdb.org/ **

** Learn more about Arctos at https://arctosdb.org/ **

** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

**Comment by Jegelewicz** [comment] 2020-06-15 19:48
duplicate of #2792

**Closed by Jegelewicz** 2020-06-15 19:48 UTC
Labels: contact
