### ISSUE TITLE
Duplicate parts in MSB Mamm record

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2107] opened 2019-06-04 17:05 UTC
I need help tracking down the potential part duplicates for https://arctos.database.museum/guid/MSB:Mamm:89665

One of the liver samples is sequencing as Sorex monticolus, not Neotoma mexicana. There is an automated remark as to a potential part duplication with 
specimen_part.collection_object_id 21321183.
and 
specimen_part.collection_object_id 21342689
but I don't know how to resolve these IDs to a specimen.

**Comment by dustymc** [comment] 2019-06-04 17:19
Those comments were from some update intended to resolve something ambiguous involving containers - they will all refer to the same specimen, there's just a remote chance that the update created duplicate parts. One or more of these three things:

<img width="899" alt="Screen Shot 2019-06-04 at 10 16 39 AM" src="https://user-images.githubusercontent.com/5720791/58899472-e02eaf00-86b1-11e9-8e66-33bdd4528773.png">

might be a duplicate of one of those three things - that's it. (I think the one without the remark cannot be a potential duplicate either, but I'm not 100% sure of that.)

```

select
  specimen_part.collection_object_id partID,
  specimen_part.derived_from_cat_item CIid,
  flat.guid
from
  specimen_part,
  flat
where
  specimen_part.derived_from_cat_item=flat.collection_object_id and
  specimen_part.collection_object_id in (21321183,21342689)
 11  ;

    PARTID	 CIID
---------- ----------
GUID
------------------------------------------------------------------------------------------------------------------------
  21321183    2007354
MSB:Mamm:89665

  21342689    2007354
MSB:Mamm:89665

```

**Comment by campmlc** [comment] 2019-06-04 18:49
OK, so that means this must be an error from the field, e.g. wrong tissue
put into wrong vial or mislabeled vial. That is harder to sort out, but
good to know.

**Closed** 2021-01-21 20:06 UTC
Labels: Function-ContainerOrBarcode
