### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by gradyjt** [ArctosDB/arctos#3131] opened 2020-09-28 19:28 UTC
test issue 
@campmlc

**Comment by campmlc** [comment] 2020-09-28 19:31
Thanks, got it! Now I can tag you - @gradyjt 
 You can go up to the Watch tab at top of page and set your watch settings to a particular issue or all issues. If you do that, you will get notification of issues and responses via email, and can respond from your email. Otherwise, if you file an issue, you have to log in here to see the response.
I am going to close this with comment, as the issue is resolved.

**Closed by campmlc** 2020-09-28 19:31 UTC
