### ISSUE TITLE
Expand slider width in Customize Results and Search Tools

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#6068] opened 2023-03-28 02:18 UTC
Can we expand the width of the slider on the right of the Customize Results and Search Tools?
On my laptop, the slider is so narrow that it is almost impossible to grab to scroll up or down in the Customize table.

This would greatly improve the user experience.

Priority: High for me, as the level of difficulty makes it almost impossible for me to use this tool.

![Screenshot 2023-03-27 20 15 00](https://user-images.githubusercontent.com/14808196/228110069-87c3940e-61ca-4fd5-81c2-70fb8844cc66.png)

**Comment by dustymc** [comment] 2023-03-28 15:29
duplicate of https://github.com/ArctosDB/arctos/issues/5553

**Closed by dustymc** 2023-03-28 15:29 UTC
Labels: Priority-High (Needed for work), User experience
