### ISSUE TITLE
Data Entry Inconsistency

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2310] opened 2019-10-16 06:07 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
his is not exactly a bug, but it might as well be. In data entry, if you start from the Data Entry drop down and select data entry and go to your last entered record, you can edit the record and then save, at the very bottom of the screen, by clicking on Save this as a New Record. However, if you have already entered a record and have exited the data entry screen to check on or edit the record in AJAX, and then go back to data entry by clicking on a record key and then editing that record, instead of "Save this as a New Record" when you reach the bottom, instead you see "Clone this Record". Why two completely different approaches? The problem is that, depending on your starting point for data entry, you either can edit an existing record and then save the edits as a new record at the bottom of the screen, or, if you made the mistake of starting from AJAX, you get to the bottom and cannot save edits as a new record, but must instead discard all the edits you have just made, Clone the record, and then re-enter them. But you don't know which option you are going to get until you have already made your edits and end up at the bottom of the screen.
The choices should be the same whether you enter data entry from the main menu or return to it from the AJAX grid. Screen color is not sufficient info to keep track of where you are or where you started from.
Even better, for future reference, we should have the option of saving a record as we go and then continuing to edit until the record is complete. As is, if you make a single mistake, or forget that you came in from Ajax and have to clone first, then you are forced to re-enter the entire record completely from scratch.
This could be accomplished by changing the data entry screen to a series of pop-up boxes that prompt for a given tables' worth of data - first, accession and identifiers, then collectors preparators, then ID, then attributes (or better yet, locality info first . . . ) etc. This would be a massively better approach that would not only reduce frustration and speed up data entry but make it more accurate.
I will now return to re-entering my record for the fourth time. Perhaps this time I will get it right. God help the poor undergraduates trying to do this.

To Reproduce
Enter a record. Repeat. Check record in AJAX. Try to go back and re-enter a new record from the AJAX grid by clicking on an existing record key.

**Comment by dustymc** [comment] 2019-10-16 18:11
Some of this is documentation - I think @KyndallH had something pretty good at some point...

Some of this is resources - one screen is used for a few different things because one (complicated) app is easier to maintain than many (complicated) apps are.

Some of it might be your settings, but maybe I'm not understanding or you have things some particular way for a reason.

Starting here:

<img width="280" alt="Screen Shot 2019-10-16 at 10 49 41 AM" src="https://user-images.githubusercontent.com/5720791/66944928-fefb6580-f002-11e9-8a25-9d77ca27ae88.png">

The "green screen" will load as if you'd just saved a record - that is, it will be "seeded" with data from the last record, filtered by your preferences. Your comments suggest you have everything set to 'show' (not carry)?

>you can edit the record

At this point the data in your screen exists ONLY in your screen - it's pulled from a former record, has been pushed to your screen, and doesn't exist as a new record. The only option is 'save as new' because nothing else exists; you are not editing anything because there's nothing to edit.

>by clicking on Save this as a New Record

That's all that exists - you can turn the stuff in your browser into a new record.

>go back to data entry by clicking on a record key and then editing that record

Correct - that loads existing data into your browser, you can change (not create) it by saving.

> instead you see "Clone this Record". Why two completely different approaches? 

Clone creates something that didn't exist - the seed of a new record (in your browser) from the record you were just editing.

>Screen color is not sufficient 

What would be?

> we should have the option of saving a record as we go and then continuing to edit until the record is complete.

I'm not quite sure what this means. Automagically creating records seems like a very good way to end up with a huge mess, if that's what you're suggesting. Incrementally saving as you type would alter existing records; you suggest above that was NOT your intent so that's probably not what you're asking for.

>series of pop-up boxes

I am positive that anyone who entered data in Sybil/Versata would very strongly disagree! All of my experience suggests that having everything in front of you rather than hiding behind a tab makes for much cleaner data. That said, you can more or less do this now by hiding the stuff that you can enter with the 'add more' option.

**Comment by campmlc** [comment] 2019-10-16 18:21
This situation is something where we could use a usability analysis by
someone with experience with user interfaces. All I'm saying is that, while
I'm arguably not the most tech savy or organized person on the planet, I do
not think I am alone in finding this form to be incredibly frustrating and
difficult to use. Every time I use it, I end up having to re-enter data on
the same record multiple times. Each time, unless I focus intentently and
even if I do, I forget some step that results in duplication or loss of
data. Surely we can come up with something better that would improve
efficiency and data quality.

**Comment by Jegelewicz** [comment] 2019-10-16 18:22
We probably need to take this issue apart. Let's start with this:

> if you have already entered a record and have exited the data entry screen to check on or edit the record in AJAX, and then go back to data entry by clicking on a record key and then editing that record, instead of "Save this as a New Record" when you reach the bottom, instead you see "Clone this Record".

One thing that might help here is when you are in AJAX grid and "go back to data entry by clicking on a record key" the screen color should be blue (I think?) which signals that you are editing a record that has already been entered, not creating a new record from a previously entered record. Perhaps if the "Clone this Record" button were placed at the top of the screen (first thing you see) along with something like "This record has been added to the bulkloader, any changes you make in this screen will edit the existing record. If you wish to use this record to seed a new record "Clone this Record".

**Comment by campmlc** [comment] 2019-10-16 18:24
Yes, that would be a good first start.

**Comment by campmlc** [comment] 2019-10-16 18:49
I guess what I am getting at with the pop up idea is that there is too much
information to process on the single page.We don't have to use a mouse. But
if the data entry were parsed into sections we could scroll forward and
back to, I could change just those fields I need to change in each section,
not have to look at 50 fields at once and decide which to edit.
Another fun thing I just found is that, if you use Add Extras during data
entry but end up not saving a record (because you forgot to Clone) and have
to re-enter the record, the extras get added regardless. So you end up with
duplicate extras in the extras bulkloader. Given this, we need a way to
delete extras that will not be used after we mark the correct ones to load.

**Comment by Jegelewicz** [comment] 2019-10-16 18:59
> have in both places

I am always a fan of this one.

**Comment by dustymc** [comment] 2019-10-16 19:44
The data entry screen is complicated because it has to do everything for everyone; enter minimal-data algae and parasites with a host and lots of parts and everything else, edit all of that, edit things that were entered with other applications, handle data that won't fit in the underlying structure, etc. The built-in screen was initially intended for those few users who didn't write their own data entry apps. "Those few users" has somehow evolved into "everybody" (which I'll interpret as evidence that it's not too bad overall despite the design approach...). 

The infrastructure for stand-alone apps still exists, or it's trivial to write to a text file which can be bulkloaded with about anything (and that could also be automated from an app, I think). Rather than making the complicated thing more complicated in an attempt to make it simpler, it might be worth investigating the current stand-alone possibilities in some capacity. I don't know what appropriate technologies are out there at the moment, but things like feeding code tables to Excel probably isn't entirely unrealistic.

See also https://github.com/ArctosDB/arctos/issues/2178; perhaps that can somehow lead to clonable apps or something. That might be a good place to introduce a usability analyst as well.

>both places

Been there, done that! It's not overly difficult to replicate the controls, but they take up screen space and at some point (probably in google code - I can't find it) we (whoever that was...) decided to remove them from the top. We might find some "there when you need it" functionality; software has come a long way since I looked at that.

**Comment by campmlc** [comment] 2019-10-16 19:58
Teresa, you have a  Google form we can use as a test?

**Comment by campmlc** [comment] 2019-10-17 21:23
A further complication to this occurs when using the Clone feature from within the identifiers tab in specimen record. This feature clones the existing record into the bulkloader. When you do this and go to browse and edit and click the record key, you see a blue record. However, in this case, the record needs to be edited and saved, not cloned again, to avoid duplicating the source cataloged item. The two at the bottom of the page are Clone this Record and Save Edits.  I do think we need some user interface text to differentiate the source of a record, and clarify what would be an appropriate action. In this case, a blue record viewed from from the AjAX record key should say "This record has been added to the bulkloader, any changes you make in this screen will edit the existing record. If you wish to use this record to seed a new record use "Clone this Record" before making any edits". Alternately, a blue record from the Clone feature in specimen record should say "This record has been cloned from an existing cataloged item. Please edit and save as a new record to avoid duplicate catalog entries." or some such thing. And yes, we should have this and the Clone, Save as New Record, and Save Edits buttons at the top of the page as well as the bottom.

**Comment by Jegelewicz** [comment] 2019-10-17 21:47
Dang it, I thought I put this here yesterday. I have incorporated some code table values, but thinking more long term, it would be great if I could have the form use the Arctos code tables dynamically (especially the Agent names). 

https://docs.google.com/forms/d/1YUJH8iWjbwUsOB84mEWtsy94X8E75OmOAdRS9UGDpNw/edit?ts=5da1ecf4

Is a form I created to let me have students create an attributes bulkload for me. I haven't tried Dusty's suggestion to add the Agent's AJAX thing...

> http://arctos.database.museum/ajax/agent.cfm?q=tere exists if it can somehow be integrated.

**Comment by mbprondzinski** [comment] 2019-10-24 15:49
Okay, I see this has been a problem.   I won't clone records using the single entry data screen.  I may experiment with this, however.

**Comment by Jegelewicz** [comment] 2019-10-24 15:52
@mbprondzinski it probably would help if you take notes/screenshots when you experiment. Then we can write up some recommendations or documentation. Thanks!

**Comment by Jegelewicz** [comment] 2021-07-08 17:14
Closing as duplicate of #3691

**Closed by Jegelewicz** 2021-07-08 17:14 UTC
Labels: Display/Interface, Function-DataEntry/Bulkloading, Priority-High
