### ISSUE TITLE
Object Tracking Problem - Find Container fails

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#3794] opened 2021-08-02 20:09 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Trying to find a barcoded container yields only the collection, not the position in the collection

**To Reproduce**
1. Go to Object Tracking
2. Click on Find Container, enter MSB1038353 barcode
3. See part location: "Genomic Resources" 

**Expected behavior**
This is a cryovial in a freezer box in a freezer rack in DGR4 - I see none of this. Also happens going from Container details to Tree View

**Desktop (please complete the following information):**
 - - Browser [e.g. chrome, safari] Chrome

**Additional context**
Happening since last week

**Priority**
Very high - preventing work from being done

**Comment by dustymc** [comment] 2021-08-02 20:43
Duplicate of https://github.com/ArctosDB/arctos/issues/3788

**Closed by dustymc** 2021-08-02 20:43 UTC
Labels: Bug
