### ISSUE TITLE
Aphia Ids in "Arctos" source

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2167] opened 2019-07-15 18:41 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html
From last Taxonomy Committee Meeting

**Is your feature request related to a problem? Please describe.**
Arctos (via WoRMS) seems to be working well, but the functionality is not available unless that source is chosen. The functionality could be useful to those using both Arctos and Arctos Plants sources.

**Describe the solution you'd like**
Can we get the Aphia ID refresh functional in the Arctos and Arctos PLants sources so that when Aphia ids are added, updates will be made? (A consious decision on the part of someone managing taxa in these sources)

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment] 2019-07-15 18:49
This is a duplicate of https://github.com/ArctosDB/arctos/issues/1939 (and still a really great recipe for making inconsistent data in the most opaque way possible).

**Closed by dustymc** 2019-07-15 18:49 UTC
Labels: Enhancement, Function-Taxonomy/Identification, Priority-Normal
