### ISSUE TITLE
Code Table Request - One preservation attribute for "formalin-fixed, stored in 70% ethanol"

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#4309] opened 2022-02-04 17:03 UTC
**How to Use This Form**
This is a template with examples and guidance on how to best communicate with the Arctos Working Group. Please delete this section along with anything in square brackets ```[ ] ``` below before submitting. 

[ **Instructions for reference:** ]
[ Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html ]

[ Code Table Documentation is https://handbook.arctosdb.org/how_to/How-to-Use-Code-Tables.html ]

[[Video Tutorial - Submit a Code Table Request](https://youtu.be/t2jHbsRA3lk)]

**Goal**
To have one value to include both the fixation "formalin-fixed" and the storage medium "70% ethanol"

**Context**
[ Describe why this new value is necessary and existing values are not. ]
The alternative, doing this in two steps, I argue adds work, could lead to more errors, and as an additional step, could easily be forgotten by workers, leading to incomplete records. 

**Table**
[ Code Tables are http://arctos.database.museum/info/ctDocumentation.cfm. Link to the specific table you are requesting changes to here. ]

**Proposed Value**
Preservation - (formalin-fixed, stored in 70% ethanol)

**Proposed Definition**
A process whereby a whole organism, body, carcass, etc. is sufficiently fixed in a formalin solution (typically 10% formalin, aka 3.7% formaldehyde), rinsed, and stored long-term in a 70% ethanol solution.

**Collection type**
Could be all collections

**Attribute data type**
[ "Attributes" may apply to catalog records, parts, localities, and collecting events. You must specify a datatype (free-text, categorical, or number+units) if this request involves attributes. ]

**Attribute value**
[ For categorical attributes, code table controlling value  ]

**Attribute units**
[  For number+units attributes, code table controlling units  ]

**Available for Public View**
[  **Yes | No** to indicate whether the proposed value will be available for public view or available only for logged in operators.  ]

**Other ID BaseURL**
[  For OtherIDs, provide the following *or* explain why the unresolvable ID type is necessary:
1. "Base URL" with which to prepend entered values, and
2. A functional example URL, which should consist of the base URL provided in (1) plus a relevant value.  ]

**ID_References**
[  If the request involves https://arctos.database.museum/info/ctDocumentation.cfm?table=ctid_references, the changes must be coordinated with the Database Admin team for notifications to function.  ]

**Priority**
[  Please choose a priority-label to the right.  ]

**Comment by Jegelewicz** [comment] 2022-02-04 17:06
duplicate of https://github.com/ArctosDB/arctos/issues/4223 (at least in principle)

**Comment by cjconroy** [comment] 2022-02-04 17:09
Michelle Koo suggested if I wanted this for mammals I should create a new code table request. So that's what I did.

**Comment by Jegelewicz** [comment] 2022-02-04 17:10
Yeah - I just wanted to make sure the issues were linked!

**Comment by ebraker** [comment] 2022-02-15 19:54
I agree with @cjconroy - the two-step process will most certainly lead to errors. Also, as it stands we would have to use two bulkloaders in order to create records for the vast majority of fluid-preserved specimens (regular catalog record bulkloader plus part attributes for a formalin-fixed 70% ethanol specimen).

**Comment by cjconroy** [comment] 2022-02-15 20:04
Thanks for your support!

**Comment by campmlc** [comment] 2022-02-15 20:13
Yes, I can support this, but we may then need for MSB a similar attribute of ethanol fixed 70% ethanol preservation. These would be for our standard specimen fixation in 95% ethanol, transfer to 70% for storage, which is all our incoming fluid preserved specimens for mammals.

**Comment by campmlc** [comment] 2022-02-15 20:18
Currently we have "ethanol-fixed" but this does not leave the option of specifying the storage solution.

**Comment by Jegelewicz** [comment] 2022-02-17 21:32
Code table committee says add.

**Comment by Jegelewicz** [comment] 2022-02-17 22:12
Added.

**Closed by Jegelewicz** 2022-02-17 22:12 UTC
Labels: Function-CodeTables
