### ISSUE TITLE
Split ALMNH Earth Sciences Collections

### ISSUE THREAD

**Issue by jcabbott13** [ArctosDB/arctos#3409] opened 2021-02-05 16:04 UTC
We need to split the Geology and Paleontology out of the ALMNH Earth Sciences collections and do away with "Earth Sciences" for ALMNH. This should be easily done using the "Other Identifier" field where Geology is indicated by a G in the accession number string. All "G" collections would go to geology; everything else will go to paleontology. Please let us know what we can do move this along. Thanks!

**Comment by Jegelewicz** [comment] 2021-02-05 17:28
Discussed further in https://github.com/ArctosDB/data-migration/issues/442

**Comment by Jegelewicz** [comment] 2021-02-05 17:29
We need to just bite the bullet and get this done.

**Comment by jcabbott13** [comment] 2021-02-05 17:32
Thanks....it holds us up from getting these collections in GBIF and that is important for future proposals.

**Comment by Jegelewicz** [comment] 2021-02-05 17:33
It has been tickling the back of my brain for a while, but I was waiting for someone there to bring it up again because I have too much to do already...

**Comment by jcabbott13** [comment] 2021-02-05 17:34
Understood...sorry to add to the list, but let us know if we can do anything on this end.

**Comment by dustymc** [comment] 2021-02-05 17:43
The first step is creating a new collection.

After that's created, @lkvoong will need to lock things down and transfer whatever needs it to the new collection. I believe she may have magic for creating redirects in that process - are those needed?

@ArctosDB/arctos-working-group-officers we should review https://handbook.arctosdb.org/documentation/catalog.html#guid-prefix particularly "must never be allowed to change or expire" with a view towards incoming collections.

**Comment by Jegelewicz** [comment] 2021-02-05 17:51
There will actually be two new collections:

ALMNH:Paleo
ALMNH:Geol

both will be ES collections

@jcabbott13 and @aklompma please confirm that those GUID prefixes are OK

**Comment by jcabbott13** [comment] 2021-02-05 17:54
@aklompma should comment on this, but I think we wanted "GEO" rather than "GEOL"

**Comment by mbprondzinski** [comment] 2021-02-10 16:18
Why didn't this show up in my mailbox like everything else?!

**Comment by Jegelewicz** [comment] 2021-02-10 16:29
@mbprondzinski you weren't mentioned - sorry about that.

@dustymc @lkvoong can we get this done ASAP?

**Comment by dustymc** [comment] 2021-02-10 16:35
https://github.com/ArctosDB/arctos/issues/3409#issuecomment-774182383

We are not sure of what's being asked. We need new collection requests for any new collections, and clear instructions for anything else that needs to happen.

**Comment by Jegelewicz** [comment] 2021-02-10 16:37
> new collection requests

OK help me out - this institution already exists - where do they request a new collection?

**Comment by dustymc** [comment] 2021-02-10 16:47
https://handbook.arctosdb.org/how_to/new-collection.html

<img width="235" alt="Screen Shot 2021-02-10 at 8 47 11 AM" src="https://user-images.githubusercontent.com/5720791/107542013-97b0df80-6b7c-11eb-8b8e-bc8208583fa7.png">

**Comment by Jegelewicz** [comment] 2021-02-10 16:58
@mbprondzinski can we set up a time to go through this form together?

I am available today after 3PM MST or tomorrow before the AWG meeting (between 9 and 11 AM MST).

**Comment by mbprondzinski** [comment] 2021-02-10 17:00
I'm doing it right now!  I take it they are both ES, though the GUIDprefix will be Paleo and Geo?

**Comment by mbprondzinski** [comment] 2021-02-10 17:01
Do I need to fill this out twice?

**Comment by mbprondzinski** [comment] 2021-02-10 17:11
Why does it tell me I'm an "invalid admin user?!"

**Comment by mbprondzinski** [comment] 2021-02-10 17:15
Why is it saying I'm an "invalid admin-user?"
![image](https://user-images.githubusercontent.com/43214224/107545785-48c17500-6b91-11eb-89b0-37ac388382fd.png)

**Comment by mbprondzinski** [comment] 2021-02-10 17:16
It didn't like "Mary Beth Prondzinski" either!

**Comment by mbprondzinski** [comment] 2021-02-10 17:23
Can somebody please respond while I have this up on my computer?  I filled the thing out according to instructions and now I can't save it!  There is NO REASON why it says I'm an "invalid admin-user"!  Please help...someone....

**Comment by aklompma** [comment] 2021-02-10 17:29
I just discovered the conversation has been ongoing for a while. 
As far as I am concerned, we'd like to get rid of Earth Sciences altogether and just have a ALMNH:Paleo and ALMNH:Geo collection rather than Paleontology and Geology being subdivisions within Earth Sciences.

**Comment by mbprondzinski** [comment] 2021-02-10 17:36
I didn't get any messages on this either, Adiel.  I am having a dickens of a time trying to "create" two new collections and Arctos keeps telling me I'm an "invalid admin user"  (!)  I'm also being ignored by the Arctos community so I'm about ready to throw in the towel.  There is no acronym in the code table for "Paleo" or "Geo" only "ES", and they are added by the institution that wants them under the field "GUID_Prefix".  That's all I can tell you.  I filled out the request to split the collections, but I am unable to save it.

MB

**Comment by dustymc** [comment] 2021-02-10 17:39
Use your Arctos username; I'll clarify the form.

**Comment by mbprondzinski** [comment] 2021-02-10 17:42
Geez, thank you!  It didn't like the mentor name for Teresa either, so I used myself again.

**Comment by mbprondzinski** [comment] 2021-02-10 17:49
Collections have been created:  ALMNH:Paleo and ALMNH:Geo

**Comment by campmlc** [comment] 2021-02-10 19:26
Yay! Looks like the process was awful. We may have to do something similar
at UNM, so hopefully we can figure out how to streamline. Please document
all the problems you ran into!

**Comment by aklompma** [comment] 2021-02-10 19:56
> Collections have been created: ALMNH:Paleo and ALMNH:Geo

Yay!

**Comment by mbprondzinski** [comment] 2021-02-10 20:33
Okay here is documentation for "creating a new collection" under menu item "Join Arctos":
1. If you already are an established Arctos database institution and just wanting to add another collection type, go to "Finalize collection creation request" under "Join Arctos."
2. Read through the "Prerequisites" and if anything there isn't clear or hasn't been discussed with your institution, then don't proceed. If you believe you know what you're doing,* check all the boxes to affirm. *Note: the "admin_user" is the admin's login name NOT their Agent name.  
3. Your new GUID_prefix should be confirmed with your institution and the DBA team.
4. Your "preferred taxonomy source" should be decided ahead of creating the new collection. (There is a wide variety of taxonomy resources to choose from.) 
5. Have your Loan Policy URL copied from menu item "Manage Data," "Metadata," "Manage Collection."
6. After you've checked all the boxes, proceed.
7. Fill in the information on the form.  Sign it with your login name and your mentor's login name if you know it, or simply sign your login name in the mentor's field as well.
8. Voila!  A new collection has been created.

**Comment by dustymc** [comment] 2021-02-10 21:01
Thanks, that should be merged with the existing docs.

I'd move (3) to (1) - we need to see that early in the process.

(8) should be ".. new collection REQUEST..." - this form just gives us what we need to create collections, actually doing so necessitates people with scary passwords, and so...

(9): Summon @lkvoong and let her know the guid_prefix(s) you've submitted.

**Comment by mbprondzinski** [comment] 2021-02-10 21:07
I fixed your edits, Dusty.  Do I need to summon @lkvoong?  Thanks...

**Comment by Jegelewicz** [comment] 2021-02-10 21:57
@dustymc and @mbprondzinski WHERE should [this](https://github.com/ArctosDB/arctos/issues/3409#issuecomment-777010914) documentation go? There is just no intuitive way for anyone to know that [this](https://arctos.database.museum/Admin/pre_collection.cfm) is where you create a collection for an existing Arctos institution. 

I propose that we change "Finalize Collection Creation Request" to "Create a New Collection" because that what this does!

Then, we can put what Mary Beth wrote at the top of the page.

**Comment by dustymc** [comment] 2021-02-10 22:07
>where

https://handbook.arctosdb.org/how_to/new-collection.html (but there are somehow two similar forms??)

>change "Finalize Collection Creation Request" to "Create a New Collection" because that what this does!

It doesn't, it's a request, someone with a scary password must do the creation

**Comment by Jegelewicz** [comment] 2021-02-10 23:38
Yep so, "Create New Collection Request"?

**Comment by Jegelewicz** [comment] 2021-02-11 00:09
Update to documentation. - https://handbook.arctosdb.org/how_to/new-collection.html#existing-institutions

**Comment by Jegelewicz** [comment] 2021-02-11 00:10
Who gave the thumbs up and why can't I see that anymore?

**Comment by acdoll** [comment] 2021-02-11 00:30
Not sure... maybe Dusty? You get another one from me - thanks for doing the documentation!

**Comment by Jegelewicz** [comment] 2021-02-11 00:33
It's easy when someone else writes it!

**Comment by dustymc** [comment] 2021-02-11 01:54
Stealth mode...

You forgot (9) which could be part of (8)

>(9): Summon @lkvoong and let her know the guid_prefix(s) you've submitted.

**Comment by jcabbott13** [comment] 2021-02-11 13:44
If I'm understanding correctly, we have now have the appropriate ALMNH:Paleo and ALMNH:GEO collections, but what needs to be done to actually parse the records from the original ALMNH:ES into these?

**Comment by mbprondzinski** [comment] 2021-02-11 15:07
@lkvoong please be advised we have requested two new collections: ALMNH:Paleo and ALMNH:Geo

Thank you!

**Comment by campmlc** [comment] 2021-02-11 15:20
Thanks for documenting this, @mbprondzinski and @Jegelewicz !

**Comment by Jegelewicz** [comment] 2021-02-11 17:40
> You forgot (9) which could be part of (8)
> 
>     (9): Summon @lkvoong and let her know the guid_prefix(s) you've submitted.

It is part of 8 - that particular issue template already @'s her.

**Comment by dustymc** [comment] 2021-02-18 18:14
Done, right?

**Closed by dustymc** 2021-02-18 18:14 UTC
Labels: Priority-High

**Comment by mbprondzinski** [comment] 2021-02-18 18:15
Yes, thanks!
