### ISSUE TITLE
Ability to search on taxonomy field 'taxon status' from curatorial pane of specimens search

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#1695] opened 2018-09-19 21:34 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

There is currently no easy way to find all the specimen records in one's collection that are identified under invalid (unaccepted) names.

**Describe the solution you'd like**

Addition of the field 'taxon status' with a drop down menu listing the options (currently I believe there are only 3: valid, invalid, NULL) to the curatorial search pane of the specimen search form.

I expect that if I could search using this I would discover that many of the taxon names used in my collection are either NULL for this field or miscoded (valid when they should invalid or vice versa) so I will want some way to fix those in taxonomy, preferably a faster way than searching and editing one-record-at-a-time. (eg. find lots of taxon records & bulk update their taxon status field to 'valid')

This would allow data entry of invalid names as IDs for specimens and we can easily find those specimens later & fix their IDs (how to fix? Another problem that could be automated somehow.... perhaps a tool similar to the batch ID update tool (or a modification of that tool) that gives the user the ability to opt for "use the valid ID of this name" for the sci name. For this to work one would have to had already made relationships between names so Arctos knows that name x is a synonym of name y (and which of the two is invalid).

**Describe alternatives you've considered**

I try to rely on memory to keep the names in my collection valid. Not ideal!

**Additional context**

**Priority**
I would like to have this resolved by date: __2019_____

**Comment by dustymc** [comment] 2018-10-01 16:33
This will be in next release.

Performance is not very good - we just don't have the processors.

The hierarchical editor in conjunction with the classification loader can consistently bulk-update.

I'm not sure how possible automation might be. In relationship data, we might have

TaxonA- exists
TaxonB - exists
TaxonA-->"bad duplicate of"-->TaxonB
TaxonB-->"bad duplicate of"-->TaxonA
(and back and forth a few more times, maybe...)

which doesn't tell you much about what's currently preferred. We might be able to get that from taxon_status, depending on what happens with https://github.com/ArctosDB/arctos/issues/1700.

**Closed by dustymc** 2018-10-01 16:33 UTC
Labels: Function-SearchOrDownload, infrastructure-limited
