### ISSUE TITLE
error feedback- I got this error when logged in trying to move containers

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#4536] opened 2022-04-11 17:20 UTC
As an operator logged in, I shouldn't get this generic error. 
In Edit Container: Move all children of this container to barcode
Trying to move freezer racks in positions in freezer DGR12749 (which has failed) to freezer DGR12547. 
Both freezers have positions. I need the racks in freezer positions in DGR12749 to move out of the freezer rack positions in that freezer and into the complementary freezer rack positions in DGR12547. 

I suppose I could go into the recipient freezer and delete all positions first, and then the racks + positions from the source freezer would follow? But that means the source freezer positions are deleted, it means extra steps, and it makes no sense - the source freezer positions are not moving, only the racks they hold.

**Comment by campmlc** [comment] 2022-04-11 17:32
I tried deleting the positions in the recipient freezer, and the tools still doesn't work.

**Comment by campmlc** [comment] 2022-04-11 17:33
Priority High - impeding work.

**Comment by dustymc** [comment] 2022-04-11 17:46
duplicate of https://github.com/ArctosDB/arctos/issues/4537

**Closed by dustymc** 2022-04-11 17:46 UTC
Labels: contact
