### ISSUE TITLE
Cannot find parasites by otherID num after host-parasite relationship made

### ISSUE THREAD

**Issue by cjconroy** [ArctosDB/arctos#3437] opened 2021-02-16 23:44 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Many parasites have had their relationship status changed from Self to Parasite Of. This seems to block them from being found under Other ID num. 

**To Reproduce**
1. Search MVZ for all mammals that are Host Of. Only 32 records. 
2. For example, one of them, 176804, is host to MSB:Para:18142. 
3. But, if you search all MVZ mammals for OtherID is ANY MSB:Para, you get 0, since we cleaned up all the unreciprocated host-parasites. 

**Expected behavior**
Seems like it would be a typical search to look for any specimens that are related to specimens in another collection. For example, how many MVZ mammals are also represented in Arctos by MSB parasites?  Can't clearly do that. I also tried searching for MVZ mammals that have relationship Host Of, and Related Identifier Type as MSB:Para. Nothing returns. I tried Term of 18142 to get that specific mammal host, but nothing. 

Seems that one would have to find all mammals that are hosts, and then trim that list down to just the MSB:Para. At the moment, there are only 32, but I expect numbers will grow. We have a lot at the Manter museum which will hopefully go online someday. 

**Priority**
Medium

**Comment by campmlc** [comment] 2021-02-16 23:50
I'm having the same problem. A search of MSB: Mamm with other ID MSB:Para  and vice versa only finds 6 records with collected with and same lot as relationships, not host of and parasite of.
Also, the Term field in relationships is not working at all.



![Screenshot 2021-02-16 13 22 44](https://user-images.githubusercontent.com/14808196/108136283-04454600-7077-11eb-967c-87146de59e82.png)
![Screenshot 2021-02-16 13 19 59](https://user-images.githubusercontent.com/14808196/108136287-060f0980-7077-11eb-82aa-dca67db81350.png)

**Comment by Jegelewicz** [comment] 2021-02-16 23:51
You have to search for anything with a relationship other than self in the relationships section, those "other IDs" are now treated as "related Ids".

![image](https://user-images.githubusercontent.com/5725767/108136021-6fdae380-7076-11eb-8bd6-62b22384032d.png)

This is a problem because it isn't an intuitive thing...

You can narrow down to a single other collection, but at some point you may want multiple collections here.

![image](https://user-images.githubusercontent.com/5725767/108136335-1de68d80-7077-11eb-834f-c6c11bcc1bf3.png)

**Comment by campmlc** [comment] 2021-02-16 23:53
See my example - that search isn't working either. . . .

**Comment by Jegelewicz** [comment] 2021-02-16 23:54
Is that because they are related by NK numbers?

**Comment by Jegelewicz** [comment] 2021-02-16 23:56
Nope, that's not it. I'm stumped because @campmlc search should return a whole bunch of records.

**Comment by dustymc** [comment] 2021-02-17 00:39
I think this is a duplicate of the issue asking to make id_references explicit, but its not on any of my lists - anyone know what crack that fell through?

**Comment by campmlc** [comment] 2021-02-17 00:50
I don't know why this doesn't work now, when it used to work in Oracle?
What changed?

**Comment by dustymc** [comment] 2021-02-17 15:24
>I don't know why this doesn't work now, when it used to work in Oracle?

I believe you asked to change it, but I still can't find that Issue.

This is different in test, and could use some testing.

**Comment by Jegelewicz** [comment] 2021-02-17 18:00
I got something in test:

![image](https://user-images.githubusercontent.com/5725767/108247006-5639aa80-710f-11eb-9b00-fc2f573c8ef9.png)

Don't know how correct that is, but seems plausible.

**Comment by campmlc** [comment] 2021-02-17 20:47
That looks reasonable to me. I'll take a look when I get back to my
computer.

**Closed** 2021-02-18 05:14 UTC
Labels: Bug
