### ISSUE TITLE
Feature Request - UI for managing catalog record search and results customization splashpage

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#5624] opened 2023-02-09 01:50 UTC
**Is your feature request related to a problem? Please describe.**

There's no UI and lots of people want lots of changes.

**Describe what you're trying to accomplish** 

change stuff in customize search, customize results forms

**Describe the solution you'd like**

build UI

**Describe alternatives you've considered**

* spreadsheet replace
* sql uopdates

**Additional context**

Maybe nobody ever used the old form's UI, not sure if this is a real ongoing need or just random complaints?

**Priority**

I don't know, see above.

**Comment by Jegelewicz** [comment] 2023-02-09 14:37
I am not sure what this is about? is it this?

![image](https://user-images.githubusercontent.com/5725767/217842727-51cb8eb8-59be-4bf0-9fbb-f0b4ecbd3c77.png

**Comment by Jegelewicz** [comment] 2023-02-09 14:48
If so, Here is what I remember - in the old UI, we could expand all for each section - which is what I did if I wanted something more than the contracted "simple" version. It was all or nothing by section and in a way easy-peasy. When I hit show all, the box expanded and stuff was there. Now when I select Show all options, there is a lag, the thing above shows up for either so brief a flash that I think there was a power surge or this morning it sat there for a few seconds before returning to the now expanded section. It is distracting! #5477 AND during this morning's lag I nearly started clicking things.

I don't know how many people were picking selected fields to show in search in the old UI. I never did. I always used all or nothing and just entered stuff in whatever field I needed. WAAAAYYY easier than parsing through a giant list of possibilities to find the one thing I wanted.

For results though, I can see this being difficult because there is no other way than scrolling through the big long list (you cannot CTRL+F on the popup). One thing that would make it so much easier IMO is if whatever fields I used in the query just showed up in the results instead of me needing to pick them twice from a huge list that often appears to be in no logical order (even when it is). If I asked for things with part name "skin", then I probably want to see part names....

Anyway, I may not even be talking about what you are asking about! I can move all of this if it isn't applicable.

**Comment by dustymc** [comment] 2023-02-09 15:24
> is it this?

The terms in that, and the related results customization.

>old UI

Not related. (And a completely different flow/UI, but maybe that's the problem I'm having so much trouble understanding - we've got a completely different THING but some users don't quite ken that and are trying to use it like the old; it's not so that's frustrating. ???)

**Comment by campmlc** [comment] 2023-03-17 17:36
agree with @Jegelewicz  that this is a problem with usage. Perhaps the customize forms will alleviate some of the difficulty.

**Comment by dustymc** [comment] 2023-03-17 17:41
Not sure we're in the same library, much less on the same page...

This is a request for a UI to the data that runs the two customize forms.

Until this happens, I can provide CSV which can be adjusted and reloaded. (As I've done several times in the past - and it can break all of Arctos, so maybe a UI isn't the best idea anyway.)

>all just want to be able to do what they used to do.

There's a pretty great API....

**Comment by Jegelewicz** [comment] 2023-05-03 00:06
Duplicate of #6096 ?

**Comment by dustymc** [comment] 2023-05-03 00:31
Nope, this is https://github.com/ArctosDB/arctos/issues/6210 without the spreadsheets and scary passwords.

**Comment by Jegelewicz** [comment] 2023-05-03 15:15
Ah Ha! I just now got it! This is about MANAGE this

![image](https://user-images.githubusercontent.com/5725767/235959915-3a262961-7b45-4e5a-8a11-49ee97f061ea.png)

Which is a bit like managing the Tools Directory? What is needed from us?

**Comment by dustymc** [comment] 2023-05-03 15:25
Yes, to manage the data behind that (and so also the API and such - eg anyone with access to this potential tool can break VERY "interesting" things, along with confusing everyone by changing all the field names and mangling the documentation, including that available remotely - eg MCZ might still be using our v1 webservice, and ALMNH's API definitely is.).

>What is needed from us?

Help in understanding this. [inline documentation](https://arctos.database.museum/doc/field_documentation.cfm) has been around forever (and can do all of the above) - does anyone use it, is it necessary, can we just do what we did with the spreadsheets, does any or all of that need documentation, etc. etc.

**Comment by Jegelewicz** [comment] 2023-05-03 17:40
> [inline documentation](https://arctos.database.museum/doc/field_documentation.cfm) has been around forever (and can do all of the above) - does anyone use it, is it necessary, can we just do what we did with the spreadsheets, does any or all of that need documentation, etc. etc.

I have edited it maybe once or twice to add "clickthrough". It is scary to use though and I'm not even sure that I understand the implications of changing things other than definition. I feel like it would be valuable to have a few users understand this UI and be able to confidently make changes to relieve you of some of that burden. If managing the customize search and results thing can be accomplished via this tool, then perhaps we ask for a few volunteers (or we pick them) and hold a training on how to do that?

**Closed** 2024-01-03 21:44 UTC
Labels: Enhancement
