### ISSUE TITLE
Arctos Permit Search?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1569] opened 2018-06-13 20:20 UTC
I suggest that we should have the basic info on permits that we provide to GGBN publicly searchable on Arctos. This would include permit available yes/no and permit type (dropdown list).  The Nagoya Protocol, which went into effect in 2014, regulates usage of organisms, tissues, and DNA from signatory countries, with the goal of ensuring that any usage of genetic resources provide benefits sharing to the originating country in exchange for access to the specimens. Nagoya does not only apply to tissue collections - it is any biological material collected internationally. And researchers from the EU or China or other signatories will need to have the info on permits for specimens from Mexico etc. to inform their loan requests. This may not affect all Arctos collections, but it definitely affects active collections that are still bringing in specimens from abroad.

I think Arctos should be on top of this, not behind the curve. Is this going to be a pain? Yes. But we should be aware and proactive.

More info here:   https://academic.oup.com/bioscience/article/65/6/543/304968

**Comment by dustymc** [comment] 2018-06-13 20:58
Here's the structure:

```
UAM@ARCTOS> desc permit
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 PERMIT_ID							   NOT NULL NUMBER
 ISSUED_DATE								    DATE
 EXP_DATE								    DATE
 PERMIT_NUM							   NOT NULL VARCHAR2(25)
 PERMIT_REMARKS 							    VARCHAR2(4000)

UAM@ARCTOS> desc permit_type;
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 PERMIT_TYPE_ID 						   NOT NULL NUMBER
 PERMIT_ID							   NOT NULL NUMBER
 PERMIT_TYPE								    VARCHAR2(255)
 PERMIT_REGULATION							    VARCHAR2(255)

UAM@ARCTOS> desc permit_agent;
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 PERMIT_AGENT_ID						   NOT NULL NUMBER
 PERMIT_ID							   NOT NULL NUMBER
 AGENT_ID							   NOT NULL NUMBER
 AGENT_ROLE							   NOT NULL VARCHAR2(255)

UAM@ARCTOS> desc permit_trans;
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 PERMIT_ID							   NOT NULL NUMBER
 TRANSACTION_ID 						   NOT NULL NUMBER
```

I'll need to know exactly what you want to see (search and results) and where before implementing anything, and that's probably useful for this conversation as well.

What we share with GGBN is https://github.com/ArctosDB/DDL/blob/master/flat/ggbn_flat_permit.sql (and that's likely to change soon). Basically just one of...

* Permit not required
* Permit not available
* Permit available

and "contact collection for information," and that only for permits linked to accessions.

**Comment by campmlc** [comment] 2019-03-15 21:00
See #1563

**Comment by dustymc** [comment] 2022-02-16 00:17
Duplicate of https://github.com/ArctosDB/arctos/issues/1372

**Closed by dustymc** 2022-02-16 00:17 UTC
Labels: Priority-High (Needed for work), Function-SearchOrDownload
