### ISSUE TITLE
Request to expand Agent search -- include Issued by and Id By relationships  in 'used by collection' queries 

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#7463] opened 2024-02-28 02:35 UTC
**Describe the problem**

click Agent:Search https://arctos.database.museum/agent.cfm

enter:
Marion Russell Smith
in the 'search most anything' field

limit results to

used by collection
UAM:Ento

get "no records found"

but the agent exists
https://arctos.database.museum/agent/21329833

and has done 21 IDs:

https://arctos.database.museum/search.cfm?identified_agent_id=21329833&collection_id=4

Note that if I repeat the search without the 'used by collection' it works.

This 'used by collection' bug I think is also killing searches for localities.

**Describe the solution you'd like**
_How might we accomplish your goals?_

```Used by Collection``` queries should include Issued Ids and Issued by relationships. (maybe one is easier to implement than the other so please let us know?) 

this is expected result from using the Used By collection field.

**Comment by dustymc** [comment] 2024-02-28 02:38
This is documented behavior, not a bug. This issue could be turned into a feature request if the desired functionality can be clarified.

<img width="339" alt="Screenshot 2024-02-27 at 18 36 25" src="https://github.com/ArctosDB/arctos/assets/5720791/792f6a1e-27c1-4a63-a40a-a1122d7d23e9">

**Comment by DerekSikes** [comment] 2024-02-28 02:44
the documented behavior is to make searches fail? I'm confused.

What needs clarifying? If the agent is used by a collection or not? Any place an agent can appear in UAM:Ento would count as 'used by' in my mind (identifications, collector, creator, preparator, etc)

**Comment by Jegelewicz** [comment] 2024-02-28 17:26
Same issue when used in object tracking - selecting a collection makes EVERY search fail to find anything - not sure why it is even there.

using collection
![image](https://github.com/ArctosDB/arctos/assets/5725767/94aebed2-e75c-4959-879a-cf4be29575a8)

no collection
![image](https://github.com/ArctosDB/arctos/assets/5725767/d625e708-b708-461a-8a00-fb8eef33357e)

**Comment by DerekSikes** [comment] 2024-02-28 17:34
It's not a bug, apparently.

**Comment by dustymc** [comment] 2024-02-28 17:37
>documented behavior is to make searches fail?

If by "fail" you mean "do exactly what the documentation says they'll do"???

>etc

I can't write code to that. If someone wants to be precise I can figure out the cost and see if we have the CPU to pay it.

>localities

Unrelated, Issue please.

>Same issue when used in object tracking 

Unrelated, Issue please.

**Comment by DerekSikes** [comment] 2024-02-28 18:22
Also, can we not have fields on search forms that are non-functional? It seems like the field was added to forms before the functionality behind the field was implemented?

**Comment by DerekSikes** [comment] 2024-02-28 18:31
The 'used by collection' field does not work

**Comment by dustymc** [comment] 2024-02-28 18:42
Adding ``identification_agent.agent_id`` and ``coll_obj_other_id_num.issued_by_agent_id`` roughly quadruples the cost - my test query generally runs in a little over 3 seconds without these, and in the neighborhood of 12 seconds with them. Everything seems to be using indexes and current statistics, I don't think there's a lot of room for further optimization.

I think we can afford the cost at the moment (eg with the current number of agent/record intersections), but ~12 seconds is also a wildly different user experience than 3. (See eg https://www.browserstack.com/guide/how-fast-should-a-website-load - I'm not convinced anyone knows the real numbers and we certainly don't have a typical audience, but users VERY quickly wander off.)

The implementation and maintenance costs of this are negligible.

The documentation (apparently already problematic?) will become more complex as things are added.

Please advise.

**Comment by mkoo** [comment] 2024-02-28 19:36
> The 'used by collection' field does not work

I actually use it all the time so it does work just not as expected! 

How's this suggestion (and maybe addresses some concerns for implementation too?); we change up that field and add another so it's clearer how the collection is being used?

- change the field to Collection Use in Transaction or as Collector
- add field Collection Use in Identification

(for now skip the Issued By usage as that was me adding that in and not Derek's original concern)
Also please suggest better wording above!

**Comment by dustymc** [comment] 2024-03-07 18:31
>skip the Issued By

That gets the cost down to ~double current, which is at least worth an experiment - will be in next release.

I'm also nuking the tooltip-things in favor of standard data-helplink documentation; maybe that's contributed to the confusion??

**Closed** 2024-03-12 00:40 UTC
Labels: Priority-Normal (Not urgent), Function-Agents, Function-Taxonomy/Identification, Display/Interface
