### ISSUE TITLE
Specimen event bulkloader rounding verbatim coordinates to nearest degree in locality coordiantes.

### ISSUE THREAD

**Issue by mvzhuang** [ArctosDB/arctos#3124] opened 2020-09-21 23:40 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Events loaded with the specimen event bulkloader is loading verbatim coordinates appropriately, but rounds the coordinates in locality to nearest degree. 

i.e. 
https://arctos.database.museum/guid/UTEP:Ento:10621

**To Reproduce**
1) batch load specimen events.

**Expected behavior**
Load the coordinates to both the collecting event and locality unless otherwise designated. Example data here. I already loaded these, but this is what my file looks like. Any easy way to fix this or should I delete everything?
[insecgeoref2_readyforupload.zip](https://github.com/ArctosDB/arctos/files/5258645/insecgeoref2_readyforupload.zip)

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment] 2020-09-22 14:34
This should be brought under the "component loader" fold - https://github.com/ArctosDB/arctos/issues/3125

There no way to save any existing data - PG is discarding data in the transformation, everything needs rebuilt around a more appropriate datatype.

**Comment by Jegelewicz** [comment] 2020-09-22 14:40
This should be a priority!

**Comment by dustymc** [comment] 2020-09-22 14:47
>priority

Then polishing up the template in https://github.com/ArctosDB/arctos/issues/2974 should be as well; it's (soft) blocking this.

**Comment by Jegelewicz** [comment] 2020-09-23 16:38
@mvzhuang I think I can fix these I fixed the example you gave above manually...

**Comment by Jegelewicz** [comment] 2020-09-23 16:54
Looking at the zip file - a lot of these localities are standard, so creating them in advance and naming them probably makes a lot of sense. That way you can just use the locality names in your event loads.

See https://arctos.database.museum/editLocality.cfm?locality_id=11270717

**Comment by Jegelewicz** [comment] 2020-09-23 16:54
I just loaded thousands of localities so let me know if you need anything!

**Comment by Jegelewicz** [comment] 2020-09-23 18:06
@mvzhuang while making fixes, I have found that you sometimes have what are duplicate localities but the remark means they won't merge. This isn't necessarily a problem, just wanted you to see it.

Searching localities for specific locality =West Virginia University Forest
![image](https://user-images.githubusercontent.com/5725767/94051732-31761c80-fd95-11ea-8c94-3d73f419f272.png)

Results in these:

![image](https://user-images.githubusercontent.com/5725767/94051685-1e634c80-fd95-11ea-918b-de911bf5dc6c.png)

**Comment by Jegelewicz** [comment] 2020-09-23 18:11
I went through the places in the file attached, merged stuff that could be merged and fixed coordinates for those localities. Let me know if there is anything else I can do!

**Comment by mvzhuang** [comment] 2020-09-23 18:44
wait how'd you do that? I have a couple thousand more localities that need to be fixed because I was uploading all of our georeferences that we did last month. Is there a way to bulk edit localities? I thought the locality bulkloader only created localities not edited?

**Comment by Jegelewicz** [comment] 2020-09-23 18:55
I am merging the ones that are the same, then editing the single locality. Working through by searching on rounded coordinates!

**Comment by Jegelewicz** [comment] 2020-09-23 18:57
It's kinda a pain, but also as you go you notice stuff that should probably be merged further (but would have to be done manually).

**Comment by mvzhuang** [comment] 2020-09-23 19:08
I think it might be faster to just delete and reupload then. There's about 1800 uniquish localities and I have 7 days left on this ant grant. Also shouldn't our auto locality merger thingy merge stuff and then we can merge further afterwards?

**Comment by Jegelewicz** [comment] 2020-09-23 19:18
> Also shouldn't our auto locality merger thingy merge stuff and then we can merge further afterwards?

It will eventually. I've probably fixed a couple hundred. Do you have an actual list of the localities or is that just a guess? I actually think I can fix up a file to have Dusty SQL in the coordinates to the existing localities but he's out today as far as I know.

**Comment by mvzhuang** [comment] 2020-09-23 19:34
Number is according to geolocate collaborative. I can make a file of current locality nicknames and coordinates. just need to name them all

**Comment by campmlc** [comment] 2020-09-23 20:14
Quick related question - how often does the locality merger run? I loaded
specimens with shared localities a few weeks ago, and there were problems
that need fixing. But they all loaded as unique localities - I'm waiting on
the merge to edit. Timeline?

**Comment by Jegelewicz** [comment] 2020-09-23 20:14
You should be able to put a higher geography on this if it has coordinates

https://arctos.database.museum/editLocality.cfm?locality_id=11265512

**Comment by Jegelewicz** [comment] 2020-09-23 20:15
@mvzhuang I think I can get a whole bunch of these done fairly quickly - what would help is a list of unique rounded lat/long combos.

**Comment by Jegelewicz** [comment] 2020-09-23 20:16
> Timeline?

That's a Dusty question.

**Comment by mvzhuang** [comment] 2020-09-23 20:19
> You should be able to put a higher geography on this if it has coordinates
> 
> https://arctos.database.museum/editLocality.cfm?locality_id=11265512

Yea these were the things i wanted to fix after we repatriated the data from geolocate collaborative. Not easy to fix mistakes from the collaborative client. There's a a few like that. 

ok can do about the coordinates list.

**Comment by mvzhuang** [comment] 2020-09-23 20:27
Took out stuff that has been fixed already. there's about 500 of these though!
[UniqueRoundedLatLong.zip](https://github.com/ArctosDB/arctos/files/5271736/UniqueRoundedLatLong.zip)

**Comment by mvzhuang** [comment] 2020-09-23 20:34
also @Jegelewicz can you show me the search you're running? I opened the rounded coordinates field, but when I search by 0, -79, arctos gets angry

**Comment by Jegelewicz** [comment] 2020-09-23 20:40
![image](https://user-images.githubusercontent.com/5725767/94067180-b7e92900-fdaa-11ea-9fd4-979c80f4803c.png)

**Comment by mvzhuang** [comment] 2020-09-23 20:40
ok thanks!

**Comment by Jegelewicz** [comment] 2020-09-23 20:41
I think we can whip these out pretty quick if we teamwork it!

**Comment by Jegelewicz** [comment] 2020-09-23 23:10
I added coordinates for all localities in the following groups:
All 9 or -9 latitudes
All 8 or -8 latitudes
All 33 or -33 latitudes
All 34 or -34 latitudes
All 35 or -35 latitudes

I'll pick away at these while watching TV tonight too.

**Comment by Jegelewicz** [comment] 2020-09-23 23:58
All 7 or -7 latitudes
All 6 or -6 latitudes

**Comment by mvzhuang** [comment] 2020-09-24 00:00
ok i'm working through some 40s!

**Comment by Jegelewicz** [comment] 2020-09-24 01:32
Anything with a latitude that starts with 5 or -5 is done!

**Comment by mvzhuang** [comment] 2020-09-24 01:40
I paused to try to get all the localities merged. Hopefully that will make things faster

**Comment by Jegelewicz** [comment] 2020-09-24 02:47
Just finished up the latitude 3 and -3

**Comment by Jegelewicz** [comment] 2020-09-24 03:01
Gotta shut down for the night. I'll get back to it in the am.

**Comment by dustymc** [comment] 2020-09-24 10:36
This should be fixed, but still needs converted to the "component loader" format.

There's a PG trigger on the temp table that converts various formats to DD.dd format and loads the conversion product, which was being returned in an inappropriate Oracleish datatype. That should be avoided if possible - I think PG12's generated columns would work, and be a lot less opaque.

I can delete anything that needs deleted.

The auto-merger doesn't do anything for 30 days, and then it's wildly variable - maybe 10 minutes, possibly months if there's lots to do. It was designed to run instantly, which seems to work a lot better to me, but there was pushback on that. Issue....

**Comment by Jegelewicz** [comment] 2020-09-24 14:06
@mvzhuang I have some calls to take today, but can continue helping with this!

**Comment by mvzhuang** [comment] 2020-09-24 14:44
Same. I have interviews and some meetings until afternoon

**Comment by Jegelewicz** [comment] 2020-09-24 14:47
Like JOB interviews? We need to have a call....

**Comment by mvzhuang** [comment] 2020-09-24 14:49
no no hiring work study interviews. I finaled another work study out of the community work study program but they didn't tell us how to hire them really until the beginning of the semester, so just got applicants finished last week.

**Comment by mvzhuang** [comment] 2020-09-24 14:56
@dustymc ok, here's the file of all the GUIDS that I need "accepted" specimen events deleted from. Let me know if I need to send it to you in any other format. 
[SpecimenEventGuids_Deletion.zip](https://github.com/ArctosDB/arctos/files/5277000/SpecimenEventGuids_Deletion.zip)

I'll reupload the specimen events for those ones after

**Comment by Jegelewicz** [comment] 2020-09-24 15:36
@mvzhuang @dustymc 

Just noticed this

![image](https://user-images.githubusercontent.com/5725767/94167025-3e544800-fe49-11ea-8188-4919f56e8ab5.png)

https://arctos.database.museum/Locality.cfm?Action=editCollEvnt&collecting_event_id=11716867

Not sure what happened here, but this should probably not happen?

Also, I guess I should just stop adding coordinates to localities?

**Comment by dustymc** [comment] 2020-09-24 15:38
I can smell the Excel from here....

**Comment by Jegelewicz** [comment] 2020-09-24 15:39
Should that cause some sort of error so that we don't get stuff like that?

**Comment by Jegelewicz** [comment] 2020-09-24 15:40
I mean, I guess it is VERBATIM, so "#NAME?" must be what was in there! UGH

**Comment by mvzhuang** [comment] 2020-09-24 15:43
probably is my fault. Something funky happened when I was messing with formulas maybe. looks like that's the only one it happened to

**Comment by dustymc** [comment] 2020-09-24 15:45
https://github.com/ArctosDB/arctos/issues/2678 is capable of that (if there's some pattern which can be defined), but seems to be stuck in the kind of limbo from which few things recover.

@mvzhuang those events should be gone

**Comment by mvzhuang** [comment] 2020-09-24 17:43
Ok it looks like when the date got transcribed, it got transcribed as "-7-Aug-2020" and then Excel's autoformat decided to be annoying somewhere along the process...
maybe anything with a # sign? I can't imagine why that would ever be in verbatim date.

yay everything has coordinates that make sense now! Thanks Teresa and Dusty!!

**Comment by Jegelewicz** [comment] 2020-09-25 21:12
The actual issue seems to be fixed? Closing.

**Closed by Jegelewicz** 2020-09-25 21:12 UTC
Labels: Bug, Priority-Critical, Tool - Bulkoad Events
