### ISSUE TITLE
Enhancement - Search results remove row

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#5617] opened 2023-02-07 23:50 UTC
Make remove button a check box and make it a permanent column (default) and add a button to remove checked rows.

**Comment by campmlc** [comment] 2023-02-08 00:35
And remove the word _row and narrow the column width.

**Comment by dustymc** [comment] 2023-02-08 01:20
duplicate of https://github.com/ArctosDB/arctos/issues/5414

**Closed by dustymc** 2023-02-08 01:20 UTC
Labels: Function-SearchOrDownload, Display/Interface
