### ISSUE TITLE
Feature Request - clone non-Linnean classifications

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#6299] opened 2023-05-16 16:57 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

See https://github.com/ArctosDB/data-migration/issues/1455#issuecomment-1550010264

When cloning non-Linnean classifications from a local source into a new name, the classification terms don't transfer when there is no classification term type.

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

Clone the classification for non-Linnean things

**Describe the solution you'd like**
How might we accomplish your goals?

Can we do this even when there is no term type? (see [Marble](https://arctos.database.museum/name/Marble#ArctosRocks)) 

**Describe alternatives you've considered**

A bunch of copy and paste

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.

**Comment by dustymc** [comment] 2023-05-16 17:00
I'm calling this a bug and going direct implementation, clearly all classifications should be treated equally.

**Comment by dustymc** [comment] 2023-05-16 20:53
@Jegelewicz I think this is actually NOT a bug with the cloning, just a symptom of an invalid assertion (which is from a bug of its own).

<img width="386" alt="Screenshot 2023-05-16 at 1 46 48 PM" src="https://github.com/ArctosDB/arctos/assets/5720791/60093030-c831-4834-8a0e-9ea4745b3dfe">

Edit the classification, get rid of display_name='', and it'll save. Please confirm, and close this if you don't have any problems.

I think that behavior is correct - there's no point in asserting "thing==''" and that should be prevented.

I will - uhh, something, eventually resulting in cleaning up my mess involving display_name.

**Comment by dustymc** [comment] 2023-07-12 20:25
done?

**Closed by dustymc** 2023-07-12 20:25 UTC
Labels: Bug

**Comment by Jegelewicz** [comment] 2023-07-12 20:49
Not sure? Haven't tried it yet.
