### ISSUE TITLE
Automated loan form 

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1645] opened 2018-08-09 18:30 UTC
From Paul Morris at Harvard:
Mariel,

(1) Here's our updates to the loan reminder email code, and our addition of periodic reminders to collection managers for long overdue loans.

https://github.com/MCZbase/MCZbase/blob/master/ScheduledTasks/reminder.cfm

https://github.com/MCZbase/MCZbase/blob/master/ScheduledTasks/longtermreminder.cfm

(2) Here's the list of changes to the code to add warnings to alert collection management staff about potentially problematic loanees when creating loans (along with additions of properties of agents that allow them to be marked as problematic.

https://github.com/MCZbase/MCZbase/search?p=2&q=Redmine+324&type=Commits&utf8=%E2%9C%93

**Comment by dustymc** [comment] 2018-08-09 18:34
duplicate of #1448

**Closed by dustymc** 2018-08-09 18:34 UTC
