### ISSUE TITLE
Query Stats and Usage Stats tool not working

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2773] opened 2020-06-11 21:20 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Query Stats and Usage Stats tool not working
Query Stats leads to page that says deprecated
Usage Stats leads to  error below.

**To Reproduce**
1. Go to Reports/Services
2. Click on View Statistics
3. Scroll down to Query Statistics or Usage Statistics

[queryStats.pdf](https://github.com/ArctosDB/arctos/files/4767399/queryStats.pdf)
[MoreCitationStats.pdf](https://github.com/ArctosDB/arctos/files/4767402/MoreCitationStats.pdf)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Chrome

**Priority**
Please assign a priority-label. High, needed for annual reports.

**Comment by dustymc** [comment] 2020-06-11 21:35
Duplicate of https://github.com/ArctosDB/arctos/issues/2750

**Closed by dustymc** 2020-06-11 21:35 UTC
Labels: Bug, function-Reports
