### ISSUE TITLE
Order of Data Fields in Bulkloader, Ajax Editor, and CSV downloads

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#2103] opened 2019-06-01 23:56 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**
Yes - we need a standard format in which data are entered via the single record data screen, and the speciemen bulkloader, (also Buklload builder csv) and this needs to be the same order in which fields are downloaded as csv from the specimen bulkloader out of the Ajax grid. 

**Describe the solution you'd like**
We have discussed this previously - making the order of columns standardized and consistent based on the data tables and related information content. E.g. Other ID 1 should be downloaded and displayed with Other ID Type 1 and Other ID References 1 rather than having these scattered randomly throughout the export file. Ditto for all specimen event fields, collecting event fields, agent info, etc.

**Describe alternatives you've considered**
Spend several hours each time I need to edit a csv download or bulkload builder file reformatting the csv  in order to put columns into some human-comprehensible order. I need this  when editing student data entry csv downloads from the AJAX grid and also to edit aArctos Air entries and  make this actually a usable tool.

**Additional context**
Start of google doc showing the order needed for mammal collections based on the MSB Mamm data entry table and bulkload column headers.
https://docs.google.com/spreadsheets/d/1HwD8-UWOi1wG7x71NZbaVdQz9ULscSLBVh7_vVBsIE4/edit?usp=sharing

**Priority**
Please assign a priority-label.
Critical

**Comment by dustymc** [comment] 2019-06-03 13:36
Duplicate of https://github.com/ArctosDB/arctos/issues/1811#issuecomment-472516449

**Closed by dustymc** 2019-06-03 13:36 UTC
Labels: Priority-Critical
