### ISSUE TITLE
flatten part locations for a list of barcodes

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#1421] opened 2018-02-01 18:38 UTC
Is there a way to get a flattened list of locations from a list of barcodes? 

Right now, if I search for barcodes, it will pull up the hierarchical list. However, when I click flatten locations, I get nothing. 

<img width="1040" alt="screen shot 2018-02-01 at 9 37 14 am" src="https://user-images.githubusercontent.com/16887896/35696289-8a944900-0733-11e8-82ee-19e8fe8dc51a.png">

<img width="778" alt="screen shot 2018-02-01 at 9 37 22 am" src="https://user-images.githubusercontent.com/16887896/35696297-8cfce6ac-0733-11e8-9014-2dc3aa22797f.png">

**Comment by dustymc** [comment] 2018-02-01 19:05
Duplicate of #1329

**Closed by dustymc** 2018-02-01 19:05 UTC
