### ISSUE TITLE
Now what do I do?!  

### ISSUE THREAD

**Issue by mbprondzinski** [ArctosDB/arctos#3174] opened 2020-10-26 20:57 UTC
I entered my Agents, everything was clean, I validated, I downloaded, I uploaded, I looked at the table.  So???  What else am I supposed to do?  Is my data in Arctos or still in the bulkloader?  There is nothing to tell me if I succeeded or am in limbo.

Please advise!

Mary Beth

**Comment by acdoll** [comment] 2020-10-26 21:23
What are you trying to load? Object/specimen records or Agents? With some of the loaders, if you don't see an error message, that means it worked (that will be addressed as Dusty standardizes all the various uploaders). Try a quick search on what you've entered?

**Comment by mbprondzinski** [comment] 2020-10-26 21:45
I loaded agents.  None of them appear to be in Arctos.  I don't know what else I'm supposed to do.  It said there were 81 agents uploaded, but there is "no data available."

**Comment by acdoll** [comment] 2020-10-26 22:11
Did you happen to see this on the page after validation? "Non-fatal errors have been detected. A member of the Arctos Advisory Committee can force-load these data":
![image](https://user-images.githubusercontent.com/12507297/97233874-56e7b300-17a5-11eb-9bb3-31c7c0f239f6.png)

I get that message whenever I enter names with an initial for the middle name (which is almost always). I wish there was a better work around - I usually end up entering them by hand.
I'm not sure who is on the "Arctos Advisory Committee", but if your agents are sitting in a bulkloading queue, I'm sure @dustymc can help push them through.

**Comment by Jegelewicz** [comment] 2020-10-26 22:38
@mbprondzinski please attach the file.

**Comment by mbprondzinski** [comment] 2020-10-26 22:56
Ooh, that's good to know.  Fortunately I didn't have any middle initial s in thiss batch.  Everything appeared to be clean so I thought it would all enter without a hitch.

**Comment by mbprondzinski** [comment] 2020-10-26 23:06
[Teresa splitAgentNames.xlsx](https://github.com/ArctosDB/arctos/files/5441991/Teresa.splitAgentNames.xlsx)

**Comment by mbprondzinski** [comment] 2020-10-26 23:07
> @mbprondzinski please attach the file.

**Comment by mbprondzinski** [comment] 2020-10-26 23:10
It won't accept the CSV file.

**Comment by mbprondzinski** [comment] 2020-10-26 23:11
[Teresa.splitAgentNames.xlsx](https://github.com/ArctosDB/arctos/files/5441999/Teresa.splitAgentNames.xlsx)

**Comment by mbprondzinski** [comment] 2020-10-27 13:35
So that line was added after I validated?  It looks like it’s just part of the process.  You either get an error message in your “View Table” which I didn’t see any, or you get that????  It’s not very explanatory in the least.  Why is it the last thing on the to-do list?

This is the first time I’ve done this myself, so I really didn’t know what to expect.  Anyway, I shipped the file off to Teresa.  Poor Teresa…

Thanks for filling me in, Andy.

**Comment by mbprondzinski** [comment] 2020-10-27 13:37
Hi Teresa, don’t know if you got this last night.  I was doing it on my phone and things don’t always turn out the way I expected (!)  There must be some reason why the data doesn’t upload.

Thanks for you help, as always!

**Comment by Jegelewicz** [comment] 2020-10-27 13:53
@mbprondzinski I loaded the file for you. There was one name that Arctos flagged as a possible duplicate:

preferred_name="Bill Wilson",
first_name="Bill",
middle_name="",
last_name="Wilson"
possible duplicate of Wil Wilson (nocase first name variant+last name match)

which means you wouldn't have been able to load the file. If Bill Wilson is the same person as Wil Wilson, please mark Bill as a bad duplicate of Wil, otherwise leave them be.

When you have your agents with initials, just send me the file and I'll load it for you!

**Closed** 2020-12-01 22:27 UTC
Labels: contact
