### ISSUE TITLE
Request - Need a way to search for a list of parts by user and date

### ISSUE THREAD

**Issue by happiah-madson** [ArctosDB/arctos#8098] opened 2024-09-10 13:46 UTC
Help us understand your request (check below):
- [x] search or data request (help with SQL or provide the specific fields you are trying to retrieve for your collection)
- [ ] add a new Github user to the Arctos Users team
- [ ] a new barcode series
- [ ] a new term for data entry or management 
- [ ] a change or new report or label
- [ ] update to an Agent (split, merge, or other type of change)
- [ ] bulkload changes (to Agents, Identifiers, etc that are not already available as a bulkloading tool)
- [ ] new feature or otherwise a good idea to make Arctos even better
- [ ] quarantine taxon name and suggested replacement (please supply links)
- [ ] other

**Describe what you're trying to do** 
We need to search for a complete list of **parts** that were entered by two of our students during a known period of time. We know this is doable for records, but we need it for parts. We would like: barcodes, catalog number, scientific name (ie, a flat download) if possible.

**Comment by happiah-madson** [comment] 2024-09-10 13:46
@falco-rk

**Comment by dustymc** [comment] 2024-09-10 21:49
```
select 
    specimen_part.part_name,
    pc.barcode,
    flat.cat_num,
    flat.scientific_name,
    getPreferredAgentName(specimen_part.created_agent_id) created_agent,
    specimen_part.created_date
from
    flat
    inner join specimen_part on flat.collection_object_id=specimen_part.derived_from_cat_item
    inner join coll_obj_cont_hist on specimen_part.collection_object_id=coll_obj_cont_hist.collection_object_id
    inner join container p on coll_obj_cont_hist.container_id=p.container_id
    left outer join container pc on p.parent_container_id=pc.container_id
where
    flat.guid_prefix='OGL:Genomic' and
    specimen_part.created_agent_id in (getAgentID('Zachary Anderson'),getAgentID('Mia Bender')) and
    to_char(specimen_part.created_date,'YYYY-MM-DD') between '2024-08-01' and '2024-09-11'

```

**Comment by falco-rk** [comment] 2024-09-12 16:29
@dustymc can you add part disposition to the output?

**Comment by falco-rk** [comment] 2024-09-12 16:59
Thanks!

**Comment by falco-rk** [comment] 2024-09-12 17:17
So i'm getting this error:

ERROR: canceling statement due to user request Where: SQL statement "SELECT array_agg(distinct agent_id) FROM agent_attribute where deprecation_type is null and attribute_type in ( select attribute_type from ctagent_attribute_type where purpose='identifier' ) and attribute_value ilike name and not exists ( select agent_id from agent_attribute nd where nd.agent_id=agent_attribute.agent_id and nd.deprecation_type is null and nd.attribute_type='bad duplicate of' )" PL/pgSQL function getagentid(text) line 47 at SQL statement

But it worked earlier today so i am confused

**Comment by dustymc** [comment] 2024-09-12 17:45
Yea, I think TACC is having some sort of bad hair day, and that's an expensive query anyway. If you want to update with values I didn't make up I can run it for you.

**Comment by falco-rk** [comment] 2024-09-12 17:59
I'm not sure if this is what you mean, but I have the csv from earlier and all i need is the part disposition added
[sql_miabender_MTA_list_for_Maggie(in).csv](https://github.com/user-attachments/files/16983715/sql_miabender_MTA_list_for_Maggie.in.csv)

**Comment by falco-rk** [comment] 2024-09-12 19:26
I figured out how to get disposition another way!

**Comment by dustymc** [comment] 2024-09-12 20:10
>csv

No, I meant the parameters - I made stuff up to test my SQL, it's probably not what you want, I don't know what you actually want so I can't pull the data for it.

**Comment by dustymc** [comment] 2024-09-20 19:13
Done?

**Closed by dustymc** 2024-09-20 19:13 UTC
Labels: Priority-High (Needed for work), Curatorial Search
