### ISSUE TITLE
Better handling for subgenus in classification and identification

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3390] opened 2021-01-27 20:53 UTC
Also, I think we need a way for people to SEARCH _Cancellaria (Pyruclia) solida_ and get all of the _Cancellaria solida_ because there will be people who do that....

_Originally posted by @Jegelewicz in https://github.com/ArctosDB/arctos/issues/1704#issuecomment-768418856_

**Comment by Jegelewicz** [comment] 2021-01-27 20:55
@dustymc it seems like the best way to do this would be to add the names with the subgenera in parens as type quarantine with the related name being the regular Linnean one without the subgenus in it. I can do this, but I have A LOT to add - could we add the relationship stuff to the name loader or get a name relationship loader?

**Comment by Jegelewicz** [comment] 2021-01-27 20:57
but also, why are there any invalid characters in a quarantine name? I tried to add

![image](https://user-images.githubusercontent.com/5725767/106053044-90330600-60a7-11eb-9ab9-09e7cdf48cc3.png)

and got this:

![image](https://user-images.githubusercontent.com/5725767/106052993-7f829000-60a7-11eb-8c14-7e662473683a.png)

**Comment by dustymc** [comment] 2021-01-27 21:29
>SEARCH Cancellaria (Pyruclia) solida

That's one reason we make display_name - it's a classification term, searchable like any other.

>add the names

Classifications exist to support discoverability; I can see no reason to make a big mess here.

**Comment by Jegelewicz** [comment] 2021-01-27 22:05
I fail to see how any of the above works. There is a classification for _Cancellaria solida_ with _Cancellaria (Pyruclia) solida_ in it, but how would any catalog record search for _Cancellaria (Pyruclia) solida_ except 

![image](https://user-images.githubusercontent.com/5725767/106059647-400c7180-60b0-11eb-8b14-33c58bc7f19d.png)

ever find anything identified as _Cancellaria solida_? I don't think that is very intuitive....and I am sure that anyone performing the search would just enter _Cancellaria (Pyruclia) solida_ in the identification search field - which turns up nothing.

**Comment by Jegelewicz** [comment] 2021-01-27 22:05
And before you WONT FIX, shouldn't there be at least a little discussion?

**Comment by dustymc** [comment] 2021-01-27 22:38
I don't think the idea of adding names-that-aren't-names requires discussion, but mostly I'm just trying to get some sort of a milestone attached.... Thanks for fixing my twitchyness.

The junk in your screenshot definitely needs discussion - I don't think it predictably works now, that's just going to get worse as we add diversity to classifications, and it's nothing but clutter for collections that don't use that stuff (because they use mineral/cultural/"phylocode"/etc. classifications that don't have ranks, or don't have those particular ranks). I don't have any great ideas, I just use 'any...' when I need to find something, and that hits all taxon terms. (Or it does now - I had some weird blocking in there from the last time the PRC thought it would be fun to melt Arctos.)

https://arctos.database.museum/SpecimenResults.cfm?taxon_name=Cancellaria%20(Pyruclia)%20solida&debug=1

Increasingly diverse data also means I'm probably going to have less and less success trying to generate something like "Cancellaria (Pyruclia) solida," and I'm not sure what that means - we need a new term, or display_name needs to be something that users provide, or  ??????????????? What you've done serves that purpose here, but it melts what I'd done, which keeps the botanists happy (eg make "display_name: Scheuchzeria palustris L. subsp. americana (Fernald) Hultén" from https://arctos.database.museum/name/Scheuchzeria%20palustris%20subsp.%20americana).

**Comment by campmlc** [comment] 2021-01-27 23:29
I'm not sure I'm following the problem. Is it that not all collections use
subgenera? Isn't this the same as not all collections using some other
taxonomic hierarchy? Or is it that subgenus is not a thing?

**Comment by campmlc** [comment] 2021-01-27 23:30
Also, isn't this a taxon concept? Scheuchzeria palustris L. subsp.
americana (Fernald) Hultén

**Comment by dustymc** [comment] 2021-01-27 23:43
Big-picture, our taxonomy isn't as predictable as our search form (and the cache behind it) might suggest. Search subfamily=bla and find some random stuff from whatever collections prefer classifications that have that term at that rank. Not ideal. I _think_ that if we somehow make that better we'll probably also make the really weird stuff - like subgenus - more discoverable, but the I don't have any specific suggestions for getting there either.

>Also, isn't this a taxon concept? Scheuchzeria palustris L. subsp. americana (Fernald) Hultén

Very much no, that's just a string in a format that botanists expect to find. Taxon concepts are data objects containing taxa and publications, and the publication usually comes with come circumscription information (although I suppose that's not really required). There's nothing in any string, no matter how fancy, that might lead to you knowing if the authors think an individual is or is not part of what they consider to be the taxa.

**Comment by Jegelewicz** [comment] 2021-01-28 15:48
Summary of the problem(s):

TPT is using subgenra and although this isn't one of their taxa, it is similar AND there is at least one catalog record using it in identifications, so I can use it for demo purposes.

_Cancellaria (Pyruclia) solida_

Because this is equivalent to Cancellaria solida, we have decided that our list of taxon names should only include Cancellaria solida. Fair enough, but doesn't that just make Cancellaria (Pyruclia) solida a less-preferred version of Cancellaria solida?

Because TPT plans to use Cancellaria (Pyruclia) solida, in the TPT (via Arctos) classification, I would include the following:

genus = Cancellaria
subgenus = Cancellaria (Pyruclia)
species = Cancellaria (Pyruclia) solida

Problem 1 - When someone wants to id something as Cancellaria (Pyruclia) solida, they will instead need to use Cancellaria solida {Cancellaria (Pyruclia) solida}. How would anyone KNOW that? Sure, we can write a ton of documentation, but I would bet $$ that every time someone new (and anyone who hasn't done it for a while) wants to use Cancellaria (Pyruclia) solida, there will be a GitHub issue.

Problem 2 - When anyone searches Arctos for Cancellaria (Pyruclia) solida in taxonomy, they will get zip, unless they search for it in the Taxon Term field - not intuitive at all.

Problem 3 - When anyone searches catalog records for identifications of Cancellaria (Pyruclia) solida, they will get zip, unless they use the always-has the-potential-to-time-out Any taxon, ID, common name field OR enter Cancellaria (Pyruclia) solida in the Species field of the search form - also not intuitive.

Problem 4 - Derek could say "This one is Cancellaria {Cancellaria (Pyruclia)} and that one is Cancellaria, but he can only choose ONE taxonomic source for his classifications, so all of his Cancellaria will either include the subgenus (Pyruclia) or they won't. And what about the other subgenera of Cancellaria? How will we allow them? See more in #1704

My proposed solution to use a quarantined name = Cancellaria (Pyruclia) solida with the relationship to Cancellaria solida has been shot down, and it wouldn't fix problem 4, which hasn't come up yet, but I am sure it will eventually.

Alternative solutions would be greatly appreciated!

**Comment by sharpphyl** [comment] 2021-01-28 16:02
I agree with all the issues Teresa has listed above.  Here's another.  I have a species that WoRMS classifies as Helix (Xerophila) redassiana.  I can't add this name with the subgenus, so I entered it without (Xerophila) as Helix redassiana and got this rebuke.

<img width="818" alt="Screen Shot 2021-01-28 at 8 49 45 AM" src="https://user-images.githubusercontent.com/15368365/106163156-19007f00-6146-11eb-869a-b06a4ddda555.png">

Here are the relevant source files:
https://arctos.database.museum/name/Helix%20redassiana 
http://www.marinespecies.org/aphia.php?p=taxdetails&id=1466978 - yes it's a taxon inquirendum

Can someone explain why we can't match the WoRMS structure for subgenera?

**Comment by dustymc** [comment] 2021-01-28 16:09
>doesn't that just make Cancellaria (Pyruclia) solida a less-preferred version of Cancellaria solida?

My understanding is no, that's more equivalent to "Soricidae: Sorex cinereus" than to "Sorex somealternatespelling" - it's classification mixed in the name, not a taxon. 

Following that, users should expect "not a taxon" behavior.

Subgenera can be names. If Pyruclia is the most specific name you have you can just use it, no need to wrap it in weird.

See above re: search - I'm not all all convinced that any of that does what's expected with any regularity, subgenera are a relatively tiny part of that.

**Comment by dustymc** [comment] 2021-01-28 16:24
>rebuke

Seems justified to me - I can see no evidence that anyone ever considered Helix redassiana to be a taxon. Xerophila redassiana seems to exist but I have no idea if it is, or might be referring to, the same thing. That doesn't necessarily mean what you've done isn't correct, but neither me nor Arctos can uncover any evidence to support it so it certainly deserves a second look.

>why we can't match the WoRMS 

Normalization.

* We could get them (or better yet GN) to "translate" subgenus-embedded names.
* We could do what we're doing, and perhaps find a way to make search (and/or other classification-based functionality) better.
* We could revert to accepting less-predictable "names" (which comes with lots of ``Genus (some unrelated comment/ former genus/etc.) species`` garbage that I'd not like to clean up again), and ensure that some users are only going to find some proportion of what they're looking for.

The first is out of our control, the second seems at worst mildly inconvenient, the third seems outright evil, and I can't think of anything else.

**Comment by Jegelewicz** [comment] 2021-01-28 16:40
> Subgenera can be names. If Pyruclia is the most specific name you have you can just use it, no need to wrap it in weird.

All the evidence suggest otherwise. Just as one would NEVER say the species is "solida", it seems that one would also never say that the subgenus is "Pyruclia".

**Comment by dustymc** [comment] 2021-01-28 16:53
>one would also never say that the subgenus is "Pyruclia"

I think the usual path starts with "genus is Pyruclia" and then the debate over rank (classification) begins. I don't know that subgenera cannot be minted from the aether, but I can't find evidence of it happening either. In any case I can see no reason why Pyruclia would not be a perfectly valid name.

"solida" doesn't come to exist by demotion or administrative debate, it's born as part of a compound term.

**Comment by sharpphyl** [comment] 2021-01-28 17:53
None of us working with our collection have taxonomic expertise, so we rely on the curated names from WoRMS to apply to our specimens' identifications.  If WoRMS thinks a subgenus is (currently) part of the name, we don't question it or restructure it.  We want the specimen's taxon name to match the WoRMS taxon name.  We want their taxon status to be the Arctos taxon status (#2591).  Are we expecting something that can't be done?

**Comment by Jegelewicz** [comment] 2021-03-18 17:22
Before I launch into further discussion, I need to make sure I understand how subgenus is being handled within classifications. Should subgenus in a local classification be entered as 1 or 2?

1. Genus (Subgenus)
2. Subgenus

**Comment by dustymc** [comment] 2021-03-18 18:38
My current formatted name builder (which died, but it's all caught up now) is expecting (2). It could probably be changed if there's some compelling reason to do so, but I think that's "correct." It uses that to build display_name eg https://arctos.database.museum/name/Ursus%20arctos#Arctos

```
<i>Ursus (Ursus) arctos</i> (Linnaeus, 1758)
```

It's tricky to use that to search, and performance sucks with %term% (required to get "between" the HTML) - maybe we need to autogenerate a search term (or a few of them) without the markup, and maybe authors?

How/if I'm going to autogenerate anything under #3311 is a great mystery - maybe we need to back WAY up and consider where we're going before I do anything that's only going to work for a limited subset of the data.

**Comment by Jegelewicz** [comment] 2021-03-18 23:39
Amphibiaweb's handling for reference:
https://amphibiaweb.org/cgi/amphib_query?where-genus=Rana&where-species=amurensis
![image](https://user-images.githubusercontent.com/5725767/111711215-d8051c80-8810-11eb-8312-a0efe65c3c76.png)

**Comment by sharpphyl** [comment] 2021-03-19 14:48
Even in your [Ursus (Ursus) example](https://arctos.database.museum/name/Ursus%20arctos#Arctos), the display name and the scientific name don't match.  Search can only be done on the scientific name Ursus.  A search for Ursus (Ursus) returns nothing.  

Same issue for _Cancellaria (Pyruclia) solida_ ([WoRMS 464689](http://www.marinespecies.org/aphia.php?p=taxdetails&id=464689)) searchable in Arctos as _Cancellaria solida_  which has no aphiaID in WoRMS.

Is it not possible to align the scientific and the display name throughout the taxon page for searchability (and my sanity).  See same inconsistency between Identification and the classification shown in https://arctos.database.museum/guid/DMNS:Inv:30511.

<img width="455" alt="Screen Shot 2021-03-19 at 8 45 02 AM" src="https://user-images.githubusercontent.com/15368365/111798270-88b20100-888f-11eb-99bd-f65954f686d3.png">

**Comment by dustymc** [comment] 2021-03-19 16:11
>display name and the scientific name don't match

They're not supposed to, that's why we have both.

> Search

https://github.com/ArctosDB/arctos/issues/3390#issuecomment-802195494

>searchable in Arctos as 

<img width="474" alt="Screen Shot 2021-03-19 at 9 08 14 AM" src="https://user-images.githubusercontent.com/5720791/111809905-b2b8f280-8892-11eb-855b-898d7ec23939.png">

>has no aphiaID

The string is different (because we're different systems with different kinds of data and different goals), the concept is the same.

I don't understand the problem, obviously.

**Comment by sharpphyl** [comment] 2021-05-18 02:37
I can't reproduce the results you got above (and the valid taxon has already changed to _Pyruclia solida_).  I am more likely to work from the Search Catalog screen.  Here's a new example I created today.  The catalog ID is _Callyspongia aculeata_ because I can't create the subgenus in the taxon name. The WoRMS record (and our classification) is  

<img width="692" alt="Screen Shot 2021-05-17 at 4 41 18 PM" src="https://user-images.githubusercontent.com/15368365/118565062-c071e380-b72e-11eb-86c7-7f1dbab0e625.png">

A search for the species as listed in WoRMS returns nothing since we the ID assigned is without the subgenus..  

<img width="470" alt="image" src="https://user-images.githubusercontent.com/15368365/118565510-87863e80-b72f-11eb-8aca-6cfdb33e9040.png">

I also get nothing if I search for _Callyspongia (Cladochalina) aculeata_ in Taxon Name in the Taxonomy search screen.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/15368365/118565613-c1efdb80-b72f-11eb-874a-e76c12f10a89.png">

As expected, I get our two specimens if I search for _Callyspongia aculeata_ but that name isn't in WoRMS so the classification assigned to it is for _Callyspongia (Cladochalina) aculeata_,

<img width="470" alt="image" src="https://user-images.githubusercontent.com/15368365/118566121-a5a06e80-b730-11eb-97be-6b911bd077a7.png">

I also get them if I search under Taxon Name on this screen.  

<img width="470" alt="image" src="https://user-images.githubusercontent.com/15368365/118565702-eea3f300-b72f-11eb-8846-f1903dc4a78b.png">

How would I know that?  What's the difference between the two Taxon Name fields?  If it's a Taxon Name, why can't I assign the WoRMS AphiaID 166205 to it? Instead I have assigned this AphiaID to _Callyspongia aculeata_ without the subgenus.  The scientific name on the record comes from Arctos and doesn't match the Preferred Name in WoRMS.

<img width="1505" alt="Screen Shot 2021-05-17 at 2 44 53 PM" src="https://user-images.githubusercontent.com/15368365/118557341-46d3f880-b722-11eb-9425-96f9193f892d.png">

Also,  most WoRMS names with subgenus aren't making it into WoRMS (via Arctos).  I will admit that GBIF seems to omit the subgenus or maybe they haven't caught up with WoRMS.  My concerns are 1) search results for names with a subgenus and 2) how volunteers should deal with WoRMS classifications with a subgenus.  Is this only a WoRMS issue?

**Comment by dustymc** [comment] 2021-05-18 03:23
>nothing if I search for Callyspongia (Cladochalina) aculeata in Taxon Name i

That's not a taxon name - it's a taxon name with embedded classification data - so that's expected.

>What's the difference between the two Taxon Name fields? 

That should all be in the help links, but one's identification (eg, whatever you want it to be) and the other's taxon name. I am VERY open to better labeling/documentation/etc. suggestions. For clarity, the two "fields" are

* identification.scientific_name is your identification string, doesn't necessarily involve taxonomy at all, and is (or should be) labeled "identified as" or similar, and
* taxon_name.scientific_name is the "namestring"

(And it's  replicated in taxon_term of type 'scientific_name' for search purposes)

>why can't I assign the WoRMS AphiaID 166205

You can, looks like you did.

>scientific name on the record comes from Arctos 

Correct, that's autogenerated for search purposes, that's documented as well - https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxon_term

>doesn't match the Preferred Name in WoRMS.

If you mean the identification, you can use the A {string} formula to make that whatever you want. If you mean something else, elaborate please.

> 1) search results for names with a subgenus

<img width="556" alt="Screen Shot 2021-05-17 at 8 03 51 PM" src="https://user-images.githubusercontent.com/5720791/118584111-181e4800-b74b-11eb-9067-c2a363c696ea.png">

finds

<img width="562" alt="Screen Shot 2021-05-17 at 8 04 37 PM" src="https://user-images.githubusercontent.com/5720791/118584125-22404680-b74b-11eb-916d-38453048edde.png">

because

<img width="671" alt="Screen Shot 2021-05-17 at 8 05 04 PM" src="https://user-images.githubusercontent.com/5720791/118584148-308e6280-b74b-11eb-9486-7d823629259b.png">

on https://arctos.database.museum/name/Callyspongia%20aculeata#WoRMSviaArctos

>how volunteers should deal with WoRMS classifications with a subgenus

That's up to your policies. I'm happy to elaborate on what I'd do, or the functional implications of various possibilities, but I can't tell you what you should do.

Want to organize a zoom chat or similar?

**Comment by sharpphyl** [comment] 2021-05-18 14:28
Our Taxonomy Committee meets tomorrow 5/19.  @Jegelewicz Can we discuss this at our meeting.  If you could join us, @dustymc that would  help me and perhaps others.  

> That's not a taxon name - it's a taxon name with embedded classification data - so that's expected.

How can it not be a taxon name if it has a WoRMS AphiaID?

**Comment by dustymc** [comment] 2021-05-18 15:14
I'll try to be there.

WoRMS assigns AphiaIDs to all kinds of not-taxonomy, or maybe they have a different model or something - whatever the reason, their "namestrings" are not limited to things we consider "taxonomy," and ours are.

**Comment by sharpphyl** [comment] 2021-05-18 19:42
> their [WoRMS] "namestrings" are not limited to things we consider "taxonomy," and ours are.

But we include subgenus in our taxonomy tables.  

<img width="209" alt="Subgenus in list" src="https://user-images.githubusercontent.com/15368365/118712997-b3acc880-b7de-11eb-9ee3-462de9a38976.png">

<img width="1311" alt="Subgenus in table" src="https://user-images.githubusercontent.com/15368365/118713064-c2937b00-b7de-11eb-94f9-d53131641555.png">

See you tomorrow.  Thanks for trying to attend.

**Comment by dustymc** [comment] 2021-05-18 19:48
>But we include subgenus in our taxonomy tables

That's classification. "Taxonomy" is only one field - taxon_name.scientific_name.

**Comment by sharpphyl** [comment] 2021-05-18 20:57
Yes, it's classification, but to enter a word into that field, it has to be in our taxon table of names.  Right?

From the Handbook (https://handbook.arctosdb.org/documentation/taxonomy.html): **Taxon Name**.  "The sole distinguishing feature of this field is that a curator, usually a taxonomist, considers the name to be formal taxonomy."

If WoRMS considers [_Callyspongia (Cladochalina) aculeata_ ](http://www.marinespecies.org/aphia.php?p=taxdetails&id=166205)to be a taxon name, why don't we?

This is seldom an issue for mollusca.  The WoRMS source, MolluscaBase.org, considers the binomial to be "accepted" and the subgenus to be accepted but an "alternate representation."  Both are assigned an unique AphiaID.  If we have a mollusca subgenus in a legacy ID, we can use strings.  The subgenus appears in WoRMS more frequently with echinoderms, sponges, etc. as the accepted taxon.

Obviously, I'm still trying to understand why this is an issue within Arctos.

**Comment by dustymc** [comment] 2021-05-18 21:18
>sole distinguishing feature 

That needs updated.

>why don't we?

Same reason we don't consider http://www.marinespecies.org/aphia.php?p=taxdetails&id=1507624 to be a name - it just isn't!

>understand why this is an issue

Discoverability. I'm working on the assumption that the primary function of taxonomy in Arctos is to get users to catalog records. The less arbitrary variation we have in names, the better that'll work. "Bla bla" and "Bla (Bla) bla" are the same THING, having only one of them loses no information, there's zero cost to allowing only one form. In return we get much better discovery, can talk to many more things, and we eliminate the possibility of "Bla (frog)" and "Bla (plant)" being introduced (again).

What is it that you think you're missing by not allowing various formats in names? I suspect that if you can spell that out so that I can understand it (you might need to type slow and use small words) we can find a solution that does whatever you're looking to do without making a mess of a core "node" of Arctos.

**Comment by sharpphyl** [comment] 2021-05-19 19:40
The number of taxon names where I've assigned a WoRMS classification with a subgenus is so small that it's probably not worth rebuilding the display_name builder unless other collections have a similar problem.  Just thought it was interesting and weird.

**Comment by Jegelewicz** [comment] 2021-05-19 19:54
I think we need to revisit this - https://github.com/ArctosDB/arctos/issues/3390#issuecomment-769178111

**Comment by Jegelewicz** [comment] 2021-05-19 20:37
Everyone says all of that is no problema - need to document.

Should we present subgenus as Genus (Subgenus) or Subgenus? @camwebb  says just subgenus.

Need to document:
Add accepted names with subgenus from WoRMS to Arctos source @sharpphyl 
Subgenus should be just one name @Jegelewicz 
Fix all subgenera that are Genus (Subgenus) @Jegelewicz

**Comment by dustymc** [comment] 2021-05-19 22:36
@sharpphyl here's worms subgenus data

```
arctosprod@arctos>> select scientific_name, term from taxon_name inner join taxon_term on taxon_name.taxon_name_id=taxon_term.taxon_name_id
arctos-> where source='WoRMS (via Arctos)' and term_type in ('subgenus');
              scientific_name               |                term                
--------------------------------------------+------------------------------------
 Cribrilaria alcicornis                     | Cribrilaria
 Cribrilaria venusta                        | Cribrilaria
 Pareudesmoscolex laciniosus                | Desmoscolex (Pareudesmoscolex)
 Corythostoma                               | Pseudocella (Corythostoma)
 Pareudesmoscolex pratensis                 | Desmoscolex (Pareudesmoscolex)
 Hessonoporus carinulatus                   | Alloporus (Hessonoporus)
 Corythostoma filipjevi                     | Pseudocella (Corythostoma)
 Trachybaicalia carinata                    | Baicalia (Trachybaicalia)
 Moraria poppei meridionalis                | Moraria (Moraria)
 Moraria mrazeki macedonica                 | Moraria (Moraria)
 Moraria laurentica americana               | Moraria (Moraria)
 Corvusiana corvus                          | Stagnicola (Corvusiana)
 Trachybaicalia carinata var. fuchsiana     | Baicalia (Trachybaicalia)
 Trachybaicalia carinata var. hoernesiana   | Baicalia (Trachybaicalia)
 Flabellum transversale conicum             | Flabellum (Flabellum)
 Atlantotrichus leptotrichoides             | Leptotrichus (Atlantotrichus)
 Lissopecten hyalinus                       | Chlamys (Lissopecten)
 Flabellum transversale transversale        | Flabellum (Flabellum)
 Flabellum transversale triangulare         | Flabellum (Flabellum)
 Granulilittorina philippiana               | Echinolittorina (Granulilittorina)
 Uca vocans vocans                          | Uca (Gelasimus)
 Uca vocans excisa                          | Uca (Gelasimus)
 Vexillum echinatum astephana               | Vexillum (Costellaria)
 Charybdis hoplites longicollis             | Charybdis (Goniohellenus)
 Uca vocans hesperiae                       | Uca (Gelasimus)
 Caryophyllia octopali var. incerta         | Caryophyllia (Caryophyllia)
 Uca bellator minima                        | Uca (Australuca)
 Pareudesmoscolex lacustris                 | Desmoscolex (Pareudesmoscolex)
 Pareudesmoscolex verrucosus                | Desmoscolex (Pareudesmoscolex)
 Dinia dentifera                            | Atys (Dinia)
 Corythostoma kreisi                        | Pseudocella (Corythostoma)
 Corythostoma triaulolaimus                 | Pseudocella (Corythostoma)
 Uca vocans pacificensis                    | Uca (Gelasimus)
 Aspalima erecta idonea                     | Limopsis (Aspalima)
 Cristellaria obtusata var. subalata        | Cristellaria (Marginulina)
 Caryophyllia scobinosa decapali            | Caryophyllia (Caryophyllia)
 Echininus viviparus                        | Tectarius (Echininus)
 Microchironomus deribae                    | Chironomus (Microchironomus)
 Cribrilaria innominata vicariata           | Puellina (Cribrilaria)
 Dinia compitorum                           | Atys (Dinia)
 Columbella broderipi var. punctata         | Columbella (Mitrella)
 Microchironomus tener                      | Chironomus (Microchironomus)
 Cancellaria balboae                        | Cancellaria (Euclia)
 Dinia truncatula                           | Atys (Dinia)
 Helicostyla cincinniformis                 | Helicostyla (Hypselostyla)
 Cribrilaria biavicularia                   | Cribrilaria
 Cribrilaria bifida                         | Cribrilaria
 Cribrilaria cassidainsis                   | Cribrilaria
 Cribrilaria denticulata                    | Cribrilaria
 Cribrilaria hexaspinosa                    | Cribrilaria
 Cribrilaria innominata                     | Cribrilaria
 Cribrilaria minima                         | Cribrilaria
 Cribrilaria octospinosa                    | Cribrilaria
 Helicostyla cailliaudi                     | Helicostyla (Calocochlea)
 Galba emarginata angulata                  | Galba (Stagnicola)
 Leonia jolyi                               | Cyclostoma (Leonia)
 Helicostyla cunctator                      | Helicostyla (Orthostylus)
 Lithophaga curta                           | Lithophaga (Leiosolenus)
 Alabastrina atlasica                       | Alabastrina (Atlasica)
 Mesodon appressus                          | Mesodon (Patera)
 Stenotrema fraternum                       | Stenotrema (Euchemotrema)
 Hexaplex duplex canariensis                | Hexaplex (Trunculariopsis)
 Helix redassiana                           | Helix (Xerophila)
 Alycaeus granum                            | Alycaeus (Dioryx)
 Alycaeus troglodytes                       | Alycaeus (Chamalycaeus)
 Alycaeus gibbus                            | Alycaeus (Alycaeus)
 Chamalycaeus cyclophoroides koshuensis     | Chamalycaeus (Metalycaeus)
 Caryophyllia smithii var. castanea         | Caryophyllia (Caryophyllia)
 Caryophyllia smithii var. esmeralda        | Caryophyllia (Caryophyllia)
 Caryophyllia smithii var. clara            | Caryophyllia (Caryophyllia)
 Bolania conoidalis fossanensis             | Bolania (Bolania)
 Schistoloma alta                           | Schistoloma (Schistoloma)
 Flammulina lifouana                        | Flammulina (Monomphalus)
 Diplommatina godeffroyana var. latecostata | Diplommatina (Diancta)
 Diplommatina fuscula var. vitiana          | Diplommatina (Moussonia)
 Retinella sculptilis                       | (Glyphognomon)
 Ferrissia arkansasensis                    | Ferrissia (Ferrissia)
 Thais tuberosa                             | Thais (Thalessa)
 Thais virgata                              | Thais (Thalessa)
 Thais melones                              | Thais (Vasula)
 Cancellaria laurettae                      | Cancellaria (Euclia)
 Morula marginalba                          | Morula (Morula)
 Tellina palatam                            | Tellina (Quidnipagus)
 Pecten radula                              | Pecten (Comptopallium)
 Anadara nodifera                           | Anadara (Tegillarca)
 Synprosphyma fistulata                     | Synprosphyma (Synprosphyma)
 Micrarionta tryoni carinata                | Micrarionta (Xerarionta)
 Helicella apicina                          | Helicella (Xerotricha)
 Plectopylis fultoni                        | Plectopylis (Endothyrella)
 Ryssota zeus                               | Ryssota (Lamarckiella)
 Helicostyla mindoroensis                   | Helicostyla (Chrysallis)
 Systrophia zeteki                          | Systrophia (Systrophiella)
 Lepidochitona thamnopora                   | Lepidochitona (Dendrochiton)
 Labyrinthus labyrinthus                    | Labyrinthus (Labyrinthus)
 Cancellaria nodulifera                     | Cancellaria (Habesolatia)
 Trochonanina moreleti                      | Trochonanina (Trochozonites)
 Thais alouina                              | Thais (Mancinella)
 Tropidauchenia gastrum laticosta           | Tropidauchenia (Grandinenia)
 Pearsonia hispida                          | Pearsonia (Pearsonia)
 Ischnochiton floridanus                    | Ischnochiton (Stenoplax)
 Thais triangularis                         | Thais (Thais)
 Thais lata                                 | Thais (Mancinella)
 Chlamys incantata                          | Chlamys (Chlamys)
 Thais speciosa                             | Thais (Thais)
 Ampelita basizona                          | Ampelita (Helix)
 Aegista pannosa                            | Aegista (Plectotropis)
 Oospira takagii                            | Oospira (Atractophaedusa)
 Tropidauchenia costigera                   | Tropidauchenia (Grandinenia)
 Clausilia monticola                        | Clausilia (Phaedusa)
 Helicostyla roissyana                      | Helicostyla (Calocochlea)
 Caseolus betamajor                         | Caseolus (Caseolus)
 Luria isabella atriceps                    | Luria (Basilitrona)
 Caseolus compactus betamajor               | Caseolus (Caseolus)
 Caseolus compactus                         | Caseolus (Caseolus)
 Geomitra delphinula                        | Geomitra (Craspedaria)
 Schistoloma alta sibuyanica                | Schistoloma (Schistoloma)
 Helix deaniana                             | Helix (Planispira)
 Helix mooreana                             | Helix (Polygyra)
 Plectopylis clathratula                    | Plectopylis (Sykesia)
 Callyspongia affinis                       | Callyspongia (Cladochalina)
 Archelix russadirensis                     | Archelix (Dupotetia)
 Alabastrina pallaryi                       | Alabastrina (Siretia)
 Cancellaria solida                         | Cancellaria (Pyruclia)
(123 rows)

```

**Comment by Jegelewicz** [comment] 2021-05-20 13:51
This adds clarity to our discussion - https://github.com/tdwg/dwc/issues/320#issuecomment-844630430

> kingdom, phylum, ..., and subgenus are all taxa (or at least complete names), while genericName, infragenericEpithet, specificEpithet and infraspecificEpithet are parts of names (that are combinations). The ../Subgenus elements in ABCD are equivalent to infragenericEpithet (#30), not subgenus.

BUT makes me thing that our "subgenus" should be in the form Genus (Subgenus) for consistency with the way we treat species and subspecies?

**Comment by campmlc** [comment] 2021-05-20 14:38
I agree with subgenus being a taxon. If the format is genus(subgenus),
would it still be searchable as "subgenus" only?

**Comment by dustymc** [comment] 2021-05-20 14:47
> searchable as "subgenus" only?

No, and that format cannot be a name so can't be used in identifications, won't work in the hierarchical editor, etc.

**Comment by Jegelewicz** [comment] 2021-05-20 15:37
The format Genus (Subgenus) would only be used in the classification.

**Comment by Jegelewicz** [comment] 2021-05-20 15:38
Well, then maybe we should be calling it infragenericEpithet...

**Comment by Jegelewicz** [comment] 2021-05-20 21:13
@sharpphyl you probably already know but

species = Ursus arctos
genericName = Ursus
specificEpithet = arctos

The genus one really throws me. No one creates a Genus without a species, so in reality there is no such term as "genus" that stands alone (yet we use it all the time...) in reality we are talking about the genericName (which is what GBIF calls it in it's taxonomy table, even though it appears as "Genus" on their website).
![image](https://user-images.githubusercontent.com/5725767/119049047-4d11e100-b97d-11eb-9054-d7694095ab17.png)

Just as there can be no "species" without a genericName AND a specificEpithet, there can be no subgenus without a genericName AND an infraspecificEpithet - they come as a pair or they are kind of meaningless (or they mean something other than intended). So

subgenus = Callyspongia (Cladochalina)
genericName = Callyspongia
infragenericEpithet = Cladochalina

At least that is my understanding - I could be (and probably am) not completely correct.

**Comment by Jegelewicz** [comment] 2021-05-20 21:14
FYI - this is one of the reasons that a genus with no "children" (aka species) is almost always "doubtful" in GBIF. (Maybe always, but I can't say that with certainty...)

**Comment by sharpphyl** [comment] 2021-05-21 13:23
> At least that is my understanding - I could be (and probably am) not completely correct.

It all makes sense.  Thanks!

**Comment by sharpphyl** [comment] 2021-06-06 00:19
> @sharpphyl here's worms subgenus data

@dustymc   I tried to run the SQL to see if I got rid of all the WoRMS (via Arctos) with subgenera {and moved the classification to Arctos).  When I run it from your post above, I get this message.

SQL:
arctosprod@arctos>> select scientific_name, term from taxon_name inner join taxon_term on taxon_name.taxon_name_id=taxon_term.taxon_name_id arctos-> where source='WoRMS (via Arctos)' and term_type in ('subgenus');

ERROR: syntax error at or near "arctosprod" Position: 1

**Comment by Jegelewicz** [comment] 2021-07-08 16:36
Leaving this open because of https://github.com/tdwg/dwc/issues/320 and https://github.com/tdwg/dwc/issues/30

**Comment by Jegelewicz** [comment] 2021-12-15 21:42
New SQL

select scientific_name, term from taxon_name inner join taxon_term on taxon_name.taxon_name_id=taxon_term.taxon_name_id where source='WoRMS (via Arctos)' and term_type in ('subgenus')

**Comment by Jegelewicz** [comment] 2021-12-15 21:43
<html><body>


  | scientific_name | term
-- | -- | --
1 | Tritonium pericochlion | Tritonium (Buccinum)
2 | Bathybuccinum clarki | Bathybuccinum (Ovulatibuccinum)
3 | Uca bellator minima | Uca (Australuca)
4 | Tritonium schantaricum | Tritonium (Fusus)
5 | Flabellum transversale triangulare | Flabellum (Flabellum)
6 | Flabellum transversale transversale | Flabellum (Flabellum)
7 | Oospira takagii | Oospira (Atractophaedusa)
8 | Plectopylis clathratula | Plectopylis (Sykesia)
9 | Allolobophora longa occulta | Helodrilus (Allolobophora)
10 | Chamalycaeus cyclophoroides koshuensis | Chamalycaeus (Metalycaeus)
11 | Neptunea communis borealis | Fusus (Neptunea)


</body>
</html>

**Closed** 2021-12-15 21:45 UTC
Labels: Priority-Normal (Not urgent), Function-Taxonomy/Identification, dwc terms
