### ISSUE TITLE
nature_of_id overburdened?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3940] opened 2021-09-16 21:57 UTC
@ArctosDB/arctos-code-table-administrators had a great discussion today about the [terms in nature of id](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctnature_of_id) and we realized that we may be trying to convey too much information with one term. Right now, people are looking to this term to describe both WHAT was used to develop an identification and HOW the identification was developed. We suggest the following:

change nature_of_id to id_method
the controlled values for this would be essentially what they are now except that audio/visual would be removed (of all the terms there, it really only refers to WHAT was used not how the evaluation was made).

add a new identification field - id_evidence
definition - General description of the evidence to which the id_method was applied in order to arrive at the identification.

controlled vocabulary:
- primary - (or direct) material that is or was all or part of the object identified as taxon (lizard in ethanol, feather, insect, leaf, blood)
- secondary - (or trace) material that indicates the presence of the object identified as taxon (footprint, nest, scat, photograph, sound recording, digital image, fossil material?)
- tertiary - (or human observation) a human records information about an object identified as taxon, but no direct material support or trace exists (field notes, point count surveys)

While it may seem that the catalog record itself provides the id_evidence, there can be multiple types of evidence included in the parts of any given catalog record, so indicating which kind of evidence was used in determining the identification will help everyone understand its repeatability and perhaps support the id confidence value. We also discussed the fact that the ability to associate an identification with an individual part (this id was made with molecular data from that tissue would be even better, but we aren't sure we are there just yet. See #3630)

**Comment by ebraker** [comment] 2021-09-17 18:37
wait - I think we (or at least I!) still want 'audio-visual' as an option for method since we are getting rid of 'field photo' under collecting_source.

**Comment by Jegelewicz** [comment] 2021-09-17 18:48
But I thought that "field photo" would be the id_evidence? "audio-visual" does not describe an action (id_method). We may need some new method (although for images, I thought we decided that fine features and features would be the method).

**Comment by ebraker** [comment] 2021-09-17 21:24
I think it would be useful to keep audio-visual as a type of ID_method. We did narrow the definitions of features and fine features to "in hand"/primary evidence. If an outside user just sees the a field: "evidence = secondary" and doesn't look further into the code table definition, it doesn't readily communicate that someone determined/verified an ID based on a photo (esp if photo is not attached to the record). I really would like to keep this, as it can (not always) convey some level of confidence and adds precision.

**Comment by Jegelewicz** [comment] 2021-09-20 14:17
Given the above - do we really need to change anything?

**Comment by ebraker** [comment] 2021-09-20 18:17
I think we should still create the id_evidence types - we talked about adding them to each nature_of_id definition and then the possibility of pulling them out into their own table if the community is on board.

**Comment by dustymc** [comment] 2021-09-20 18:31
I think I don't understand something important about this.

Method belongs in identification.publication_id.

I can't wrap my head around the intent of the method values. A trace fossil IS "all or part of the object identified as taxon" and also "secondary" (so something random should be expected??), I'm not sure it makes sense to lump CT scans and fuzzy bigfoot sightings (and I don't see a way to avoid that given the definition of "tertiary"), etc., etc., etc. 

I think maybe this is (sorta??) an attempt to link parts with identifications, but I'm not sure it does that. (And that's starting to sound like "usage" which leads to loans which contain parts, and with that there's not much reason to categorize, you can just specify the actual material used.)

?????

**Comment by Jegelewicz** [comment] 2021-09-20 19:12
> link parts with identifications

I think that would be the ideal situation.

> And that's starting to sound like "usage" which leads to loans which contain parts, and with that there's not much reason to categorize, you can just specify the actual material used.

But that is not an easy thing to get at, especially when there are 20 identifications on a catalog record. I feel like I am in an endless loop of, "we need details! but we want to find stuff with a click of a single button!"

BTW - this all came about because we have opposition to the removal of "field photo" from collecting source. #2494

**Comment by dustymc** [comment] 2021-09-20 19:41
>opposition to the removal of "field photo"

Can you be more specific? I thought we were down to some understandable objection to "... caught," and I'm not understanding what that could have to do with identifications.

**Comment by Jegelewicz** [comment] 2021-09-20 19:46
@ebraker can answer that.

**Comment by ebraker** [comment] 2021-09-24 17:37
> I thought we were down to some understandable objection to "... caught,"

Yes, I don't particularly love replacing "field photo" with "wild caught" under collecting_source as it is a bit misleading. However, if this is what we want to do (rather than flag field photo as something that triggers mappabilty), then I want to make sure all my current records with the "field photo" designation have "audio-visual" as nature_of_ID before we update them to "wild caught." Even though these are different tables, they relate to parts and IDs and (can) convey a level of confidence. If my observations don't have media or parts attached, I need some way to say that the determination was made from a photo and not  directly/in hand. Audio-visual does this, so this was my concession (take field photo away from collecting_source, as long as we keep audio-visual).

I just had oral surgery so I'm on all sorts of wacky substances right now. Hope I'm making sense!

**Comment by campmlc** [comment] 2021-09-24 17:41
I thought we were replacing "wild caught" with "wild"?

**Comment by Jegelewicz** [comment] 2021-09-24 18:37
> I thought we were replacing "wild caught" with "wild"?

That is the plan

**Comment by dustymc** [comment] 2021-09-27 15:14
Thx @ebraker. Here's what I think should be considered.

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollecting_source explains how your critter got to where you found it. I believe the current options boil down "[did|did not] get there by itself" and "we don't know."

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctnature_of_id is just what it sounds like; the collector saw it, heard it, observed its behavior, etc., and drew taxonomic conclusions from that, future IDs have some other information (photo, bones, DNA) available. (I still think "field" best conveys what the collector had available, but I'm scared to even go look for that issue.)

https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_event_type tells me what happens next - if it was only photos then this should be "observation," if the event ended with a bang then "collection" would be more appropriate. (And maybe everything except the photo was lost - or just not borrowed - and we'll still end up with 'looked at a picture' identifications.)

When there are only photos, "evidence" is some weird part-or-media thing which will probably be completely obvious once we've found the record, but might be less searchable than desirable (although I'm not sure what use case that search might support, so ???).

"Mappable" is going to be some sum of all that, along with other stuff (perhaps coordinate error); every user will likely have a slightly different idea of what's appropriate for any particular use (or they should, if they knew they could).

I can't say how **your** "field photos" should be migrated or if that's the same path any others might follow. (Hence https://github.com/ArctosDB/arctos/issues/1450 and various attempts to prioritize it and related: NO future user can have any real idea what was intended by any usage of any undefined value, and that just keeps getting fuzzier as time goes by and people move on and etc.)

**Comment by mkoo** [comment] 2021-11-09 05:36
good topic and clean-up. I'm stealing some of Dusty's response above for some documentation on workflow with respect to CT. Maybe it's a new best practise page? I'll have to think about this, but useful prompt @dustymc 
meanwhile I think we can close this

**Closed by mkoo** 2021-11-09 05:36 UTC
Labels: Priority-Normal (Not urgent), Function-Taxonomy/Identification, Function-CodeTables, Enhancement, NeedsDocumentation, Tool - Bulkload Records, Tool - Bulkload Identifications

**Comment by jldunnum** [comment] 2021-11-09 11:56
Can I throw one more thought into our overburdened nature of ID stream? Often I make identifications through a combination of character diagnoses and geographic distribution, any thoughts on adding the ability to select two natures of ID?

______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________
