### ISSUE TITLE
Error with the "Fix/view with Arctos tools button" in the Bulkload Catalog Records

### ISSUE THREAD

**Issue by phalacrocorax66** [ArctosDB/arctos#3016] opened 2020-08-11 18:54 UTC
When I try to Fix/view errors in my csv file in the Catalog Record Bulkloader, an error message appears and I have to download the errors instead.

1. Go to upload a csv file on the Bulkload Catalog Records section of the website. 
2. When uploaded click "Check and load these records"
3. Then click "Fix/view with Arctos tools"
4. An error message pops up, screenshot below
![error2](https://user-images.githubusercontent.com/63082834/89936930-3a39d700-dbc9-11ea-9f62-3696cdc8a708.PNG)

**Desktop:**
 - OS: 64 bit Windows 10
 - Browser Firefox
 - Version 79.0

**Comment by dustymc** [comment] 2020-08-11 19:20
Duplicate of https://github.com/ArctosDB/arctos/issues/2727

**Closed by dustymc** 2020-08-11 19:20 UTC
