### ISSUE TITLE
Bulkload Agent fail with no reason

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#7741] opened 2024-04-30 14:25 UTC
See data in bulkload agent tool. I don't know why these are failing.

https://arctos.database.museum/loaders/bulkload_agents.cfm

**Comment by dustymc** [comment] 2024-04-30 14:31
duplicate of https://github.com/ArctosDB/arctos/issues/7714 (and at least the issue numbers aren't confusing....)

**Closed by dustymc** 2024-04-30 14:31 UTC
Labels: Priority-High (Needed for work), Function-Agents, Error Explanation
