### ISSUE TITLE
inconsistent display of media labels below thumbnails on object records

### ISSUE THREAD

**Issue by krgomez** [ArctosDB/arctos#1930] opened 2019-02-15 20:39 UTC
**Describe the bug**
The media labels for images display inconsistently below thumbnails on object records. We use description labels frequently and I am finding that these labels only sometimes display below the thumbnail. Specifically, descriptions seemed to be consistently displaying below the thumbnails this fall and then at some point this winter they started not displaying for new media uploaded.

**To Reproduce**
See screenshots.

**Expected behavior**
I would expect a description to either always display or not. Also it would be good to know, if there are two description labels, which one will display on the object record page and which won't. In the art collection we are using the description label to record the copyright statement so that it will display below the thumbnail, making copyright information associated with media obvious to the user.

**Screenshots**
The following are examples of media for two objects by the same artist. In the first, there are two description labels and the © David Mollett displays on the record. In the second, there is one description label, but the © David Mollett does not display on the record.

![screen shot 2019-02-15 at 11 24 02 am](https://user-images.githubusercontent.com/40579515/52882583-a2af1180-3114-11e9-9b4d-cb1c1f831681.png)

![screen shot 2019-02-15 at 11 24 21 am](https://user-images.githubusercontent.com/40579515/52882596-acd11000-3114-11e9-986d-941230fbb1d1.png)

![screen shot 2019-02-15 at 11 24 36 am](https://user-images.githubusercontent.com/40579515/52882676-edc92480-3114-11e9-9101-c462130f2f4d.png)

![screen shot 2019-02-15 at 11 24 48 am](https://user-images.githubusercontent.com/40579515/52882688-f9b4e680-3114-11e9-86e6-5e02c271a096.png)

**Desktop (please complete the following information):**
MacOS High Sierra 10.13.6, Firefox 

**Priority**
I would like to have this resolved by date: whenever it's possible, and maybe there is a different way I could be handling media labels to get the text I want to appear below the media consistently do that, let me know if there is!

**Comment by dustymc** [comment] 2019-02-15 23:25
I think the problem is encumbrances when the cache tried to build - the media related-stuff cache will only use public data.

Arctos is a community, and as such we can always talk about display. Trying to shape data to interfaces is going to cause unpredictability.

**Comment by krgomez** [comment] 2019-02-18 17:30
Okay, thanks for explaining. So when the encumbrances are lifted, the descriptions will display?

**Comment by dustymc** [comment] 2021-01-21 22:09
Duplicate of https://github.com/ArctosDB/arctos/issues/2813

**Closed by dustymc** 2021-01-21 22:09 UTC
