### ISSUE TITLE
data loans and specimen parts

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#799] opened 2015-12-17 02:57 UTC
Some data loans have parts. Decide if that's desirable, make sure the forms and documentation work if so, cleanup and disallow if not.

declare 
  prtcnt number;
  specnt number;
begin
  for r in (select loan.transaction_id,guid_prefix,loan_number from loan,trans,collection where loan.transaction_id=trans.transaction_id and trans.collection_id=collection.collection_id and loan_type='data' order by guid_prefix,loan_number) loop
    dbms_output.put_line(r.guid_prefix || ': ' || r.loan_number);
    select count(*) into specnt from loan_item,cataloged_item where loan_item.collection_object_id=cataloged_item.collection_object_id and loan_item.transaction_id=r.transaction_id;
    dbms_output.put_line('    specimens: ' || specnt);

```
 select count(*) into prtcnt from loan_item,specimen_part where loan_item.collection_object_id=specimen_part.collection_object_id and loan_item.transaction_id=r.transaction_id;
dbms_output.put_line('    parts: ' || prtcnt);
```

  end loop;
end;
/
MLZ:Bird: 1511
    specimens: 0
    parts: 1
MLZ:Bird: 1513
    specimens: 0
    parts: 13
MSB:Mamm: 2013.025.Mamm
    specimens: 0
    parts: 4
MSB:Mamm: 2014.002.Mamm
    specimens: 0
    parts: 1
MVZ:Bird: 2007.6794.Bird
    specimens: 0
    parts: 0
MVZ:Bird: 2012.7582.Data
    specimens: 726
    parts: 0
MVZ:Bird: 2012.7586.Data
    specimens: 807
    parts: 0
MVZ:Bird: 2012.7590.Data
    specimens: 125
    parts: 0
MVZ:Bird: 2012.7593.Data
    specimens: 566
    parts: 0
MVZ:Bird: 2012.7597.Data
    specimens: 0
    parts: 5
MVZ:Bird: 2012.7637.Data
    specimens: 756
    parts: 0
MVZ:Bird: 2015.8223.Data
    specimens: 0
    parts: 1
MVZ:Bird: 2015.8224.Data
    specimens: 0
    parts: 9
MVZ:Bird: 2015.8233.Data
    specimens: 0
    parts: 2
MVZ:Egg: 2008.6875.Bird
    specimens: 0
    parts: 0
MVZ:Egg: 2012.7583.Data
    specimens: 0
    parts: 3
MVZ:Egg: 2012.7587.Data
    specimens: 0
    parts: 11
MVZ:Egg: 2012.7594.Data
    specimens: 0
    parts: 10
MVZ:Egg: 2012.7640.Data
    specimens: 30
    parts: 0
MVZ:Herp: 2007.6726.Herp
    specimens: 0
    parts: 0
MVZ:Herp: 2012.7584.Data
    specimens: 940
    parts: 0
MVZ:Herp: 2012.7588.Data
    specimens: 575
    parts: 0
MVZ:Herp: 2012.7591.Data
    specimens: 31
    parts: 0
MVZ:Herp: 2012.7595.Data
    specimens: 594
    parts: 0
MVZ:Herp: 2012.7598.Data
    specimens: 283
    parts: 0
MVZ:Herp: 2012.7638.Data
    specimens: 299
    parts: 0
MVZ:Herp: 2013.7811.Data
    specimens: 11
    parts: 0
MVZ:Mamm: 2012.7585.Data
    specimens: 547
    parts: 0
MVZ:Mamm: 2012.7589.Data
    specimens: 1390
    parts: 0
MVZ:Mamm: 2012.7592.Data
    specimens: 329
    parts: 0
MVZ:Mamm: 2012.7596.Data
    specimens: 721
    parts: 0
MVZ:Mamm: 2012.7599.Data
    specimens: 124
    parts: 0
MVZ:Mamm: 2012.7639.Data
    specimens: 445
    parts: 0
MVZ:Mamm: 2014.7931.Mamm.Data
    specimens: 0
    parts: 0
UAM:EH: 2012-23.EH
    specimens: 0
    parts: 1
UAM:EH: 2012-25
    specimens: 0
    parts: 0
UAM:EH: 2014-11.EH
    specimens: 0
    parts: 24
UAM:EH: 2014-13.EH
    specimens: 0
    parts: 3
UAM:EH: 2014-15.EH
    specimens: 0
    parts: 0
UAM:EH: 2014-17.EH
    specimens: 0
    parts: 50
UAM:EH: 2014-19.EH
    specimens: 0
    parts: 1
UAM:EH: 2014-21.EH
    specimens: 0
    parts: 1
UAM:EH: 2014-22.EH
    specimens: 0
    parts: 1
UAM:EH: 2015-02.EH
    specimens: 0
    parts: 0
UAM:EH: 2015-03.EH
    specimens: 0
    parts: 1
UAM:EH: 2015-04.EH
    specimens: 0
    parts: 0
UAM:EH: 2015-11.EH
    specimens: 0
    parts: 1
UAM:EH: 2015-14.EH
    specimens: 0
    parts: 7
UAM:EH: 2015-18.EH
    specimens: 0
    parts: 1
UAM:EH: 2015-21.EH
    specimens: 0
    parts: 2
UAM:EH: 2015-22.EH
    specimens: 0
    parts: 5
UAM:EH: 2015-23.EH
    specimens: 0
    parts: 1
UAM:EH: 2015-27.EH
    specimens: 0
    parts: 1
UAM:EH: 2015-28.EH
    specimens: 0
    parts: 1
UAM:EH: 2015-31.EH
    specimens: 0
    parts: 12
UAM:ES: 518.2014.ESCI
    specimens: 6
    parts: 0
UAM:ES: 519.2014.ESCI
    specimens: 0
    parts: 8
UAM:Ento: UAM.2012.009.Ento
    specimens: 30624
    parts: 0
UAM:Ento: UAM.2014.018.Ento
    specimens: 309
    parts: 0
UAM:Ento: UAM.2014.020.Ento
    specimens: 750
    parts: 0
UAM:Ento: UAM.2015.015.Ento
    specimens: 950
    parts: 0
UAM:Herb: 2009.6.Herb
    specimens: 0
    parts: 2
UAM:Herb: 2011.44.Herb
    specimens: 22
    parts: 0
UAM:Mamm: 2014.011.Mamm
    specimens: 1
    parts: 0

**Comment by ccicero** [comment] 2015-12-17 16:49
What's the downside of allowing data loans to have parts, and what are the alternatives?

**Comment by dustymc** [comment] 2015-12-17 18:11
I created the concept of data loans for a "we downloaded all the {some plant taxon} data from Arctos and..." publication. The loan lets us track what was identified as that taxon at the time, protects those things from deletion, and ties the publication to a project. That adds value for us (documenting usage), for the authors (there's some added stability), and for users (who can at least tell what specimens weren't examined). 

That's certainly not the only use case, but there's the origin.

If someone handled something (or we handled it for them) that can conceivably be "part of the specimen," and can potentially be "blamed" for causing wear or damage, it's not a data loan. The link from the loan should be to the physical bit that was examined/photographed/whatever.

If they just downloaded something, or we downloaded something for them, it's a data loan. No physical bits were handled/examined, the data refers to cataloged items, and so the pointer from the loan should be to those cataloged items.

(Cataloged items and parts are both types of collection objects.)

If something left the building, and therefore might have been damaged in packing/transit/unpacking, there should be a shipment. If something that might be defined as a part ("thing to which one can stick a barcode") didn't leave the building, there should not be a shipment. (And so "in house" loans are uninformative - they don't tell you anything about WHAT or WHY, and everything that's embedded in "in house" can be derived from the lack of a shipment - or at least that would be the case if we were a bit better at recording shipment data.) There is no "something" involved in data loans (if there is it's not a data loan), and so I don't understand how there could be a shipment.

If we make those distinctions and record the data accurately, the data can DO STUFF for us. We can use them (possibly in conjunction with other stuff, like object condition history) to prefer (or avoid) shipment methods, evaluate packing techniques, monitor how/if normal curatorial activities (moving stuff around on shelves, pest inspections) cause damage, etc.

If we don't make those distinctions or record those data, or contaminate them with other types of data, we lose all of that potential.

**Comment by dustymc** [comment] 2016-10-18 20:28
Blocking #959; elevating priority

**Comment by dustymc** [comment] 2017-08-24 16:45
This has become an important obstacle. Lacking compelling immediate feedback, I'm going to split any loans which contain both specimen parts and cataloged items, recategorize any data loans which contain specimen parts, and prohibit using data loans for specimen parts in the future.

**Comment by amgunderson** [comment] 2017-08-24 18:26
I can only ever add specimen parts to a loan, there is no way to add just a specimen/cataloged item to a data loan.

**Comment by amgunderson** [comment] 2017-08-24 18:27
Data loans include images and other media which are parts of many objects in ethno and art and arch collections. These are parts and are loaned as data.

**Comment by dustymc** [comment] 2017-08-24 18:52
>there is no way to add just a specimen/cataloged item to a data loan.

I'm not sure we're talking about the same things, and maybe we need some new loan types or better vocabulary or something. Data loans are intended to document "nobody touched anything except their keyboard" "usage" - things the user could have/did just downloaded but was awesome and told us about it, we found our data in some publication, etc. There's no specific part (where parts are "things to which one might stick barcodes") involved, and so the linkage is to the cataloged item (which are "things to which someone felt like giving a catalog number for some reason"). That sort of usage is different than "traditional" loans and so you might want to keep it separate, and it requires different code and visualization which is why I want to keep it separate. I don't think there's a single view of the data which makes sense for both data and "normal" loans.

> images and other media which are parts 

That (if we're talking about physical stuff) should be loaned via "normal" loans, not data loans.

1. If someone touched "the specimen" (lopped off a hunk of liver, drug a skin out to take a picture, digitized associated hardcopy media, etc.) it's a "traditional" loan. A collection manager probably had to do something, some sort of physical object may have been damaged, etc.

2. If someone didn't touch "the specimen" (downloaded images, grabbed data from GBIF and we somehow found out, etc.) then it's a data loan. The CM probably didn't need to go into the collection, there's no possibility that anything physical was damaged in the process.

Does that get us all on the same page?

**Comment by AJLinn** [comment] 2017-08-24 19:51
> Data loans are intended to document "nobody touched anything except their keyboard" "usage" - things the user could have/did just downloaded but was awesome and told us about it, we found our data in some publication, etc. There's no specific part (where parts are "things to which one might stick barcodes") involved, and so the linkage is to the cataloged item (which are "things to which someone felt like giving a catalog number for some reason").

BUT, when I do a data loan that I flag in the Description Field as a Photo Request, I make a loan and add "Media" parts for the items that are depicted in the photographs. I never have to physically touch the object - normally I'm just finding the TIFF file and transferring that to someone else. Sometimes I might have to touch the 35mm slide or BW print if it hasn't been digitized, but that would be a second media file that I would note and it would be that media part I would add to the loan.

Is that wrong? Is there a better way? This system has been working great for the past 3 years that I've been doing it but I'm open to improvements ...  I also keep a running log of what I've done in the Remarks field.

**Comment by amgunderson** [comment] 2017-08-24 19:53
I'm on your page, yeah. But we might loan/grant high resolution images, which are not physical things but are recorded as specimen parts in some collections (maybe they shouldn't be). I would call those data loans because of the loan types available it makes the most sense, the images are not returnable, consumable, in house, or a transfer of custody. Should there be a loan type=media? 

Also, the only things we can add to loans in arctos are specimen/object parts. So you will need to enable collection objects or object data to be added to loans for your data loans.

**Comment by AJLinn** [comment] 2017-08-24 19:54
AND THEN... I might have to take a new photograph of an object in order to fulfill a photo request. In those cases I usually still note it as a Data loan, but I add both the object and the media parts to the loan, rather than creating two separate loans to refer to the handling part vs the transfer of the image files part.

**Comment by dustymc** [comment] 2017-08-24 20:31
>enable collection objects or object data to be added to loans for your data loans

That's what's "new" about data loans, but turns out it is/was also possible to add objects to them, so of course that happened.

Find a data load, add items, find specimens, and....

<img width="567" alt="screen shot 2017-08-24 at 1 14 30 pm" src="https://user-images.githubusercontent.com/5720791/29686556-3a135cac-88ce-11e7-88f7-19c81642c021.png">

is available.

>high resolution images, which are not physical things but are recorded as specimen parts in some collections (maybe they shouldn't be).

They probably shouldn't technically be, but the media on which they're stored might be. At least for the foreseeable future, if that somehow makes your life easier, go for it. We can revisit this after we've solved all other problems!

>Should there be a loan type=media

I think that's a good idea - I believe most of the (mis) use of data loans for objects rather than cataloged items/concepts somehow involves "media" (in the general sense, not just the Arctos table).

>finding the TIFF file and transferring that to someone else

That's definitely gray area. I would personally just upload the TIFF to Arctos, make the JPGs a derivative of it, and deal with usage as data loans, but I also understand that there are reasons to maintain tighter control of higher-resolution images.

>touch the 35mm slide or BW print

>take a new photograph of an object

I'd certainly consider those actions "traditional" loans - you're potentially damaging physical material etc., you're just not requiring the borrower to show up with a camera or creating a shipment.

**Comment by AJLinn** [comment] 2017-08-24 21:05
> That's definitely gray area. I would personally just upload the TIFF to Arctos, make the JPGs a derivative of it, and deal with usage as data loans, but I also understand that there are reasons to maintain tighter control of higher-resolution images.

Yup, our Rights & Reproductions process requires that we vet the use of our images in publications and have some sort of interaction with folks before we hand over high resolution image files for publications. This usually involves contacting the maker of the item before we give permission to reproduce the photo, due to copyright and/or [VARA](https://en.wikipedia.org/wiki/Visual_Artists_Rights_Act) constraints.

> touch the 35mm slide or BW print
take a new photograph of an object
I'd certainly consider those actions "traditional" loans - you're potentially damaging physical material etc., you're just not requiring the borrower to show up with a camera or creating a shipment.

So in these cases you'd propose that we create TWO separate loans for the same transaction, one being a "traditional" loan (in-house) [handling the object/photo/slide] and one being a "data" loan [process of transmitting the image file to the publisher/author for publication]?

Is there a way to associate those loans so we know they're part of the same initial request for information from outside?

**Comment by dustymc** [comment] 2017-08-24 21:48
>TWO separate loans

Perhaps, I suppose, but not really.... 

If you're loaning some photos and some of them already exist, it's probably technically correct to do that under two types of loans. I don't think that's what I'd do/advocate in reality though - I'd just make one "normal" loan for the material you have to handle and include some arbitrary part (which may not have to be arbitrary if you're treating images as parts) from the specimens with the pre-existing images. If you're controlling the images they'll want to use, you may never have reason to make a data loan.

I created the concept of data loans to capture something more than website statistics can, but something less than normal loans do. I don't think you'd have any trouble justifying a "normal" loan (eg, in a proposal) when a Curator/CM was involved for some reason. I think you could cause trouble by mixing "found our CC0-licensed data in a publication" usage in with your normal loan data in a proposal, and that's more in line with what data loans are intended to capture.

http://handbook.arctosdb.org/documentation/loans.html#type

Projects exist primarily to tie transactions (including multiple related loan requests) together.

Unrelated here, but Arctos allows you to license media individually, and I can add whatever licensing documents you might need to the code table. IANAL obviously, but it seems to me that some sort of "Look but don't touch" license might do what you need while also making potential users much more aware of what you have to offer.

**Comment by dustymc** [comment] 2017-08-25 15:24
1. Should we create a new loan type (http://arctos.database.museum/info/ctDocumentation.cfm?table=CTLOAN_TYPE) "media" = "Loan primarily involving media; specimen material or hard-copy archives may have been handled for digitizing purposes." (Term and/or definition suggestions appreciated!)

2. Attached are data loans which contain parts. I'll probably eventually update them to loan type "legacy" if I don't receive other instructions.

@KatherineLAnderson @amgunderson @ccicero @Jegelewicz @fsjmm1 @AJLinn @jldunnum have data here.

[temp_datanotdata.csv.zip](https://github.com/ArctosDB/arctos/files/1252201/temp_datanotdata.csv.zip)

**Comment by AJLinn** [comment] 2017-08-25 17:26
> Should we create a new loan type (http://arctos.database.museum/info/ctDocumentation.cfm?table=CTLOAN_TYPE) "media" = "Loan primarily involving media; specimen material or hard-copy archives may have been handled for digitizing purposes." (Term and/or definition suggestions appreciated!)

I say yes to new loan type "media". Definition seems fine to me.

> Attached are data loans which contain parts. I'll probably eventually update them to loan type "legacy" if I don't receive other instructions.

I'll get you a marked-up spreadsheet relating to my data loans and note which ones can be kicked over to media once created as a loan type.

**Comment by AJLinn** [comment] 2017-08-25 17:49
Updated data loan list for UAM:EH

[temp_datanotdata-UAMEH.csv.zip](https://github.com/ArctosDB/arctos/files/1252589/temp_datanotdata-UAMEH.csv.zip)

**Comment by dustymc** [comment] 2017-08-25 18:38
@AJLinn  please email me the spreadsheet - github says there's some sort of hash failure and won't let me have it....

**Closed** 2017-09-07 15:24 UTC
Labels: Blocked: Needs Discussion, Function-Transactions, Priority-Critical
