### ISSUE TITLE
agent mess - Washington Department of Game

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#6473] opened 2023-06-29 14:38 UTC
Washington Department of Game looks to be a duplicate of Washington Department of Fish and Wildlife, which would be easy were there not a bunch of relationships hanging off both. HELP!

**Comment by Jegelewicz** [comment] 2023-06-29 16:48
Moved relationships over, marked as bad duplicate of and added aka to Washington Department of Fish and Wildlife.

**Closed** 2023-06-29 17:16 UTC
Labels: Function-Agents, Help wanted, Priority - Wildfire Potential
