### ISSUE TITLE
Controlled vocabulary for part quality

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/arctos#1373] opened 2017-12-19 00:06 UTC
We need to develop a standardized vocabulary for part condition/quality to track via the new part attribute.  This has to be applicable to tissue samples for the Global Genome Biodiversity Network (GGBN) grant, but should be relevant to other part types. Currently this field is open text.  Suggestions for alternatives?

At MSB, we use the following 5 categories:  
poor   fair   good   very good   excellent

Any other systems in use? Ideas?

**Comment by ekrimmel** [comment] 2017-12-19 01:15
We use the same categories minus "very good."

**Comment by KyndallH** [comment] 2017-12-19 01:29
This may be hard. For tissues, we use a 1 - 5 scale. Then we also have unchecked, broken, incomplete, good, dessicated, skull | Top right quarter of braincase missing.; partial, etc.

Ethnology at UAM is even more complex when it comes to that field.

**Comment by dustymc** [comment] 2017-12-19 01:43
This would be a controlled-vocabulary optional supplement to part condition, not a replacement. It would be implemented as a part attribute, so would include

- value
- definition of the value (in the code table)
- determiner (optional)
- date (optional)
- remark (optional)

and any part could have any number of these. It is meant only for "tissues" but I doubt we can (or should) enforce that.

**Comment by ekrimmel** [comment] 2017-12-19 01:46
Yes, please definitely don't enforce being for "tissues" only! Lots of reasons to search on a controlled vocab part condition--we do it all the time at CHAS when looking for specimens that would be appropriate for programming or exhibit

**Comment by Jegelewicz** [comment] 2017-12-19 15:46
So my request would be the capability to enter these part attributes as part of a specimen bulkload rather than uploading specimen records then separately uploading part attributes, as the two step process creates a greater probability that attributes might end up with incorrect parts.

**Comment by campmlc** [comment] 2017-12-19 15:48
Agreed.

**Comment by dustymc** [comment] 2017-12-19 16:24
@AJLinn this is a SUPPLEMENT - there will be no migration or changes to existing data (although we could try to extract something if that's somehow useful). The new concept should be limited to ~a dozen possible values. Part condition has maintained history for a long time - Edit Parts, click "history" near the "condition" label on any part. The history was designed exactly for your use case. A part condition was "good," then went on loan, then was updated to "smashed into tiny pieces" before being re-installed - along with timestamped condition history, you can figure out who packed it for the loan, who shipped it, who was responsible for receiving it, who shipped it back, etc. (And possibly you'd want to add an Agent Rank so the next Curator has more information before loaning to that agent or shipping via that carrier or etc.)

This change will add another type of part attribute, which will display the same as your "location" data (until someone comes up with a better way of displaying parts, anyway!).

@Jegelewicz the bulkloader is currently 288 columns, 84 of them are parts. Part attributes require 6 columns. Adding 6 attributes to each part would add another 72 columns (and someone would ask for a 7th within like 10 minutes...). I don't think that's fatal to any modern version of Excel (it was through ~2011), but that's a LOT of things to keep track of, I have absolutely no idea how I'd display it in the data entry screens, etc. I don't have any actual reasons not to go there, but it still somehow doesn't seem right.

One possible alternative is https://github.com/ArctosDB/arctos/issues/1020#issuecomment-332256323

You can also use the "add more" on data entry to create up to 6 attributes per part (and any number of parts). There's some discussion regarding the functionality of that tool at https://github.com/ArctosDB/arctos/issues/1294

**Comment by campmlc** [comment] 2018-01-02 17:20
We need a status summary on this for the GGBN report.

**Comment by dustymc** [comment] 2018-01-04 01:58
>status summary on this for the GGBN report

We will assign specimen part attributes to each tissue as condition is noted. Each tissue may have any number of Attributes, each of which includes a controlled and defined value term, a date, a determiner, and optional clarifying remarks. The sum of these determinations will be made available with each tissue, and provide a comprehensive picture of tissue quality.

**Comment by dustymc** [comment] 2018-02-08 15:46
This has become a duplicate of #1384

**Closed by dustymc** 2018-02-08 15:46 UTC
Labels: Function-CodeTables, Function-SpecimenRecord
