### ISSUE TITLE
error feedback Fix/View with Arctos Tools 

### ISSUE THREAD

**Issue by cefilipek** [ArctosDB/arctos#2822] opened 2020-06-23 15:49 UTC
** Please include enough information to re-create the problem if this request involves Arctos forms. Links and screenshots are helpful. **

I bulkloaded a file and when I went to fix the errors that would not allow the records to load using "Fix/View with Arctos Tools" I received an error message saying "the tag [cfgrid] is not implemented yet." 

I am using a Mac running macOS Catalina Version 10.15.4 with Google Chrome Version 83.0.4103.106.

<img width="873" alt="Screen Shot 2020-06-23 at 10 41 38 AM" src="https://user-images.githubusercontent.com/56844074/85425600-fe767f80-b53e-11ea-9b06-5ea77e8c539c.png">

**Comment by dustymc** [comment] 2020-06-23 15:55
Duplicate of https://github.com/ArctosDB/arctos/issues/2727

**Closed by dustymc** 2020-06-23 15:55 UTC
Labels: Bug, Tool - Bulkload Records, contact

**Comment by Jegelewicz** [comment] 2020-06-23 15:56
@cefilipek try using Datatables at the top of the form.

**Comment by cefilipek** [comment] 2020-06-23 16:02
@Jegelewicz I don't see Datatables. Is that the download data with errors or is there a separate link I'm not seeing?

**Comment by Jegelewicz** [comment] 2020-06-23 16:05
Oh wait, You are still at the stage where the records haven't been loaded - Th Arctos tools aren't working as far as I know - so the best option is to download csv, fix stuff and reload - the error messages will be in the status column of the file you download. Let me know if this sounds crazy....

**Comment by cefilipek** [comment] 2020-06-23 16:07
That makes sense. Thank you very much! I misunderstood download as upload for some reason, so I was reluctant to do so, but this makes more sense.
