### ISSUE TITLE
Loan Sidebar: "Most Recently Used Loan Number"

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos#2445] opened 2020-01-13 23:41 UTC
Is it possible to add another sidebar on [Create Loan](http://arctos.database.museum/Loan.cfm?Action=newLoan) that lists "most recently used loan number" (as an alternative to "Next Available Loan Number")? For those of us who use funky loan number systems (e.g., not YYYY.#.Colln) it would be handy so we could easily know the last number used and name our next loan accordingly, and would save Oracle from attempting to autoincrement funky numbers.

**Comment by Jegelewicz** [comment] 2020-01-14 00:36
I'm on board with this - in the end it may be much more useful than "next available".

**Comment by campmlc** [comment] 2020-01-14 00:42
Agree.

**Comment by campmlc** [comment] 2020-07-14 18:08
Reviving this - still have "next available loan number" displaying the last used. Perhaps we can have the option to choose one or the other. But right now the loan number displayed for MSB is incorrect and will result in problems.

**Comment by dustymc** [comment] 2020-07-14 18:10
duplicate of https://github.com/ArctosDB/arctos/issues/1949

**Closed by dustymc** 2020-07-14 18:10 UTC
Labels: Enhancement, Function-Transactions, Priority-High, Priority-Normal
