### ISSUE TITLE
Feature Request: Autopopulate default agents in loan forms

### ISSUE THREAD

**Issue by jldunnum** [ArctosDB/arctos#7384] opened 2024-02-07 19:02 UTC
For every Division of Mammals loan I create Joe Cook and I are the agents.  I would love to have these be automatic unless I decide to change them. Same goes for the shipped from address. Its always me and my address. 
Any way I can have the default agent of Joseph A. Cook autopopulate the "authorized by" field, Jonathan L. Dunnum populate the "in house contact" field and shipped from agent, and "shipped from address" be the following:
Jonathan L. Dunnum, Senior Collection Manager--Division of Mammals--Museum of Southwestern Biology--CERIA (bldg 83), room 204--MSC03 2020--1 University of New Mexico--Albuquerque, NM 87131--USA

**Comment by dustymc** [comment] 2024-02-13 00:29
I think this is more or less a duplicate of https://github.com/ArctosDB/arctos/issues/5691 (same idea, maybe different data) - https://github.com/ArctosDB/arctos/issues/6746 (place to store the recipes) seems a necessary precursor.

**Comment by Jegelewicz** [comment] 2024-03-11 22:08
> Is this functionality still waiting for resolution of https://github.com/ArctosDB/arctos/issues/6746?

yes

**Closed** 2024-07-17 01:53 UTC
Labels: Priority-Normal (Not urgent), Function-Transactions, contact
