### ISSUE TITLE
Agent Merge Request - Alva H. Felger

### ISSUE THREAD

**Issue by Cpittman53** [ArctosDB/arctos#7685] opened 2024-04-18 17:51 UTC
Use this template when you discover two agents that you believe represent the same person or organization.

**Agent that should remain after the merge**
This agent should represent the same person or organization as the agent below, but be of higher quality (more complete name, or includes additional information such as dates, relationships, addresses). Navigate to the agent page, copy the url and paste it below:

A. H. Felger
(https://arctos.database.museum/agent/10003790)

**Agent that will no longer remain after the merge**
This agent should be of lower quality than the agent into which it will be merged. Navigate to the agent page, copy the url and paste it below:

Alva H. Felger
(https://arctos.database.museum/agent/21250312)

**Reason for merge**
Please provide the reason you believe that these two agents represent the same person or organization.

I believe this two represent the same agent, associated with the work of an ornithology professor in Colorado. Both have specimens in DMNS collections, and UCM records note that the agent collected specimens in Colorado.

Please add this issue to the Agents Project

@ArctosDB/agents-committee

**Comment by dustymc** [comment] 2024-04-18 18:03
@ArctosDB/agents-committee this template should be updated; there is no 'merge' in the model. The template is probably still useful for facilitating intercollection communication, but the way to respond has changed and the language should probably change.

A person should transfer any useful data from the bad agent to the good agent, then create a 'bad duplicate of' relationship from the bad. Anyone using the 'bad' will get a periodic notification. Records can be moved from one agent to another using the Manage/Agents option in the search results tools menu.

**Closed** 2024-04-23 17:34 UTC
Labels: Function-Agents
