### ISSUE TITLE
Collection Codes need definitions

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3151] opened 2020-10-01 17:59 UTC
https://arctos.database.museum/info/ctDocumentation.cfm?table=ctcollection_cde

Values need definitions

**Comment by dustymc** [comment] 2020-10-02 13:58
Duplicate of  https://github.com/ArctosDB/arctos/issues/3150

https://handbook.arctosdb.org/documentation/catalog.html#guid-prefix and https://handbook.arctosdb.org/documentation/catalog.html#collection-code are and have been linked from pre-collection.

**Closed by dustymc** 2020-10-02 13:58 UTC
