### ISSUE TITLE
Blank/Missing Records From Bulkloader

### ISSUE THREAD

**Issue by Cpittman53** [ArctosDB/arctos#7517] opened 2024-03-11 15:27 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

There are missing records associated with a series of bird entries from a volunteer. I went to load the records the volunteer entered on Friday, and checked on them today. For the volunteer (user: mgardett), it shows that they have entered 16 records as of today but only 5 appear once I search for them. I know see that some records that were previously entered last week have the same issue.

**To Reproduce**
1. Search mgargett under Agents
2. Click on the "Show All Activity"
3. Click on the 16 DMNS:Bird catalog records
4. See error where there are only 5 entries present

**Expected behavior**

I was expecting to see 16 records in the search, with full information.

**Screenshots**

![image](https://github.com/ArctosDB/arctos/assets/106274900/f979bcd2-e6b7-4d87-b4fb-f20cdd800b59)

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 122

**Additional context**

Similar records are missing under the usernames cpittman and kcutler

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by camwebb** [comment] 2024-03-11 16:26
_It seems I'm also having a problem with the bulkloader, and I think it is the same as in this issue, so adding here:_

On Friday I did a test bulkload:

```csv
enteredby,accn,guid_prefix,identifier_1_value,identifier_1_type,identifier_2_value,identifier_2_type,identification_1,identification_1_order,identification_1_agent_1,identification_1_date,identification_1_attribute_type_1,identification_1_attribute_value_1,identification_2,identification_2_order,identification_2_agent_1,identification_2_date,identification_2_attribute_type_1,identification_2_attribute_value_1,agent_1_name,agent_1_role,agent_2_name,agent_2_role,agent_3_name,agent_3_role,agent_4_name,agent_4_role,event_verbatim_date,event_began_date,event_ended_date,attribute_1_type,attribute_1_value,locality_higher_geog,event_verbatim_locality,locality_specific,record_event_habitat,locality_attribute_1_value,locality_attribute_1_type,coordinate_dec_long,coordinate_dec_lat,coordinate_datum,coordinate_max_error_distance,coordinate_max_error_units,coordinate_lat_long_units,coordinate_georeference_protocol,locality_min_elevation,locality_max_elevation,locality_elev_units,record_event_type,record_event_collecting_source,record_event_determiner,record_event_determined_date,record_event_verificationstatus,part_1_name,part_1_condition,part_1_count,part_1_disposition,part_1_barcode
ElenaTT,2023.002.Herb,UAM:Herb,V181500,ALAAC,7805,collector number,Betula glandulosa,1,unknown,,verbatim identification,,,2,,,verbatim identification,,Lynn J. Gillespie,collector,J. M. Saarela,collector,Laurie L. Consaul,collector,R. D. Bull,collector,"July 10, 2008",2008-07-10,2008-07-10,description,,"Canada, Nunavut","Victoria Island: Camp 13 km north of Oterkvik Point, 10 km north of coast at Coronation Guff, upper camp area.","Camp 13 km north of Oterkvik Point, 10 km north of coast at Coronation Guff, upper camp area.; Victoria Island.","Gentle south-facing slope; Sedge-Dryas tundra to wet meadow, lichens abundant; 50-75% ground cover; calcareous substrate. Found only in moist tundra on slope between two flat terraces. Associates: Carex scirpoidea, Dryas integrifolia. Low shrub to 20 cm tall. Staminate and pistillate catkins present; only 2 plants seen with current year's inflorescences. Uncommon.","on label ; Verb. lat 68d 36' 50s N ; Verb. long 112d 34' 21s W",georeference source,-112.5725,68.6139,unknown,50,m,decimal degrees,not recorded,50,70,m,collection,wild,ElenaTT,2024-01-09,accepted,whole organism,unchecked,1,being processed,H1294765
```
Parts of the record can be found: 

```sql
SELECT * from coll_obj_other_id_num where display_value = 'V181500'
-- collection_object_id = 32385987
SELECT * from collector where collection_object_id = 32385987
-- four collectors: correct
```

but this data is not yet in `flat`:

```sql
SELECT * from flat where collection_object_id = 32385987
```
There _is_ a record, but it has almost no data.

I note that Flat Status shows: Flat Processing = 609,555. So I think the issue is that `flat` is still just way behind. Even though it's been two days.

**Comment by dustymc** [comment] 2024-03-11 19:30
https://arctos.database.museum/info/flat_status.cfm

Duplicate of https://github.com/ArctosDB/arctos/issues/6705

**Closed by dustymc** 2024-03-11 19:30 UTC
Labels: Priority-High (Needed for work)
