### ISSUE TITLE
noncompliant agent notifications

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos#3902] opened 2021-09-03 15:36 UTC
**Is your feature request related to a problem? Please describe.**

Creating an agent which appears to not follow the documentation spawns an email. Those often don't get noticed. From a user:

>Is there not a way to make these emails collection-specific? Or better yet, specific to the person who created the suspect agent? I don't need automated emails 8 days in a row regarding something that does not pertain to my collection. 

>collection-specific

The notification goes to the user's collections - in this case the user has access to a lot of collections. (I get them too, but I somehow missed this one.)

>person who created the suspect agent?

I think the targeting has to somehow be wider than that - the person who created the agent already got a notification on the agent page. The current message goes to 'manage_collection' Operators in the creating user's collections.

**Describe what you're trying to accomplish** 

Leverage The Community to fix problem, but also not be overly annoying.

**Describe the solution you'd like**

I have no idea.

**Describe alternatives you've considered**

Still no idea.

**Additional context**

Agents who don't meet the guidelines almost inevitably end up as duplicates - any amount of annoyance seems better than that!

**Priority**

??????

**Comment by Jegelewicz** [comment] 2021-09-03 16:32
HAHAHA! I get these and I often fix them (I fixed the one an intern created earlier this week). BUT, I left the one Carla created, because she should be getting the notices and I figured she should also know what to do about it.

**Comment by Jegelewicz** [comment] 2021-11-09 15:44
Closing as duplicate of #2550

**Closed by Jegelewicz** 2021-11-09 15:44 UTC
Labels: Function-Agents, Enhancement, Help wanted
