### ISSUE TITLE
Agent merge history

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#2928] opened 2020-07-15 22:53 UTC
While talking about #2927 the Taxonomy Committee also thought we should add a similar solution to agent mergers.

1. Proposed mergers should come with an explanation
2. Accepted merges should append the explanation to the remaining agent as a history of the merge ( I believe the "merge" does what it says and that extra names from the "bad duplicate" are added to the remaining agent as aka's  - someone correct me if that is wrong).

**Comment by ewommack** [comment] 2020-07-15 23:17
That sounds like a good idea to me.

**Comment by dustymc** [comment] 2020-07-16 15:29
>Proposed mergers should come with an explanation

This would discourage cleanup; anything marked for merger should be mostly self-evident, and everyone's copied on the notifications and available to answer questions.

I'm not actually sure what mergers do now - we've gone back and forth a few times, the possibilities are (1) to lose maybe-useful data or (2) to perpetuate whatever garbage caused a duplicate to be created in the first place. I _think_ we're currently on (2) and documentation requires the agent marking for merge to grab whatever's useful but not 100% sure.

**Comment by Jegelewicz** [comment] 2020-07-16 15:38
> This would discourage cleanup

I disagree and when getting an announcement that an agent has been marked for merger, understanding why that was done would be useful.

> anything marked for merger should be mostly self-evident

Anything is a lot of stuff and mostly leaves some things that require explanation. Nobody has to write a paragraph, just a simple reason will do - "J. D. collected at the same time and many of the same species and John Doe".

> everyone's copied on the notifications and available to answer questions

Questions can be avoided if an explanation is provided in the first place - also could save 10 different people reviewing the agents before deciding they don't need to ask a question.

**Comment by Jegelewicz** [comment] 2020-07-16 15:39
> I'm not actually sure what mergers do now

!!!!!

This needs documentation.

**Comment by dustymc** [comment] 2021-10-08 15:07
Why should always be the same: creator(s) didn't follow https://handbook.arctosdb.org/documentation/agent.html#creating--maintaining-agents. 

"Who" has been captured for a very long time.

There is no information lost, just moved - please see documentation.

If we are to raise the bar for merge, then we must also raise the bar for creation. We cannot have easy creation and difficult cleanup without losing core functionality.

We could add some sort of 'merged with' log, it would be some work and require some resources so needs discussed.

**Comment by lin-fred** [comment] 2022-02-09 22:06
Reviving this issue.

Looking to get a recording of explanation of why, who and when with merging agents (could this method also be used for the "not same as"?) We have this information when we make an agent, but not when one gets merged.

This has been a multi year discussion so I'm looking to revive this and get everyone's inputs again!

**Comment by ewommack** [comment] 2022-02-09 22:12
Added to March 3 AWG Issues meeting for discussion

**Comment by dustymc** [comment] 2022-02-10 02:02
I think there are two discussions here.

1. When to merge. I'm a very big fan of "when there's no compelling data to separate them" - that approach absolutely leads to cleaner data. (https://github.com/ArctosDB/arctos/issues/4122 would facilitate splitting when necessary.) I could be convinced to go the other way, but only if we greatly restrict creation in some way.
2. What happens when there's a merge. PG has pretty great JSON capabilities, I can just grab agent data as it's being deleted and stash it with the good dup. Here's a start - what's missing? (For being-merged agents there will always be exactly one relationship which will contain the who/when metadata.)

```
{
   "AGENT":[
      {
         "agent_id":21300608,
         "agent_type":"person",
         "agent_remarks":"Digitization Technician. New Mexico Museum of Natural History and Science, Collections Assistant, Museum of Southwestern Biology Division of Genomic Resources, Previous Manager, UTEP Biodiversity Collections",
         "preferred_agent_name":"Teresa J. Mayfield-Meyer",
         "createby":"Carla Cicero",
         "created_date":"March, 14 2016 19:53:50 +0000"
      }
   ],
   "AGENT_NAMES":[
      {
         "agent_name_type":"middle name",
         "agent_name":"Jegelewicz"
      },
      {
         "agent_name_type":"aka",
         "agent_name":"Teresa J. Mayfield"
      },
      {
         "agent_name_type":"birth name",
         "agent_name":"Teresa Ann Jegelewicz"
      },
      {
         "agent_name_type":"first name",
         "agent_name":"Teresa"
      },
      {
         "agent_name_type":"last name",
         "agent_name":"Mayfield-Meyer"
      },
      {
         "agent_name_type":"login",
         "agent_name":"jegelewicz"
      },
      {
         "agent_name_type":"preferred",
         "agent_name":"Teresa J. Mayfield-Meyer"
      },
      {
         "agent_name_type":"aka",
         "agent_name":"0000-0002-1970-7044"
      }
   ],
   "ADDRESS":[
      {
         "address_type":"ORCID",
         "address":"https://orcid.org/0000-0002-1970-7044",
         "valid_addr_fg":1,
         "address_remark":""
      },
      {
         "address_type":"correspondence",
         "address":"635 Cougar Loop NE\r\nAlbuquerque, NM 87122",
         "valid_addr_fg":1,
         "address_remark":""
      },
      {
         "address_type":"GitHub",
         "address":"https://github.com/Jegelewicz",
         "valid_addr_fg":1,
         "address_remark":""
      },
      {
         "address_type":"phone",
         "address":"214-693-9269",
         "valid_addr_fg":1,
         "address_remark":""
      },
      {
         "address_type":"email",
         "address":"jegelewiczt@unm.edu",
         "valid_addr_fg":0,
         "address_remark":"still active but prefer other email address"
      },
      {
         "address_type":"email",
         "address":"jegelewicz66@gmail.com",
         "valid_addr_fg":1,
         "address_remark":""
      },
      {
         "address_type":"correspondence",
         "address":"Museum of Southwestern Biology\r\nDivision of Genomic Resources\r\nMSC03 2020\r\n1 University of New Mexico\r\nAlbuquerque, NM 87131",
         "valid_addr_fg":0,
         "address_remark":""
      },
      {
         "address_type":"shipping",
         "address":"University of Texas at El Paso\r\n500 West University Avenue\r\nEl Paso, TX 79902\r\nBiology Bldg. #222\r\n",
         "valid_addr_fg":0,
         "address_remark":""
      }
   ],
   "AGENT_RELATIONS":[
      {
         "agent_relationship":"employee of",
         "createby":"Teresa J. Mayfield-Meyer",
         "related_agent":"Museum of Southwestern Biology, Division of Genomic Resources",
         "created_on_date":"May, 23 2018 10:25:55 +0000",
         "relationship_began_date":"2018-02-19",
         "relationship_end_date":"2019-09-30",
         "relationship_remarks":""
      },
      {
         "agent_relationship":"employee of",
         "createby":"Teresa J. Mayfield-Meyer",
         "related_agent":"University of Texas - El Paso",
         "created_on_date":"September, 12 2017 11:09:13 +0000",
         "relationship_began_date":"2016-02-08",
         "relationship_end_date":"2018-01-31",
         "relationship_remarks":""
      },
      {
         "agent_relationship":"employee of",
         "createby":"Teresa J. Mayfield-Meyer",
         "related_agent":"New Mexico Museum of Natural History and Science",
         "created_on_date":"January, 14 2020 17:21:42 +0000",
         "relationship_began_date":"2019-10-04",
         "relationship_end_date":"2020-09-30",
         "relationship_remarks":""
      },
      {
         "agent_relationship":"associate of",
         "createby":"Teresa J. Mayfield-Meyer",
         "related_agent":"Hannah Cantrell",
         "created_on_date":"July, 02 2020 10:32:24 +0000",
         "relationship_began_date":"2019-10-04",
         "relationship_end_date":"",
         "relationship_remarks":""
      },
      {
         "agent_relationship":"associate of",
         "createby":"Teresa J. Mayfield-Meyer",
         "related_agent":"Arctos Working Group Officers",
         "created_on_date":"August, 23 2021 17:52:18 +0000",
         "relationship_began_date":"2017-07-01",
         "relationship_end_date":"2019-06-30",
         "relationship_remarks":"Treasurer"
      }
   ]
}
```

**Comment by Jegelewicz** [comment] 2022-03-09 22:32
From today's Agent Committee Meeting

We think that this process needs to be a bit less automated. @droberts49 provided the example of the need to immediately address an incoming email that two agents have been marked for merge when you are pretty sure they shouldn't be in order to avoid the need to undo a merge that shouldn't have happened. Emails about agent merge are sporadic and easily missed and we feel that the potential for making messes is equal to the potential mess of duplicate agents. Here is what we discussed.

 - We need to know who marked  agents for merge and WHY
   - We need a why because even if you should be following the handbook, we assume that there are going to be nuances in it that would help us understand and make a decision on if we really should stop a given merge.
 - Is there a script that automatically merges some agents -> if that is so, we request that is stops and we discuss its use before it goes forward again.
 - With the growth in collections, we are going to have more overlap with names than we have in the past. We will need to review this process, because we don't have a super robust method for handling same name, different person scenarios. 
 - Maybe we should consult with a genealogist (or archivist?) to see how people who deal with human names and tracking people store multiple generations of people across the entire globe. 
   - In Wikidata they use Q numbers -> maybe speak to them and their work on archiving names. 

Just as we have community discussion around quarantine of taxon names, we suggest a more human process for completing agent merges. We suggest the following:

Agents marked for merge be reviewed by the Agent Committee before a merge actually is finalized. The committee would need a report or the ability to search agents by relationship, so that we could find all of the "bad duplicate of" agents for review. With very little change, we could require an explanation for the bad duplicate of relationship in the remark for the relationship. If the Agents Committee cannot understand why the merge was requested, an issue will be created for discussion with the person who created the relationship and representatives from the collections affected.

**Comment by droberts49** [comment] 2022-03-09 23:17
Here is the recent situation I dealt with:
We had the name "Carl [Buhle"](https://arctos.database.museum/info/agentActivity.cfm?agent_id=21297195) migrated into Arctos in 2015 as part of our accession records. We added the name "[C. A. Buhl](https://arctos.database.museum/info/agentActivity.cfm?agent_id=21336792)" on 2/15/2022 as this name was on a specimen and we had determined that it was distinct enough from "Carl Buhle". We are the only collection in Arctos with either of these names.

The agent marked for merge email came through on 2/15/2022 -- the SAME DAY we created the record. This does not appear to be a person who identified it, but an automated process.
![image](https://user-images.githubusercontent.com/16580148/157554680-acaca9c4-33db-4c2b-b805-263b9dc3b6a9.png)

I *happened* to catch this email when it came through -- I had to drop everything that I was doing and immediately address this to prevent the merge. Diving into biographical research and one's collection records to find documentation is a time consuming process. Both records have more biographical information, which ends up helping the Arctos community, but this process shouldn't include a panic attack on our end and having to drop the other things that we are working on. There needs to be a sufficient reason to have the merge in the first place, not just that the two names looks similar. The current system places the burden for proof at the wrong point; it should be required when a merge is proposed.

Arctos is growing. In our collection, we have numerous cases of families passing down names -- yet, these are distinct people. We are going to have more situations where there are agents with the same name; I googled my name and there are definitely things that come up that aren't associated with me, but with other people with the same name. Merging name records without going through and verifying that two agents are in fact the same person is irresponsible in terms of data quality.

I support requiring that agent merges be proposed by an identified person (not an automated process) and supported by evidence or reason, then these are reviewed by the agents committee.

**Comment by dustymc** [comment] 2022-03-10 02:28
@lin-fred check any recent merger - eg https://arctos.database.museum/agents.cfm?agent_id=1009287 - scroll to the bottom, click format.

> same name, different person 

https://handbook.arctosdb.org/best_practices/Agents.html#different-agent-same-name

>automated process

I can check the box and click all the squares with bicycles to prove I'm not a robot! I'm pretty sure I flagged that one, I just watch the force-create logs. IIRC they were in similar places doing similar things according to some remarks or something, and there definitely wasn't a relationship or I couldn't have flagged them. (And Sr. is Buhle and Jr. is Buhl??)

I think we have a responsibility to give people (and other things, but that's probably both less critical and easier) proper credit for their activities, and that means avoiding duplicates. I think that will always be some balance between the ease of creation and the ease of merging; if we're to raise the bar for merger, sustainability requires also raising the bar for creation (and we've recently gone the other way).

>merges be proposed by an identified person

That's been in place - for all relationships, not just ``bad duplicate of`` - for several years. 

<img width="909" alt="Screen Shot 2022-03-09 at 6 10 57 PM" src="https://user-images.githubusercontent.com/5720791/157574511-454a15e5-d52c-4279-a2b3-d328bb6b4e09.png">

>drop the other things

Would adjusting the cook time help? (It's currently [14 days](https://handbook.arctosdb.org/documentation/agent.html#deletingmerging-agents).)

>happened to catch this email 

Maybe notifications should be replicated on the post-login page? (Perhaps as part of https://github.com/ArctosDB/arctos/discussions/4031?) That would also be useful for things like https://github.com/ArctosDB/arctos/issues/4346 - users would still get the message, even if sendmail chokes on their 500 overdue loans.

This thing:

<img width="647" alt="Screen Shot 2022-03-09 at 6 19 09 PM" src="https://user-images.githubusercontent.com/5720791/157575386-d4c86427-d162-4ef2-ad06-393aed64f5c2.png">

**Closed** 2022-03-15 01:33 UTC
Labels: Priority-High (Needed for work), Function-Agents, NeedsDocumentation

**Comment by droberts49** [comment] 2022-03-26 20:31
@dustymc 
> I flagged that one, I just watch the force-create logs

I want to say that for all the agents I create these days I have to hit the force-create link. I do check by searching through agents with the last name, first name, and variations before I create a name.

> And Sr. is Buhle and Jr. is Buhl??

Yes -- I think it is related to the family's emigration with the senior using their home country's spelling and the junior using the "Americanized" name. Plus, wouldn't the name with an "e" and one without the "e" give pause to merging these?

**Comment by lin-fred** [comment] 2022-07-13 14:47
> @lin-fred check any recent merger - eg https://arctos.database.museum/agents.cfm?agent_id=1009287 - scroll to the bottom, click format.

Btw this is great!

**Comment by campmlc** [comment] 2022-10-11 07:39
Agree, no point to it at all. Error messages should mean something
important, not be annoying and ignored.
