### ISSUE TITLE
Bulk update specimen attributes?

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#3412] opened 2021-02-05 23:38 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Is your feature request related to a problem? Please describe.**

In entomology collections when loans go out the specimens are often unidentified and not sexed (and sometimes lifestage, eg 'adult' is also not recorded).

When the loans come back the specimens are identified, and often sorted by sex etc.

We have a tool to bulk-change the identifications of specimens but the only way to bulk change attributes is via bulkloading. It would be nice to be able to add attributes like lifestage = "adult" and sex = "female" etc. at the same time as we are bulk changing the IDs (and object tracking) all from the same form.  

**Describe what you're trying to accomplish** 
An clear and concise overview of the goals; why are you asking for this?

**Describe the solution you'd like**
How might we accomplish your goals?

**Describe alternatives you've considered**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues gets sent into a black hole of despair.
medium

**Comment by dustymc** [comment] 2021-03-04 00:46
duplicate of https://github.com/ArctosDB/arctos/issues/1959

**Closed by dustymc** 2021-03-04 00:46 UTC
Labels: Enhancement
