### ISSUE TITLE
Relationship restrictions for potential dupe agents

### ISSUE THREAD

**Issue by adhornsby** [ArctosDB/arctos#6839] opened 2023-10-18 15:41 UTC
# Error Text
ERROR: "bad duplicate of" and "potential duplicate of" agents cannot be in other relationships.  Delete all relationships to or from this agent and save before proceeding.

# Where it happened
https://arctos.database.museum/agents.cfm

# Steps to get there
Trying to set up "potential duplicate of" relationship between Pipe Holzemer and Richard Holzemer, which are also both "associate of" Bell Museum.

# Problem
The error and solution are clear.  I'm just wondering why this needs to be the case and if we can lift the restriction.  It's useful for us to have both the associate and potential dupe relationships.

# Solution
**Community response with directions for how to correct the problem**

**Comment by Jegelewicz** [comment] 2023-10-18 16:22
"potential duplicate of"

should be available even when other relationships exist? It doesn't DO any merging - just indicates that someone thinks the agents might be the same.

Still, I agree about #6813

**Comment by adhornsby** [comment] 2023-10-18 18:08
Gotcha, and I can stop making agents with that little info going forward.  I have tended to make them when I know they're going to show up for us a lot, regardless of how much info we have at the moment.

**Closed** 2024-02-27 01:57 UTC
Labels: Function-Agents, Priority-Low (Wish list), Error Messages, Error Explanation
