### ISSUE TITLE
UUID: Temporary universal unique identifier - how long till the vanish off a record?

### ISSUE THREAD

**Issue by KyndallH** [ArctosDB/arctos#4859] opened 2022-07-22 18:45 UTC
How long do the UUIDs (Temporary universal unique identifier for use only in linking records in the specimen bulkloader to records in other bulkloaders.) stick around? Do we have to manually delete them off of records? Or is there some hold up I need to address to get them off the records?

This one record was entered in 2021.

<img width="893" alt="Screen Shot 2022-07-19 at 12 47 52 PM" src="https://user-images.githubusercontent.com/16887896/180503764-d2a549c3-cfab-4a19-8ddd-eb40ad5afc39.png">

**Comment by dustymc** [comment] 2022-07-22 21:54
duplicate of https://github.com/ArctosDB/arctos/issues/4856

**Closed by dustymc** 2022-07-22 21:54 UTC
