### ISSUE TITLE
Code Table Request - different types of ectoparasites

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#6468] opened 2023-06-28 19:17 UTC
Can we add different ectoparasite options to the code table ctexamined_detected? The definition for 'ectoparasite' is "Use a more specific term if known. Unspecified parasites that live on or embedded in the body surface of the host, including, but not limited to fleas, ticks, mites, lice, and diptera."

maybe something like the following?

ectoparasite: feather louse
ectoparasite: feather mite
ectoparasite: tick
ectoparasite: flea

We'd need specific definitions for each of those.

**Comment by dustymc** [comment] 2023-06-29 00:29
https://docs.google.com/spreadsheets/d/1bboO2LLBd1D26ykbomQvIFU9ocOH9L9V0lBqCSipaBc/edit#gid=0


https://arctos.database.museum/info/ctDocumentation.cfm?table=ctexamined_detected

tick I think is certainly in scope

I'd recommend 'mite' instead of 'feather mite' if that doesn't lose too much, but I don't know enough to have strong feelings either way. 

In General:

1. The List will become unusable with some number of values so if something can be left out it should be, and 
2. At some point 'mite' starts to need the metadata that an identification can carry, and it becomes necessary to catalog (with or without parts) the mite in order to access that.

I don't think anyone knows quite where those lines are, but they do exist and should be part of the consideration for this table.

**Comment by campmlc** [comment] 2023-07-06 20:19
duplicate of #6260

**Closed** 2023-07-06 20:20 UTC
Labels: Function-CodeTables
