### ISSUE TITLE
Data Entry Errors/Problems

### ISSUE THREAD

**Issue by dperriguey** [ArctosDB/arctos#1754] opened 2018-10-22 18:11 UTC
I found 2 main data entry bugs/functional problems that we are experiencing. One other issue is also noted.  

1. Geology attributes are blank when you go back to edit a record from the data entry screen, although they are not really empty. When a person enters geology attributes and goes back to edit a record, the geology tab-downs that they selected are no longer selected and blank. The problem is that the record is not really blank. I can see from my end in the bulkloader browser that geology attributes are associated with the record. When I find an error and ask someone to correct it or if they find an error and need to correct it, they have to redo all the geology attributes. This also seems to occasionally happen with specimen event determiner; not sure if this has been fixed yet. 

2. This might need to be a different report. People cannot go back and edit several records from the data entry screen if an identification hasn't been entered. They can only go back and edit that specific record with a blank identification. I have students that enter several records at a time, need to have things entered into Arctos such as identifications or geology attributes, and then need to go back and make edits. If a student needs goes back to edit their records, they cannot access all their records; the data entry screen blocks them. As a preliminary way to get around this, I am having students enter a dummy identification so they can access all their records.  

3. It would also be nice if the drop-down arrow for accessing records from the Data Entry screen showed our record numbers, not the randomly generated number associated with the record for Arctos. 

1. Enter at least 2 record with geology attributes and a blank identification. 
2. Look at the record from the bulkloader browser. See the fields with values.
3. Go back to look at the record in the Data Entry screen. Notice the empty geology attributes and inability to access other records from the bottom right drop-down arrow. 

**Expected behavior**
I expect people to be able to see their records as they entered them and to have access to all their records. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32556913/47309793-9bf31080-d5f2-11e8-9f84-f9e717af12d7.png)

![image](https://user-images.githubusercontent.com/32556913/47309822-a90fff80-d5f2-11e8-8275-ac5103734e60.png)

![image](https://user-images.githubusercontent.com/32556913/47309860-c513a100-d5f2-11e8-92a8-f04bf1989c16.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 70.0.3538.67 (Official Build) (64-bit)

**Priority**
I would like to have this resolved by date: asap

**Comment by dustymc** [comment] 2018-10-22 20:44
Geology load will be fixed for next release.

(2) is by design - the form generally tries to make you fix things that will cause load failure. Definitely a separate Issue if you'd like to discuss.

I need a unique identifier which always exists to pass around. There is no suitable "our record number."

**Closed by dustymc** 2018-10-22 20:44 UTC
Labels: Function-DataEntry/Bulkloading, Priority-Normal, bug

**Comment by dperriguey** [comment] 2018-10-22 20:51
Ok, cool. I'm not sure what "next release" means. Is it an overall Arctos update?

There's not a way to mask the unique identifier with the record number?
