### ISSUE TITLE
Delay in viewing specimen records after entry

### ISSUE THREAD

**Issue by ufarrell** [ArctosDB/arctos#6705] opened 2023-09-04 10:34 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
I entered two individual mineral specimens (catalogue numbers 1575 and 1595) into the Trinity College Dublin Mineral collection (guid_prefix: TCDGM:Mineral). They both made it through 'autoload_core' but then went missing.

**To Reproduce**
1. Go to 'Data Entry > Enter Records' 
2. Click on 'TCDGM:Mineral'
3. Enter record (Accn: [TCDGM:Mineral]9999), )...
4. Go to 'Data Entry>Browse and Edit'
5. Load all selected records

**Expected behavior**
The specimen is entered and appears in searches

**Screenshots**
This is a screenshot of what I get when I search for the record by catalogue number. The blue arrow goes to this address: 'https://arctos.database.museum/guid' (i.e. missing the actual guid) before redirecting to the search page. If I search by the collection 'TCDGM:Mineral' I get no results.

![image](https://github.com/ArctosDB/arctos/assets/11726107/914aff1e-aaa3-4d93-a20f-5bb2d62310eb)

**Data**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.5
 - Browser: Firefox
 - Version: 117.0

**Additional context**

**Priority**

**Comment by dustymc** [comment] 2023-09-04 15:01
https://arctos.database.museum/info/flat_status.cfm

**Comment by DerekSikes** [comment] 2023-09-04 17:42
Friday Sep 1 after Arctos came back on line, I added a new identification to 4 specimens but searching now I am not finding them - with many different search strategies to find them. It's as if the IDs I added vanished.

**Comment by dustymc** [comment] 2023-09-06 13:39
@ufarrell I'm not sure how to say it better than what's on the top of the page, but clearly someone needs to!

I have limited resources so I have to pay the costs up front (when something changes, rather than when something's requested) by caching the core of the complex data into a simpler (so cheaper to query) structure. 90-some-odd-something percent of the time, that happens within a minute. When someone makes some huge change (or occasionally when there's some sort of problem) it can take days to catch up. I'm not sure if this is related or not, but around this time I noticed that someone messed with https://arctos.database.museum/name/unidentifiable#Arctos which set a millionish records to update. If anything ever happens on https://github.com/ArctosDB/arctos/issues/6111 it'll take several days to catch up. Etc.

I usually have some flexibility in my side of that, and I can prioritize one (or a dozen, or MAYBE a hundred) records ahead of some huge mass by request.

@ArctosDB/documentation (I think maybe that's not the current project - help @ebraker @Jegelewicz !) - help making the blurb at the top of  https://arctos.database.museum/info/flat_status.cfm better (or something to use as pagehelp or whatever) please?

**Comment by Jegelewicz** [comment] 2023-09-06 13:55
I don't see a way to make the blurb better, and right now it looks like stuff is current

![image](https://github.com/ArctosDB/arctos/assets/5725767/b360e300-5d28-4cc3-b694-e90583a6fa6f)

I never check this thing so I don't know what other statuses appear here, but I think that perhaps a description of the status or a way for me to know what data is included in "error_in_processing" might help.

**Comment by ufarrell** [comment] 2023-09-06 14:21
Thanks Dusty, I get it now. Yes, I think a definition of status would be good - 'status X = in progress'

Seems obvious now, but when I returned to this I had a vague memory of a third status, but couldn't remember what it said, and I wasn't sure if there was some error indicated by the error-in-processing that maybe I needed to go away and find. Also had a brief moment of wondering if "current" meant "currently in progress". 

If possible, maybe keeping that third status visible, even when NumberRecords  = 0 would be informative as well

**Comment by dustymc** [comment] 2023-09-06 14:53
How's this?

<img width="528" alt="Screenshot 2023-09-06 at 07 50 55" src="https://github.com/ArctosDB/arctos/assets/5720791/57ec8910-6589-45b6-875c-1c27f751b019">

**Comment by Jegelewicz** [comment] 2023-09-06 14:55
That's helpful, but the next step for me is what are the errors? Are they mine? what should I be doing?

Any way to give us that?

**Comment by dustymc** [comment] 2023-09-06 15:02
>errors

If you can do anything about them then you'll have no problem finding them....

Just ping me. I try to keep on top of errors, it doesn't always work. (That one was what almost all of them are, someone swaparooing a GUID around. I don't have a technical and sustainable solution for that and the situation would not be allowed if I had my way so I just cringe and force-refresh.)

**Comment by Jegelewicz** [comment] 2023-09-06 15:07
> swaparooing a GUID

What does that mean exactly?

**Comment by campmlc** [comment] 2023-09-06 15:19
Can we get some description on the status page as to what current, flat, filtered flat etc mean, and what it means if there are large vs small numbers there? It still isn't obvious what numbers in those various columns mean in terms of potential wait times.

**Comment by dustymc** [comment] 2023-09-06 15:37
I've gathered some related conversations below. If I had any better ideas for how any of this could work, it'd already work like that. If someone else has better ideas then PLEASE spell them out here!

https://github.com/ArctosDB/arctos/issues/6320
https://github.com/ArctosDB/arctos/issues/4714
https://github.com/ArctosDB/arctos/issues/4659
https://github.com/ArctosDB/arctos/issues/6700
https://github.com/ArctosDB/arctos/issues/6106
https://github.com/ArctosDB/arctos/issues/5511
https://github.com/ArctosDB/arctos/issues/6146
https://github.com/ArctosDB/arctos/issues/6121

**Comment by mkoo** [comment] 2023-10-06 06:10
The form help text at the top of the page is better (except for a typo)
currently:
```
 FLAT is the cache which supports most searches and provides the data available in many Arctos views. Changes to underlying data should propate to FLAT and become visible.

Updates and catalog record entries are processed in the order they enter the queue. Most updates are available everywhere within a minute, occasionally large changes can necessitate days or even weeks of processing.

Very occasionally, a change to underlying data is not reflected in FLAT. This should be reported in Issues. Individual records may be marked for refresh by any Operator with access. Larger jobs may be coordinated with the DBA team.

FILTERED_FLAT serves the same purpose to public users.

More discussion: https://github.com/ArctosDB/arctos/issues/6705 
```

Only comment is to fix typo (```propate ``` to ```propogate```)
When completed, please close this issue ! @dustymc

**Closed** 2023-10-06 22:24 UTC
Labels: Priority-High (Needed for work), Display/Interface

**Comment by dustymc** [comment] 2024-07-17 15:06
Commenting here because this Issue is linked from flat status.

Someone (or some intersection, I'm not sure) loaded a bunch of 'no data' records, which resulted in a very large locality (and maybe event) merge, after which tens (hundreds?) of thousands of records need to refresh. This resulted in

* https://github.com/ArctosDB/arctos/issues/7945
* https://github.com/ArctosDB/arctos/issues/7946
* https://github.com/ArctosDB/arctos/issues/7948

How can we better communicate any of this?

**Comment by dustymc** [comment] 2024-07-17 16:25
Addressing @AdrienneRaniszewski comment from https://github.com/ArctosDB/arctos/issues/7946#issuecomment-2233623182 here in an attempt to centralize information.


>better explanations right on the flat_status page would be great, so I don't have to sort through github discussions. 

Can someone please help with appropriate text?

>A way to figure out how long I need to wait would also be super useful, I think.

I don't have that information. This is often caused by incoming changes - the count is going up and down at the same time, occasionally from multiple sources. The rate of change also influences both the rate at which other things can change, and the rate at which refreshes can be processed.

> how many records are processed per minute. 

I don't have that information. The processor just uses what resources it can, and the data across records is wildly different. I could make it more predictable, but I'd have to aim that at the worst case scenario. Wild guess, that's maybe 500 records per minute, and for comparison it's running at around 3000 right now. I've done everything I can to make things more efficient, and part of the cost is a lack of transparency. 

>where are my records in the queue. 

Absolutely no idea. It tries for first in / first out, but that's not very informative.

>Until then, I'm just periodically searching for my records and crossing my fingers. 

Very open to better ideas, no matter how radical. (Not allowing public access to the primary DB might mean - after a LOT of code rewrites - that we don't need a cache, or we could potentially try to make updates less often in larger chunks, or ????????? Or throwing massive amounts of hardware at the current environment is usually the cheapest option, if someone wants to tackle that.)

>But luckily this extreme delay doesn't happen often. Thanks Dusty!

I think still something well over 90% of the time the cache is less than a minute stale. I understand that's not very comforting when you're waiting for something to happen.

**Comment by campmlc** [comment] 2024-07-17 16:38
We hear this over and over that the cause of so many problems is "limited resources". What do we do to fix this? What "resources" do we need to acquire? What grant do we need to write or what hardware or cloud storage do we need to pay for? Do we have a list of this somewhere?
And shouldn't things like locality merges on a subset of records take lower priority than new entry? Are we dealing with one single pipeline or lane for all inputs, so that a single issue can delay everything for everyone?

**Comment by dustymc** [comment] 2024-07-17 19:17
>"limited resources"

https://github.com/ArctosDB/internal/issues/330

>priority

https://github.com/ArctosDB/PG/issues/30

and from https://github.com/ArctosDB/arctos/issues/7946#issuecomment-2233972780:

> collection_cde basis

https://github.com/ArctosDB/arctos/issues/7952

Also https://github.com/ArctosDB/arctos/issues/7953 from the same comment.
