### ISSUE TITLE
Data quality contact message

### ISSUE THREAD

**Issue by AJLinn** [ArctosDB/arctos#2954] opened 2020-07-22 17:22 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Each time I log in I am greeted by a red-box and message:
<img width="863" alt="Screen Shot 2020-07-22 at 9 14 07 AM" src="https://user-images.githubusercontent.com/17605945/88207171-de001a80-cbfb-11ea-87d4-35283ade86fd.png">

**Expected behavior**
I followed the instructions, checked the Manage Collections screen for this collection and there does appear to be a valid data quality contact with valid email address.
What else do I need to do to stop being greeted by this cheery message each and every time I log in? Can/should I just remove my "manage collection" access? I've not been contacted by ALMNH for any assistance with this collection. 

**Priority**
Normal (though I'm starting to find it more annoying!)

**Comment by dustymc** [comment] 2020-07-22 17:28
It's a couple clicks away, but brandonsthompson 

Database User Status: | LOCKED

is the problem. Arctos only sends emails to active operators. That's a very intentional feature, not a bug.

The "correct" solution is to ensure that collection has an active data quality contact.

Removing your admin access to the collection will get rid of the red thing for you, but won't fix the problem.

**Comment by Jegelewicz** [comment] 2020-07-22 17:32
@mbprondzinski what's up with Brandon? Also John, who is the data quality manager for ALMNH:Ento. I get this every time I log in as well - but I just click through because I've been too busy to check the stuff.

@AJLinn had access because she is listed as a mentor - I just revoked it so that should fix this for her,

**Comment by mbprondzinski** [comment] 2020-07-22 17:56
I don’t know @Teresa Jegelewicz Mayfield<mailto:jegelewiczt@unm.edu>…if something happens to me…like god forbid, Covid…they are all going to be out of luck!  At least Adiel keeps plugging along.  I’m still working on the Mammals which turns out to be a much bigger problem than originally anticipated.  Hundreds of specimens that were never entered and no way of checking to see if they really exist until I can spend some time in the collections.  Names that only have the last name,  dates all entered wrong  (the whole collection dates back to the mid-1900s except for a very few specimens, yet they were all entered as the 1800s (!), and so on.  If there is one thing I have learned from all this:  never let a student enter data unless they’ve been thoroughly vetted!!!!!  Ha…

How is Kevin’s collection going?  He’s in Antarctica so I doubt he will be doing anything with that anytime soon.

Oh well, happy pandemic!

**Comment by campmlc** [comment] 2020-07-22 17:59
@mbprondzinski<https://github.com/mbprondzinski> Let me know if you need
any help with Mammals!

**Comment by Jegelewicz** [comment] 2020-07-22 18:08
I'm slowly plugging away on Kevin's stuff on the weekends. I am gettig fairly close, but dealing with a lot of the same issues you have with the mammals. It's just really messy data plus lots of crazy localities! Good times!

**Comment by mbprondzinski** [comment] 2020-07-22 18:16
Hi Mariel,  Thanks for the offer.  I will definitely let you know.  I am almost done going through the original data logs.  I finally gave up trying to enter the measurements in each record because it was taking too long. I am wondering if it will be easier to enter the measurements after the collection is entered into Arctos?  Some of the measurements are in the records, but most aren’t.  What would you suggest?  Here is what they look like (note that in some cases, other information is entered in the Remarks field):
occurrenceRemarks
(TL) = 110 mm (TV) = 40 mm (HF) = 27 mm (E) = 14 mm

Apparently whoever initially entered the data decided the measurements were irrelevant (!)  Of course, as you can see, there were no specific fields set up for measurements so I put them in the remarks field.

**Comment by campmlc** [comment] 2020-07-22 18:23
Yes, you can do an attribute bulkload if that's easier. They are standard
measurements for total length, tail, hind foot ( probably with claw) ear (
probably from notch).

**Comment by mbprondzinski** [comment] 2020-07-22 18:31
I will let you know when I think I'm ready for uploading agents.

**Closed** 2022-02-15 17:12 UTC
Labels: Priority-Normal (Not urgent), Function-Users
