### ISSUE TITLE
Locality Search results are funky

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3028] opened 2020-08-18 22:59 UTC
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
When I search using https://arctos.database.museum/showLocality.cfm the results are funky. When a locality includes more than one collecting event, it will show up multiple times in the results, but that isn't what I expect to be getting here, I expect to be getting **localities**.

**To Reproduce**
1. Go to https://arctos.database.museum/showLocality.cfm
2. Search Locality attribute = lithostratigraphic formation, Attribute Value = Finlay Limestone Formation
3. Scroll down results and find that locality https://arctos.database.museum/editLocality.cfm?locality_id=11141896 is included in the list twice (there are two associated collecting events)

**Expected behavior**
A search for localities containing some thing will result in a list of unique localities rather than a list of unique events using those localities.

**Screenshots**

** Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label.

**Comment by dustymc** [comment] 2020-08-18 23:24
Duplicate of https://github.com/ArctosDB/arctos/issues/2916

**Comment by Jegelewicz** [comment] 2020-08-18 23:25
Thanks - I couldn't find that....

**Closed by dustymc** 2020-08-18 23:24 UTC
Labels: Display/Interface, Function-Locality/Event/Georeferencing, Function-SearchOrDownload, Priority-High
