### ISSUE TITLE
media thumbnails (now: example records)

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/arctos#990] opened 2016-11-30 00:41 UTC
I'm working on the website and there is a link to this record as an example of data digitization from paper records:

http://arctos.database.museum/guid/UAM:ES:16773

Could you add some kind of generic thumbnail to those, so it doesn't look so bad when you open up that record as an example from the website?

**Comment by campmlc** [comment] 2016-11-30 00:49
Carla,
Here is an example with data transcribed from the Rausch ledger and linked
to vouchers.

http://arctos.database.museum/guid/MSB:Para:1351

Mariel

**Comment by campmlc** [comment] 2016-11-30 01:00
Here is the host observation record for that parasite record- with data
transcribed from the paper ledger. See the tagged in media link at bottom.
Note that it links to a real host voucher in MSB Mamm - but the data for
the mammal record is not as comprehensive because it was derived from the
tag only.
http://arctos.database.museum/guid/MSB:Host:7333

**Comment by dustymc** [comment] 2016-11-30 01:08
As much as I like dinosaurs, something with a TAG would be good to include in a demo.

http://arctos.database.museum/showTAG.cfm?media_id=10430745 contains a "soft" link to a specimen, which I think is sorta neat functionality....

Actually, it might be good to include all of those options, with the point being that there's a LOT of flexibility in the model - you can digitize something very general (locality/accn notes) and link it to lots of specimens, or link media to one specimen (http://arctos.database.museum/guid/UAM:EH:UA92-017-0001 has a neat video), or "soft link" stuff via TAGs (doesn't prevent eg, deleting the target), or "hard link" via TAGs (make key-pair relationships as in Mariel's examples), or do all of those things, or do them incrementally as you find resource, or WHATEVER.

**Comment by ccicero** [comment] 2016-11-30 01:14
Mariel - I am getting a 404 error (logged out) for the link to MSB:Host:7333, and when I search on that number it returns 0 records.  I logged in and that one is encumbered, so we shouldn't link to any record from the website that's not accessible. 

Dusty - Nice examples, and I will make a page showing different examples and 'especially' gold standard ones. After I'm done editing the basic pages. Thanks.

**Comment by campmlc** [comment] 2016-11-30 01:34
Carla - I will un-encumber the host record. The issue is that we have a
mammal voucher, but we can link the data to the host observation based on
the paper ledger which provides much more information, plus there is a tag
to the parasite voucher, the observational record, and the host voucher.
The data transcription/MSB host observation record enabled us to link the
parasite and host voucher specimens. This is a good example of how
transcribing paper catalogs and tagging specimens adds data and value to
voucher specimens, and allows for specimen discovery across collections.

**Comment by campmlc** [comment] 2016-11-30 01:38
The host record is now un-encumbered, so you should be able to see all
three records and their respective TAGs to the ledger and their
relationships to each other (or will be able to as of 24 hrs from now). Let
me know if that is not the case. I would like this to be one of the gold
standard examples.
 Mariel
http://arctos.database.museum/guid/MSB:Para:1351

**Comment by dustymc** [comment] 2016-11-30 02:11
We should develop guidance regarding "same individual as" - the Mamm record has the "same" relationship and scary red border, the Host does not (eg, it's a self-reference) - that probably confuses people, and may be even less clear from eg, GBIF. I'm not sure it matters what we do, but we should try to be consistent, or explain what we're up to, or something.

And could you (have you?) write up something about what you're doing with the Host catalog? (My understanding was that you'd delete the host in this situation and just point everything at the mammal - I'm guessing you've found some reason not to?)

Fun!

**Comment by campmlc** [comment] 2016-12-01 17:01
"Same individual as" relationships theoretically should always be
reciprocal, and in this example both records had the same as relationship
initially. But after I started looking at
http://arctos.database.museum/guid/MSB:Mamm:192800 as a possible gold
standard example, I removed the relationship from the MSB Host record and
tried to do the same for the MSB Mamm record (but could not for some
reason) because the associated red border makes the records look like there
is something seriously wrong - and not something we would want to display
to the public. I think it would be preferable to have some means of
removing the red border from the record that we WANT to be cited and only
have the red border on the record that we wish to flag as a duplicate of
another, valid, record. Is this possible?

In this case, I think it is valid keep both the host observation record and
the mammal voucher record, rather than deleting or encumbering the host
record,  because one provides a data check for the other. The host record
is an observational record derived from the source data ledger, whereas the
parasite and mammal voucher records are based on the derived data of
specimen tags or labels.These specimens are all in multiple divisions and
in some cases, multiple collections. It is difficult and takes a
considerable amount of time as well as access to all the respective
collections to update records to match the observational data. Why not just
make the host observation record available, put a red border around it, BUT
- get rid of the red border around the actual, citable, voucher specimen.

**Comment by dustymc** [comment] 2016-12-01 17:51
>red border ... seriously wrong

Yea, probably. The intent is "seriously weird," not wrong.

The relationship needs to be noticeable - I think most all users expect that every record in a database represents an independent sample. That's far from true, and we need (I think) SOME way of communicating/highlighting that information. And that needs to go both ways - however I find "your data," (your "preferred" record in Arctos, your "non-preferred" record in Arctos, the material you've deposited at some other institution, as part of a download from GBIF, a separate "Occurrence" as part of a download from GBIF, etc., etc., etc. - I (and the people who are trying to understand my citations, and....) should be able to tell that we're dealing with some flavor of "duplicate." 

I'm 100% open on how to do that, and don't really have any clever ideas. The only thing I can think of is more relationships - add a "preferred same individual as"/"non-preferred same individual as" or something, where "preferred same..." would be exempt from the red border (or whatever CSS trick we use to alert users that SOMETHING weird is happening). That seems likely to lead to conflicts - you think your record should be preferred, I like mine better, users are left scratching their heads....

Just dump the red border altogether, and hope people notice the relationships??

**Comment by campmlc** [comment] 2016-12-01 19:10
I would suggest dumping the external red border, but leave the red border
around the "same individual as" relationship.

**Comment by dustymc** [comment] 2016-12-01 20:37
>dumping the external red border, but leave the red border around the "same individual as" relationship

Done for next release.

**Comment by dustymc** [comment] 2017-07-12 18:31
I believe this is all implemented or captured in https://arctosdb.org/learn/gold-standard-records/ - please re-open if something still needs attention.

**Closed by dustymc** 2017-07-12 18:31 UTC
Labels: Enhancement, Function-Media, Priority-Normal, Type-Form/Function
